### ISSUE TITLE
Creating a DataVolume in the namespace having resource quota

### ISSUE THREAD

**Issue by anencore94** [kubevirt/containerized-data-importer#1043]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/kind enhancement

--------------------
**What happened**:

When I create dataVolume in the specific namespace, which has resourceQuota limits, the dataVolume created, but the requested image does not imported. (i tested images with spec.source.registy & spec.source.http both.)

I found error messages occurred in 'cdi-deployment pod log', which said:
```
importer-controller.go:296] error processing pvc "{$pvcName}" : importer pod API create errored: pods "importer-{$pvcName}-{$arbitraryCharacters}" is forbidden: failed quota: {$resourceQuotaName}: must specify limts.cpu, limits.memory
```
In such namespace and resourceQuota, I specified limits.cpu and limits.memory.

By inspecting source codes, i found that the function "CreateImporterPod" use pvc.Namespace to make Importer pod.
However, in the pod.spec section, it seems that there isn't any part inserting resourceQuota and its limits.
But, when creating any pod in namespace having some resourcequota, the section "spec.containers.resources.limits" is required.

Thus, the importer pod didn't created and also pvc-scratch didn't created.
Therefore importing image didn't succeeded, so the Status.Phase of DataVolume remained in "PVCBound", not "Succeeded".

--------------------
**What you expected to happen**:
Is this situation does not considered?
or Is there any solution that i'm missing to make importer-pod and datavolume in namespace having resourcequota?

--------------------
**How to reproduce it (as minimally and precisely as possible)**:
1. create namespace
2. create resourcequota in that namespace
3. create datavolume in that namespace

--------------------
**Anything else we need to know?**:

--------------------
**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
  - Tested on both version:
    - v1.11.0
    - v1.10.9
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- Install tools:
- Others:
  - OS version : ubuntu 18.04.3 LTS

**Comment by awels** [comment]
Hi,

Thanks for the report, you are correct we do not set request cpu/memory limits. Definitely something we need to look into. To make it work right now, you can specify some default limits in the namespace. For an example look here: https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/#motivation-for-default-cpu-limits-and-requests but this is definitely something we need to address at some point.

**Comment by WoohyungHan** [comment]
> Hi,
> 
> Thanks for the report, you are correct we do not set request cpu/memory limits. Definitely something we need to look into. To make it work right now, you can specify some default limits in the namespace. For an example look here: https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/#motivation-for-default-cpu-limits-and-requests but this is definitely something we need to address at some point.

hi, @awels :) How do you think this problem should be solved? I think we have two choices. 
1. Just hard coded with reasonably small amount of resource
2. Give configuration as option to how much resource is consumed by cdi-deployment.

I think second one looks better.

**Comment by awels** [comment]
Not having given it too much thought, I would lean towards 2 as well, and if 2 is not specified default to something reasonable. How much is something reasonable we will have to figure out. We can add some fields to CDIConfig object to configure the override for the default.

**Comment by hyoung-90** [comment]
If nobody working on it, I'll solve it.

**Comment by awels** [comment]
We currently have no one working on it, but I created a card for it, so it will be under consideration for our next sprint. If you have some time to work on it that would be great.

**Comment by anencore94** [comment]
Hi.
I've been working on this issue, and now faces some decision-problems to discuss with you guys.

Based on this comment,
>Not having given it too much thought, I would lean towards 2 as well, and if 2 is not specified default to something reasonable. How much is something reasonable we will have to figure out. We can add some fields to CDIConfig object to configure the override for the default.

1) Does the **'some fields to CDIConfig object'** need to be required or not?
I think if we want to make **'cdi-users'** to  decide the default values, the field should be a required field. However, if we want to use some **'our reasonable'** default values, then the field should be an optional field as you said above.

2) Which type will be better for 'some fields to CDIConfig object' ?
There are some candidates like:
a) several fields of type 'k8s.io/api/core/v1/ResourceList'
b) one fields of type 'k8s.io/api/core/v1/ResourceRequirements'
c) one fields of type 'k8s.io/api/core/v1/ResourceQuotaSpec'

3) Is there any idea to decide what is **'our reasonable default values'**, if these values will be specified in the sourcecode?
I think it could be:
a) zero (unlimited for cpu, memory field)
b) the minimum value of each fields (maybe we have to get somehow)
c) any other ideas ?

**Comment by awels** [comment]
>     1. Does the **'some fields to CDIConfig object'** need to be required or not?
>        I think if we want to make **'cdi-users'** to  decide the default values, the field should be a required field. However, if we want to use some **'our reasonable'** default values, then the field should be an optional field as you said above.
> 

I am thinking they should be optional. They are there in case our 'reasonable default values' turn out to not be reasonable for a particular workload. This gives the users of CDI the option to change them to work for that workload.

>     2. Which type will be better for 'some fields to CDIConfig object' ?
>        There are some candidates like:
>        a) several fields of type 'k8s.io/api/core/v1/ResourceList'
>        b) one fields of type 'k8s.io/api/core/v1/ResourceRequirements'
>        c) one fields of type 'k8s.io/api/core/v1/ResourceQuotaSpec'
> 

I am thinking ResourceRequirements, we could then directly copy the struct from the config object to the pod spec. @mhenriks Any thoughts on this? Maybe have an intermediate struct that has a namespace, so we can specify the requirements per namespace

>     3. Is there any idea to decide what is **'our reasonable default values'**, if these values will be specified in the sourcecode?
>        I think it could be:
>        a) zero (unlimited for cpu, memory field)
>        b) the minimum value of each fields (maybe we have to get somehow)
>        c) any other ideas ?

If we pick a), which would be equivalent of not specifying them, and trying to run in a namespace with a quota, the pods would never schedule. But since we have provided the override the user could use the override and make it. This would put the burden on the user to configure it correctly to make it work. We would also have to account for different namespaces having different quotas.

If we pick b) we would basically have to do some trial and error and see what is enough for most cases and go with that. This would put the burden on us to figure out reasonable defaults. Only in some cases would the user have to do something special. We would still have to account for different namespaces having different quotas.

I had one random thought. If the namespace has a resource quota defined, we could read the quotas of that namespace and based on the values in the quota construct the limits out of it. This of course becomes 'interesting' when multiple quotas exist, so its probably not a good idea.

**Comment by mhenriks** [comment]
@anencore94 @awels 

Is it not unreasonable to expect defaults specified like [here](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/#create-a-limitrange-and-a-pod) when resource quotas are in use?

But it probably makes sense to have a way to override those defaults.  A good first step may be to include an optional [LimitRangeSpec](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L5216-L5220) in the `CDIConfig` spec?

**Comment by awels** [comment]
If we compare [LimitRangeSpec](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L5216-L5220) to [ResourceRequirements](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L2087) you will notice both in the end are a set of [ResourceList](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L4598). However LimitRangeSpec includes a lot of extra information we will never use when specifying the request/limits in the pods. For this reason I am leaning towards ResourceRequirements as part of CDIConfig object.

**Comment by anencore94** [comment]
I am leaning towrads ResourceRequirements too. Since it seems making temporary pods in resourcequota-namespace needs only requests/limits from now on.

**Comment by WoohyungHan** [comment]
@awels @anencore94 

I think `the default value of resource quota` is not a big problem. The temporary pod does not use much cpu, so set to minimal (maybe 1 vcpu?) is enough. but, we can make a path for modifying in the CDIConfig for who want to change this.
