### ISSUE TITLE
CDI upload failed

### ISSUE THREAD

**Issue by wavezhang** [kubevirt/containerized-data-importer#1066]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
CDI upload failed, it upload fast at the beginning, and then became stuck/ with very very low upload speed until timeout.
**What you expected to happen**:
CDI upload success
**How to reproduce it (as minimally and precisely as possible)**:
upload large image following [CDI Upload User Guide
](https://github.com/kubevirt/containerized-data-importer/blob/master/doc/upload.md) with slow storage and fast network.
**Anything else we need to know?**:
I could upload success when I limit upload speed using curl.
**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
1.10.9
- Kubernetes version (use `kubectl version`):
1.15.2
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by wavezhang** [comment]
It seems that if storage is slow, there will be network congestion between cdi upload proxy and cdi upload server, but the upload between client and upload proxy keeps going, which cause more trouble.

**Comment by mhenriks** [comment]
Hi @wavezhang thanks for the big report.  How are you exposing the upload proxy (ingress/route/nodeport/port forward)?

Can you attach proxy/uploadserver logs?

**Comment by wavezhang** [comment]
I epxort upload proxy using nodeport with ipvs mode.

proxy logs:
```
I1230 07:06:24.134414       1 uploadproxy.go:46] Note: increase the -v level in the api deployment for more detailed logging, eg. -v=2 or -v=3
W1230 07:06:24.134901       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1230 07:23:26.667541       1 uploadproxy.go:179] Received valid token: pvc: test, namespace: default
```
uploadserver logs:
```
I1230 07:23:18.279591       1 uploadserver.go:61] Upload destination: /dev/cdi-block-volume
I1230 07:23:18.280681       1 uploadserver.go:63] Running server on 0.0.0.0:8443
2019/12/30 07:23:26 http: TLS handshake error from 100.65.228.128:47234: EOF
I1230 07:23:26.686583       1 uploadserver.go:244] Content type header is ""
I1230 07:23:26.686653       1 data-processor.go:252] Calculating available size
I1230 07:23:26.690480       1 data-processor.go:256] Checking out block volume size.
I1230 07:23:26.692435       1 data-processor.go:264] Request image size not empty.
I1230 07:23:26.692468       1 data-processor.go:269] Target size 10Gi.
I1230 07:23:26.692836       1 data-processor.go:182] New phase: TransferScratch
I1230 07:23:26.704774       1 util.go:169] Writing data...
error: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
```

**Comment by richard-fairthorne** [comment]
For anyone stumbling across this issue using LENS, the proxy lens uses (at least on macos) will buffer the transfer and then crash. Use kubectl port-forward instead, and the transfer will happen at a reasonable pace.

Hope that helps somebody.
