### ISSUE TITLE
x509 error when running offline

### ISSUE THREAD

**Issue by mjschmidt** [kubevirt/containerized-data-importer#1067]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug?

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**: I successfully used CDI online to create a pvc (and then a VM) with a pvc where it would get its OS from an endpoint. Awesome, then I took it offline and CDI pod is giving me an x509 error and I can't find where to correctly configure the container to not give me an x509 and to accept my offline certificate (pulling from an s3 minio bucket). 

**What you expected to happen**: Container runs with no x509 errors, or the default cert has a ca bundle that accepts all machines by default via an insecure option or something configurable through the cdi yaml?

**How to reproduce it (as minimally and precisely as possible)**: Run CDI offline with a s3 bucket like minio that is using a self signed cert for ingress controller

**Anything else we need to know?**: 
I just need to know one of the following:
* How do I correctly configure the pod on start up to use a different CA bundle
* Where is that CA bundle file found in the container so that I can do a quick update to the container and push my own copy with an over written. The container is `docker pull kubevirt/cdi-importer:v1.11.0`

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.11.0
- Kubernetes version (use `kubectl version`): 1.16.x
- Cloud provider or hardware configuration: hardware centOS7
- Install tools: kubectl?
- Others:

**Comment by mhenriks** [comment]
Hi @mjschmidt certs can be stored in a ConfigMaps that are referenced in DataVolumes.  See here:  https://github.com/kubevirt/containerized-data-importer/blob/f017dedde8cd689cb0d19845c3ff40a44273d9a5/doc/datavolumes.md#https3registry-source

**Comment by mjschmidt** [comment]
Oh! Let me give this a try! That is exactly what I need!
