### ISSUE TITLE
Importer often stalls and stops downloading

### ISSUE THREAD

**Issue by timstoop** [kubevirt/containerized-data-importer#1072]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I've created a DataVolume that downloads from S3 (tried with HTTP as well, same result) and it often stalls. It starts downloading pretty quickly and then after a while it stalls and stops downloading completely. Deleting the Pod will restart the download, after which it stalls and stops the download at (usually) a different point. Removing the importer when this happens, sometimes allows it to finish the download on a new run. There does not seem a way to trigger it to restart an already started download.

**What you expected to happen**:
Download either finishes without a problem or the process recognises the stall and restarts so it doesn't have to download the entire image anew.

**How to reproduce it (as minimally and precisely as possible)**:
Create a DV that downloads from either HTTP or S3. We experience this with large (25GB+) images.

**Anything else we need to know?**:
I left one around for more than an hour and it did not update the log output anymore, where before it updated the log output once every few seconds.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.11.0
- Kubernetes version (use `kubectl version`): v1.15.7
- Cloud provider or hardware configuration: GCE
- Install tools: ?
- Others: ?

**Comment by awels** [comment]
Hi, sorry didn't see this sooner.

Can you get me a copy of an importer log? Also another thing to try is to convert the image to raw before importing. There are some known issues with certain versions of qemu-img streaming conversion that might be affecting you, I want to rule them out.

**Comment by timstoop** [comment]
Ah I found a "solution" by using the SSD variant. Now I'm running into the next problem, but I'll create a new issue for that (it always runs out of space, even when I create a disk twice the size of the original raw image).

But it seems that a normal pd-standard simply cannot keep up with the traffic and qemu just stops downloading. I was already using a raw image. I'll replicate the issue and send you the log, but it just stops downloading at some point, without any additional information.

**Comment by timstoop** [comment]
```
I0111 12:23:41.393103       1 importer.go:51] Starting importer
I0111 12:23:41.393452       1 importer.go:107] begin import process
I0111 12:23:41.579726       1 data-processor.go:253] Calculating available size
I0111 12:23:41.583415       1 data-processor.go:261] Checking out file system volume size.
I0111 12:23:41.583449       1 data-processor.go:265] Request image size not empty.
I0111 12:23:41.583468       1 data-processor.go:270] Target size 52504764416.
I0111 12:23:41.583570       1 util.go:37] deleting file: /data/lost+found
I0111 12:23:41.586608       1 data-processor.go:183] New phase: Convert
I0111 12:23:41.586630       1 data-processor.go:189] Validating image
I0111 12:23:41.853738       1 qemu.go:212] 0.00
I0111 12:23:43.741855       1 qemu.go:212] 1.01
I0111 12:23:45.247482       1 qemu.go:212] 2.02
I0111 12:23:47.122166       1 qemu.go:212] 3.02
I0111 12:23:48.791920       1 qemu.go:212] 4.03
I0111 12:23:50.429692       1 qemu.go:212] 5.04
I0111 12:23:52.324043       1 qemu.go:212] 6.05
I0111 12:23:54.207421       1 qemu.go:212] 7.05
I0111 12:23:55.763789       1 qemu.go:212] 8.06
I0111 12:23:57.663417       1 qemu.go:212] 9.07
I0111 12:23:59.310323       1 qemu.go:212] 10.08
I0111 12:24:01.029222       1 qemu.go:212] 11.09
I0111 12:24:02.669057       1 qemu.go:212] 12.09
I0111 12:24:04.850224       1 qemu.go:212] 13.10
I0111 12:24:06.362256       1 qemu.go:212] 14.11
I0111 12:24:07.936244       1 qemu.go:212] 15.12
I0111 12:24:09.726150       1 qemu.go:212] 16.12
I0111 12:24:11.473538       1 qemu.go:212] 17.13
I0111 12:24:13.181538       1 qemu.go:212] 18.14
I0111 12:24:15.043894       1 qemu.go:212] 19.15
I0111 12:24:16.918596       1 qemu.go:212] 20.16
I0111 12:24:18.614001       1 qemu.go:212] 21.16
I0111 12:24:20.420975       1 qemu.go:212] 22.17
```

It just stops here. I can leave it going for hours and no new line will be printed. In this case, I waited about 5 minutes, but I tried this often last week as well and left it running for an hour or longer a few times as well.

**Comment by timstoop** [comment]
O now I'm seeing the same on an SSD, so maybe disk space is not the culprit?

**Comment by awels** [comment]
No this is likely a bug in qemu-img. I would have to go find the bugzilla with the exact report, but the gist of it is that qemu-img starts 4 threads that start reading data while it is converting and in certain conditions those threads can deadlock and basically halt the process. AFAIK that got fixed recently, but we are running an older version right now because of a different bug in qemu-img.

I just took another look at the code as I was confused why it was running through qemu-img when you have a raw file already. I think we found a bug (I will fix that). But to confirm can you do an experiment for me? Can you either xz or gz the raw file before importing it? That way it will force it through a different code path for the transfer (but it might use temporary scratch space the size of the target space)

**Comment by awels** [comment]
#1080 fixes the above mentioned bug.

**Comment by timstoop** [comment]
I solved it in another way (used a VM in GCE to copy the stuff to a new Volume and attached that to Kubernetes as a new PVC), so I do not have stuff ready to go. But I expect to have to do all this sometime soon again, so I'll revisit this then.

**Comment by timstoop** [comment]
To confirm, if I gzip the raw file, I cannot reproduce the problem, so that seems to have fixed it. Might have been luck?

**Comment by awels** [comment]
Its because when you gzip the file, the transfer doesn't happen using qemu-img, which is the problem. Instead it uses the go client to transfer the file. I have a pending PR that should fix the problem permanently without you having to gzip the file.
