### ISSUE TITLE
CDI should fall back if HTTP server doesn't support byte ranges

### ISSUE THREAD

**Issue by mdbooth** [kubevirt/containerized-data-importer#1073]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

CDI will fail to download via HTTP if the server does not support byte ranges. This is because of the use of qemu-img convert to do the download. qemu-img uses the qemu curl block driver, which fundamentally requires random access, IOW there is no workaround for this limitation in qemu. It's also worth noting that downloading this way will likely not result in a very efficient download.

**What you expected to happen**:

If qemu-img convert fails because of a limitation of qemu-img, CDI should automatically fallback to download to scratch space and convert from local file.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Here is the relevant part of the qemu curl driver which is going to generate the error:

https://github.com/qemu/qemu/blob/master/block/curl.c#L797-L802

As mentioned, this limitation of fundamental to the architecture of a qemu block driver.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
Hi,

Thanks for the report, I agree CDI should fall back if the http server doesn't support byte ranges. Do you have an example of an http server that doesn't support byte ranges? I can create one with go fairly easily, just trying to understand where this is occurring in the wild.

**Comment by mdbooth** [comment]
OpenStack Glance :)

However, anything serving content without a random-access backend would not support byte ranges.
