### ISSUE TITLE
Suggest help target in Makefile

### ISSUE THREAD

**Issue by anencore94** [kubevirt/containerized-data-importer#1092]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

Current Makefile have 'make all' target and it is the first target, therefore if user run 'make' it runs 'make all'.

**What you expected to happen**:

I'm not sure what is the convention in this project.
Therefore i just carefully suggest to add 'help' target, which shows target lists and explain(by echo string) what each target does.

Actually, explanation sentences will be the sentences in the README.md file in hack directory.
I think it would be better when users see what each 'make targets' does with Makefile only, not seeing developer's guide document.

**How to reproduce it (as minimally and precisely as possible)**:
NONE

**Anything else we need to know?**:

Also, If 'make help' target is accepted, how about change default target to 'make help' rather than 'make all'?

By the way, if you think it is worth and you allowed, i would be appreciated to work on it by myself.

Thanks.

**Environment**:
NONE

**Comment by awels** [comment]
Hi,

I see no issues with making that change, if you want to make it, feel free to create a PR.
