### ISSUE TITLE
Using fork of openshift/library-go

### ISSUE THREAD

**Issue by mhenriks** [kubevirt/containerized-data-importer#1097]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

#1091 references a fork of openshift/library-go

Once the following PR is merged, CDI should go back the mainline:

https://github.com/openshift/library-go/pull/540

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
This still applies right @mhenriks

**Comment by aglitke** [comment]
@mhenriks please take a look and see if we can make the needed methods public in openshift/library-go#540

**Comment by mhenriks** [comment]
created https://github.com/openshift/library-go/pull/1486

**Comment by alromeros** [comment]
Closting this since it's been addressed by https://github.com/openshift/library-go/commit/434fa21f5e457d51f436c4b3804c7803db1da42d.

**Comment by mhenriks** [comment]
thanks for the reminder @akalenyu

**Comment by mhenriks** [comment]
Unfortunately have to wait until we move to k8s 1.29 (release-4.16+ branch in library-go) to do this
