### ISSUE TITLE
Add Helm chart supporting

### ISSUE THREAD

**Issue by woohhan** [kubevirt/containerized-data-importer#1114]
Thanks for helping and reviewing #1055 commits. We're using cdi to upload an image to pv, and it works perfectly well. However, there are some difficulties in deploying and maintaining cdi on many environments. So we created simple helm chart and using it, and I think the helm chart can replace `make manifests` feature. If we move on to helm charts instead of making all substitution code, I think we can maintain more easily our code and deploying.

You can see example helm chart here: https://github.com/woohhan/cdi-chart

**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
NONE

**What you expected to happen**:
NONE

**How to reproduce it (as minimally and precisely as possible)**:
NONE

**Anything else we need to know?**:
NONE

**Environment**:
NONE

**Comment by awels** [comment]
Hi,

Thanks for the suggestion. We currently don't have the capacity to maintain a helm chart, but if you are willing to contribute and maintain it, we are willing to host it in our repository.

**Comment by woohhan** [comment]
Thanks for your reply :) It would be nice If I could. I will create a pull request for this.

**Comment by harshitgupta1337** [comment]
Hello @woohhan @awels 
What is the current status of this effort to add Halm charts to CDI ? I would like to contribute to it if that is still not part of CDI repo.

**Comment by awels** [comment]
There is no progress, from our perspective since we have the operator, doing a helm chart doesn't make much sense, so we are not scheduling resources to work on it. But if you are able to provide a PR with it, we can definitely review and approve it if needed.
