### ISSUE TITLE
Exposing cdi-uploadproxy is not working

### ISSUE THREAD

**Issue by abhiniveshjain** [kubevirt/containerized-data-importer#1117]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
I am using CDI alongwith virtctl to upload an image and getting below error. 

Internal error occurred: failed calling webhook "datavolume-mutate.cdi.kubevirt.io": Post https://cdi-api.cdi.svc:443/datavolume-mutate?timeout=30s: dial tcp 10.x.x.x:8443: connect: no route to host

I am giving cdi-uploadproxy IP but somehow it is going to cdi-api IP and failing with above error.  

I am running this on Openshift 4.2, I have setup CDI using below commands. here version is v1.13.0

export VERSION=$(curl -s https://github.com/kubevirt/containerized-data-importer/releases/latest | grep -o "v[0-9]\.[0-9]*\.[0-9]*")
oc create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-operator.yaml
oc create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-cr.yaml

for exposing the svc, I executed below commands.
oc get cm -n cdi cdi-uploadproxy-signer-bundle -o=jsonpath="{.data['ca-bundle\.crt']}" > tls.crt && \
oc create route reencrypt -n cdi --service=cdi-uploadproxy --dest-ca-cert=tls.crt && \
rm tls.crt

**What you expected to happen**:
Image upload should work.

**How to reproduce it (as minimally and precisely as possible)**:
Covered in previous sections where i mentioned the steps that I followed.

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.13.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: 3 node cluster on baremetal servers.
- Install tools: kubevirt
- Others:

**Comment by mhenriks** [comment]
Hi @abhiniveshjain, Before sending data to cdi-uploadproxy `virtctl` creates a `DataVolume` to store the data.  DataVolumes are CRDs and CDI has validation/mutation webhooks that are triggered when they are created/updated.  Based on the error above, it appears that the k8s apiserver cannot connect to `cdi-apiserver` through the `cdi-api` service.  Confirm that the ip address in the error matches `cdi-apiserver` pod ip.  You may also want to check that there is no  `NetworkPolicy` [1] blocking traffic to `cdi-apiserver` in the `cdi` namespace.

By the way, on OpenShift, a route for `cdi-uploadproxy` should be created by `cdi-operator`.  Is that not happening for you?


[1] https://docs.openshift.com/container-platform/4.2/networking/configuring-networkpolicy.html

**Comment by abhiniveshjain** [comment]
Thanks Micheal for your response. I have checked and didn't see any network policy.

[root@localhost win2012iso]# oc get networkpolicies --all-namespaces
No resources found.

IP address in server is matching with the cdi-apiserver pod IP  I can see one route also created, it looks like below.

[root@localhost win2012iso]# oc get route
NAME              HOST/PORT                                                   PATH   SERVICES          PORT    TERMINATION   WILDCARD
cdi-uploadproxy   cdi-uploadproxy-cdi.apps.paeprod.baremetal.edge-sites.net          cdi-uploadproxy   <all>   reencrypt     None
[root@localhost win2012iso]# oc describe route cdi-uploadproxy
Name:                   cdi-uploadproxy
Namespace:              cdi
Created:                17 hours ago
Labels:                 cdi.kubevirt.io=
Annotations:            haproxy.router.openshift.io/timeout=60m
                        openshift.io/host.generated=true
Requested Host:         cdi-uploadproxy-cdi.apps.paeprod.baremetal.edge-sites.net
                          exposed on router default (host apps.paeprod.baremetal.edge-sites.net) 17 hours ago
Path:                   <none>
TLS Termination:        reencrypt
Insecure Policy:        <none>
Endpoint Port:          <all endpoint ports>

Service:        cdi-uploadproxy
Weight:         100 (100%)
Endpoints:      10.x.x.x:8443

Considering this, what else could be causing this?
.

**Comment by mhenriks** [comment]
Hi @abhiniveshjain there appears to be an issue with your cluster network.  The cdi-apiserver pod should be accessible by ip.  I'd exec into various pods to test connectivity by running `curl --insecure https://10.x.x.x:8443/`.  Start with the `cdi-apiserver` pod.  Then try another pod in the `cdi` namespace.  Then try pods in other namespaces.

**Comment by abhiniveshjain** [comment]
I have exposed cdi-api service and then restarted both worker nodes as cluster operator authentication was showing degraded. This solved the problem. Thanks for your help.

**Comment by abhiniveshjain** [comment]
Closing the issue.
