### ISSUE TITLE
virtctl image-upload is stuck

### ISSUE THREAD

**Issue by abhiniveshjain** [kubevirt/containerized-data-importer#1123]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
I am using CDI along with virtctl to upload an image and it is getting stuck in below step. It doesn't finish even in 30 minutes.

./virtctl image-upload \
--uploadproxy-url=https://x,x,x,x:443 \
--pvc-name=iso-win2k12-pvc \
--access-mode=ReadOnlyMany \
--pvc-size=16Gi \
--image-path=/tmp/Win2k12R2.ISO \
--insecure \
--wait-secs=3600

DataVolume default/iso-win2k12-pvc created
Waiting for PVC iso-win2k12-pvc upload pod to be ready...

POD keeps showing below status

[root@paeprod-master-0 tmp]# oc get pod
NAME                         READY   STATUS              RESTARTS   AGE
cdi-upload-iso-win2k12-pvc   0/1     ContainerCreating   0          30m

I am seeing below events in pod logs. for storage, I am using ceph-rook based filesystem.

Events:
  Type     Reason              Age                            From                       Message
  ----     ------              ----                           ----                       -------
  Warning  FailedScheduling    <invalid>                      default-scheduler          persistentvolumeclaim "iso-win2k12-pvc-scratch" not found
  Warning  FailedScheduling    <invalid>                      default-scheduler          pod has unbound immediate PersistentVolumeClaims (repeated 2 times)
  Normal   Scheduled           <invalid>                      default-scheduler          Successfully assigned default/cdi-upload-iso-win2k12-pvc to paeprod-worker-0
  Warning  FailedAttachVolume  <invalid> (x3 over <invalid>)  attachdetach-controller    AttachVolume.Attach failed for volume "pvc-84d3c70f-5732-11ea-9d51-20040fec89f0" : attachment timeout for volume 0001-0009-rook-ceph-0000000000000001-21564fc1-5733-11ea-91e8-0a580a810082
  Warning  FailedAttachVolume  <invalid> (x3 over <invalid>)  attachdetach-controller    AttachVolume.Attach failed for volume "pvc-848a5f2c-5732-11ea-9d51-20040fec89f0" : attachment timeout for volume 0001-0009-rook-ceph-0000000000000001-211bc948-5733-11ea-91e8-0a580a810082
  Warning  FailedMount         <invalid> (x3 over <invalid>)  kubelet, paeprod-worker-0  Unable to mount volumes for pod "cdi-upload-iso-win2k12-pvc_default(84cf0557-5732-11ea-9d51-20040fec89f0)": timeout expired waiting for volumes to attach or mount for pod "default"/"cdi-upload-iso-win2k12-pvc". list of unmounted volumes=[cdi-data-vol cdi-scratch-vol]. list of unattached volumes=[cdi-data-vol cdi-scratch-vol default-token-nxl26]

**What you expected to happen**:
image upload should complete and VM should come up.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I am running this on Openshift 4.2, I have setup CDI using below commands. here version is v1.13.0

export VERSION=$(curl -s https://github.com/kubevirt/containerized-data-importer/releases/latest | grep -o "v[0-9].[0-9].[0-9]")
oc create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-operator.yaml
oc create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-cr.yaml

I am trying to bring up windows VM by following below blog.
https://kubevirt.io/2020/KubeVirt-installing_Microsoft_Windows_from_an_iso.html

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):v1.13.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: Baremetal servers
- Install tools:
- Others:

**Comment by awels** [comment]
Hi

```
Warning FailedAttachVolume (x3 over ) attachdetach-controller AttachVolume.Attach failed for volume "pvc-84d3c70f-5732-11ea-9d51-20040fec89f0" : attachment timeout for volume 0001-0009-rook-ceph-0000000000000001-21564fc1-5733-11ea-91e8-0a580a810082
Warning FailedAttachVolume (x3 over ) attachdetach-controller AttachVolume.Attach failed for volume "pvc-848a5f2c-5732-11ea-9d51-20040fec89f0" : attachment timeout for volume 0001-0009-rook-ceph-0000000000000001-211bc948-5733-11ea-91e8-0a580a810082
```
Tells me there is something wrong with your ceph configuration. Can you create regular PVCs on it? Something like create a PVC, then create a pod that uses that PVC and can write something to it?
