### ISSUE TITLE
`cdi` CR should not have operator as a finalizer

### ISSUE THREAD

**Issue by briantopping** [kubevirt/containerized-data-importer#1149]
/kind bug

**What happened**:
I have been trying to get CDI to work the first time, but I can't tell what I am doing wrong sometimes, so I deleted everything. Except the `cdi` namespace survived with a `cdi` CR and a CM in it. I lazily thought I could just delete the namespace and rid myself of both, only to find a finalizer on the operator on the CR. There's no way to add the operator back in now because the `cdi` namespace is in the process of being deleted. Deadlock.

**How to reproduce it (as minimally and precisely as possible)**:
* Install CDI with instructions
* create a `cdi` API object
* Uninstall CDI with the `cdi` API object still around
* delete the namespace without the operator running

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 1.17.0
- Kubernetes version (use `kubectl version`): 1.17.4
- Cloud provider or hardware configuration: private cloud

**Comment by mhenriks** [comment]
Hi @briantopping unfortunately, that finalizer is currently needed so the operator can cleanup some resources that cannot have ownerRefs.  Have you tried manually removing the finalizer on the CDI CR in order to get unstuck?

**Comment by briantopping** [comment]
Yes, that worked very quickly. I was trying to to remove the finalizers on the namespace which is why I wasn't having success. Hopefully someone is able to use this information, thanks!
