### ISSUE TITLE
DataVolume progress improvement (metric collection)

### ISSUE THREAD

**Issue by MaxNosov** [kubevirt/containerized-data-importer#1203]
It would be better to collect progress metrics from source pod via service instead of direct pod IP call to minimize affection by network policies.

**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
Some network policies may block metric traffic of source pod, so DataVolume.status.progress has N/A value instead of progress all the time.

**What you expected to happen**:
Expected to see progress updates with percents but got persistent N/A value.

**How to reproduce it (as minimally and precisely as possible)**:
Create network policy (on an network policies supported environment) that may block traffic of source pod and run any CDI job,

**Environment**:
- CDI version: any (tested on v1.11.0 - v.1.16.0)
- Kubernetes version: any  (currently testeв on v1.17 - v1.18)

**Comment by awels** [comment]
Sorry it has taken so long, this fell through the crack. So if I understand correctly you want us to create a service that points to the pod, and instead of the controller directly connecting to the pod, the controller connects to this new service?

**Comment by awels** [comment]
I created a JIRA card in our board https://issues.redhat.com/browse/CNV-26190 to track this.

**Comment by alromeros** [comment]
Hello @MaxNosov, sorry for the delay but we are working on a PR to implement the requested feature https://github.com/kubevirt/containerized-data-importer/pull/2906. We still need to fix some stuff and decide if it's worth merging, but hopefully we'll reach a consensus soon.

**Comment by alromeros** [comment]
Hey @MaxNosov, after discussing with the team, we've decided to not implement this feature since it's hard to justify the benefits against the possible drawbacks. For more information check the PR https://github.com/kubevirt/containerized-data-importer/pull/2906, if justified we can always return to it. Closing the issue in the meantime, thanks!
