### ISSUE TITLE
QoS of CDI Pods

### ISSUE THREAD

**Issue by qwang1** [kubevirt/containerized-data-importer#1214]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
All CDI Pods don't have requests/limits for computing resources, so the QoS is BestEffort, which has the lowest running priority and would be terminated/evicted first once resources shortage occurs.

**What you expected to happen**:
As KubeVirt infra Pods, CDI Pods would better provide Guaranteed QoS.

**How to reproduce it (as minimally and precisely as possible)**:
```$ kubectl get pod <cdi-pod> -o yaml```

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): CDI v1.17.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
https://github.com/kubevirt/containerized-data-importer/blob/master/doc/quota.md CDI does have resource requests/limits and those can be configured with the CDIConfig object.

**Comment by qwang1** [comment]
The feature has been implemented, so I'm going to close the issue. Thank you all.
