### ISSUE TITLE
Support create qcow2 disk type when import data

### ISSUE THREAD

**Issue by scuzhanglei** [kubevirt/containerized-data-importer#1234]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind enhancement

**What happened**:
now, when import data from URL, the disk.img is always raw type. do we have a plan to support other disk type: like qcow2 ?
**What you expected to happen**:
user can choose disk type when import data from url
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by qwang1** [comment]
@scuzhanglei We do support QCOW2 disk type. See https://github.com/kubevirt/containerized-data-importer/blob/master/doc/supported_operations.md#supported-matrix
Then QEMU will convert disk images to RAW and write to the storage.
