### ISSUE TITLE
[flaky test] [rfe_id:138][crit:high][vendor:cnv-qe@redhat.com][level:component] Upload tests [test_id:4274] Upload datavolume with long name creates correct scratch space, pod and service names

### ISSUE THREAD

**Issue by nunnatsa** [kubevirt/containerized-data-importer#1239]
/kind bug

Test appears flaky on pull-containerized-data-importer-e2e-os-3.11.0-crio.

*24h report*: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/containerized-data-importer/flakefinder-2020-06-16-024h.html#row0

**Comment by brybacki** [comment]
It looks like a network failure - `connect: no route to host`, if it repeats then we will look deeper:

https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1230/pull-containerized-data-importer-e2e-os-3.11.0-crio/1272649076814385152/artifacts/pods/1_cdi-a01lt_cdi-uploadproxy-84477594c7-4kwdc-cdi-uploadproxy.log

**Comment by brybacki** [comment]
did not repeat in more than week

**Comment by brybacki** [comment]
Did not reoccur in last 8 days

**Comment by awels** [comment]
Closing based on above.
