### ISSUE TITLE
[flaky test] [rfe_id:138][crit:high][vendor:cnv-qe@redhat.com][level:component] Upload tests [test_id:4275] Upload datavolume with long name including special chars '.' - creates correct scratch space, pod and service names

### ISSUE THREAD

**Issue by nunnatsa** [kubevirt/containerized-data-importer#1240]
/kind bug

Test appears flaky on pull-containerized-data-importer-e2e-k8s-1.17-hpp.

24h report: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/containerized-data-importer/flakefinder-2020-06-16-024h.html#row0

**Comment by brybacki** [comment]
This test, the same way as in issue #1239, looks like temporary network error: `connect: connection timed out`. It only failed once. There is nothing unusual in other logs. 

https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1230/pull-containerized-data-importer-e2e-k8s-1.17-hpp/1272535826533715968/artifacts/pods/1_cdi-gmnp2_cdi-uploadproxy-7cbfc57667-mb5kb-cdi-uploadproxy.log

**Comment by brybacki** [comment]
did not repeat in more than a week,

**Comment by awels** [comment]
Closing based on above.
