### ISSUE TITLE
[Flaky Test]  [vendor:cnv-qe@redhat.com][level:component]DataVolume tests Verify DataVolume should [test_id:3932]succeed creating dv from imageio source

### ISSUE THREAD

**Issue by nunnatsa** [kubevirt/containerized-data-importer#1241]
/kind bug

Test appears flaky on pull-containerized-data-importer-e2e-k8s-1.17-ceph.

24h report: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/containerized-data-importer/flakefinder-2020-06-16-024h.html#row0

**Comment by brybacki** [comment]
This is interesting. I need to consult the details.

DV is missing condition Running with reason Completed. 
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1230/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1272535826542104577/artifacts/1_dvs.log

PVC probably looks good:
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1230/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1272535826542104577/artifacts/1_pvcs.log

**Comment by AlonaKaplan** [comment]
Another failing job with the same issue - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1256/pull-containerized-data-importer-e2e-os-3.11.0-crio/1275796476714291200
