### ISSUE TITLE
Upload Go Server doesn't handle CORS Preflight

### ISSUE THREAD

**Issue by glekner** [kubevirt/containerized-data-importer#1251]
**BUG REPORT**: 
/kind bug

**What happened**:
When triggering a `POST` Request from Javascript, adding an `Authorization` Header triggers a [
CORS Preflight](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request)

Console Error:
```
Access to fetch at 'https://cdi-uploadproxy-cdi.apps.ostest.test.metalkube.org/v1alpha1/upload-async' from origin 'http://localhost:9000'
has been blocked by CORS policy: Response to preflight request
doesn't pass access control check: 
No 'Access-Control-Allow-Origin' header is present on the requested resource.
If an opaque response serves your needs, set the request's mode to 'no-cors'
to fetch the resource with CORS disabled
```
**What you expected to happen**:
The Upload server should be able to handle the CORS Preflight `OPTIONS` request.
We need to respond to the preflight request with an `Access-Control-Allow-Methods` response header, which lists `POST`
and `Access-Control-Allow-Origin: *`

**How to reproduce it (as minimally and precisely as possible)**:
Run an Ajax POST request from a browser.
**Anything else we need to know?**:

This Repo might help - https://github.com/rs/cors

**Comment by awels** [comment]
Fixed by #1229

**Comment by glekner** [comment]
Unfortunately it doesn't @awels,
The added header from #1229 is sent as a response to the upload request, it isn't sent as a response to the CORS Preflight request, which happens before the upload request. 
Please correct me if i'm wrong @mhenriks

**Comment by mhenriks** [comment]
The uploadproxy does not handle the `OPTIONS` requests.

**Comment by mhenriks** [comment]
@glekner have you tried doing a "simple request" as described here?

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests

Or maybe the presence of `Authorization` header precludes you doing a simple request?

**Comment by glekner** [comment]
> Or maybe the presence of Authorization header precludes you doing a simple request?

Yes. Adding the `Authorization` header triggers a CORS Preflight.
