### ISSUE TITLE
[flaky ci]Block PV Cloner Test Should clone data across namespaces 

### ISSUE THREAD

**Issue by maya-r** [kubevirt/containerized-data-importer#1266]
/kind bug

Via [flakefinder](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/containerized-data-importer/index.html)

Block PV Cloner Test Should clone data across namespaces

/go/src/kubevirt.io/containerized-data-importer/tests/cloner_test.go:560 Unexpected error: <*errors.errorString | 0xc000390a00>: { s: "DataVolume target-dv not in phase Succeeded within 4m30s", } DataVolume target-dv not in phase Succeeded within 4m30s occurred /go/src/kubevirt.io/containerized-data-importer/tests/cloner_test.go:586

Failing job - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1252/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1275795973028712449

Originally filed as https://github.com/kubevirt/kubevirt/issues/3677 but it'd be better to have it as an issue in the CDI repository.

**Comment by awels** [comment]
Should be addressed by #1255

**Comment by maya-r** [comment]
Closing as the last appearance was 5 days ago, whereas #1255 was 4 days ago.
Sounds right.
