### ISSUE TITLE
 [flaky ci][test_id:1368]Upload tests should succeed given a valid token

### ISSUE THREAD

**Issue by maya-r** [kubevirt/containerized-data-importer#1267]
/kind bug

Via [flakefinder](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/containerized-data-importer/index.html)

[rfe_id:138][crit:high][vendor:cnv-qe@redhat.com][level:component]Upload tests should [test_id:1368]succeed given a valid token

/go/src/kubevirt.io/containerized-data-importer/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43 Unexpected error: <*errors.errorString | 0xc001a6c000>: { s: "Unexpected return value 502 expected 200, Response: {}", } Unexpected return value 502 expected 200, Response: {} occurred /go/src/kubevirt.io/containerized-data-importer/tests/upload_test.go:94

Failing job- https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1252/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1275795973028712449

Originally filed as https://github.com/kubevirt/kubevirt/issues/3676 but it'd be better to have it as an issue in the CDI repository.

**Comment by mhenriks** [comment]
should be addressed here:  https://github.com/kubevirt/containerized-data-importer/pull/1269
