### ISSUE TITLE
[rfe_id:138][crit:high][vendor:cnv-qe@redhat.com][level:component] Upload tests [test_id:3997] Upload image to data volume - kill container and verify retry count

### ISSUE THREAD

**Issue by arnongilboa** [kubevirt/containerized-data-importer#1285]
/kind bug
/triage build-officer

**What happened**:
```
[Fail] [rfe_id:138][crit:high][vendor:cnv-qe@redhat.com][level:component] Upload tests [It] [test_id:3997] Upload image to data volume - kill container and verify retry count 
/go/src/kubevirt.io/containerized-data-importer/tests/upload_test.go:572
```

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1282/pull-containerized-data-importer-e2e-os-3.11.0-crio/1280070581491863553

**Comment by brybacki** [comment]
`            s: "command terminated with exit code 137",` 
probably this can be improved, will look into the problem

**Comment by brybacki** [comment]
and here:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1296/pull-containerized-data-importer-e2e-os-3.11.0-crio/1282397790550364161

**Comment by brybacki** [comment]
I am experimenting on a quick fix here:
https://github.com/kubevirt/containerized-data-importer/pull/1297

**Comment by brybacki** [comment]
does not happen since the #1297 was merged, 
we can close it
