### ISSUE TITLE
VDI files not automatically converted to raw

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/containerized-data-importer#1287]
/kind bug

**What happened**:
Executed `virtctl image-upload` against a VirtualBox VDI disk image
Created VM
Started VM
VM failed to boot saying `no bootable`

qemu supports vdi natively per [doc](https://www.qemu.org/docs/master/system/images.html) and manual process check ... so what gives??

**What you expected to happen**:
VM boots as expected

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
This is pretty silly when CDI has conversion code
https://github.com/kubevirt/containerized-data-importer/blob/master/pkg/importer/data-processor.go#L190
https://github.com/kubevirt/containerized-data-importer/blob/master/pkg/image/qemu.go#L101

There are many many disk img types.  Either we support them natively as qemu does, provide a switch to convert them to raw, or be very explicit about it in docs. 

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
Is this not explicit enough? https://github.com/kubevirt/containerized-data-importer/blob/master/doc/supported_operations.md

**Comment by mazzystr** [comment]
@awels definitely not

**Comment by awels** [comment]
For a variety of reasons we only support RAW and qcow2 conversions with optional xz and gz compression. I am trying to understand what is not sufficient so we can address the issue.

**Comment by mazzystr** [comment]
I'm good with qemu running qcow2 or raw virtual disks.  

This issues is regarding migration of a source virtual disk which could be something else like VMware vmdk or Oracle/VirtualBox vdi.  Right now users are having to manually run `qemu-img` or get a surprise `no boot disk found` error.  I could have swore 2 or 3 weeks ago my vdi auto converted.  That's definitely not happening now.  That is a big loss in functionality whereas oVirt/RHEV and OpenStack world have seamless migration tools.  

Funkier yet it appears there _is_ some auto qemu-img code but it isn't being activated correctly. 

There's also a conversation happening in kubevirt-devel mailing list

**Comment by awels** [comment]
At no point have we supported anything but qcow2 or raw images. if it worked something probably converted it to one of the two formats before you uploaded. I am monitoring that email thread.
