### ISSUE TITLE
[Flaky CI] Cloner Test Suite [test_id:4277] Clone datavolume with long name

### ISSUE THREAD

**Issue by awels** [kubevirt/containerized-data-importer#1290]
/triage build-officer

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Test failed: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1288/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1281217011686313984

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by brybacki** [comment]
ubfortunately no artifacts for this test
