### ISSUE TITLE
[Flaky CI] DataVolume tests Delete PVC during registry import Should create a new PVC when PVC is deleted during import

### ISSUE THREAD

**Issue by awels** [kubevirt/containerized-data-importer#1291]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/triage build-officer
/kind bug
> /kind enhancement

**What happened**:
Test failed: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1288/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1281217011686313984
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by brybacki** [comment]
and again on nfs:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1336/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1292786671821000704
