### ISSUE TITLE
[Flaky CI] [vendor:cnv-qe@redhat.com][level:component]DataVolume tests [rfe_id:1115][crit:high][vendor:cnv-qe@redhat.com][level:component][test] CDI Import from HTTP/S3 [test_id:1990] CDI Data Volume - file is removed from http server while import is in progress

### ISSUE THREAD

**Issue by omeryahud** [kubevirt/containerized-data-importer#1294]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-officer

**What happened**:
Flakefinder reported a flay test:
```
[vendor:cnv-qe@redhat.com][level:component]DataVolume tests [rfe_id:1115][crit:high][vendor:cnv-qe@redhat.com][level:component][test] CDI Import from HTTP/S3 [test_id:1990] CDI Data Volume - file is removed from http server while import is in progress
```
in this Prow job:
- [Timed out](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1281/pull-containerized-data-importer-e2e-k8s-1.18-upg/1280485566932062208)

**What you expected to happen**:
Test to pass
**How to reproduce it (as minimally and precisely as possible)**:
See Prow job
**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by brybacki** [comment]
There are is DV nor the PVC in the artifacts - this is bad, I cannot check the actual values of conditions and annotations, the http-fileserver logs show that the file was removed - then restored - so everythnig is good here, I have no idea what happened. Need to investigate more.
