### ISSUE TITLE
Support importing disks from a Vmware source

### ISSUE THREAD

**Issue by mansam** [kubevirt/containerized-data-importer#1298]
/kind enhancement

In order to support a [VMware provider in the VM Import Operator](https://github.com/kubevirt/vm-import-operator/issues/292), support is needed in CDI for importing disks from a VMware source. This would involve the creation of a new DataVolumeSource. 

Transferring disks from VMware hosts would be done with nbdkit and the VDDK library. Because the VDDK library can't be redistributed, it would need to be provided via some kind of sidecar container with an image that the end user would have to provide.

The DataVolumeSource for VMware will likely need the following fields:

* the ESXi or vCenter URL
* the moRef of the VM this disk is attached to
* the fileName from the virtual disk's VirtualDeviceFileBackingInfo 
* the cert thumbprint of the vCenter or ESXi host
* Reference to a credentials secret containing the username and password

CC @mrnold @fdupont-redhat

**Comment by fdupont-redhat** [comment]
Instead of the ESXi or vCenter URL, I think that `hostname` + `port` would be more generic.

Instead of the `moRef` of the VM, I think that the `UUID` is more valuable, as it is unique across vCenter and ESXi. The `moRef` is different between ESXi and vCenter, which means that passing the `moRef` from the inventory (sync'd from vCenter) to ESXi host would fail. With the `UUID`, you can use the [FindByUuid](https://godoc.org/github.com/vmware/govmomi/object#SearchIndex.FindByUuid) method.

**Comment by mansam** [comment]
`URL` follows the pattern from the other DataVolumeSources, changing to hostname + port would be a break from that convention.

nbdkit wants the moref of the the VM, so we can't pass it the UUID. If in VM Import the import spec is being created with a vCenter URL + moref, then the CDI datasource will get the vCenter URL and moref passed to it. If the spec is created with an ESXi host and moref, that will get passed to the CDI datasource instead.

**Comment by fdupont-redhat** [comment]
Fine to keep `URL` to not break the DataVolumeSources.

About `moRef`, I'll defer to @mrnold. If the importer pod is built with govmomi, it can retrieve the `moRef` from the `UUID`. But does it really need to ship govmomi? @mrnold, besides the fields mentioned in the issue description, do you need to retrieve more properties? If no, then shipping govmomi only to convert `UUID` to `moRef`  seems overkill.

Somehow, one of the layers need to get the correct `moRef`. @mansam, do you think the VMImport CR could be created with the `UUID` and resolve the `moRef` on the fly? This way, the inventory only stores the `UUID`.

**Comment by mrnold** [comment]
The importer pod does not need govmomi right now, so it is easiest to just pass the moRef. But it might need govmomi later for changed block tracking, depending on how we implement warm migration. It might be worth including it pre-emptively if it's not possible to add it in later.

**Comment by fdupont-redhat** [comment]
Oh, that's true. You'll need govmomi for warm migration.
I've also looked at ImageIO data source and it ships with oVirt SDK, so it makes sense to ship govmomi now.
Then, what's the point of passing `moRef` if the importer pod can resolve it from the `UUID`?

**Comment by mansam** [comment]
Ok, I'll update the client to search by UUID since we're going to have the importer resolve the moRef itself.

**Comment by mansam** [comment]
Closing since since #1320 is merged.
