### ISSUE TITLE
[Flaky CI] [rfe_id:1277][crit:high][vendor:cnv-qe@redhat.com][level:component]Cloner Test Suite [test_id:4000] Create a data volume and then clone it while killing the container and verify retry count

### ISSUE THREAD

**Issue by omeryahud** [kubevirt/containerized-data-importer#1301]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-officer

**What happened**:
Flakefinder reported a flaky test
```
[rfe_id:1277][crit:high][vendor:cnv-qe@redhat.com][level:component]Cloner Test Suite [test_id:4000] Create a data volume and then clone it while killing the container and verify retry count
```
in this Prow job:
 - [Prow link](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1292/pull-containerized-data-importer-e2e-os-3.11.0-crio/1282244281364385792)

**What you expected to happen**:
Test to pass
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by brybacki** [comment]
Does not repeat after #1297, might be closed
