### ISSUE TITLE
Support Data Volume Source from another data volume

### ISSUE THREAD

**Issue by nirarg** [kubevirt/containerized-data-importer#1309]
/kind enhancement

**What happened**:
As described under https://kubevirt.io/cdi-api-reference/master/definitions.html#_v1alpha1_datavolumesource,
DataVolumeSource can be HTTP, S3, Registry or an existing PVC.
In order to clone from another DataVolume, currently the only option is to use **PVC**, which has no indication about the DataVolume creation status.
In case the source DataVolume and the target DataVolume are created in parallel, the target DataVolume might be created from not completed source DataVolume.

**What you expected to happen**:
Need to add another DataVolumeSource type: **DataVolume**
When using this DataVolumeSource, the clone process should be start only when the source DataVolume is with status **succeeded**.

**Comment by awels** [comment]
Fixed by #1400
