### ISSUE TITLE
Improve controller unit tests

### ISSUE THREAD

**Issue by jeffvance** [kubevirt/containerized-data-importer#131]
The current controller unit tests are more like functional tests in that they call higher level functions (`NewController`, `ProcessNextItem`) rather than some of lower level funcs (which may need to be exported?).
1.  We should _consider_ moving the current unit tests to _/test/_ so they are treated as functional tests and create real controller unit tests.
2.  We probably should remove the tests using an empty namespace since this is not a supported condition.

**Comment by shiywang** [comment]
@jeffvance are you plan to work on this ? 
@nellyc unit test is not QE's responsibility right ? so I guess the related card should be no-qe IIUC.

**Comment by jeffvance** [comment]
@shiywang yes, one of us will work on more granular controller unit tests.

**Comment by jeffvance** [comment]
Also see pr #174

**Comment by nellyc** [comment]
this should be measured by #216

**Comment by jeffvance** [comment]
various test related prs have basically fixed this issue and we also now use goveralls for code coverage.
