### ISSUE TITLE
import image failed. qemu-img: Could not open '/data/disk.img'

### ISSUE THREAD

**Issue by Sad-polar-bear** [kubevirt/containerized-data-importer#1311]
import image failed.what is't this fault

I0723 09:23:12.132964       1 data-processor.go:207] New phase: Process
I0723 09:23:12.133003       1 data-processor.go:207] New phase: Convert
I0723 09:23:12.133014       1 data-processor.go:213] Validating image
E0723 09:23:12.148667       1 prlimit.go:174] qemu-img failed output is:
E0723 09:23:12.148686       1 prlimit.go:175]     (0.00/100%)

E0723 09:23:12.148694       1 prlimit.go:176] qemu-img: file system may not support O_DIRECT
qemu-img: Could not open '/data/disk.img': Could not open '/data/disk.img': Invalid argument

E0723 09:23:12.148747       1 data-processor.go:204] exit status 1
qemu-img execution failed
kubevirt.io/containerized-data-importer/pkg/system.executeWithLimits
	pkg/system/prlimit.go:178
kubevirt.io/containerized-data-importer/pkg/system.ExecWithLimits
	pkg/system/prlimit.go:111
kubevirt.io/containerized-data-importer/pkg/image.convertToRaw
	pkg/image/qemu.go:102
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream

**Comment by awels** [comment]
The problem is this: E0723 09:23:12.148694 1 prlimit.go:176] qemu-img: file system may not support O_DIRECT

What kind of storage are you using? If you are using NFSv3 it won't work, need a minimum of NFSv4

**Comment by mhenriks** [comment]
Looks like the filesystem on your scratch PVC does not support O_DIRECT.

This PR disabled filesystem caching when converting to raw:  https://github.com/kubevirt/containerized-data-importer/pull/1102

I think we should revisit that issue.  Disabling cache at the OS level is not a appropriate fix IMO.

**Comment by Sad-polar-bear** [comment]
I sloved this problem.Because of file system type is tmpfs
