### ISSUE TITLE
when my pvc is remote ceph storage,how can I import vm image to pvc

### ISSUE THREAD

**Issue by Sad-polar-bear** [kubevirt/containerized-data-importer#1314]
Hi,
   Now,I have a remote ceph. I use storageclass bond ceph pool to a pvc, and I want to import vm image to pvc, it doesn't work.Please help me.
 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-pvc
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "http://mys3.com/pushs3/CentOS7.2_AMD64_v3-20200723184927.0"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 55Gi
  storageClassName: ceph-storage-class

it doesn't work: 
[root@openstack-stein03 Kubevirt]# kubectl get po
NAME                READY   STATUS              RESTARTS   AGE
importer-ceph-pvc   0/1     ContainerCreating   0          49min

**Comment by Sad-polar-bear** [comment]
kubectl describe show: 

Events:
  Type     Reason                  Age    From                     Message
  ----     ------                  ----   ----                     -------
  Normal   Scheduled               2m19s  default-scheduler        Successfully assigned default/importer-ceph-pvc to 10.175.130.230
  Normal   SuccessfulAttachVolume  2m19s  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-dd345625-99f6-428b-b046-2d0753850590"
  Warning  FailedMount             16s    kubelet, 10.175.130.230  Unable to attach or mount volumes: unmounted volumes=[cdi-data-vol], unattached volumes=[cdi-data-vol default-token-hbtwv]: timed out waiting for the condition

**Comment by Sad-polar-bear** [comment]
I have solved this problem,thks

**Comment by flywalker** [comment]
What is the cause and how to solve it
