### ISSUE TITLE
[flaky test][rfe_id:138][crit:high][vendor:cnv-qe@redhat.com][level:component]Upload tests should succeed given a valid token (form) [It]

### ISSUE THREAD

**Issue by stu-gott** [kubevirt/containerized-data-importer#1315]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/triage build-officer

**What happened**:

```
 • Failure [162.331 seconds]
[rfe_id:138][crit:high][vendor:cnv-qe@redhat.com][level:component]Upload tests
/go/src/kubevirt.io/containerized-data-importer/tests/upload_test.go:45
  should
  /go/src/kubevirt.io/containerized-data-importer/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
    succeed given a valid token (form) [It]
    /go/src/kubevirt.io/containerized-data-importer/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43
    Unexpected error:
        <*errors.errorString | 0xc0007a0000>: {
            s: "Unexpected return value 502 expected 200, Response: {}",
        }
        Unexpected return value 502 expected 200, Response: {}
    occurred
    /go/src/kubevirt.io/containerized-data-importer/tests/upload_test.go:111
```

**What you expected to happen**:
test should pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Prow job: 
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1310/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1286334366905012224

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by awels** [comment]
So the 502 is the k8s api server saying it is busy. We get these every once in a while due to the CI system being under high load. Its transient and not a bug.

**Comment by stu-gott** [comment]
Closed base on comment by @awels
