### ISSUE TITLE
Getting "readlink: illegal option -- f" when building on macOS

### ISSUE THREAD

**Issue by visheshtanksale** [kubevirt/containerized-data-importer#1317]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Make fail with following error
```
$ make all
./hack/build/in-docker.sh "DOCKER_PREFIX= DOCKER_TAG= VERBOSITY= PULL_POLICY= NAMESPACE= ./hack/build/build-manifests.sh"
readlink: illegal option -- f
usage: readlink [-n] [file ...]
make: *** [manifests] Error 1
```
The `readlink` on macOS does not support `--f` option. 
**What you expected to happen**:
CDI should build cleanly.
**How to reproduce it (as minimally and precisely as possible)**:
Execute on macOS machine `make all` 
**Anything else we need to know?**:
Is macOS a support platform for building CDI. I can create a PR to replace using readlink with more platform independent command.

**Comment by awels** [comment]
None of us use macs for development, so if you can provide a PR that will help, we are more than happy to look at it and accept it that makes it work for you.
