### ISSUE TITLE
While running the first lab on a fresh CDI install on openSuse's Kubic, cannot get VM to run. 

### ISSUE THREAD

**Issue by birdiesanders** [kubevirt/containerized-data-importer#1327]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind enhancement

**What happened**:
I applied the spec from the lab to create the VM, started it with virtctl, and it remains in "scheduling" permanently. 

Error logs:2020-08-04T04:22:28.900455133Z  {"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/testvm","pos":"vm.go:789","reason":"failed to find a sourceFile in containerDisk containerdisk: Failed to check /proc/1/root/var/disk for disks: open /proc/1/root/var/disk: no such file or directory","timestamp":"2020-08-04T04:22:28.900396Z"}

**What you expected to happen**:
I expect the VM to start.

**How to reproduce it (as minimally and precisely as possible)**:
Install a kubic cluster, install CDI per the documentation, run the first lab exactly. 

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v0.31.0
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T00:00:00Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"

- Cloud provider or hardware configuration: Kubic installs in plain VMs, rancher local-path and longhorn for PV storageclasses.

- Install tools:
- Others:

**Comment by awels** [comment]
Are you sure this doesn't belong in the kubevirt tracker?
