### ISSUE TITLE
[Flakey CI] [rfe_id:138][crit:high][vendor:cnv-qe@redhat.com][level:component] Upload tests Upload datavolume creates correct scratch space, pod and service names [test_id:4273] with short DataVolume name

### ISSUE THREAD

**Issue by omeryahud** [kubevirt/containerized-data-importer#1338]
/kind bug
/triage build-officer

**What happened**:
Flakefinder found this to be flakey test:
```
[rfe_id:138][crit:high][vendor:cnv-qe@redhat.com][level:component] Upload tests Upload datavolume creates correct scratch space, pod and service names [test_id:4273] with short DataVolume name
```
It failed on this job with a 502 response code (maybe due to high CI load?):
- https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1336/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1292786671825195008

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by omeryahud** [comment]
Happened again here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1350/pull-containerized-data-importer-e2e-k8s-1.18-hpp/1306567592877494272

**Comment by maya-r** [comment]
Happened again after we added retries here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1452/pull-containerized-data-importer-e2e-k8s-1.18-hpp/1318916210141696000

0x68 seems to be "connection reset by peer".
