### ISSUE TITLE
[Flaky CI]Operator delete CDI tests [test_id:3954]should delete an upload pod

### ISSUE THREAD

**Issue by alonSadan** [kubevirt/containerized-data-importer#1352]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug
/triage build-officer
> /kind enhancement

**What happened**:
came up by the falke finder on two PRs #1348  #1347 :
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1348/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1299990503575523328
**What you expected to happen**:
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
pull-containerized-data-importer-e2e-k8s-1.17-ceph lane.

**Comment by omeryahud** [comment]
Another failure here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1342/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1306254529540395008
