### ISSUE TITLE
[Flaky CI] [rfe_id:138][crit:high][vendor:cnv-qe@redhat.com][level:component]Upload tests should succeed given a valid token (form async)

### ISSUE THREAD

**Issue by phoracek** [kubevirt/containerized-data-importer#1355]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1351/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1301182358656913408

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
This is caused by high load on CI servers, the 502 is because the kubeapi server was not responding in time.
