### ISSUE TITLE
[Flaky CI] Namespace with quota Should create clone in namespace with quota

### ISSUE THREAD

**Issue by tiraboschi** [kubevirt/containerized-data-importer#1368]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Flakefinder reported a flaky test:

```Namespace with quota Should create clone in namespace with quota```

Today we got it here:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1360/pull-containerized-data-importer-e2e-k8s-1.18-hpp/1303306101449560064
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1362/pull-containerized-data-importer-e2e-k8s-1.18-upg/1303319953599893504

In both the cases the issue is due to a timeout:
```
/root/go/src/kubevirt.io/containerized-data-importer/tests/cloner_test.go:694
Unexpected error:
    <*errors.errorString | 0xc000514a60>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
/root/go/src/kubevirt.io/containerized-data-importer/tests/cloner_test.go:1094
```

**What you expected to happen**:
No timeout error

**How to reproduce it (as minimally and precisely as possible)**:
Check logs of Prow jobs

**Anything else we need to know?**:
It's just fleky CI, on other executions is successfully passed.
Maybe it's just about raising the timeout limit

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
Fixed by #1363
