### ISSUE TITLE
[Flaky CI] [rfe_id:138] ... Upload tests should succeed given a valid token (alpha)

### ISSUE THREAD

**Issue by tiraboschi** [kubevirt/containerized-data-importer#1369]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Flakefinder reported a flaky test:

`[rfe_id:138][crit:high][vendor:cnv-qe@redhat.com][level:component]Upload tests should succeed given a valid token (alpha)`

We got it on:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1360/pull-containerized-data-importer-e2e-k8s-1.18-hpp/1304019301732192257

due to
```
/root/go/src/kubevirt.io/containerized-data-importer/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43
Unexpected error:
    <*errors.errorString | 0xc00035e010>: {
        s: "Unexpected return value 502 expected 200, Response: {}",
    }
    Unexpected return value 502 expected 200, Response: {}
occurred
/root/go/src/kubevirt.io/containerized-data-importer/tests/upload_test.go:113
```

**What you expected to happen**:
No failures

**How to reproduce it (as minimally and precisely as possible)**:
Flaky CI

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
Yeah we have random failures like this every once in a while. The 502 comes from the kube api server. This usually means the CI host is overloaded and the cluster is so slow it won't respond in time. Not much we can do about it.
