### ISSUE TITLE
[Flaky CI] ... [test_id:2555]fail creating import dv: invalid qcow large size 

### ISSUE THREAD

**Issue by tiraboschi** [kubevirt/containerized-data-importer#1370]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Flakefinder reported a flaky test:
`[vendor:cnv-qe@redhat.com][level:component]DataVolume tests Verify DataVolume should [rfe_id:1120][crit:high][posneg:negative][test_id:2555]fail creating import dv: invalid qcow large size`

It's a timeout issue:

```
• Failure [317.268 seconds]
[vendor:cnv-qe@redhat.com][level:component]DataVolume tests
/root/go/src/kubevirt.io/containerized-data-importer/tests/datavolume_test.go:35
  Verify DataVolume
  /root/go/src/kubevirt.io/containerized-data-importer/tests/datavolume_test.go:116
    should
    /root/go/src/kubevirt.io/containerized-data-importer/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
      [rfe_id:1120][crit:high][posneg:negative][test_id:2555]fail creating import dv: invalid qcow large size [It]
      /root/go/src/kubevirt.io/containerized-data-importer/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43
      Timed out after 270.000s.
      Expected
          <bool>: false
      to be true
      /root/go/src/kubevirt.io/containerized-data-importer/tests/datavolume_test.go:202
```
We got it more than once:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1360/pull-containerized-data-importer-e2e-k8s-1.18-upg/1303306101453754368
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1360/pull-containerized-data-importer-e2e-k8s-1.17-hpp/1303306101436977152

**What you expected to happen**:
No failures

**How to reproduce it (as minimally and precisely as possible)**:
Flaky CI

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
Fixed by #1363
