### ISSUE TITLE
Efficient cross namespace PVC cloning

### ISSUE THREAD

**Issue by salanki** [kubevirt/containerized-data-importer#1467]
> /kind enhancement

**Abstract**:
Current PVC cloning between namespaces copies the data between the PVCs. This is both slow, and a waste of resources. The current in-namespace cloning depends on Volume Snapshots. The snapshot based clone can be replaced by [CSI Volume Cloning](https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/) which will lead to faster clones requiring less ceremony.

The CSI Volume Cloning can also be leveraged to do instant, zero-copy cross-namespace volume cloning.

**Implementation**:
The cross-namespace cloning can be achieved in a semi hacky way using the following process:

Assume the cloned PVC is `A` and the target is a new PVC named `C` in a different namespacae.

- Create a new PVC, `B` in the source namespace with `dataSource` set to PVC `A`.
- Once created. Patch the newly created PVC `B` with `{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'`
- Store the name of the `PersistentVolume` allocated to `B` in memory.
- Delete PVC `B`
- Patch the `PersistentVolume` and remove `spec.claimRef`
- Create the new PVC `C` in the target namespace with `volumeName` set to the name of PV backing the now deleted PVC
- Patch PVC `C` with `{"spec":{"persistentVolumeReclaimPolicy":"Reclaim"}}'`

To ensure security, apply the same permission checks as for the current copy based cross-namespace volume cloning. This method requires `storageClass` to be the same. If they differ, fall back to the copy method.

**Comment by salanki** [comment]
It seems as you build docker images the same way as in Kubevirt:

```
export DOCKER_PREFIX=registry.gitlab.com/atlantic-crypto/kubevirt
export DOCKER_TAG=my-tag
make push
```

**Comment by mhenriks** [comment]
Our intention has been to leverage a community implementation of PVC namespace transfer to implement this feature.  But there has not been a lot of traction (partially my fault for not pushing hard enough).  Here is the latest KEP:  https://github.com/kubernetes/enhancements/pull/2110

**Comment by fdupont-redhat** [comment]
Isn't it possible to simply delete the PVC in the source namespace, set the `claimRef` on the PV to the future PVC in the destination namespace and then create the new PVC ?

There might be a race condition during deletion of the PVC and setting the `claimRef`, but there may be an annotation that can be set before deleting the PVC and that would make the PV unavailable for other PVCs.

**Comment by fdupont-redhat** [comment]
Nevermind my comment. I should have read the referenced KEP. What is the plan to get the KEP accepted?

**Comment by salanki** [comment]
> Isn't it possible to simply delete the PVC in the source namespace, set the `claimRef` on the PV to the future PVC in the destination namespace and then create the new PVC ?
This is pretty much what we do in #1552.

**Comment by fdupont-redhat** [comment]
It's not that obvious from the doc in the PR. But, I probably lack some terminology to fully grasp the content :)

**Comment by brybacki** [comment]
As discussed on the PR #1552, there were some bits missing to approve and merge it. The idea and the implementation was actually good, but it conflicted with some more generic requirements.

As of now, the "Cluster scoped DataVolume/PVC namespace transfer API" #1673 is merged, and also the CEPH in the CI was updated (https://github.com/kubevirt/kubevirtci/pull/562), so we can go back to the 1552 and implement the efficient clone. 

Part of the original PR is already implemented in a different way (ns transfer), and there are merge conflicts now, so it would require more work and a new clean PR. 

@salanki , @YitzyD: I noticed you were really interested in moving things forward, and I suppose you already use this solution in production. We now have the capacity to work on the task and finalize it. Are you still working on some version of #1552? Are you OK if I take the task and adapt the code to use the new #1673?

**Comment by salanki** [comment]
We are currently using this PR in production successfully. As much as we would like to refactor #1552 to use #1673, we don't have the bandwidth to do it ourselves at this time, so please go ahead and take a crack at it. We are here to answer any questions you might have.

**Comment by brybacki** [comment]
That is great, I am on it.

**Comment by brybacki** [comment]
In progress: [1824]( https://github.com/kubevirt/containerized-data-importer/pull/1824)
This now works with CDI - Size Expansion and Namespace Transfer, PR is not yet finished, now working on some last bugs, cleanup and documentation.

**Comment by brybacki** [comment]
@salanki , @YitzyD: feel free to look and comment on https://github.com/kubevirt/containerized-data-importer/pull/1824

I have added a full test suite (reusing most of existing clone tests), and I still need to update the documentation. 

The only functional differences I can think of is are:
- dv status: CloneSourcePVLost (handled somewhere in existing datavolume-controller as error) and CloneTargetPVCLost (re-using Failed with reason ErrClaimLost and message specifying the pvc name)
- annotation AnnCSICloneCapable is not available. Right now to use CSI Volume Cloning one has to update the `StorageProfile.Spec.ClaimPropertySets[0].CloneStrategy = cdiv1.CloneStrategyCsiClone`
```
	AnnCSICloneCapable     = "cdi.kubevirt.io/CSICloneVolumeCapable" // Annotation for the target storageClass denoting whether the underlying CSI Driver supports CSI Volume Cloning ("true"/"false")
```

**Comment by brybacki** [comment]
@t3hmrman There is a PR in progress that might address some of your problems:
https://github.com/kubevirt/containerized-data-importer/pull/2004

**Comment by t3hmrman** [comment]
Thanks for the heads up @brybacki , that looks like it will help for the cross namespace issue!
