### ISSUE TITLE
Tests does not work in disconnected cluster environment

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/containerized-data-importer#1468]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 
> Uncomment only one, leave it on its own line:

/kind bug

**What happened**:
When trying to run CDI tests inside of disconnected environment, there are issues with test-infra containers.
In the disconnected environment we populate internal registry with all necessary container images, we use ICSP to point all pull requests to our internal registry.
There is one issue (best practice) with ICSP, it doesn't allow tags (latest, vX.Y.Z, etc), so we have to use digest for all images.

We are able to modify all test-manifests to use proper images and also digests, but we can not control what init containers do.

For an example, there is this cdi-docker-registry-host pod.
```
# oc logs -f cdi-docker-registry-host-7b4765c769-r5kdm -c registry-populate

[..]

STEP 1: FROM kubevirt/container-disk-v1alpha         <<<< HERE IS NO DIGEST SPECIFIED AND ICSP WILL NOT ROUTE IT
error creating build

(Full log in car)
```
Which then result in:
```
# oc logs -f cdi-docker-registry-host-7b4765c769-r5kdm -c registry

2020/11/05 14:30:28 http: TLS handshake error from [::1]:35246: remote error: tls: bad certificate
2020/11/05 14:40:33 http: TLS handshake error from [::1]:47336: remote error: tls: bad certificate
```

**What you expected to happen**:
Ability to run CDI tests in disconnected environment.

**How to reproduce it (as minimally and precisely as possible)**:

Run tests in disconnected environment.

**Comment by chadcrum** [comment]
Also to add - Besides the fact that there is no digest on `STEP 1: FROM kubevirt/container-disk-v1alpha`, it also seems to be occurring within the container, so the ICSP on the cluster will not translate the image to the local disconnected registry.

If there was a parameter to control the source in the deployment manifest, it would be easier to control.
