### ISSUE TITLE
[vendor:cnv-qe@redhat.com][level:component]DataVolume tests Verify DataVolume should [rfe_id:1115][crit:high][test_id:1478]succeed creating import dv with given valid registry url

### ISSUE THREAD

**Issue by ashleyschuett** [kubevirt/containerized-data-importer#1472]
Is this a BUG REPORT or FEATURE REQUEST?:

/kind bug

/triage build-officer

What happened:
Flakefinder reported a flaky test

[vendor:cnv-qe@redhat.com][level:component]DataVolume tests Verify DataVolume should [rfe_id:1115][crit:high][test_id:1478]succeed creating import dv with given valid registry url

in this Prow job:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1463/pull-containerized-data-importer-e2e-k8s-1.17-hpp/1323313161767489536

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1463/pull-containerized-data-importer-e2e-k8s-1.18-upg/1323354935298887681

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1463/pull-containerized-data-importer-e2e-k8s-1.18-upg/1323313161754906624

What you expected to happen:
Test to pass
How to reproduce it (as minimally and precisely as possible):

Anything else we need to know?:

Environment:

    CDI version (use kubectl get deployments cdi-deployment -o yaml):
    Kubernetes version (use kubectl version):
    Cloud provider or hardware configuration:
    Install tools:
    Others:

**Comment by ashleyschuett** [comment]
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1448/pull-containerized-data-importer-e2e-k8s-1.17-hpp/1323270630056923136

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1448/pull-containerized-data-importer-e2e-k8s-1.18-hpp/1323270630052728832

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1448/pull-containerized-data-importer-e2e-k8s-1.18-upg/1321916334354731009

**Comment by tomob** [comment]
Fixed with #1620
