### ISSUE TITLE
Issue with Validation of Image with CDI

### ISSUE THREAD

**Issue by MarkSpencerTan** [kubevirt/containerized-data-importer#1497]
> /kind bug

**What happened**:
We have a use case where we need to configure a VM and then snapshot the disk image and reuse it for future VM deployments.

I was able to pull the disk image from the VM's compute pod in the folder that gets mounted from the persistent storage volume, and then used that to build a new image, however, when I deploy another VM with that updated image I get the following error:

https://gist.github.com/MarkSpencerTan/b8a841c958fe444cead5d9fe63021672

What's weird is when I use the exact same image but without the CDI and only using the containerDisk option of kubevirt, the VM spins up just fine. Also when running QEMU manually with the .img/qcow2 disk it spins up just fine.

**What you expected to happen**:

Expecting the CDI to import the image and the persistent storage would be instantiated for the vm.

**How to reproduce it (as minimally and precisely as possible)**:

1. Spin up a VM in kubevirt using DataVolumes/CDI
2. Copy the running disk using `kubectl cp` from within the compute container of the VM
3. Build the disk again and publish it to a docker registry to use for another deployment
4. Spin up a new VM with the updated image and the cdi imported pod should throw the same errors.

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v.1.26.0
- Kubernetes version (use `kubectl version`): 1.17.13

**Comment by awels** [comment]
Are you saying the VM is running while you copy the disk image? If so, there is no practical way to guarantee that what you copy is going to be a valid image.

**Comment by MarkSpencerTan** [comment]
> Are you saying the VM is running while you copy the disk image? If so, there is no practical way to guarantee that what you copy is going to be a valid image.

@awels yep it's currently running when I pull it from the pod. I tested the image and it works with Qemu just fine or if I launch it without CDI in kubevirt as only a containerDisk, but are you suggesting there could've been some other thing that could've gotten messed up as a result of copying the image while it's in running state?

I tried to set the VM to running:false before pulling the disk but it kills the pod where I'm copying the disk image from so I'm not sure how I'm able to grab the disk without it running.

I guess after I kill the vm I can spin up another pod and have that pod use the persistent volume created by CDI and I can potentially extract it from that pod instead of the one spun up by kubevirt. I was hoping there would be an easier way though :( what do you think?

**Comment by MarkSpencerTan** [comment]
@awels I tried extracting the disk image when it was stopped and the same error is happening.

**Comment by awels** [comment]
So the normal workflow is to clone the pvc using CDI when the VM is stopped. Example on how to do this is here: https://github.com/kubevirt/containerized-data-importer/blob/master/doc/clone-datavolume.md
