### ISSUE TITLE
Large qcow2 image fails using cdi upload proxy service exposed over NodePort with unexpected return value 400

### ISSUE THREAD

**Issue by soodpr** [kubevirt/containerized-data-importer#1509]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**: 
1. installed single node 1.17.3+k3s1 on Ubuntu 18.04 VM.
2. Install v0.34.2 kubevirt+ virtctl
3. Install v1.26.1 cdi
4. create uload-pvc.yaml as below:

> apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload-pvc
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.upload.target: ""
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 110Gi
5. Try uploading .qcow2 image using virtctl image-upload as shown below:
virtctl image-upload --uploadproxy-url=https://<cluster-ip>:31001/v1alpha1/upload --pvc-name=upload-pvc --pvc-size=110Gi --image-path=<path-to-qcow2-image> --insecure

6. Uploading fails with unexpected return value 400, Saving stream failed: Virtual image size 107374182400 is larger than available size 25367150592 (PVC size 107374182400, reserved overhead 0.055000%). A larger PVC is required

**What you expected to happen**:
Successfully uploaded the image

**How to reproduce it (as minimally and precisely as possible)**:
Steps are mentioned above

**Anything else we need to know?**:
Also, converted the .qcow2 image to raw and then compressed it using gzip but it fails with “unexpected return value 500” and cdi-upload-upload-pvc pod logs have error “Unable to transfer source data to target file: unable to write to file: write /data/disk.img: no space left on device”
 
**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 1.26.1
- Kubernetes version (use `kubectl version`): "v1.19.3+k3s3
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by maya-r** [comment]
What does `qemu-img info /path/to/img.qcow2` say?

**Comment by awels** [comment]
If you check the first error message, looks like your upload PVC size is about 25G, while the disk image wants 110G. Are you sure you don't have an existing PVC with the same name that is the smaller size?

**Comment by soodpr** [comment]
> qemu-img info /path/to/img.qcow2

qemu-img info img.qcow2
image: img.qcow2
file format: qcow2
virtual size: 100G (107374182400 bytes)
disk size: 2.9G
cluster_size: 65536
Format specific information:
    compat: 1.1
    lazy refcounts: false
    refcount bits: 16
    corrupt: false

**Comment by soodpr** [comment]
> 25G

you are right, even in the cdi-upload-<pvc> logs, the pvc size it is taking is 25G. sharing the logs below.
[cdi-upload-upload-pvc-pod.txt](https://github.com/kubevirt/containerized-data-importer/files/5627489/cdi-upload-upload-pvc-pod.txt)

Any idea why its not using the upload-pvc which is of 110Gi.

**Comment by awels** [comment]
So it looks like you are using local storage, and that local storage is shared between all the local storage PVs, Since it is upload we cannot determine the format ahead of time, so we have to use scratch space, and then convert it to the target space. So in essence it is using twice the size. I suspect what is happening that you have enough space for upload to the scratch space, but since that is using the same storage as the target once written there is not enough space left for the copy. Once done with the upload the scratch space will be released, but for a period of time with an upload we require 2x the space.

However according to your qemu-img info, the actual size used is about 3G. So you need 100G + 3G minimum available of real space on the node you are uploading to.

**Comment by soodpr** [comment]
> So it looks like you are using local storage, and that local storage is shared between all the local storage PVs, Since it is upload we cannot determine the format ahead of time, so we have to use scratch space, and then convert it to the target space. So in essence it is using twice the size. I suspect what is happening that you have enough space for upload to the scratch space, but since that is using the same storage as the target once written there is not enough space left for the copy. Once done with the upload the scratch space will be released, but for a period of time with an upload we require 2x the space.
> 
> However according to your qemu-img info, the actual size used is about 3G. So you need 100G + 3G minimum available of real space on the node you are uploading to.

Thanks @awels for your inputs. I got some pointers and checked my k3s node size using df -h command. It was only 99.5 GiB, so resized it using my ubuntu lvm disk using this [link](https://vander.host/knowledgebase/operating-systems/how-to-resize-an-ubuntu-18-04-lvm-disk/). In my case, its a single node k3s cluster. Closing it since i am able to upload the .qcow2 image and run a VM.
