### ISSUE TITLE
Getting connection refused error while importing private registry image into a DataVolume

### ISSUE THREAD

**Issue by soodpr** [kubevirt/containerized-data-importer#1518]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**: i am getting "Unable to process data: Get http://localhost:5000/v2/: dial tcp [::1]:5000: connect: connection refused" when i am trying to import the docker image build and push to private registry. Below are the steps which i have followed:

1. Create a container image with Docker:
> cat << END > Dockerfile
FROM scratch
ADD img.qcow2 /disk/
END
sudo docker build -t img:latest .

2. Run private registry, tag the docker image and push it to private registry.

> $sudo docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
d29c96a93c4c        registry:2          "/entrypoint.sh /etc…"   26 hours ago        Up 3 hours          0.0.0.0:5000->5000/tcp   registry

> $sudo docker images
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
localhost:5000/img   latest              e155140da089        2 days ago          2.82GB

3. Import the registry image to DV:

> cat << END > datavolume.yaml
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: img-dv
  namespace: vm-images
spec:
  source:
    registry:
      url: " docker://localhost:5000/img:latest"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 330Gi
END

4. Also, i have disabled TLS security:
> kubectl patch configmap cdi-insecure-registries -n cdi \
  --type merge -p '{"data":{"mykey": "localhost:5000"}}'

**What you expected to happen**:
Import of docker image works successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Steps are mentioned above.
**Anything else we need to know?**:
I am able to run CURL commands to check the registry images:
$ curl -X GET http://localhost:5000/v2/img/tags/list
{"name":"img","tags":["latest"]}

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.26.1
- Kubernetes version (use `kubectl version`): 1.19.4+k3s1
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
So CDI is running inside the cluster, so if you have a registry on your local host that will be outside of the cluster, and thus you need some way for cdi to connect to your local registry. Right now you have it pointed to localhost inside the cluster, which would be the pod the importer is running in, which doesn't have the registry. Either run the registry inside the cluster, and push into it, or somehow make the registry on your local machine visible inside the cluster under a particular name, and use that.

**Comment by soodpr** [comment]
> So CDI is running inside the cluster, so if you have a registry on your local host that will be outside of the cluster, and thus you need some way for cdi to connect to your local registry. Right now you have it pointed to localhost inside the cluster, which would be the pod the importer is running in, which doesn't have the registry. Either run the registry inside the cluster, and push into it, or somehow make the registry on your local machine visible inside the cluster under a particular name, and use that.

@awels - thanks for clarifying why its failing. So, i tried following the first approach by running the registry inside the k3s cluster using this [link](https://llimon.github.io/post/k3s-registry/). I am able to run the pod given in this link by pulling the busybox image from private registry but when i try to do same by importing the .qcow2 image to DataVolume, its failing with error shown in the DataVolume description: 
Warning  Error             4s (x2 over 6s)  datavolume-controller  Unable to process data: Get https://1ocalhost:5000/v2/: dial tcp: lookup 1ocalhost on 10.43.0.10:53: server misbehaving

**Comment by soodpr** [comment]
Able to resolve the issue by changing the configmap cdi-insecure-registries to point to private registry's host IP instead of localhost.
I am assuming that since k3s cluster is running on virtualized host and cdi will be trying to contact that localhost. 
Registry can be accessed on host IP where its running, so i have replaced it and it worked.
