### ISSUE TITLE
"v1beta1.upload.cdi.kubevirt.io" failed with: OpenAPI spec does not exist

### ISSUE THREAD

**Issue by rmohr** [kubevirt/containerized-data-importer#1525]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

**What happened**:

This happened with `v1alpha1` in the past and is happening again with the new `v1beta1` api:

```
E1210 00:09:42.123318       1 controller.go:116] loading OpenAPI spec for "v1beta1.upload.cdi.kubevirt.io" failed with: OpenAPI spec does not exist
```

The apiserver tries actually pretty often to re-read it and writes this a lot to the logs over time. Not sure if has any effect apart from that.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 1.26.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
This seems like a duplicate of #666 which got fixed recently by #1485

**Comment by rmohr** [comment]
> This seems like a duplicate of #666 which got fixed recently by #1485

This is not yet in 1.26.1?

**Comment by awels** [comment]
No it is in 1.27.0

**Comment by rmohr** [comment]
> No it is in 1.27.0

ack. Closing  then. Thanks.

/close
