### ISSUE TITLE
[flaky ci] [rfe_id:138][crit:high][vendor:cnv-qe@redhat.com][level:component] Upload tests [test_id:1985] Upload datavolume should succeed on retry after failure

### ISSUE THREAD

**Issue by dhiller** [kubevirt/containerized-data-importer#1537]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement
/triage build-watcher

**What happened**:

Test `[rfe_id:138][crit:high][vendor:cnv-qe@redhat.com][level:component] Upload tests [test_id:1985] Upload datavolume should succeed on retry after failure` flaked on PR https://github.com/kubevirt/containerized-data-importer/pull/1534

Run: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1534/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1339281962237431808

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

```
/root/go/src/kubevirt.io/containerized-data-importer/tests/upload_test.go:885
Timed out after 384.077s.
uploadFileNameToPath should return nil, even if not ready
Expected
    <*url.Error | 0xc000a8a810>: {
        Op: "Post",
        URL: "https://127.0.0.1:18443/v1beta1/upload",
        Err: {
            Op: "read",
            Net: "tcp",
            Source: {IP: [127, 0, 0, 1], Port: 49902, Zone: ""},
            Addr: {IP: [127, 0, 0, 1], Port: 18443, Zone: ""},
            Err: {Syscall: "read", Err: 0x68},
        },
    }
to be nil
/root/go/src/kubevirt.io/containerized-data-importer/tests/upload_test.go:930
```

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by phoracek** [comment]
Happened again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1543/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1340554972575567872

**Comment by shwetaap** [comment]
Seen again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1601/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1354083977714995200

**Comment by brybacki** [comment]
I suppose this is part of a more generic problem: https://github.com/kubevirt/containerized-data-importer/issues/1587, we are verifying a partial solution https://github.com/kubevirt/containerized-data-importer/pull/1598 (that should work in environments with robust proxy).
