### ISSUE TITLE
[flaky ci]  all clone tests [rfe_id:1277][crit:high][vendor:cnv-qe@redhat.com][level:component]Cloner Test Suite [test_id:4953]Should clone imported data within same namespace and preserve fsGroup

### ISSUE THREAD

**Issue by dhiller** [kubevirt/containerized-data-importer#1538]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement
/triage build-watcher

**What happened**:

Test `all clone tests [rfe_id:1277][crit:high][vendor:cnv-qe@redhat.com][level:component]Cloner Test Suite [test_id:4953]Should clone imported data within same namespace and preserve fsGroup` flaked on PR https://github.com/kubevirt/containerized-data-importer/pull/1534

Offending run: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1534/pull-containerized-data-importer-e2e-k8s-1.18-upg/1339281962237431810

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

```
/root/go/src/kubevirt.io/containerized-data-importer/tests/cloner_test.go:77
Unexpected error:
    <*errors.errorString | 0xc00027acb0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
/root/go/src/kubevirt.io/containerized-data-importer/tests/framework/pvc.go:172
```

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by phoracek** [comment]
Happened again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1543/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1340554972575567873

**Comment by orenc1** [comment]
Another recurrence on Dec 27th, 2020: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1546/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1340898235035684864
