### ISSUE TITLE
clone token missing, thrown on RancherLabs Harvester platform. When using KCLI for K3S deploy

### ISSUE THREAD

**Issue by larssb** [kubevirt/containerized-data-importer#1553]
> /kind bug

**What happened**:
I get this error:

```
{"level":"error","ts":1609186904.8528516,"logger":"controller","msg":"Reconciler error","controller":"clone-controller","name":"k3s-test-master-0-disk0","namespace":"longhorn-system","error":"clone token missing","errorVerbose":"clone token missing\nkubevirt.io/containerized-data-importer/pkg/controller.validateCloneToken\n\tpkg/controller/clone-controller.go:660\nkubevirt.io/containerized-data-importer/pkg/controller.(*CloneReconciler).validateSourceAndTarget\n\tpkg/controller/clone-controller.go:356\nkubevirt.io/containerized-data-importer/pkg/controller.(*CloneReconciler).reconcileSourcePod\n\tpkg/controller/clone-controller.go:229\nkubevirt.io/containerized-data-importer/pkg/controller.(*CloneReconciler).Reconcile\n\tpkg/controller/clone-controller.go:204\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:209\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:188\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90\nruntime.goexit\n\tGOROOT/src/runtime/asm_amd64.s:1357","stacktrace":"kubevirt.io/containerized-data-importer/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\tvendor/github.com/go-logr/zapr/zapr.go:128\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:237\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:209\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:188\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nkubevirt.io/containerized-data-importer/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\tvendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90"}
```

N.B. the error mentions the namespace *longhorn-system*. That's me trying that namespace. I've also tried it without specifying that namespace. Then the *default* namespace will be used.

When I use [KCLI](https://github.com/karmab/kcli) to create a [K3S](k3s.io) cluster on the RancherLabs [Harvester](https://github.com/rancher/harvester) platform.

My KCLI cmd is: `kcli create kube k3s --paramfile k3s-test_deploy_parms.yml --force`

**What you expected to happen**:

That KCLI is successfull in cloning the required disks for K3S master and worker nodes. Instead I find that error in the logs of the *cdi-deployment...* Pod.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install Harvest, e.g. an ISO install. See [this](https://rancher.com/blog/2020/announcing-harvester-open-source-hyperconverged-infrastructure-software) blog
1. Install KCLI, e.g. with the container method. See [here](https://kcli.readthedocs.io/en/latest/index.html?highlight=macos#container-install-method)
1. Setup KCLI config to use the kubevirt provider. Read [here](https://kcli.readthedocs.io/en/latest/index.html?#kubevirt)
1. Execute `kcli info kube k3s` to get the parameters to use when deploying K3S with the cmd (`kcli create kube k3s --paramfile k3s-test_deploy_parms.yml --force`) mentioned above
1. Execute: `kcli create kube k3s --paramfile k3s-test_deploy_parms.yml --force`

* KCLI will write *Waiting for import to complete...* until it times out. And the *cdi-deployment...* Pod will containt the *clone token missing* err.

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.26.1
- Kubernetes version (use `kubectl version`): v1.19.4+k3s1 (Harvester)
- Cloud provider or hardware configuration: RancherLabs [Harvester](https://github.com/rancher/harvester). On a Dell PowerEdge R710 server 
- Install tools: 
- Others:

----

Thank you very much

**Comment by awels** [comment]
Sounds like an issue with harverster to me. The message indicates that a clone is failing due to a token not being valid. The most likely issue is that the token expired before harvester started the clone.

**Comment by larssb** [comment]
Hi @awels,

Its working. Mr. [Karmab](https://github.com/karmab) made some necessary changes in order to make this work for the [KCLI](https://github.com/karmab/kcli) tool.

So closing.
