### ISSUE TITLE
Load Credentials from other namespaces when the DataVolume source is HTTP or Registry

### ISSUE THREAD

**Issue by zhhray** [kubevirt/containerized-data-importer#1574]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind enhancement

**What happened**:

In most scenarios, I'd like to have a secret managed in a public namespace, but in any other business namespace the datavolume can get a secret from that public namespace.

**What you expected to happen**:
Load k8s secret from other namespaces when the DataVolume source is HTTP or Registry

**How to reproduce it (as minimally and precisely as possible)**:
Add "namespace" parameter for DataVolumeSourceHTTP and DataVolumeSourceRegistry

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by zhhray** [comment]
Can someone respond to this demand? In fact, most of the time, credentials should be handed over to the administrator for unified management. The end user should not have to manage these credentials. So you need to maintain these credentials in a separate namespace.

**Comment by zhhray** [comment]
```bash
type DataVolumeSourcePVC struct {
	// The namespace of the source PVC
	Namespace string `json:"namespace"`
	// The name of the source PVC
	Name string `json:"name"`
}
```
In fact, I think that since DataVolume with source type`DataVolumeSourcePVC` allows to specify other namespaces, other sources should be able to support this, right?

**Comment by zhhray** [comment]
> I am sorry, I missed this coming in. The main problem is that we did not give the service account for CDI the ability to read secrets out of other namespaces. The only namespace it has access to is the namespace cdi is installed in. Secrets are very sensitive so we are very reluctant in giving the SA the ability to read them out of other namespaces.

```bash
type DataVolumeSourcePVC struct {
	// The namespace of the source PVC
	Namespace string `json:"namespace"`
	// The name of the source PVC
	Name string `json:"name"`
}
```
In fact, I think that since DataVolume with source type`DataVolumeSourcePVC` allows to specify other namespaces, other sources should be able to support this, right?

**Comment by awels** [comment]
Well that is for cloning a PVC from one namespace to another. That is an entirely different class of objects vs secrets. We also implemented a bunch of safety checks before allow a clone. For instance the person cloning need the appropriate rbac in both namespaces in order for the clone to be allowed.
