### ISSUE TITLE
[flaky CI] Connection reset on upload tests: Syscall: "read", Err: 0x68 

### ISSUE THREAD

**Issue by brybacki** [kubevirt/containerized-data-importer#1587]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-watcher
> /kind enhancement

**What happened**:
Tests fail:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1562/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1349817936973402113
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1562/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1349817936973402113
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1564/pull-containerized-data-importer-e2e-k8s-1.17-hpp/1349559485869330433
with:
```
Expected
    <*url.Error | 0xc0004483c0>: {
        Op: "Post",
        URL: "https://127.0.0.1:18443/v1beta1/upload-async",
        Err: {
            Op: "read",
            Net: "tcp",
            Source: {IP: [127, 0, 0, 1], Port: 42062, Zone: ""},
            Addr: {IP: [127, 0, 0, 1], Port: 18443, Zone: ""},
            Err: {Syscall: "read", Err: 0x68},
        },
    }
to be nil
```
   

**What you expected to happen**:
Test pass
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by maya-r** [comment]
0x68 is 104:

/usr/include/asm-generic/errno.h:#define	ECONNRESET	104	/* Connection reset by peer */

**Comment by maya-r** [comment]
I suspect kubectl port-forward is flaky. There are quite a lot of bugs opened for it.

**Comment by brybacki** [comment]
upload proxy log:
```
2021/01/14 05:19:34 http: proxy error: dial tcp 10.97.224.46:443: connect: connection refused
```

**Comment by brybacki** [comment]
this might solve part of the problem https://github.com/kubevirt/containerized-data-importer/pull/1598

**Comment by brybacki** [comment]
/reopen
this still needs some investigation
