### ISSUE TITLE
Primary and scratch PV can end up in different zones

### ISSUE THREAD

**Issue by puckipedia** [kubevirt/containerized-data-importer#1592]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
The importer's scratch disk and target disk are in different zones (`failure-domain.beta.kubernetes.io/zone`) from each other, causing the importer to be unschedulable.

**What you expected to happen**:
The importer's scratch disk and target disk are in the same zone, allowing the importer pod to be scheduled, and allowing it to import the image.

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl apply -f examples/import-kubevirt-datavolume.yaml` while using a CSI driver that has more than one zone, and cannot mount PVs cross-zone.

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.29.0
- Kubernetes version (use `kubectl version`): v1.16.15-gke.6000
- Cloud provider or hardware configuration: GKE
- Install tools: Manually used `kubectl apply`
- Others:

**Comment by awels** [comment]
Hi, thanks for the report, can I get some more information as I am a little confused. AFAIK when you have a storage class with multiple zones, the storage class have volumeBindingMode: WaitForFirstConsumer. So if you create a PVC it will be pending until you start a POD that uses it. The same would be true for a scratch PVC. So unless something is misconfigured, when the POD is scheduled and started it should create the PVs that get bound to the PVCs in the same zone as the POD is starting.

Obviously it is not working for you, can you show me the PVCs and the POD yaml?

**Comment by puckipedia** [comment]
Oh, aha! The GCE CSI's default StorageClass is set to `volumeBindingMode: Immediate`, which would explain the behavior seen here, but isn't very obvious to a newcomer to the whole storage infrastructure :) I guess this issue can be closed then?

**Comment by awels** [comment]
Interesting, their documentation: https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/regional-pd#dynamic-provisioning indicates WaitForFirstConsumer in the example. If switching to WFFC solves the problem, feel free to close the issue. If not I will need that extra information.

**Comment by puckipedia** [comment]
Bingo, that was it! After struggling a bit on how to configure the scratch disk storage class, it successfully imported a disk image; thanks for the help!
