### ISSUE TITLE
[flaky CI] ALL Operator tests Operator cert config tests should allow update

### ISSUE THREAD

**Issue by awels** [kubevirt/containerized-data-importer#1596]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-watcher
> /kind enhancement

**What happened**:
Several test runs failed with: ALL Operator tests Operator cert config tests should allow update
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1565/pull-containerized-data-importer-e2e-k8s-1.17-hpp/1351624394878750720
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1565/pull-containerized-data-importer-e2e-k8s-1.17-hpp/1350081798712856576
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by tomob** [comment]
Added some diagnostics with PR #1626.

**Comment by dhiller** [comment]
Seen again here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1631/pull-containerized-data-importer-e2e-k8s-1.18-hpp-destructive/1356712421678387201

**Comment by maya-r** [comment]
flake with diagnostics: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1644/pull-containerized-data-importer-e2e-k8s-1.18-hpp-destructive/1358760418180337664

**Comment by phoracek** [comment]
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1644/pull-containerized-data-importer-e2e-k8s-1.18-hpp-destructive/1358760418180337664
