### ISSUE TITLE
[Flakey CI] [rfe_id:138][crit:high][vendor:cnv-qe@redhat.com][level:component] Upload tests [test_id:1985] Upload datavolume should succeed on retry after failure	

### ISSUE THREAD

**Issue by omeryahud** [kubevirt/containerized-data-importer#1623]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-watcher

**What happened**:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1601/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1354083977714995200
```
• Failure [413.645 seconds]
[rfe_id:138][crit:high][vendor:cnv-qe@redhat.com][level:component] Upload tests
/root/go/src/kubevirt.io/containerized-data-importer/tests/upload_test.go:741
  [test_id:1985] Upload datavolume should succeed on retry after failure [It]
  /root/go/src/kubevirt.io/containerized-data-importer/tests/upload_test.go:951
  Timed out after 384.108s.
  uploadFileNameToPath should return nil, even if not ready
  Expected
      <*url.Error | 0xc0002b0000>: {
          Op: "Post",
          URL: "https://127.0.0.1:18443/v1beta1/upload",
          Err: {
              Op: "read",
              Net: "tcp",
              Source: {IP: [127, 0, 0, 1], Port: 46590, Zone: ""},
              Addr: {IP: [127, 0, 0, 1], Port: 18443, Zone: ""},
              Err: {Syscall: "read", Err: 0x68},
          },
      }
  to be nil
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by nelsonspbr** [comment]
Observed again:
- https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1597/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1356598549369851904
- https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1621/pull-containerized-data-importer-e2e-k8s-1.18-hpp/1356693672736854016

**Comment by dhiller** [comment]
Observed again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1632/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1357322946242154497

**Comment by xpivarc** [comment]
Again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1620/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1358760795692863488

**Comment by phoracek** [comment]
Happened again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1645/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1358778286074761218
