### ISSUE TITLE
VMDK Import crashes when no Snapshot is present in VM object

### ISSUE THREAD

**Issue by cscharfstein-23** [kubevirt/containerized-data-importer#1634]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind enhancement

**What happened**:
When trying to import a VMDK from a vcenter instance the importer container crashes with a SIGSEGV in the vddk-datasource.go file.
**What you expected to happen**:
Succesful import of the VMDK File
**How to reproduce it (as minimally and precisely as possible)**:
Import a VM from vcenter (using source: vddk in the yaml) which never had a snapshot taken. 
However simply deleting all snapshots the VM still seems to import fine.
**Anything else we need to know?**:
I think this might go back to the VM Object not having a snapshot list property when no snapshot was ever taken before. 
**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.28.3
- Kubernetes version (use `kubectl version`): 1.19.4
- Cloud provider or hardware configuration: 4 Node vSphere Cluster
- Install tools:
- Others:

**Comment by mrnold** [comment]
Thanks for your debugging efforts. I think I have managed to reproduce this, but only when the "backingFile" field in my yaml does not exactly match the VMDK name:

```
YAML backingFile: "[iSCSI_Datastore] marnold-nosnap/marnold-nosnap.vmdk "
vCenter Virtual Disk: "[iSCSI_Datastore] marnold-nosnap/marnold-nosnap.vmdk"

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x208d6d4]

goroutine 1 [running]:
kubevirt.io/containerized-data-importer/pkg/importer.(*VMwareClient).FindDiskFromName(0xc000422480, 0xc000042066, 0x35, 0x1b, 0xc000044174, 0x8)
	pkg/importer/vddk-datasource.go:398 +0x424
```

Does this match the crash you are seeing? I found a few places in the code that can fail in similar ways, so I want to make sure I get the right one.

**Comment by cscharfstein-23** [comment]
Hi, 
Yes, that looks pretty similar to what I saw. thanks for the quick response.

**Comment by cscharfstein-23** [comment]
Hi, Unfortunately I ran into this issue again but taking a Snapshot did not resolve it. 
I am 100% certain about the backingFile name in the YAML:
`backingFile: "[vsanDatastore] 07de1b60-1683-085c-2706-7cd30a57dc28/ubuntu-container.vmdk" `
Copied from vCenter: `[vsanDatastore] 07de1b60-1683-085c-2706-7cd30a57dc28/ubuntu-container.vmdk`
And I keep seeing Go Exceptions in the importer again:
`I0204 13:17:23.968279       1 importer.go:52] Starting importer
I0204 13:17:23.968395       1 importer.go:132] begin import process
I0204 13:17:23.968409       1 vddk-datasource.go:763] Creating VDDK data source: backingFile [[vsanDatastore] 07de1b60-1683-085c-2706-7cd30a57dc28/ubuntu-container.vmdk], currentCheckpoint [], previousCheckpoint [], finalCheckpoint []
I0204 13:17:24.058113       1 vddk-datasource.go:447] VM 421f2fc0-afd7-c61a-be03-581e96f297c8 found in datacenter Datacenter:datacenter-3 @ /Datacenter: vm-3913
I0204 13:17:24.059951       1 vddk-datasource.go:308] Current VM power state: poweredOff
I0204 13:17:24.063749       1 vddk-datasource.go:329] Logged out of VMware.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2089b84]
goroutine 1 [running]:
kubevirt.io/containerized-data-importer/pkg/importer.(*VMwareClient).FindDiskFromName(0xc0002f0e80, 0xc000044016, 0x4a, 0x1b, 0xc000042114, 0xc)
	pkg/importer/vddk-datasource.go:397 +0x424
kubevirt.io/containerized-data-importer/pkg/importer.createVddkDataSource(0xc000046012, 0x16, 0xc000048057, 0x1b, 0xc000042114, 0xc, 0xc000040064, 0x3b, 0xc00004800e, 0x24, ...)
	pkg/importer/vddk-datasource.go:778 +0x429
kubevirt.io/containerized-data-importer/pkg/importer.NewVDDKDataSource(...)
	pkg/importer/vddk-datasource.go:759
main.main()
	cmd/cdi-importer/importer.go:168 +0x1c76`

**Comment by mrnold** [comment]
Oh okay, so it was looking for the disk on a different VM entirely. That makes sense, thanks for the log snippet. I will change this so it shows a more helpful error message instead of just crashing.
