### ISSUE TITLE
[flaky ci] [vendor:cnv-qe@redhat.com][level:component]DataVolume tests Delete PVC during registry import [test_id:4962]Should create a new PVC when PVC is deleted during import 

### ISSUE THREAD

**Issue by dhiller** [kubevirt/containerized-data-importer#1642]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

/triage build-watcher

**What happened**:

Test flaked: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1632/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1357322946233765888

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

```
/root/go/src/kubevirt.io/containerized-data-importer/tests/datavolume_test.go:1503
Unexpected error:
    <*errors.errorString | 0xc0000e7870>: {
        s: "DataVolume test-dv not in phase Succeeded within 10m0s",
    }
    DataVolume test-dv not in phase Succeeded within 10m0s
occurred
/root/go/src/kubevirt.io/containerized-data-importer/tests/datavolume_test.go:1534
```

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by xpivarc** [comment]
Again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1620/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1358760795692863488
