### ISSUE TITLE
smart-clone-controller don't delete the snapshot

### ISSUE THREAD

**Issue by Muyan0828** [kubevirt/containerized-data-importer#1682]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind enhancement

**What happened**:
when i create a VM rootfs use DataVolume which source is PVC(provide by ceph-rbd), cdi cloneStrategyOverride is snapshot, as far as I know, datavolume-controller will create a snapshot for source PVC, and then smart-clone-controller will create a PVC from snapshot, but when targetPVC status change to bound, smart-clone-controller will delete the snapshot, for ceph-rbd, all clones would break if deleted the parent snapshot

**What you expected to happen**:
Can you provide a new cloneStrategyOverride for not deleting snapshots？

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.28.0
- Kubernetes version (use `kubectl version`): v1.19.7
- Cloud provider or hardware configuration: 
- Install tools: 
- Others:

**Comment by mhenriks** [comment]
Hi @Muyan0828 how are you deploying ceph?  And what versions?  And what do you mean by clones breaking?  We test ceph rbd cloning in CI and are not aware of any issues

**Comment by Muyan0828** [comment]
Hi @mhenriks We deploy via rook(v1.4.6), and ceph version is v14.2.11，when a PVC is created from ceph-rbd Snapshot, if the snapshot is removed, the PVC will become unavailable
