### ISSUE TITLE
Resize volume after clone

### ISSUE THREAD

**Issue by salanki** [kubevirt/containerized-data-importer#1687]
/kind enhancement

Follow on to: https://github.com/kubevirt/containerized-data-importer/pull/1552

When using PVC cloning as source for a `DataVolume`, creation fails if the `DataVolume` size is larger than the source PVC size. Often when creating VMs, one wants to have a different disk size than the template disk volumes. Being able to specify this size in the `DataVolume` on creation is a much better UX than having to specify the smaller size of the template in the `DataVolume` on creation, just to have to go back and resize it after.

Resizing on creation can easily be accommodated in the CDI by first cloning the source volume with its original size, and then modifying the size of the newly created PVC. The cloning should not be considered complete until the resize is complete.

**Comment by arnongilboa** [comment]
@tomob , isn't it related to your [PR](https://github.com/kubevirt/containerized-data-importer/pull/1719) to preallocate cloning DV?

**Comment by salanki** [comment]
@yitzyd do you want to push the code you wrote for this to a branch and link it here?

**Comment by aglitke** [comment]
We discussed this at the Dec 5, 2022 Sig Storage meeting and it seems that this issue can be closed.  It is possible to clone to a larger PVC and the online resize functionality will handle any resizing that is necessary.  Are you okay with closing this issue?

**Comment by aglitke** [comment]
Closing per the previous comment.
