### ISSUE TITLE
cdi should add nodeSelector

### ISSUE THREAD

**Issue by llhhbc** [kubevirt/containerized-data-importer#1695]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

/kind enhancement

**What happened**:
I am create kubevirt's vm use dataVolume, but the pvc and pv is binding to node1 that vm should not scheduled to.

**What you expected to happen**:
datavolume's pod should have the same nodeSelector as vm

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
You can specify the node placement in the CDI CR in the spec.workloads https://github.com/kubevirt/containerized-data-importer/blob/main/pkg/apis/core/v1beta1/types.go#L364 this uses the standard nodeplacement/affinity rules.

**Comment by llhhbc** [comment]
I'm talking about dv components, not cdi. When I use local storage, my pvc is bound to a physical machine, and the physical machine bound to pvc should match the physical machine required by my pod, otherwise my pod cannot use the pvc.
@awels cid workloads is not work for me.

**Comment by maya-r** [comment]
I suspect this use case is better handled by [WaitForFirstConsumer](https://github.com/kubevirt/kubevirt/blob/master/docs/localstorage-disks.md#the-problem).

**Comment by awels** [comment]
@maya-r Yes I suspect the same, I am guessing he wants to CDI to magically know which node the VM is going to get scheduled on, and populate the disk on that node. The problem CDI cannot know, only the kubernetes scheduler knows based on the pod requirements of the virt-launcher pod. This is why we build the WFFC mechanism into kubevirt, were we defer populating the disks until after the scheduler has decided where the VM is going to run.

**Comment by llhhbc** [comment]
> @maya-r Yes I suspect the same, I am guessing he wants to CDI to magically know which node the VM is going to get scheduled on, and populate the disk on that node. The problem CDI cannot know, only the kubernetes scheduler knows based on the pod requirements of the virt-launcher pod. This is why we build the WFFC mechanism into kubevirt, were we defer populating the disks until after the scheduler has decided where the VM is going to run.

@awels @maya-r Your pod to be mirrored should use the same nodeSelector as my final vm pod, keeping the same scheduling rules.

**Comment by llhhbc** [comment]
> I suspect this use case is better handled by [WaitForFirstConsumer](https://github.com/kubevirt/kubevirt/blob/master/docs/localstorage-disks.md#the-problem).

@maya-r This can't fulfill my needs
