### ISSUE TITLE
Functionality for user to provide Priority Class for importer/uploader pod

### ISSUE THREAD

**Issue by visheshtanksale** [kubevirt/containerized-data-importer#1696]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind enhancement

**What happened**:
User does not have the ability to specify the priority class for the importer or uploader pod created CDI controller.

**What you expected to happen**:
User should be able to specify the priority class name for the Importer or uploader pod on either the DV object or by some other configuration.

**Anything else we need to know?**:
There are two design options 
1) Adding priority class name field to DV object
2) Adding priority class name field to CDI config object.

**Comment by awels** [comment]
Can you provide any use cases for this? Normally the upload/importer pods should be low priority and if they get killed, we will restart them. Is this more a combination of PriorityClass and Quotas?

**Comment by visheshtanksale** [comment]
Yes it is more of a combination of PriorityClass and Quota. 
User has quota available in a higher priority class but has nothing in the lower priority class. Because CDI does not allow priority class selection user's importer/upload pod do not get scheduled.
Also, for some of the critical VMs it would be really nice to have importer pod do its job without being killed.

**Comment by awels** [comment]
Thanks for the use case, I have created an appropriate card and put it on our backlog for prioritization, of course PRs are welcome, but I think we need to do some brain storming to figure out at what level it makes most sense (I am leaning towards the DV level at this point)

**Comment by visheshtanksale** [comment]
For meal as well it makes more sense to put it on the DV level.

**Comment by visheshtanksale** [comment]
@awels I have create PR https://github.com/kubevirt/containerized-data-importer/pull/1740 with proposed API changes. Please let me know what do you think about it.

**Comment by awels** [comment]
This was merged, closing.
