### ISSUE TITLE
cdi-import want to use registry-mirros config

### ISSUE THREAD

**Issue by mzzgaopeng** [kubevirt/containerized-data-importer#1715]
Hi
When I use the cdi source is the registry, can the relevant configuration file define a configuration similar to "registre-mirrors"

I see insecure-rgistries defined in the configmap of cdi-insecure-registries.

We finally expect to configure two registries. When one of them fails, it will automatically pull the one from the other warehouse, just like applying registry-mirros in docker.

**Comment by awels** [comment]
That is currently not possible. It could be an interesting enhancement, but we would have to figure out the API for this. Right now the url is a single string.

**Comment by mzzgaopeng** [comment]
> That is currently not possible. It could be an interesting enhancement, but we would have to figure out the API for this. Right now the url is a single string.

Recently, I adjusted the transport of cdi-importer to realize the scenario of injecting multiple registries through annotation to support multiple registries.

**Comment by awels** [comment]
Is there a PR you could share? I am sure other people would like this ability as well.
