### ISSUE TITLE
Custom TLS configmap for registry source only works for certain key name

### ISSUE THREAD

**Issue by visheshtanksale** [kubevirt/containerized-data-importer#1748]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

- Specified custom TLS cert with following keys

```
apiVersion: v1 
data: 
ca_1.pem: | 
-----BEGIN CERTIFICATE----- 
... 
-----END CERTIFICATE----- 
ca_2.pem: | 
-----BEGIN CERTIFICATE----- 
... 
-----END CERTIFICATE----- 
kind: ConfigMap 
metadata: 
name: my-registry-certs 
```

- Added the above config map as  custom TLS cert configmap for a DV with Registry Data Source
I get following error in the importer logs
```
E0224 18:42:42.418638       1 data-processor.go:221] Get https://docker.my-test.com/v2/: x509: certificate signed by unknown authority
```
This works ok for HTTP data source. But it does not work for Registry data source. The Registry data source expects the key name to end with `.crt`.

This seems to be because of the limitation on https://github.com/containers/image mentioned [here](https://github.com/kubevirt/containerized-data-importer/blob/main/vendor/github.com/containers/image/v5/types/types.go#L550) in comments

The CDI [documentation](https://github.com/kubevirt/containerized-data-importer/blob/main/doc/image-from-registry.md#tls-certificate-configuration) states that key names in the custom TLS cert configmap are irrelevant.

**What you expected to happen**:
The key names in custom TLS cert configmap should be irrelevant for Registry Data Sources.

**How to reproduce it (as minimally and precisely as possible)**:
Create a custom TLS cert Config Map with key names not ending with `.crt`. Add this Config Map to data volume with Registry as source.

**Comment by mhenriks** [comment]
Thanks for the bug report!  Off the top of my head, I see a couple ways to fix this:

1.  when creating registry import pod, read in the configmap and explicitly map all the keys with ".crt" extension.  Unfortunately we would lose the dynamic nature of mounting configmap as a directory.  Also would require permission to read configmaps in every namespace

2.  Update the docs.

What do you think @visheshtanksale?

**Comment by visheshtanksale** [comment]
Thanks @mhenriks for your comment. I think updating the docs will be better solution.
