### ISSUE TITLE
Virtctl image-upload keeps resulting in "timed out waiting for the condition"

### ISSUE THREAD

**Issue by lhchang** [kubevirt/containerized-data-importer#1848]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Attempting to upload ISO to CDI via virtctl, operation keeps timing out. Results in stuck in pending cdi-upload-iso pod.
**What you expected to happen**:
Successful upload of ISO pvc to CDI
**How to reproduce it (as minimally and precisely as possible)**:
* Following the guide: https://kubevirt.io/2020/KubeVirt-installing_Microsoft_Windows_from_an_iso.html* 
* Enable port-forwarding for cdi-uploadproxy using `kubectl port-forward service/cdi-uploadproxy 8443:443 -n cdi`
* Tested reach-ability to cdi-uploadproxy with `curl --insecure https://localhost:8443/`
* Attempted image upload using `virtctl image-upload --image-path=/path/to/iso --pvc-name=iso-pvcname --access-mode=ReadWriteOnce --pvc-size=5G --uploadproxy-url=https://localhost:443 --insecure --wait-secs=240`

**Anything else we need to know?**:
The method described worked in a previous Minikube instance that I was working in
**Environment**: 
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.35.0
- Kubernetes version (use `kubectl version`): v1.21.1
- Cloud provider or hardware configuration: Microk8s 
- Install tools: kubevirt yaml files https://github.com/kubevirt/kubevirt/releases/
- Others:

**Comment by awels** [comment]
Hi question, what kind of storage are you using. In particular I want to know if your storage class is WaitForFirstConsumer binding mode.

**Comment by lhchang** [comment]
`kubectl get storageclass` shows No resources found - was there a prior configuration I need to set? I am a bit new to Kubernetes so I had just followed the install guide on the Microk8s site. Prior to that I used Minikube and it looked like there was already a storageclass resource there by default

**Comment by awels** [comment]
Okay so if there is no storage class, do you have any PVs that could bind? Basically the pod is likely not starting because it uses a PVC that is not bound. If you `kubectl describe <upload server pod name>` it should give you an indication why it is still pending. I suspect because there are no PVs to bind to. Especially if there is no storage class.

**Comment by lhchang** [comment]
Creating a default storageclass resource fixed my issue. Thank you for the help!
