### ISSUE TITLE
Why transfer qcow2 file into scratch PVC then convert to raw when using DataVolume with registry source

### ISSUE THREAD

**Issue by LLLLLBJ** [kubevirt/containerized-data-importer#1854]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
Transferring qcow2 file into the destination PVC then specifying qcow2 format type in the domain xml is also workable, I think. Is there any other reason to convert to raw?

**What you expected to happen**:
Directly use qcow2 format type.

**Anything else we need to know?**:
Just for some information, thank you!

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
Well basically because KubeVirt uses RAW images, and not qcow2. qcow2 has a whole bunch of things you can do with that compete with capabilities provided by kubernetes. So if we support qcow2 there can/will be confusion about which (for instance snapshot) will be used when you create a snapshot.
