### ISSUE TITLE
http: TLS handshake error from 10.42.106.192:25399: remote error: tls: bad certificate

### ISSUE THREAD

**Issue by yuchunyun** [kubevirt/containerized-data-importer#1872]
**What happened**:

kubectl apply cdi-operator. yaml and cdi-cr.yaml in a brand new K8S cluster, and cdi-apiserver logs showed many errors

$ export VERSION=$(curl -s https://github.com/kubevirt/containerized-data-importer/releases/latest | grep -o "v[0-9]\.[0-9]*\.[0-9]*")
$ kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-operator.yaml
$ kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-cr.yaml

kubectl -n cdi logs -f cdi-apiserver-6c4d8cd847-j4wp5 
2021/07/28 06:36:39 http: TLS handshake error from 10.42.106.192:25399: remote error: tls: bad certificate
2021/07/28 06:36:39 http: TLS handshake error from 10.42.106.192:22967: remote error: tls: bad certificate

10.42.106.192 is the calico network address of the k8S cluster controller node

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.37.0
- Kubernetes version (use `kubectl version`):v1.20.8
- Install tools:rancher

**Comment by maxiloEmmmm** [comment]
+1

**Comment by maxiloEmmmm** [comment]
@maxiloEmmmm u can kill `cdi-apiserver` pod, cert will ok, this is my case
