### ISSUE TITLE
Is cdi-prometheus-metrics service used by any resource?

### ISSUE THREAD

**Issue by visheshtanksale** [kubevirt/containerized-data-importer#1890]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
It seems like `cdi-prometheus-metrics` service is redundant and can be removed from the CDI deployment. 

The ` prometheus.cdi.kubevirt.io` selector label is present on the cloner and importer pod. But to [get](https://github.com/kubevirt/containerized-data-importer/blob/b27ff563d11bbc6d9bff0e9e2751cd9ffc4cc2c4/pkg/controller/datavolume-controller.go#L2089) the progress of the pod the service is not used. Also, when there are multiple pods on the cluster matching the selector label, I am not sure how will the metrics be collected from all the pods using the service.

**What you expected to happen**:
If the service is not used anywhere it can be removed as part of the CDI installation. Can someone please confirm if the service is indeed not used? If its not used I will open a PR to remove it.

**Comment by awels** [comment]
It was originally added to report progress of transfer. I think at this point it does report resource usage of the transfer pods, but only while the pods are running.

**Comment by visheshtanksale** [comment]
@awels Thanks for clarifying that. Do you know how is the resource usage reported when more than one pod are running and match the service selector.

**Comment by awels** [comment]
IIRC we pass the UUID of the PVC we are populating and use that as part of the keys so we can determine, which is which. I am not sure what exactly still uses the service, if anything though. I guess we can remove it, and see if someone yells at us that it is missing.

**Comment by visheshtanksale** [comment]
Ok I will publish a PR to remove it.

**Comment by awels** [comment]
PR was merged, closing issue
