### ISSUE TITLE
[flaky] cdi-uploadproxy-nodeport" provided port is already allocated

### ISSUE THREAD

**Issue by brybacki** [kubevirt/containerized-data-importer#1988]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

In the test run https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1986/pull-containerized-data-importer-e2e-k8s-1.20-upg/1447744882301997056

Cluster did not start cleanly: The Service "cdi-uploadproxy-nodeport" is invalid: spec.ports[0].nodePort: Invalid value: 31001: provided port is already allocated

**What you expected to happen**:

 A port allocated without conflict.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by brybacki** [comment]
Similar problem:
https://github.com/istio/istio/issues/14499#issuecomment-500641742

**Comment by akalenyu** [comment]
I think I see what's happening, some of our manifests let k8s randomize the nodeport, and maybe that puts
us in a situation where a clash is possible:
https://github.com/kubevirt/containerized-data-importer/blob/main/manifests/templates/imageio.yaml.in#L76-L81

(no `nodePort` field)
