### ISSUE TITLE
Containerized only build breaks downstream

### ISSUE THREAD

**Issue by jobbler** [kubevirt/containerized-data-importer#199]
Containerizing the build process removed the ability to do a non-containerized build. Can the ability to do a non-containerized build be put back into the makefile so that the option is available?

**Comment by jeffvance** [comment]
Can you add more details? What does your downstream build process look like? What error are you getting?  Why won't a containerized build workflow work for you?
Thanks.

**Comment by copejon** [comment]
@jobbler We can implement some branching on a passed in var (e.g. `DOCKER=1 make all`) to disable dockerized builds (default being containerized builds to normalize dev envs).

@jeffvance thoughts?

**Comment by jeffvance** [comment]
@copejon agree. But since containerized builds are somewhat pervasive I want to better understand if there is another approach that allows us to still do the build in a container, like is done for kubernetes...
