### ISSUE TITLE
HTTP proxy fails

### ISSUE THREAD

**Issue by p3lim** [kubevirt/containerized-data-importer#1998]
/kind bug

**What happened**:

Configuring ImportProxy will only set `HTTP_PROXY` and `HTTPS_PROXY`, but according to curl's man page `HTTP_PROXY` is not supported, only `http_proxy` is (the lower case variant).

**What you expected to happen**:
ImportProxy should set both upper and lower case variants of the proxy environment variables.

**How to reproduce it (as minimally and precisely as possible)**:
Be behind a proxy and attempt to download an image over HTTP, it will fail.

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.39.0
- Kubernetes version (use `kubectl version`): 1.23.x
- Cloud provider or hardware configuration: hardware, on-prem
- Install tools: -
- Others: -

**Comment by p3lim** [comment]
@maya-r Any update on this? We're still unable to use CDI.

**Comment by awels** [comment]
@p3lim can you give me an example of a DV that doesn't work for you. We have functional tests in place but we might be missing a code path in that testing. If I have an example that will help. For instance https vs http or with auth and without auth makes a difference on which code path is followed.

**Comment by p3lim** [comment]
Because we've been unable to use it we completely ditched it, hopefully waiting for a fix so we could give it a go again. Because of this we don't have any examples handy.

Setting the HTTP_PROXY env variable has no effect because curl ignores it (see https://everything.curl.dev/usingcurl/proxies/env#http_proxy-in-lower-case-only), so testing with a proxy and only using HTTP should fail your tests.

**Comment by awels** [comment]
Well the thing is, we have functional tests that explicitly tests the proxy is working, with a variety of combinations of http and http, with and without auth. And we verify that the proxy is actually being used in the test (we have a proxy pod, and we check in the logs that the proxy is being used for a particular test). So I am trying to understand what we are not testing or missing in our tests. I can easily enough add lower case versions of the env variable to the pod. But I would like to ensure that solves an issue before I do it, and right now all our tests are working.

**Comment by p3lim** [comment]
I'll try and see if we can find some of the examples we tested with tomorrow and report back, but I'm not sure we kept any.

**Comment by awels** [comment]
So I managed to figure out an example of it not working, and found the problem (there were several actually, a PR to fix them all will arrive shortly)

**Comment by p3lim** [comment]
Great, as I was unable to find any copies of our experiments. Looking forward to seeing the PR(s).
