### ISSUE TITLE
CDI version issues

### ISSUE THREAD

**Issue by jeffvance** [kubevirt/containerized-data-importer#203]
CDI "releases" are arbitrary, do not represent any functional composition, and only serve to keep track of the latest kubevirt version string. There really is no CDI version, instead we have obscured "latest" with  kubvirt's version tag.

Per a recent email from @davidvossel:
_CDI's release are overwritten with every commit. This means that someone using the CDI v0.5.2 will get different code each time they they deploy depending on what happens upstream_

I propose that we either:
1) make CDI releases real and immutable. This means CDI updates its release tag when we have collected a group of prs worthy of being released, and we support that release for some _reasonable_ number of months. It also requires that kubevirt-ansible be able to consume a specific CDI release that may differ from the target kubevirt release tag. Or,
2) stop pretending that CDI has releases and use "latest".

Interested in everyone's thoughts on this. @copejon @screeley44 @erinboyd @davidvossel @aglitke

**Comment by davidvossel** [comment]
Item 1. We need releases. That's the only way other projects can reliably consume CDI. 

At a minimum, each release needs
- Container with release tag
- Source Code
- Release Manifest

Ideally there is a change log as well as list of contributors as well.
Example KubeVirt Release: https://github.com/kubevirt/kubevirt/releases/tag/v0.6.0

**Comment by jeffvance** [comment]
@davidvossel I agree. However, my understanding is that kubevirt-ansible cannot consume images that are not tagged with the same release string as kubevirt. If this is true then that needs to change too. If misunderstand then cdi should be able to implement its own releases.

**Comment by aglitke** [comment]
I thought we just recently merged a PR in kubevirt-ansible that pinned the CDI release to a specific version.  The plan was that CDI would make real releases as appropriate.  Kubevirt-ansible contains a reference to a specific CDI version and will always deploy that version until someone updates that release to a newer one.  What do we need to do to get there?

**Comment by davidvossel** [comment]
>I agree. However, my understanding is that kubevirt-ansible cannot consume images that are not tagged with the same release string as kubevirt. If this is true then that needs to change too. If misunderstand then cdi should be able to implement its own releases.

kubevirt-ansible needs the ability to treat cdi releases separate from kubevirt.  CDI should be able to perform releases at whatever cadence makes sense for the CDI project.

**Comment by jeffvance** [comment]
@aglitke This is fine. Does the CDI release string need to _exactly_ match some expected kubevirt release tag, or does CDI have the freedom to generate releases with its own, unique release strings? IOW, how tied to kubevirt's release ids is CDI?

**Comment by davidvossel** [comment]
@fabiand you may want to weigh in on this discussion

**Comment by shiywang** [comment]
>CDI should be able to perform releases at whatever cadence makes sense for the CDI project.

I'm okay with that, once my e2e [test](https://github.com/kubevirt/kubevirt-ansible/pull/246)  in kubevirt-ansible got merged and we enabled storage in CI test, I think CI will detect each releases matches fit in or not.

we can even use CI to generate a test matrix/grid to show each specific cdi version and kubevirt version functioning well or not.

**Comment by copejon** [comment]
CDI releases will now follow a cadence coinciding with the sprint development cycle.  See https://github.com/kubevirt/containerized-data-importer/blob/master/doc/releases.md#version-and-release 

Changes to the CDI release process addressed by PRs:
#214 #212 #209
