### ISSUE TITLE
kube-scheduler cannot preempt resources during the importer Pod importing image

### ISSUE THREAD

**Issue by iswbm** [kubevirt/containerized-data-importer#2033]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:

Before creating a VM Pod, a temporary Pod will be created to schedule and select a node. After the scheduling is completed, the temporary Pod container will exit immediately after it is started, the Pod will be destroyed, and the corresponding vm resources will be released. After the temporary Pod is destroyed and released , The importer Pod will start to create and work (import the image into the PV). If other Pods enter the scheduler during the import of the image, because the temporary pod that previously carried all the request information of the vm has been released, the new Pod will be scheduled Becomes inaccurate.

**What you expected to happen**:

I hope that the temporary Pod will survive until the import image is completed

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.33.1
- Kubernetes version (use `kubectl version`): v1.20.4
- Cloud provider or hardware configuration: centos7.2
- Install tools: kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-operator.yaml
- Others:

**Comment by brybacki** [comment]
Thank you for creating an issue.

What you describe here is actually an issue for a kubevirt project. kubevirt is coordinating all the pods needed for a VM, CDI is just doing the import. Also, I think this problem is already covered by an issue https://github.com/kubevirt/kubevirt/issues/6531

If you have any ideas that would help or some real-life scenarios please join the discussion here -> https://github.com/kubevirt/kubevirt/issues/6531

**Comment by iswbm** [comment]
Thank you for your reply, it is helpful to me.

**Comment by iswbm** [comment]
> Thank you for creating an issue.
> 
> What you describe here is actually an issue for a kubevirt project. kubevirt is coordinating all the pods needed for a VM, CDI is just doing the import. Also, I think this problem is already covered by an issue [kubevirt/kubevirt#6531](https://github.com/kubevirt/kubevirt/issues/6531)
> 
> If you have any ideas that would help or some real-life scenarios please join the discussion here -> [kubevirt/kubevirt#6531](https://github.com/kubevirt/kubevirt/issues/6531)

Thank you for your reply, it is helpful to me.
