### ISSUE TITLE
non amd64 support is missing

### ISSUE THREAD

**Issue by ggardet** [kubevirt/containerized-data-importer#2048]
/kind enhancement

**What happened**:
I am unable to build for aarch64 because of https://github.com/kubevirt/containerized-data-importer/blob/main/hack/build/build-go.sh#L59
It leads to:
```
[   54s] + env CDI_SOURCE_DATE_EPOCH=1636126007 CDI_GIT_COMMIT=v1.41.0 CDI_GIT_VERSION=v1.41.0 CDI_GIT_TREE_STATE=clean ./hack/build/build-go.sh build cmd/cdi-apiserver cmd/cdi-cloner cmd/cdi-controller cmd/cdi-importer cmd/cdi-uploadproxy cmd/cdi-uploadserver cmd/cdi-operator
[  142s] # kubevirt.io/containerized-data-importer/cmd/cdi-apiserver
[  142s] loadinternal: cannot find runtime/cgo
[  142s] /usr/lib64/go/1.14/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
[  142s] gcc: error: unrecognized command-line option '-m64'
```

**What you expected to happen**:
We should be able to build on non x86_64 architectures.

**How to reproduce it (as minimally and precisely as possible)**:
Try to build for aarch64

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others: openSUSE Tumbleweed aarch64

**Comment by ggardet** [comment]
If I drop `GOARCH=amd64` manually, the build succeeds on aarch64 (and also on x86_64).

**Comment by awels** [comment]
We have nightlies for ARM, just no official releases yet. for example if you look at https://quay.io/repository/kubevirt/cdi-controller?tag=latest&tab=tags you will see the arm nightlies.

**Comment by ggardet** [comment]
> We have nightlies for ARM, just no official releases yet. for example if you look at https://quay.io/repository/kubevirt/cdi-controller?tag=latest&tab=tags you will see the arm nightlies.

Where is the recipe to build those nightlies? I guess some patches are applied. At least to workaround https://github.com/kubevirt/containerized-data-importer/blob/main/hack/build/build-go.sh#L59

**Comment by awels** [comment]
The PR that added support is here https://github.com/kubevirt/containerized-data-importer/pull/1863 and the nightly job is here https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml#L107-L157 but I guess in short we just set BUILD_ARCH to crossbuild-aarch64 and run the bazel build.
