### ISSUE TITLE
importer vm image from http is too slow to use

### ISSUE THREAD

**Issue by fangzx-wang** [kubevirt/containerized-data-importer#2058]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind enhancement

**What happened**: It tooks me about five minutes to finish dv importing from a http image，but only tooks no more than 1 minute if using wget command from that http url on the same node where importer pod locates。 

**What you expected to happen**: Importer pod should has same downloading speed as using wget command

**How to reproduce it (as minimally and precisely as possible)**:
create vm by using dataVolume whose source is from http，
![image](https://user-images.githubusercontent.com/96034048/145759558-9df1b309-667d-4f8e-bba1-982747664db4.png)

**Anything else we need to know?**:
In the importer pod，why can't use "qemu-img covnert" from source http instead of using nbdkit
![无标题](https://user-images.githubusercontent.com/96034048/145760158-6f3ce03e-293c-4165-81c5-dcf810ce1a0f.png)

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.41.1
- Kubernetes version (use `kubectl version`): 1.20
- Cloud provider or hardware configuration: 
- Install tools:
- Others:

**Comment by awels** [comment]
So the CDI importer actually starts an nbdkit server that connects to the http endpoint and downloads the image, and pipes it to qemu-img for conversion. So there are many factors that could contribute to it be a little slower, but there should not be much difference between a direct qemu-img convert and one that goes through nbdkit.

**Comment by fangzx-wang** [comment]
![image](https://user-images.githubusercontent.com/96034048/146137846-570e5588-7bbe-467b-9384-469116cd06c9.png)
Using qemu-img convert on the host from the same srouce http，it only takes 27 seconds.

![image](https://user-images.githubusercontent.com/96034048/146141030-b7308f95-08ec-43eb-b096-5dd45bfacc80.png)
Using nbdkit on the host， it takes about 230 seconds.

Now we can make a conclusion that using nbdkit is slower than qemu-img convert.

**Comment by wonleing** [comment]
Is there a quick way to claim an already exist PVC as a DV? It shouldn't do any copy or upload/download work. It supposes to be completed within 1s @awels

**Comment by awels** [comment]
Yes, we use it in the snapshot restore flow. However I would question the desire to do so. We are looking at actually breaking the relationship between a DV and a PVC once the PVC is populated. The main role of a DV is to describe how you want a PVC populated, once the population completes the DV is basically some extra meta information but it serves no real purpose.

**Comment by wonleing** [comment]
> Yes, we use it in the snapshot restore flow. However I would question the desire to do so. We are looking at actually breaking the relationship between a DV and a PVC once the PVC is populated. The main role of a DV is to describe how you want a PVC populated, once the population completes the DV is basically some extra meta information but it serves no real purpose.

The extra meta info is just what I need!
Currently harvester use DV other than PVC as virtual machine's disk volume. But DV clone is too slow and consume a lot 
 of network resource, since it goes to cdi upload/download way.
I can copy and register a PVC much quicker, so I want to convert such cloned PVC to a DV, or simpler, register a DV with copied files. Any way to do this?

**Comment by wonleing** [comment]
BTW, I guess snapshot is not quite suite for this senario, at leaste the virtual machine can not restart properly with snapshot DV (many cloned vms share a same DV source). So I choose to do full clone

**Comment by alicefr** [comment]
> ![image](https://user-images.githubusercontent.com/96034048/146137846-570e5588-7bbe-467b-9384-469116cd06c9.png) Using qemu-img convert on the host from the same srouce http，it only takes 27 seconds.
> 
> ![image](https://user-images.githubusercontent.com/96034048/146141030-b7308f95-08ec-43eb-b096-5dd45bfacc80.png) Using nbdkit on the host， it takes about 230 seconds.
> 
> Now we can make a conclusion that using nbdkit is slower than qemu-img convert.

The 2 measurements are not completely correct.

Nbdkit doesn't download the image until a block is requested by qemu-img convert so you are converting AND downloading the image. For a fair comparison, you should download the image locally and then expose it with nbdkit, and then doing the conversion.

Additionally, you should use cache=none (for output -t and input -T) otherwise your measurements are influenced by what is saved in cache

**Comment by awels** [comment]
CDI also supports CSI clone if snapshot cloning doesn't work for you. Btw I have heard this argument before that a snapshot clone uses the same image and it fails. And I don't really get it. When CDI does a snapshot clone, it takes a snapshot of the source, and then creates a new PVC setting the dataSource of the PVC to be the snapshot it just created. The CSI driver then should take care of restoring the snapshot into the new PVC, and the new PVC is completely independent of the source PVC. If that is not the case for your CSI driver, then that is a bug in that driver.

You mention harvester, and last time I checked harvester had its own fast cloning mechanism by creating a storage class with some arguments that includes the image name, and each time you create a new PVC in that storage class it would make a copy of the image specified in the storage class. At least that is how I read it, and that mechanism is incompatible with how CDI works.

**Comment by Icedroid** [comment]
@fangzx-wang  @awels  ndbkit curl is very slow especially for a large windows image(4G). Do you have idea how to speed up qemu-img convent.

**Comment by alicefr** [comment]
@Icedroid does the CSI clone or CDI smart cloning could work for you? You need to import the image only once using HTTP importer and then the other PVC are copied/snapshotted from the first one. This should speed up the generation of new PVCs
