### ISSUE TITLE
http endpoint is not valid in s3 importer

### ISSUE THREAD

**Issue by rgordill** [kubevirt/containerized-data-importer#2067]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When using a s3 http endpoint, it is not understood by the importer pod, and instead https is used.

**What you expected to happen**:

Connecting to the s3 endpoint through http and not https.

**How to reproduce it (as minimally and precisely as possible)**:

Using for example a RGW endpoint (ODF) that is exposed through http internally:

```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: rhel85-dv
  namespace: rhel
spec:
  source:
    s3:
      url: "http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local/disk-templates/rhel-8.5-x86_64-kvm.qcow2"
      secretRef: rgw-credentials
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi 
```

The endpoint is passed correctly through the var:

```
    env:
    - name: IMPORTER_SOURCE
      value: s3
    - name: IMPORTER_ENDPOINT
      value: http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local/disk-templates/rhel-8.5-x86_64-kvm.qcow2
    - name: IMPORTER_CONTENTTYPE
      value: kubevirt
```
But the log throws an https endpoint:

```
I1221 11:50:13.019593       1 importer.go:52] Starting importer
I1221 11:50:13.019734       1 importer.go:135] begin import process
I1221 11:50:13.019754       1 s3-datasource.go:130] Endpoint rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local
I1221 11:50:13.019762       1 s3-datasource.go:134] bucket disk-templates
I1221 11:50:13.019766       1 s3-datasource.go:135] object rhel-8.5-x86_64-kvm.qcow2
E1221 11:50:25.297593       1 importer.go:162] RequestError: send request failed
caused by: Get "https://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local/disk-templates/rhel-8.5-x86_64-kvm.qcow2": dial tcp 172.30.233.189:443: connect: no route to host
could not get s3 object: "disk-templates/rhel-8.5-x86_64-kvm.qcow2"
kubevirt.io/containerized-data-importer/pkg/importer.createS3Reader
	/remote-source/app/pkg/importer/s3-datasource.go:147
kubevirt.io/containerized-data-importer/pkg/importer.NewS3DataSource
	/remote-source/app/pkg/importer/s3-datasource.go:58
main.main
	/remote-source/app/cmd/cdi-importer/importer.go:160
runtime.main
	/usr/lib/golang/src/runtime/proc.go:204
runtime.goexit
	/usr/lib/golang/src/runtime/asm_amd64.s:1374
```

**Anything else we need to know?**:

It may be due to the env passed to the pod:

```
    - name: INSECURE_TLS
      value: "false"
```

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): app.kubernetes.io/version: v4.9.1
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3+ffbb954", GitCommit:"3a0f2c90b43e6cffd07f57b5b78dd9f083e47ee2", GitTreeState:"clean", BuildDate:"2021-11-29T05:06:16Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Bare Metal
- Install tools: OLM (OpenShift 4.9.11)
- Others:

**Comment by awels** [comment]
You are correct we have no mechanism for disabling TLS on an S3 client. https://github.com/kubevirt/containerized-data-importer/blob/1e6976e05b68cf794b3a80440cca8af998208c94/pkg/importer/s3-datasource.go#L175 is where we create the s3 client. We did pass it a regular HTTPClient without TLS, but we need to pass it a separate configuration to disable it on line 175. Is there any reason you are not configuring a secure s3 endpoint?

I can probably write the code to disable it, but I would encourage you to enable a secure endpoint.

**Comment by rgordill** [comment]
Yes, in case we deploy an internal ODF, the RGW endpoint is published insecurely for the internal cluster. I agree for external users there should be secured to avoid compromising the data, but in this particular case it will not be necessary.

Additionally, it can confuse if you set up http and the imported does not honored your config.
