### ISSUE TITLE
improve the robustness of qemu-img convert 

### ISSUE THREAD

**Issue by npu21** [kubevirt/containerized-data-importer#2080]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind enhancement

**What happened**:
when I use kubevirt and cdi on arm64, came this error:
root@mgt01:~# kubectl logs -n cie importer-stor-mgt03-system-disk-ssd-40g-0
I1230 00:40:09.336404       1 importer.go:52] Starting importer
I1230 00:40:09.336635       1 importer.go:134] begin import process
I1230 00:40:09.348637       1 data-processor.go:356] Calculating available size
I1230 00:40:09.348679       1 data-processor.go:368] Checking out file system volume size.
I1230 00:40:09.348802       1 data-processor.go:376] Request image size not empty.
I1230 00:40:09.348818       1 data-processor.go:381] Target size 43Gi.
I1230 00:40:09.349057       1 data-processor.go:238] New phase: Convert
I1230 00:40:09.349075       1 data-processor.go:244] Validating image
I1230 00:40:09.349103       1 prlimit.go:127] qemu-image cmd:  qemu-img
I1230 00:40:09.349114       1 prlimit.go:128] qemu-image args:  [info --output=json json: {"file.driver": "http", "file.url": "http://100.126.1.82:18080/system.qcow2", "file.timeout": 3600}]
I1230 00:40:09.349134       1 prlimit.go:129] qemu-image limits: &{1073741824 30}
I1230 00:40:09.398595       1 prlimit.go:127] qemu-image cmd:  qemu-img
I1230 00:40:09.398617       1 prlimit.go:128] qemu-image args:  [convert -t none -p -O raw json: {"file.driver": "http", "file.url": "http://100.126.1.82:18080/system.qcow2", "file.timeout": 3600} /data/disk.img]
I1230 00:40:09.398636       1 prlimit.go:129] qemu-image limits: <nil>
I1230 00:40:09.409336       1 qemu.go:259] 0.00
I1230 00:40:11.421809       1 qemu.go:259] 1.00
I1230 00:40:13.225723       1 qemu.go:259] 2.00
E1230 00:40:13.549269       1 prlimit.go:178] qemu-img failed output is:
E1230 00:40:13.549297       1 prlimit.go:179]     (0.00/100%)
    (1.00/100%)
    (2.00/100%)
E1230 00:40:13.549311       1 prlimit.go:180] qemu-img: curl: Recv failure: Connection reset by peer
qemu-img: error while reading at byte 605159424: Input/output error
E1230 00:40:13.549977       1 data-processor.go:235] exit status 1
qemu-img execution failed
kubevirt.io/containerized-data-importer/pkg/system.executeWithLimits
        /go/src/github.com/kubevirt/containerized-data-importer/pkg/system/prlimit.go:182
kubevirt.io/containerized-data-importer/pkg/system.ExecWithLimits
        /go/src/github.com/kubevirt/containerized-data-importer/pkg/system/prlimit.go:111
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
        /go/src/github.com/kubevirt/containerized-data-importer/pkg/image/qemu.go:142
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
        /go/src/github.com/kubevirt/containerized-data-importer/pkg/importer/data-processor.go:259
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
        /go/src/github.com/kubevirt/containerized-data-importer/pkg/importer/data-processor.go:217
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
        /go/src/github.com/kubevirt/containerized-data-importer/pkg/importer/data-processor.go:167
main.main
        /go/src/github.com/kubevirt/containerized-data-importer/cmd/cdi-importer/importer.go:189
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1148
could not stream/convert image to raw
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
        /go/src/github.com/kubevirt/containerized-data-importer/pkg/image/qemu.go:147
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
        /go/src/github.com/kubevirt/containerized-data-importer/pkg/importer/data-processor.go:259
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
        /go/src/github.com/kubevirt/containerized-data-importer/pkg/importer/data-processor.go:217
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
        /go/src/github.com/kubevirt/containerized-data-importer/pkg/importer/data-processor.go:167
main.main
        /go/src/github.com/kubevirt/containerized-data-importer/cmd/cdi-importer/importer.go:189
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1148
Conversion to Raw failed
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
        /go/src/github.com/kubevirt/containerized-data-importer/pkg/importer/data-processor.go:261
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
        /go/src/github.com/kubevirt/containerized-data-importer/pkg/importer/data-processor.go:217
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
        /go/src/github.com/kubevirt/containerized-data-importer/pkg/importer/data-processor.go:167
main.main
        /go/src/github.com/kubevirt/containerized-data-importer/cmd/cdi-importer/importer.go:189
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_arm64.s:1148
Unable to convert source data to target
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
qemu-img convert -t none -p -O raw json: {"file.driver": "http", "file.url": "http://100.126.1.82:18080/system.qcow2", "file.timeout": 3600} /data/disk.img]  This qemu-img command will fail if network with 100.126.1.82 latency increase to > 10 ms.

**Proposal**
This issue has been resolved and I dug out that the root reason is network latency.
However, to increase the robustness  of CDI，we could download the qcow2(any supported format) first, then qemu-img convert.
Dose it make sense?

**Comment by alicefr** [comment]
@npu21 this would requires always some extra scratch space to store the downloaded file.
