### ISSUE TITLE
Why ? Could I use smart-clone to clone a PVC from an in-use PVC when my CSI support snapshot?

### ISSUE THREAD

**Issue by abserari** [kubevirt/containerized-data-importer#2092]
**What happened**:
Why is smart-clone stuck until the PVC is not in use? I think snapshot could work on running PV, so it seems reasonable to create Snapchat when target PVC is in use.

```go
		inUse, err := r.sourceInUse(datavolume, SmartCloneSourceInUse)
```

pkg/controller/datavolume-controller.go:819
```go
	nn := client.ObjectKeyFromObject(newSnapshot)
	if err := r.client.Get(context.TODO(), nn, newSnapshot.DeepCopy()); err != nil {
		if !k8serrors.IsNotFound(err) {
			return reconcile.Result{}, err
		}

		inUse, err := r.sourceInUse(datavolume, SmartCloneSourceInUse)
		if err != nil {
			return reconcile.Result{}, err
		}
		populated, err := r.isSourcePVCPopulated(datavolume)
		if err != nil {
			return reconcile.Result{}, err
		}
		if inUse || !populated {
			return reconcile.Result{Requeue: true},
				r.updateCloneStatusPhase(cdiv1.CloneScheduled, datavolume, nil, SmartClone)
		}

		if err := r.client.Create(context.TODO(), newSnapshot); err != nil {
			if k8serrors.IsAlreadyExists(err) {
				return reconcile.Result{}, nil
			}

			return reconcile.Result{}, err
		}

		return reconcile.Result{},
			r.updateCloneStatusPhase(cdiv1.SnapshotForSmartCloneInProgress, datavolume, nil, SmartClone)
	}
```

**What you expected to happen**:
Smart Clone not stuck

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a DV
2. Attach dv's PVC to pod
3. Clone DV (CSI should support snapshot)
4. 

**Anything else we need to know?**:
If I remove the check code, it's safe to clone PV?

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 1.40
- Kubernetes version (use `kubectl version`): 1.22
- Cloud provider or hardware configuration: 
- Install tools:
- Others: With ceph CSI

**Comment by brybacki** [comment]
This was done according to official kubernetes documentation, and it works like that for the Smart clone (Snapshot) and for CSI Volume Clone.

Below fragment from k8s doc:
https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/
"The implementation of cloning, from the perspective of the Kubernetes API, adds the ability to specify an existing PVC as a dataSource during new PVC creation. **The source PVC must be bound and available (not in use)**."

The kubernetes allows creating a target PVC with dataSource, so in theory we could create a PVC in this case. If everything works as described, the clone will not progress (target will not be bound), unless storage implementation has a different definition of "_available (not in use)_". 

@mhenriks what do you think?

**Comment by abserari** [comment]
I think it depends on if snapshot could have an intermediate state when snapshot a running PV, and I found that PVC cannot be created in Snapshot in use in some cloud-related documents.

https://access.redhat.com/documentation/zh-cn/openshift_container_platform/4.6/html/storage/persistent-storage-csi-snapshots-create_persistent-storage-csi-snapshots

**Comment by awels** [comment]
Its more about data consistency, kubernetes makes no guarantees about data being consistent when making a snapshot. Nothing is stopping a pod from writing data to the volume while we are trying to make a snapshot. Which could corrupt the snapshot, therefore we follow the kubernetes guidelines and don't allow a clone if the source is in use (ReadWrite) and potentially making changes.
