### ISSUE TITLE
Make the `DataProcessor` extendable by adding new `ProcessingPhase`

### ISSUE THREAD

**Issue by zhuchenwang** [kubevirt/containerized-data-importer#2094]
Hi there,

We have the use case to add customized `ProcessingPhase` in `pkg/importer/data-processor.go`. Right now we just modify the source code but it's not good for maintenance. 

Is it possible to extract the `switch` logic inside `DataProcessor.ProcessDataWithPause()` to be a `map[ProcessingPhase]func()(ProcessingPhase, error)`. Then, the method `ProcessDataWithPause()` will simply lookup the map to process the current phase and provide next phase or error.

The map can be constructed at the object construction time. Also, a method to register new phases and logics can be added.

Is there any objections to this idea? I can send a PR if possible.

**Comment by awels** [comment]
Can you elaborate a little about your use case. The basic idea with the data processor is that we have a set of phases that we think is reasonable defined in an Interface, then we have the different datasources that implement that interface. Each datasource is free to implement the different phases in whatever way they see fit based on their source. Once they are done with a particular phase, they can instruct the data processor to move to a different phase. Then once the datasource phases are done, we have some set phases that we run through to ensure the validity of the image, and maybe do a resize or something.

This has served us well, but we are not against expanding that. In short we allow the datasources to tell the data processor what to do. But you are asking for some kind of mechanism to dynamically expand the phases or just an extra phase that doesn't exist yet?

**Comment by zhuchenwang** [comment]
I want to add extra phases that doesn't exist. Let's say if I have a customized data source that needs extra phases, then I need to add those to the data processor. However, the customized data source might be too specific to contribute to the community. Therefore, I'd like to extend the data processor to register new phases without changing the original data-processor.go file.

**Comment by awels** [comment]
So basically for your needs the interface as defined is not sufficient? Now the data processor loop is very dumb, it just takes the returned next phase, and calls the function associated with that phase from the interface. We could easily replace the switch statement with phase, func map, we would also need some mechanism for a data source to register a new phase with the map.

If you have a PR that would achieve this I would be more than happy to take a look. Note we do require good unit test coverage for PRs in general. So plan on having a mock datasource that registers extra phases for unit tests so we can ensure the functionality is working correctly.

It might also be worth considering the plugin mechanism on a slightly higher level, right now you have to build a custom cdi importer container with your data source. I think it would be nicer if you just build a container with your datasource, that implements some kind of interface that the main cdi importer knows how to use. And we provide a mechanism for you to register your container with cdi, and it automatically adds that to importer container when starting an import.

Thinking about all of this, you probably also have some custom source that you provide to the data volume so it knows to use your custom data source. You are the first one to request a new data source where it doesn't make sense to just add it to the cdi code base, so we have not really thought about a plugin mechanism at all.

**Comment by zhuchenwang** [comment]
Thanks for recommendation. I will try to compose a PR.
