### ISSUE TITLE
Allow specifying a checksum on http imports

### ISSUE THREAD

**Issue by rmohr** [kubevirt/containerized-data-importer#2098]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

It can be that I overlooked it, but I did not find a way to specify a checksum for a http download.
If there is no way, it would be great if it could be added.

**What happened**:

**What you expected to happen**:

I want to avoid situations where I may have a non-booting VM due to a corrupted image which I downloaded.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by brybacki** [comment]
Idea is nice, but isn't it a duplicate of https://github.com/kubevirt/containerized-data-importer/issues/1520

**Comment by rmohr** [comment]
> Idea is nice, but isn't it a duplicate of #1520

Seems so. :)


/close
