### ISSUE TITLE
Do you have any example on how to use the gcr credentials to pull images ?

### ISSUE THREAD

**Issue by cucosion** [kubevirt/containerized-data-importer#2105]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:
I've tried to follow the instructions from the below links without success for gcr json key, I thought to encode the json with base 64 at secretKey and for secretId I've added the _json_key but it's not working
https://github.com/kubevirt/containerized-data-importer/blob/main/doc/image-from-registry.md#private-registry
https://github.com/kubevirt/containerized-data-importer/blob/main/manifests/example/endpoint-secret.yaml

In gcr I've obtained a JSON key and for normal k8s cluster I was creating a secret out of it and after I was adding it to the default service account as image pull secret and it was working fine but it seems that data-importer is not using the default service account imagePullSecrets
kubectl create secret docker-registry docker-registry-credentials --docker-server=gcr.io --docker-username=_json_key --docker-password="$(cat key.json)" --docker-email=any@valid.email
kubectl patch serviceaccount default -p '{​​​​​​​"imagePullSecrets": [{​​​​​​​"name": "docker-registry-credentials"}​​​​​​​]}​​​​​​​'

**What you expected to happen**: to be able to add gcr json key to the provided fields in Opaque Secret or 
containerized-data-importer to be able to pull the images based on existing imagePullSecrets entries

**How to reproduce it (as minimally and precisely as possible)**: just try to pull any image from a secure gcr repository

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
When you say it is not working, what error is it returning? Is it return a credential failure or a certificate failure or something else? Also we recently introduced a new pull method for registry imports that uses the node to pull the image, this way CDI doesn't have to know the pull secret at all as long as the node can pull the image you can import it. Without some more information on exactly what is going wrong I can't really help you. I don't think we ever tried the gcr as a source, so it is likely there is something we are not doing right for that registry.

**Comment by cucosion** [comment]
@awels I tried one more time to encode with base64 the accessKeyId as "_json_key" and the secretKey as base64 encoded content from json key file and **it worked**. https://cloud.google.com/container-registry/docs/advanced-authentication#json-key
It seems that I did something wrong the first time.

**Comment by awels** [comment]
One gotcha I have run into when base64 encoding something on the cli, is that you need to pass it an argument to not append a \n when encoding as that caused a problem in the generated base64 string.

Also note CDI has its own SA, so it doesn't use the default SA and thus you shouldn't have to give the default account access to the pull secret.

**Comment by awels** [comment]
Also we would really appreciate it, if you have figured out how to do it for gcr with steps, that you create a PR to update the documentation on any gcr specific things so other people can find it in the future, thank you.
