### ISSUE TITLE
Report code coverage 

### ISSUE THREAD

**Issue by nellyc** [kubevirt/containerized-data-importer#216]
Set up code coverage calculation on Travis to determine the effectiveness of the unittests

**Comment by screeley44** [comment]
@nellyc - is there an example of how to do that already, I'm assuming that is already done in the kubevirt repo that we can follow?

**Comment by nellyc** [comment]
@screeley44 Yes, it is done in kubevirt, you can probably get more information from @rmohr.
I see they are calling 'go test -cover' in: hack/goveralls.sh and this script is called in .travis.yml

**Comment by rmohr** [comment]
Yes, works exactly like @nellyc said. I think the only thing to add is that we also have a switch which detects if the tests are run on travis and if they are run on the "kubevirt/kubevirt" repo: https://github.com/kubevirt/kubevirt/blob/master/.travis.yml#L23. Also note that in theory it is possible to run goveralls alone and it would  do everything for you, but it has issues with go 1.10. Therefore we first run the tests and then tell goveralls  to upload the results only: https://github.com/kubevirt/kubevirt/blob/master/hack/goveralls.sh#L4.

**Comment by copejon** [comment]
Fixed by #274
