### ISSUE TITLE
Sometimes imports stop at a very high percentage and do not complete

### ISSUE THREAD

**Issue by rmohr** [kubevirt/containerized-data-importer#2160]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug
> /kind enhancement

**What happened**:

This can be realted to the test env, but I still thought I share it. I see in https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7232/pull-kubevirt-e2e-k8s-1.22-sig-compute-migrations/1493508177063317504 sometimes import timeouts, where an impot goes very quickly (less thana second) to almost 100% import and is then stuck for minutes: https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7232/pull-kubevirt-e2e-k8s-1.22-sig-compute-migrations/1493508177063317504/artifacts/k8s-reporter/1/pods/1_kubevirt-test-default1_importer-test-datavolume-plpkpcpcwrw8-importer.log

The system seems to be in general still responsive and no node reports disk pressure. Would be great to have a second pair of eyes on this.

Here another completely different test where the imports is stuck again, like in the other case at 99.86%: https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7187/pull-kubevirt-e2e-k8s-1.21-sig-storage/1491059208068534272/artifacts/k8s-reporter/2/1_overview.log. Job: https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7187/pull-kubevirt-e2e-k8s-1.21-sig-storage/1491059208068534272.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
So looking at the artifacts, I am noting a few things:
1. Its rook-ceph, which might be important combined with the other things
2. The preallocation flag on the importer pod is set to false [search for test-datavolume-plpkpcpcwrw8](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7232/pull-kubevirt-e2e-k8s-1.22-sig-compute-migrations/1493508177063317504/artifacts/k8s-reporter/1/1_pods.log) and scroll down a bit to see the container environment variables, which clearly state preallocation=false.
```json
{
  "name": "PREALLOCATION",
  "value": "false"
}
```
3. The logs of the importer indicate it is trying to do preallocation [here](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7232/pull-kubevirt-e2e-k8s-1.22-sig-compute-migrations/1493508177063317504/artifacts/k8s-reporter/1/pods/1_kubevirt-test-default1_importer-test-datavolume-plpkpcpcwrw8-importer.log)

So I suspect that there is a bug in that it is trying to do preallocation on block devices when the environment variable is set to false. And if you look at the pod logs, it notes that none of the faster preallocation options are available and thus falls back to basically dd'ing 0s into the device. The requested size is 1Gi, so it will write 1Gi of 0s to the device, which in combination which ceph might take a while. Which is what I think is causing the stall in writing when nearly complete. To mitigate you can try reducing the DV size to something smaller and see if that solves the issue while we investigate why it is doing a preallocation when it is not requested.

**Comment by akalenyu** [comment]
> So looking at the artifacts, I am noting a few things:
> 
> 1. Its rook-ceph, which might be important combined with the other things
> 2. The preallocation flag on the importer pod is set to false [search for test-datavolume-plpkpcpcwrw8](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7232/pull-kubevirt-e2e-k8s-1.22-sig-compute-migrations/1493508177063317504/artifacts/k8s-reporter/1/1_pods.log) and scroll down a bit to see the container environment variables, which clearly state preallocation=false.
> 
> ```json
> {
>   "name": "PREALLOCATION",
>   "value": "false"
> }
> ```
> 
> 3. The logs of the importer indicate it is trying to do preallocation [here](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7232/pull-kubevirt-e2e-k8s-1.22-sig-compute-migrations/1493508177063317504/artifacts/k8s-reporter/1/pods/1_kubevirt-test-default1_importer-test-datavolume-plpkpcpcwrw8-importer.log)
> 
> So I suspect that there is a bug in that it is trying to do preallocation on block devices when the environment variable is set to false. And if you look at the pod logs, it notes that none of the faster preallocation options are available and thus falls back to basically dd'ing 0s into the device. The requested size is 1Gi, so it will write 1Gi of 0s to the device, which in combination which ceph might take a while. Which is what I think is causing the stall in writing when nearly complete. To mitigate you can try reducing the DV size to something smaller and see if that solves the issue while we investigate why it is doing a preallocation when it is not requested.

We preallocate all block imports
https://github.com/kubevirt/containerized-data-importer/pull/2001

**Comment by rmohr** [comment]
> We preallocate all block imports
> #2001

Are there in general unwanted side-effects to expect? Like in theory I could imagine unintended storage pressure, if e.g. 20 100Gi disks are writing zeros to everything.

**Comment by awels** [comment]
Yeah, that was exactly my thought when looking at this. We have several tests writing 1Gi 0s and the ceph write buffers are just full, and the network is not fast enough to flush everything to the device. Strangely enough #2001 is supposed to fix a write failure in some tests where it seems we run into a similar problem, we are pushing so much data to ceph, that it cannot allocate the blocks fast enough and things time out. So the pre-allocation is an attempt to mitigate that problem, just have it pre-allocate the blocks and then we should have no problem writing to them. But we have pushed the issue to the pre-allocation step.

**Comment by rmohr** [comment]
@mhenriks @awels did we ever file a bug report regarding to https://github.com/kubevirt/containerized-data-importer/pull/2001 for qemu-img? 

I am not sure I understand all details of the issue and why the fix helps, but if we have a chance to not write 0 everywhere, it may make sense to explore it for scalability reasons.

**Comment by awels** [comment]
I don't quite understand the details of the fix for #2001 either, but the fix that solves the test failure is because we are writing fewer bytes to ceph, and we don't exhaust the ceph buffers as much which makes it easier to recover and continue. In kubevirtci we don't have large buffers for ceph because we want the memory for other things.

**Comment by rmohr** [comment]
@mhenriks @awels any additional insights on this? I would really love to see if we can fix all these issues in a more lazy fashion without having to write intense amounts of 0s during imports.
