### ISSUE TITLE
cdi-bazel-builder: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by BugMosquito** [kubevirt/containerized-data-importer#2211]
**What happened**:

When i build in aarch64 environment, i exec 'BUILD_ARCH=aarch64 make bazel-build' command, it occurs error:

+ docker run -v kubevirt-cdi-volume:/root:rw,z --security-opt label:disable --rm --entrypoint /entrypoint-bazel.sh quay.io/kubevirt/kubevirt-cdi-bazel-builder:0.0.13 mkdir -p /root/go/src/kubevirt.io/containerized-data-importer/_out
standard_init_linux.go:207: exec user process caused "exec format error"

I can't get quay.io/kubevirt/kubevirt-cdi-bazel-builder:0.0.13 image for aarch64, in addition,  When i exec './hack/build/bazel-build-builder.sh', it  can generate cdi-bazel-builder image for amd64, but not support aarch64

**What you expected to happen**:
I can build cdi in aarch64 environment

**How to reproduce it (as minimally and precisely as possible)**:
1. clone code
2. exec  'BUILD_ARCH=aarch64 make bazel-build'

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.42.0
- Kubernetes version (use `kubectl version`): k3s version v1.22.7+k3s1 (8432d7f2)
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Kylin 4.0.2
- Kernel (e.g. `uname -a`): Linux 4.4.131-20200704.kylin.server-generic aarch64 
- Install tools: N/A
- Others: N/A

**Comment by maya-r** [comment]
with [this commit](https://github.com/maya-r/containerized-data-importer/commit/8f07ed125a47baaf3b87ef1ca56843a03f4bf7d2) we build an arm64 builder.

blocked on #1983, kubevirt/project-infra#2000

**Comment by BugMosquito** [comment]
> with [this commit](https://github.com/maya-r/containerized-data-importer/commit/8f07ed125a47baaf3b87ef1ca56843a03f4bf7d2) we build an arm64 builder.
> 
> blocked on #1983, [kubevirt/project-infra#2000](https://github.com/kubevirt/project-infra/pull/2000)


I can across-build aarch64 images  successfully, but i just want to try build aarch64 natively, at present, there are some problems.
