### ISSUE TITLE
why cdi.Spec.CloneStrategyOverride override storageProfile.Status.CloneStrategy?

### ISSUE THREAD

**Issue by ZhangShuaiyi** [kubevirt/containerized-data-importer#2219]
According to [getCloneStrategy](https://github.com/kubevirt/containerized-data-importer/blob/v1.46.0/pkg/controller/datavolume-controller.go#L1671), CDI gets cloneStrategy in the following order:
- cdi.Spec.CloneStrategyOverride
- storageProfile.Status.CloneStrategy
- defaultCloneStrategy(snapshot)

How to configure the cloneStrategy of a specific storageclass when cdi.Spec.CloneStrategyOverride is not empty?

**Comment by brybacki** [comment]
`cdi.Spec.CloneStrategyOverride` is a global override so it changes the whole system behavior and we want to deprecate it. 

The correct way is to normally depend on default behaviour, and when needed - configure strategy on StorageProfile.

**Comment by brybacki** [comment]
There is a way to annotate StorageClass, so then the CDI will create storage profile with selected stategy - this can be done by using the `cdi.kubevirt.io/clone-strategy` annotation on storage class. The annotation can have one of the following values: `copy`, `snapshot`, `csi-clone`. I can see that it is not documented properly. 

I have also noticed that the cloneStrategy behavior is different than the rest of storageprofile: https://github.com/kubevirt/containerized-data-importer/blob/main/doc/storageprofile.md#priorities

**Comment by ZhangShuaiyi** [comment]
> There is a way to annotate StorageClass, so then the CDI will create storage profile with selected stategy - this can be done by using the `cdi.kubevirt.io/clone-strategy` annotation on storage class. The annotation can have one of the following values: `copy`, `snapshot`, `csi-clone`. I can see that it is not documented properly.
> 
> I have also noticed that the cloneStrategy behavior is different than the rest of storageprofile: https://github.com/kubevirt/containerized-data-importer/blob/main/doc/storageprofile.md#priorities

Thanks! I will try it.

**Comment by brybacki** [comment]
But `cdi.Spec.CloneStrategyOverride` is first so it works as `All or Nothing`

**Comment by ZhangShuaiyi** [comment]
Thanks! I will keep `cdi.Spec.CloneStrategyOverride` empty for now.
