### ISSUE TITLE
Provide a jinja2 template for the cdi manifest

### ISSUE THREAD

**Issue by dcritch** [kubevirt/containerized-data-importer#223]
Similar to the request for a j2 version of the kubevirt manifest [0], it would be sweet if we could also get a jinja2 template for the cdi manifest. The work being done to create one for kubevirt [1] likely can be re-used for cdi.

[0] https://github.com/kubevirt/kubevirt/issues/966
[1] https://github.com/kubevirt/kubevirt/pull/1116

See also issues #55 and #252

**Comment by jeffvance** [comment]
But see @davidvossel 's [comment](https://github.com/kubevirt/kubevirt/issues/966#issuecomment-385427933)

**Comment by dcritch** [comment]
Yes, we are aware of the caveat. The automation team is also moving to releases so we should be able to align kubevirt releases with kubevirt-ansible releases. Meanwhile, folks are going to want to be able to specify their own registry/namespace if they are hosting their registry locally, or for offline installs.

**Comment by jeffvance** [comment]
My preference at the moment is to only support Go templates, see issue #55. I am concerned that CDI becomes responsible for several different templates that are related to our versioned manifest. So whenever we need to change the manifests we'd also have to change all related templates. If we provided a Go template for the manifests are you able to convert that into innja2?

**Comment by dcritch** [comment]
That's originally what kubevirt-ansible was doing with kubevirt. While technically possible, it ends up being a messy hack with a bunch of sed's. 

I played around with a go to jinja2 converter and it seemed to work okay, but the issue was more about when to/what triggers that conversion. We'd have to track kubevirt (and cdi) to check for a new release so the j2 could be built.

@rmohr has a great extension to kubevirt's go template builder script that takes care of jinja2. How are the go templates in cdi being built now? Could a similar set of commands be bolted on to it? I dug around the cdi repo and couldn't immediately see it. I'd be happy to help if pointed to the right spot.

**Comment by jeffvance** [comment]
@dcritch 
> How are the go templates in cdi being built now?
We do not build go templates yet but we are planning on doing that at some point, which is what issue #55 is about.
Thanks for the reference to @rmohr's script.
And, btw, if the current CDI priorities are not aligned with your needs please feel free to implement this templating work. Consider Makefile and travis implications. Thanks.

**Comment by shiywang** [comment]
@dcritch are you working on this? if not I'm going to take a look, this is kind of a block for my automation job. cc @nellyc @jeffvance @copejon  as well.

**Comment by jeffvance** [comment]
Note merged pr #269. However, the only manifest that is generated from a template is _cdi-controller-deployment_. We still need to generate and consume the importer and pod manifests.

**Comment by shiywang** [comment]
@jeffvance thanks for the notice, yeah, currently, I think `kubevirt-ansible` need at least the manifest of `cdi-controller-deployment` to be exposed on release page by go template or jinja template, that's the basic requirement, furthermore, maybe we can generate and consume more resource as we need.

**Comment by shiywang** [comment]
@jeffvance @copejon @nellyc could we raise the priority of this issue, it matters `kubevirt-ansible` deployment installation/ e2e tests a lot.

**Comment by jeffvance** [comment]
@shiywang can you provide some more details on how this matters to kubevirt-ansible cdi testing? Thanks.
