### ISSUE TITLE
DataVolume copy block volume failed

### ISSUE THREAD

**Issue by daxiguafan** [kubevirt/containerized-data-importer#2315]
**What happened**:
DataVolume copy block volume failed

**What you expected to happen**:
DataVolume  copy success  

**How to reproduce it (as minimally and precisely as possible)**:
1、copy to block pvc (thist step is ok)
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: url-block
spec:
  source:
      http:
         url: "http://******/download/CentOS-8-GenericCloud-8.2.2004-20200611.2.x86_64.qcow2"
  pvc:
    storageClassName: csi-iscsi-sc
    volumeMode: Block
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 30Gi

2、copy the source block pvc to dest block pvc (this step failed)
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: cloned-datavolume-dts
  namespace: default
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
    storageClassName: csi-iscsi-sc
    volumeMode: Block
  source:
    pvc:
      name: url-block
      namespace: default

upload server fail with log:
E0606 11:58:04.092753       1 data-processor.go:278] open /dev/cdi-block-volume: device or resource busy
could not open file "/dev/cdi-block-volume"
kubevirt.io/containerized-data-importer/pkg/util.OpenFileOrBlockDevice
	pkg/util/util.go:180

**Additional context**:
find the code in pkg/util/util.go 174  
the openFile flag, os.O_EXCL should not setted without os.O_CREATE
      if blockSize >= 0 {
		// Block device found and size determined.
		outFile, err = os.OpenFile(fileName, os.O_EXCL|os.O_WRONLY, os.ModePerm)
	} else {
		....
	}

O_EXCL
If O_CREAT and O_EXCL are set, open() shall fail if the file exists. The check for the existence of the file and the creation of the file if it does not exist shall be atomic with respect to other threads executing open() naming the same filename in the same directory with O_EXCL and O_CREAT set. If O_EXCL and O_CREAT are set, and path names a symbolic link, open() shall fail and set errno to [EEXIST], regardless of the contents of the symbolic link. *[*If O_EXCL is set and O_CREAT is not set, the result is undefined.**](https://linux.die.net/man/3/open)

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): N/A
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by mhenriks** [comment]
Yeah, `O_EXCL` probably shouldn't be used in this case
