### ISSUE TITLE
Smart clone leaves "tmp" PVC in pending, deletes PV

### ISSUE THREAD

**Issue by ninjacoder80** [kubevirt/containerized-data-importer#2323]
**What happened**:

##**Smart Clone leaves "tmp" pvc in pending when cloning from one namespace to another**##
FYI Rook managed Ceph / Ceph-CSI is being used

-----------------------------------------------------------------------------------------------------

**What you expected to happen**:
##**Smart Clone should** ##
1. Create a snapshot of the source PVC
2. Create a PVC from the created snapshot
3. Delete the snapshot
4. Expand the new PVC if requested size is larger than the snapshot
5. If the DataVolume is in a different namespace, "transfer" the PVC to the target namespace via Namespace Transfer API
6. No "tmp" Snaphot PVC should be left behind

-----------------------------------------------------------------------------------------------------

**How to reproduce it (as minimally and precisely as possible)**:

##**CDI import to Datavolume PVC in "golden" namespace** (kubectl apply below)##
```apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: golden-centos-dv
  namespace: golden
spec:
  source:
    http:
      url: "http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2"
  pvc:
    storageClassName: rook-ceph-block
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
```

##**DataVolume clone PVC into new namespace customer1** (kubectl apply below)##
```apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: clone-centos-dv-customer1
  namespace: customer1
spec:
  source:
    pvc:
      namespace: golden
      name: golden-centos-dv 
  pvc:
    storageClassName: rook-ceph-block
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi 
```
-----------------------------------------------------------------------------------------------------

**Additional context**:

##**CDI to pull down image in namespace "golden"**##
```**---DV ---**
NAMESPACE   NAME                PHASE       PROGRESS   RESTARTS   AGE
golden      golden-centos-dv    Succeeded   100.0%                10m
**---PV---**
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                         STORAGECLASS      REASON   AGE     VOLUMEMODE
pvc-0dbeacb9-d433-4e8e-ad41-422f10545431   10Gi       RWO            Delete           Bound    golden/golden-centos-dv       rook-ceph-block            10m     Block
**---PVC---**
NAMESPACE   NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE     VOLUMEMODE
golden      golden-centos-dv    Bound    pvc-0dbeacb9-d433-4e8e-ad41-422f10545431   10Gi       RWO            rook-ceph-block   10m     Block
```
-----------------------------------------------------------------------------------------------------

##**Smart Clone (clone DV PVC image to namespace "customer1" from "golden" ns)**##
```**---DV---**
NAMESPACE   NAME                        PHASE       PROGRESS   RESTARTS   AGE
customer1   clone-centos-dv-customer1   Succeeded   N/A                   2m
golden      golden-centos-dv            Succeeded   100.0%                15m

**---PV---**
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                 STORAGECLASS      REASON   AGE     VOLUMEMODE
pvc-0dbeacb9-d433-4e8e-ad41-422f10545431   10Gi       RWO            Delete           Bound    golden/golden-centos-dv               rook-ceph-block            15m     Block

pvc-31584650-0e8e-49f3-acb1-c91079fa5f56   10Gi       RWO            Delete           Bound    customer1/clone-centos-dv-customer1   rook-ceph-block            117s    Block

**---PVC---**
NAMESPACE   NAME                                           STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE     VOLUMEMODE
customer1   clone-centos-dv-customer1                      Bound     pvc-31584650-0e8e-49f3-acb1-c91079fa5f56   10Gi       RWO            rook-ceph-block   117s    Block

**golden      cdi-tmp-a76ca33a-56a6-4b2e-b375-6665073ac3ce**   **Pending**                                                                        rook-ceph-block   117s    Block

golden      golden-centos-dv                               Bound     pvc-0dbeacb9-d433-4e8e-ad41-422f10545431   10Gi       RWO            rook-ceph-block   15m     Block
```
-----------------------------------------------------------------------------------------------------

##**Ceph pool image dump during Smart Cloning (while true; do rbd ls -p $pool; rbd ls -p $pool | grep -c csi; end)**##
```**--Start--**
csi-vol-24f48bea-ebfa-11ec-9315-8a0dd827368e  <-- golden image (in K8S ns "golden")

**--Next transition (snapshot image create)--**
csi-vol-24f48bea-ebfa-11ec-9315-8a0dd827368e  <-- golden image (in K8S ns "golden")
csi-snap-0d6f7131-ebfc-11ec-9315-8a0dd827368e <-- snapshot of golden image

**--Next transition (snapshot and now clone image--**
csi-vol-24f48bea-ebfa-11ec-9315-8a0dd827368e  <-- golden image (in K8S ns "golden")
csi-snap-0d6f7131-ebfc-11ec-9315-8a0dd827368e <-- snapshot of golden image
csi-vol-0e76e29f-ebfc-11ec-9315-8a0dd827368e  <-- clone of golden (in K8S ns "customer1")

**--Final transition (snapshot image was DELETED though PVC remained in K8S)--**
csi-vol-24f48bea-ebfa-11ec-9315-8a0dd827368e  <-- golden image (in K8S ns "golden")
csi-vol-0e76e29f-ebfc-11ec-9315-8a0dd827368e  <-- clone of golden (in K8S ns "customer1")
```
-----------------------------------------------------------------------------------------------------

**Environment**:
- Component versions
[operator.cdi.kubevirt.io/createVersion=v1.49.0](http://operator.cdi.kubevirt.io/createVersion=v1.49.0)
[controller-gen.kubebuilder.io/version](http://controller-gen.kubebuilder.io/version): v0.7.0
[k8s.gcr.io/sig-storage/csi-attacher:v3.4.0](http://k8s.gcr.io/sig-storage/csi-attacher:v3.4.0)
[k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0](http://k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0)
[k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0](http://k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0)
[k8s.gcr.io/sig-storage/csi-resizer:v1.4.0](http://k8s.gcr.io/sig-storage/csi-resizer:v1.4.0)
[k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1](http://k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1)
[quay.io/cephcsi/cephcsi:v3.6.1](http://quay.io/cephcsi/cephcsi:v3.6.1)
virt-operator:v0.53.1

- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by mhenriks** [comment]
Hi @tzegar, thanks for the detailed bug report, this was very easy to reproduce, will investigate a fix

**Comment by mhenriks** [comment]
Digging into this a bit.  Not sure they share the same root cause but it also appears that `ObjectTransfer` resources are not getting cleaned up either

**Comment by mhenriks** [comment]
Hi @tzegar thanks for the additional info!  Truth, as the number of cloning permutations has expanded over time (dumb clone, smart clone, smart clone with namespace transfer, csi-clone) the code branching in the DataVolume controller has become rather unwieldy and hard to reason about.  I made changes that appear to fix the problem, but I'm not very confident that I haven't broken something else.  This is not a good place to be!  Anyway, I will attempt to address this with a short term fix very soon.  With a more in depth refactor to follow.

**Comment by mhenriks** [comment]
> As can be seen, no "temp" PVC are left in Kube. The only noteworthy thing is that this method (PVC-PVC clone and Obj transfer) doesn't delete the snapshot in the CEPH pool. Now, with respect to the Smart Clone method, idk why they opted to delete the snapshot (the clone references the snapshot via layering, so why trash it? Please reference https://docs.ceph.com/en/quincy/rbd/rbd-snapshot/#getting-started-with-layering

@tzegar I cannot comment comment much about ceph internals.  At the kubernetes level, a VolumeSnapshot source is not required once the target PVC is bound.  Are you implying that keeping the VolumeSnapshot around would be more efficient on the ceph backend?

**Comment by tzegar** [comment]
> > As can be seen, no "temp" PVC are left in Kube. The only noteworthy thing is that this method (PVC-PVC clone and Obj transfer) doesn't delete the snapshot in the CEPH pool. Now, with respect to the Smart Clone method, idk why they opted to delete the snapshot (the clone references the snapshot via layering, so why trash it? Please reference https://docs.ceph.com/en/quincy/rbd/rbd-snapshot/#getting-started-with-layering
> 
> @tzegar I cannot comment comment much about ceph internals. At the kubernetes level, a VolumeSnapshot source is not required once the target PVC is bound. Are you implying that keeping the VolumeSnapshot around would be more efficient on the ceph backend?

Hello Michael,
If K8S allows VolumeSnapshots to be safely deleted with no impact on the final PVC contents, it's fine by be to delete it. 
I'm just curious how that would work with Ceph Parent-Child cloning as referenced in my previous commends. [per Ceph layering the process is parent -> protect snapshot -> clone ([link](https://docs.ceph.com/en/quincy/rbd/rbd-snapshot/#getting-started-with-layering)).

When comparing Smart Clone to PVC-PVC clone (both examples above), for the former I say the snapshot was sent to "trash bin", where as the later did not.

Regardless, I want to ensure the final clone is fully intact, trashing the snapshot just concerns me. Maybe some testing/validation would be nice to ensure all is intact with the Smart Clone method.

Eitherway, the stuck/pending temp PVC with the SmartClone method needs to be handled. I suspect that since the VolumeSnapshot was deleted as part of the process, this cause the snapshot image in Ceph to go to "trash bin", so the temp PVC had to valid PV, hence why it was stuck "pending"
