### ISSUE TITLE
Refactor Controllers - Remove Redundant Code

### ISSUE THREAD

**Issue by copejon** [kubevirt/containerized-data-importer#235]
A significant amount of boilerplate code is duplicated between the CDI, DataVolume, and (soon) the Host Assisted Cloning controller.  After the clone controller is merged, work needs to be done to shore up this redundant code and restructure common functionality into a generic controller.

**Comment by davidvossel** [comment]
> 1) use owner reference and fetch the pod's pvc from the cache (see pr #219 comments).

this my running list of controller changes we need to address at some point. I can help with some of this.  

1. owner references
2. single work queue
3. use expectations so we can trust the cache to be sycned 
4. use the cache to discover which pods are associated with import/clone jobs.

**Comment by zvikorn** [comment]
The refactoring was not completed though. right?

**Comment by davidvossel** [comment]
> The refactoring was not completed though. right?

right, the clone controller still needs to be refactored.

**Comment by zvikorn** [comment]
I meant the CDI :-)
We need super controller, some kind of interface to hold all common methods among the controllers.

**Comment by zvikorn** [comment]
PR - https://github.com/kubevirt/containerized-data-importer/pull/425
