### ISSUE TITLE
Support ReadWriteOncePod for DataVolumes

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/containerized-data-importer#2365]
There's a new pvc accessMode called ReadWriteOncePod which means that a PVC can only be accessed by one pod at a time. The ReadWriteOnce accessMode only guaranteed that a single hosted accessed the PVC at a time, but multiple pods could.

It's possible this is as simple as letting the new AccessMode pass validation as outlined in the patch below.

```
diff --git a/pkg/apiserver/webhooks/datavolume-validate.go b/pkg/apiserver/webhooks/datavolume-validate.go
index 690dbb112..4e28fe5e8 100644
--- a/pkg/apiserver/webhooks/datavolume-validate.go
+++ b/pkg/apiserver/webhooks/datavolume-validate.go
@@ -131,10 +131,10 @@ func (wh *dataVolumeValidatingWebhook) validateDataVolumeSpec(request *admission
                // here in storage spec we allow empty access mode and AccessModes with more than one entry
                accessModes := spec.Storage.AccessModes
                for _, mode := range accessModes {
-                       if mode != v1.ReadWriteOnce && mode != v1.ReadOnlyMany && mode != v1.ReadWriteMany {
+                       if mode != v1.ReadWriteOnce && mode != v1.ReadOnlyMany && mode != v1.ReadWriteMany && mode != v1.ReadWriteOncePod {
                                causes = append(causes, metav1.StatusCause{
                                        Type:    metav1.CauseTypeFieldValueInvalid,
-                                       Message: fmt.Sprintf("Unsupported value: \"%s\": supported values: \"ReadOnlyMany\", \"ReadWriteMany\", \"ReadWriteOnce\"", string(accessModes[0])),
+                                       Message: fmt.Sprintf("Unsupported value: \"%s\": supported values: \"ReadOnlyMany\", \"ReadWriteMany\", \"ReadWriteOnce\", \"ReadWriteOncePod\" ", string(accessModes[0])),
                                        Field:   field.Child("PVC", "accessModes").String(),
                                })
                                return causes
```

**Comment by aglitke** [comment]
Has ReadWriteOncePod moved to beta yet or is it still alpha?

**Comment by alromeros** [comment]
FYI this feature went beta some months ago https://github.com/kubernetes/kubernetes/pull/114494, @akalenyu do we know if the expansion pod issue you mentioned would be a problem?

**Comment by akalenyu** [comment]
> FYI this feature went beta some months ago [kubernetes/kubernetes#114494](https://github.com/kubernetes/kubernetes/pull/114494), @akalenyu do we know if the expansion pod issue you mentioned would be a problem?

Yeah, should still be there, although with populators things may be slightly different.
With WFFC you'd have the user consuming the target ReadWriteOncePod PVC,
so the expansion pod will fail at webhook/scheduling (already occupied by the user's consumer pod)

**Comment by mhenriks** [comment]
> Yeah, should still be there, although with populators things may be slightly different.
> With WFFC you'd have the user consuming the target ReadWriteOncePod PVC,
> so the expansion pod will fail at webhook/scheduling (already occupied by the user's consumer pod)

With populators, the expansion pod is technically consuming a different PVC so there shouldn't be an issue

**Comment by aglitke** [comment]
We discussed this issue again in the January 29 SIG-Storage meeting.  It seems the next step would be for someone to create an exploratory PR that allows RWOP access mode and changes the tests to use it.  This would help us to learn if CDI has any issues with this access mode.  We can add some smoke tests for it but to repeat all of the RWO tests for RWOP seems like overkill.
