### ISSUE TITLE
replace "app=containerized-data-importer" label with "cdi.kubevirt.io"

### ISSUE THREAD

**Issue by jeffvance** [kubevirt/containerized-data-importer#239]
Per comments in pr #237.
Label format would be `cdi.kubevirt.io=""`

**Comment by jeffvance** [comment]
CDI is standardizing labels and the import-controller needs to be updated to use the current cdi.kubevirt.io label. See also pr #237

**Comment by aglitke** [comment]
Would be nice to see all resources created by cdi have the same label applied.  This is what kubevirt does and makes it easy to manage the installation.

**Comment by awels** [comment]
Fixed by #512
