### ISSUE TITLE
When clone dv from an existing pvc use smart clone, some ann of dv can't be inherited by the new pvc.

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/containerized-data-importer#2391]
/kind bug

**Is your feature request related to a problem? Please describe**:
When clone dv from an existing pvc use smart clone, some ann of dv can't be inherited by the new pvc.

**Describe the solution you'd like**:
Some new anns be added to the new dv should be added to the new pvc, when using smart clone.

**Describe alternatives you've considered**:
add some ann in the yaml used to create the new dv from an existing pvc.

kubectl create -f

the new pvc relate to the new dv doesn't have these anns.

**Additional context**:
maybe in some cases, customs want to do this, I add some code in /pkg/controller/smart-clone-controller.go 

```go
	if err := setAnnOwnedByDataVolume(newPvc, dataVolume); err != nil {
		return reconcile.Result{}, err
	}
	if len(dataVolume.GetAnnotations()) > 0 {
		for k, v := range dataVolume.GetAnnotations() {
			if !strings.Contains(k, common.CDIAnnKey) {
				newPvc.Annotations[k] = v
			}
		}
	}
	if snapshot.Spec.Source.PersistentVolumeClaimName != nil {
```
these code works, but may have some pontional problems.

**Comment by awels** [comment]
Hi, thanks for the report, you are absolutely right this is a bug. We support passing annotations on all other kinds of clones (host assisted/csi clone) and there is no reason we shouldn't allow this on a smart clone as well. What you are suggesting seems reasonable for passing annotations from the target DV to the matching target PVC. If you have a PR already feel free to submit it. I might suggest adding a functional test (or modifying a functional test to include annotations)

**Comment by Longchuanzheng** [comment]
> Hi, thanks for the report, you are absolutely right this is a bug. We support passing annotations on all other kinds of clones (host assisted/csi clone) and there is no reason we shouldn't allow this on a smart clone as well. What you are suggesting seems reasonable for passing annotations from the target DV to the matching target PVC. If you have a PR already feel free to submit it. I might suggest adding a functional test (or modifying a functional test to include annotations)

Thank you very much for your timely response，I have create a PR and try to add a 'DCO signoff' to my commits and etc.  Although my code works, but I think these code may not meet the logic of reconcile and need to improve. Meanwhile, I need sometime to adding a functional test.
