### ISSUE TITLE
A featue about exporting vm image from dv to local dir.

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/containerized-data-importer#2432]
**Is your feature request related to a problem? Please describe**:
//A clear and concise description of what the problem is.

In actual use, we may want to export vm image from a dv. Meanwhile CDI doesn't have this feature. 

**Describe the solution you'd like**:
//A clear and concise description of what you want to happen.

export vm image from a dv to local directory or other destination

**Describe alternatives you've considered**:
//A clear and concise description of any alternative solutions or features you've considered.

We can create a new crd now I call it ImageExporter (IE) (may call it DataVolumeExporter or DataExporter probably better) .This crd mainly has Spec DV and Dest. DV represent which dv we want to export, and  Dest represent the local dir we want to export the image to(may be can add destations like url in the future). IE also should has Status like Phase and Progress to indicate current status. 

When create a IE， we can reuse the smart-clone feature, create a tmp DV from the source DV which has been defined by IE.Spec.DV. When tmp DV.Phase change to "succeeded", we create a Pod mount the tmp PVC relate to tmp DV as well as the local dir defined by IE.Spec.Dest. The Pod use command such as "qemu-img convert" to export the image to local dir. Also we should delete all tmp resources like tmp dv and pod after all processes completed.

At present, I have develop this feature preliminary(I haven't finished unit test about my code and features like update IE progress),  and I am welling to contribute these codes to the community.  The problem that I am currently facing is that I have no concept about the code quality the community usually accepted. Such as I used public image which is provided by docker hub,  freely name some var and const(maybe should defined in common package), etc.  I would appreciate it if someone can give me some advices about what should I do.

**Additional context**:
//Add any other context or screenshots about the feature request here.

some screenshots 

if we want to export images from dv XXX-clone-dv1
![image](https://user-images.githubusercontent.com/49519342/191737480-a1303997-e159-4a0a-b4aa-7355abdb7a08.png)

we can edit yaml like this

![image](https://user-images.githubusercontent.com/49519342/191737549-2a897cbe-f79a-4e72-8d03-125f845f6ed9.png)

tmp dv and pod will be create later and delete automatically

and the final ie status

![image](https://user-images.githubusercontent.com/49519342/191737590-038b015c-e7cf-4950-912a-8d6f7ee3956c.png)

also the images has export to dir 
![image](https://user-images.githubusercontent.com/49519342/191737628-18eefc5a-c1ac-4bde-b13f-1fb92edf0320.png)

**Comment by awels** [comment]
I actually just implemented this. The code lives in the kubevirt/kubevirt repo, and the documentation PR can be found here https://github.com/kubevirt/user-guide/pull/549 I checked the kubevirt documentation and could not find the file there yet, so next time the site is updated it should be there.

**Comment by awels** [comment]
Just found it http://kubevirt.io/user-guide/operations/export_api/#export-api

**Comment by Longchuanzheng** [comment]
oh, thank you, that's may be better.

**Comment by Longchuanzheng** [comment]
Hi, I preliminary read the doc and code about the "VirtualMachineExport". In my opinion, the feature which VirtualMachineExport can provide is subtly different from what I illustrate in this issue. I want to export the image of a VirtualMachine (the file format such as .raw, .qcow2, etc). While I think "VirtualMachineExport" is able to  export the whole VirtualMachine . 

Of course, I may have misunderstood about "VirtualMachineExport" and I will do some test manually later. If just like I said in the previous paragraph, this feature may worth discussing.

**Comment by awels** [comment]
So VirtualMachineExport just exports the disks of a VirtualMachine. It provides links for each disk, so you can download just one or all of them depending on your needs. We only export to raw (which is the format the disk is stored in) but if there is demand we can look into other formats. But having a RAW image should make it easy enough to convert to a different format once you get the disk image.

**Comment by Longchuanzheng** [comment]
A powerful feature, thank you for your introduction.
