### ISSUE TITLE
Documentation has wrong casing on config "noProxy"

### ISSUE THREAD

**Issue by cpumanaz** [kubevirt/containerized-data-importer#2443]
**Description**:
The code for spec: -> config: importProxy has "NoProxy" as the key documented, when the code is expecting "noProxy" 

**What you expected**:
The documentation of the configuration matches what the code expects, or the software changed to match the documentation

**URL**:
[Documentation Link](https://github.com/kubevirt/containerized-data-importer/blob/main/doc/cdi-config.md)

**Additional context**:
If you check the history of the commit that adds the importProxy documentation, you can see the source is `noProxy`. I tried that, and my kubectl edit is happy now.

Please change `ImportProxy.NoProxy`. in the documentation to `ImportProxy.noProxy`

**Comment by awels** [comment]
Thanks for the report, I see you fixed the issue in a PR, I just approved it.
