### ISSUE TITLE
Can i see the progress when i set source to upload?

### ISSUE THREAD

**Issue by MLintin** [kubevirt/containerized-data-importer#2449]
**Is your feature request related to a problem? Please describe**:
When i set source to upload , and upload iso to dv by https://cdi-uploadproxy-cdi.$(minishift ip).nip.io/v1alpha1/upload-async ， i can't see the progress 

**Describe the solution you'd like**:
Did I use the wrong method？ or we don't support in now version ? or Do we have a plan to do this？

**Comment by awels** [comment]
This is on purpose, from the server side we cannot see the progress as we don't know how large the data is that we are receiving, and thus we cannot calculate accurate progress.
