### ISSUE TITLE
make publish error

### ISSUE THREAD

**Issue by QZB349549482** [kubevirt/containerized-data-importer#2465]
./hack/build/bazel-docker.sh "DOCKER_PREFIX=dockerhub.kubekey.local/kubesphereio/cdi-controller DOCKER_TAG=v1.0.0 VERBOSITY= PULL_POLICY= CR_NAME= CDI_NAMESPACE= ./hack/build/build-manifests.sh"
Making sure output directory exists...
go version go1.18.3 linux/amd64
Starting rsyncd

Rsyncing /root/go/src/containerized-data-importer to container
Starting bazel server
go version go1.18.3 linux/amd64
DOCKER_PREFIX=dockerhub.kubekey.local/kubesphereio/cdi-controller
DOCKER_TAG=v1.0.0
VERBOSITY=1
PULL_POLICY=IfNotPresent
CDI_NAMESPACE=cdi
./hack/build/bazel-docker.sh "BUILD_ARCH=x86_64 ./hack/build/bazel-generate.sh -- staging/src pkg/ tools/ tests/ cmd/"
Making sure output directory exists...
go version go1.18.3 linux/amd64
Starting rsyncd

Rsyncing /root/go/src/containerized-data-importer to container
Starting bazel server
go version go1.18.3 linux/amd64
INFO: Repository com_github_pmezard_go_difflib instantiated at:
  /root/go/src/kubevirt.io/containerized-data-importer/WORKSPACE:81:21: in <toplevel>
  /root/.cache/bazel/_bazel_root/e03bf9038fc5089c0dbc8615812d9838/external/bazel_gazelle/deps.bzl:173:11: in gazelle_dependencies
  /root/.cache/bazel/_bazel_root/e03bf9038fc5089c0dbc8615812d9838/external/bazel_gazelle/deps.bzl:263:18: in _maybe
Repository rule go_repository defined at:
  /root/.cache/bazel/_bazel_root/e03bf9038fc5089c0dbc8615812d9838/external/bazel_gazelle/internal/go_repository.bzl:194:32: in <toplevel>
WARNING: Download from https://golang.org/dl/?mode=json&include=all failed: class java.io.IOException connect timed out
ERROR: An error occurred during the fetch of repository 'com_github_pmezard_go_difflib':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/e03bf9038fc5089c0dbc8615812d9838/external/bazel_gazelle/internal/go_repository.bzl", line 129, column 17, in _go_repository_impl
		fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch com_github_pmezard_go_difflib: fetch_repo: github.com/pmezard/go-difflib@v1.0.0: Get "https://proxy.golang.org/github.com/pmezard/go-difflib/@v/v1.0.0.info": dial tcp 172.217.160.113:443: i/o timeout
ERROR: /root/go/src/kubevirt.io/containerized-data-importer/WORKSPACE:81:21: fetching go_repository rule //external:com_github_pmezard_go_difflib: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/e03bf9038fc5089c0dbc8615812d9838/external/bazel_gazelle/internal/go_repository.bzl", line 129, column 17, in _go_repository_impl
		fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch com_github_pmezard_go_difflib: fetch_repo: github.com/pmezard/go-difflib@v1.0.0: Get "https://proxy.golang.org/github.com/pmezard/go-difflib/@v/v1.0.0.info": dial tcp 172.217.160.113:443: i/o timeout
ERROR: /root/.cache/bazel/_bazel_root/e03bf9038fc5089c0dbc8615812d9838/external/bazel_gazelle/cmd/gazelle/BUILD.bazel:10:11: @bazel_gazelle//cmd/gazelle:gazelle_lib depends on @com_github_pmezard_go_difflib//difflib:difflib in repository @com_github_pmezard_go_difflib which failed to fetch. no such package '@com_github_pmezard_go_difflib//difflib': failed to fetch com_github_pmezard_go_difflib: fetch_repo: github.com/pmezard/go-difflib@v1.0.0: Get "https://proxy.golang.org/github.com/pmezard/go-difflib/@v/v1.0.0.info": dial tcp 172.217.160.113:443: i/o timeout
ERROR: Analysis of target '//:gazelle' failed; build aborted: no such package '@com_github_pmezard_go_difflib//difflib': failed to fetch com_github_pmezard_go_difflib: fetch_repo: github.com/pmezard/go-difflib@v1.0.0: Get "https://proxy.golang.org/github.com/pmezard/go-difflib/@v/v1.0.0.info": dial tcp 172.217.160.113:443: i/o timeout
INFO: Elapsed time: 30.360s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    Fetching @org_golang_x_mod; fetching 30s
    Fetching @com_github_bazelbuild_buildtools; fetching 30s
    Fetching @com_github_pelletier_go_toml; fetching 30s
    Fetching @org_golang_x_sync; fetching 30s
make: *** [Makefile:135: bazel-cdi-generate] Error 1

**Comment by awels** [comment]
This looks like a networking issue or some mirror being down.
