### ISSUE TITLE
CDI with restricted policy fails to import on volume that is ext4 because it cannot remove lost+found

### ISSUE THREAD

**Issue by awels** [kubevirt/containerized-data-importer#2495]
**What happened**:
Since v1.55.0 with CDI running importer pod as non root, it is unable to delete the `lost+found` directory that is automatically created by an ext4 filesystem. This results in failures when downloading images.

**What you expected to happen**:
No error when importing with 1.55.0 on ext4 filesystem.

**How to reproduce it (as minimally and precisely as possible)**:
Run 1.55 CDI on lets say ceph with ext4 filesystem instead of xfs, this will result in a failure due to CDI not being able to delete `lost+found` directory (it should probably skip it)

**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 1.55 (with restricted policy applied)
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by mhenriks** [comment]
I just did a `make cluster-sync` with `KUBEVIRT_STORAGE=rook-ceph-default` and ceph is creating ext4 filesystems:

```bash
k get sc rook-ceph-block -o yaml
selecting docker as container runtime
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2022-11-30T21:38:12Z"
  name: rook-ceph-block
  resourceVersion: "1734"
  uid: 007cc434-8a26-4352-8942-a2d2e1fe5c36
parameters:
  clusterID: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  imageFeatures: layering
  imageFormat: "2"
  pool: replicapool
provisioner: rook-ceph.rbd.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

@awels if what you are saying is true, wouldn't our functional tests be broken for ceph lane?

**Comment by mhenriks** [comment]
created a pvc
```
k get pvc
selecting docker as container runtime
NAME     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
my-pvc   Bound    pvc-a3f6bd81-c946-4610-9ea6-a8c17be0c1b8   1Gi        RWO            rook-ceph-block   89s
```

ls pvc in pod
```
 k exec -ti my-pod -- ls /pvc
selecting docker as container runtime
lost+found
```

**Comment by mhenriks** [comment]
Since we set FS group on import pods, I suspect this is only an issue on volumes in which that does not work (nfs, etc)

**Comment by aglitke** [comment]
After some discussion we decided that CDI should only try to clean the disk.img file when restarting an import (as opposed to deleting everything).

**Comment by aglitke** [comment]
This is superseded by #2635
