### ISSUE TITLE
go 1.18.3 throwing High and Critical CVEs

### ISSUE THREAD

**Issue by kammerdiener** [kubevirt/containerized-data-importer#2499]
**What happened**:
Container scans reveal high and critical CVEs with current golang version of go 1.18.3

**What you expected to happen**:
Update go to the newest version which to mitigate the vulnerabilities.

**How to reproduce it (as minimally and precisely as possible)**:
Running a security scan for CVEs against the containers

**Additional context**:
Similar to this Issue: https://github.com/kubevirt/kubevirt/issues/8782

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 1.55.1
- Kubernetes version (use `kubectl version`): 1.21
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by awels** [comment]
Hi, I have updated our build system to use 1.18.8 already in the 1.55 branch, just haven't gotten around to making a new release that contains that.

**Comment by awels** [comment]
I spoke too soon, the code is there, forgot to update the builder, doing that now.

**Comment by shannonmitchell** [comment]
Just curious.  Do you know when a new release will be created with the version bump?

**Comment by awels** [comment]
Just kicked off the release for 1.55.2 which will include this fix.

**Comment by awels** [comment]
Release is complete, closing
