### ISSUE TITLE
go 1.18.8 throwing medium security vulnerability

### ISSUE THREAD

**Issue by kammerdiener** [kubevirt/containerized-data-importer#2506]
**What happened**:
go 1.18.8 is throwing a medium vulnerability with HTTP. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Running a vulnerability scan

**Additional context**:
This seems to be fixed in go 1.18.9

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 1.55.2
- Kubernetes version (use `kubectl version`): 1.21
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by alromeros** [comment]
@kammerdiener thanks for opening this issue!

@awels what do you think of this? I see that we are already using v1.19.2 in Kubevirt, maybe it's a good idea to update it. I can open the PR if you agree.

**Comment by awels** [comment]
I have started the work to upgrade to 1.19.5 IIRC, we already have a builder https://github.com/kubevirt/containerized-data-importer/pull/2585 we just need to update the code to use that builder, and update the appropriate libraries.
