### ISSUE TITLE
got no valid subject error specified when deploy  cdi-apiserver

### ISSUE THREAD

**Issue by meenajaeiei** [kubevirt/containerized-data-importer#2526]
**What happened**:

 Got flood error from cdi-apiserver `TLS handshake error from 172.20.13.54  no valid subject specified
> $ kubectl logs -n cdi cdi-apiserver
> I0103 01:38:46.238982       1 auth-config.go:70] Validating CN: kube-proxy
> 2023/01/03 01:38:46 http: TLS handshake error from 172.20.13.54:51206: no valid subject specified
> I0103 01:38:46.239080       1 apiserver.go:264] Getting TLS config
> I0103 01:38:46.239115       1 apiserver.go:264] Getting TLS config
> I0103 01:38:46.242979       1 auth-config.go:70] Validating CN: kube-proxy
> 2023/01/03 01:38:46 http: TLS handshake error from 172.20.13.54:51208: no valid subject specified
> I0103 01:38:46.243167       1 auth-config.go:70] Validating CN: kube-proxy
> 2023/01/03 01:38:46 http: TLS handshake error from 172.20.13.54:51204: no valid subject specified
> I0103 01:38:46.243207       1 auth-config.go:70] Validating CN: kube-proxy
> 2023/01/03 01:38:46 http: TLS handshake error from 172.20.13.54:51202: no valid subject specified
> 2023/01/03 03:11:21 http: TLS handshake error from 172.20.13.54:32794: no valid subject specified
> I0103 03:11:25.517131       1 apiserver.go:264] Getting TLS config
> I0103 03:11:25.520388       1 apiserver.go:160] ----------------------------
> I0103 03:11:25.520403       1 apiserver.go:161] remoteAddress:172.20.11.128
> I0103 03:11:25.520407       1 apiserver.go:162] username: -
> I0103 03:11:25.520411       1 apiserver.go:163] method: GET
> I0103 03:11:25.520415       1 apiserver.go:164] url: /healthz
> I0103 03:11:25.520418       1 apiserver.go:165] proto: HTTP/1.1
> I0103 03:11:25.520423       1 apiserver.go:166] headers: map[Accept:[*/*] Connection:[close] User-Agent:[kube-probe/1.21]]
> I0103 03:11:25.520439       1 apiserver.go:167] statusCode: 200
> I0103 03:11:25.520445       1 apiserver.go:168] contentLength: 2
> I0103 03:11:26.370993       1 apiserver.go:264] Getting TLS config
> I0103 03:11:26.378479       1 apiserver.go:264] Getting TLS config
> I0103 03:11:26.378630       1 apiserver.go:264] Getting TLS config
> I0103 03:11:26.378655       1 apiserver.go:264] Getting TLS config
> I0103 03:11:26.378819       1 apiserver.go:264] Getting TLS config
> I0103 03:11:26.382998       1 auth-config.go:70] Validating CN: kube-proxy
> 2023/01/03 03:11:26 http: TLS handshake error from 172.20.13.54:32824: no valid subject specified
> I0103 03:11:26.384011       1 auth-config.go:70] Validating CN: kube-proxy
> I0103 03:11:26.386239       1 auth-config.go:70] Validating CN: kube-proxy
> 2023/01/03 03:11:26 http: TLS handshake error from 172.20.13.54:32828: no valid subject specified
> I0103 03:11:26.386847       1 auth-config.go:70] Validating CN: kube-proxy
> 2023/01/03 03:11:26 http: TLS handshake error from 172.20.13.54:32830: no valid subject specified
> 2023/01/03 03:11:26 http: TLS handshake error from 172.20.13.54:32822: no valid subject specified
> I0103 03:11:26.390195       1 auth-config.go:70] Validating CN: kube-proxy
> 2023/01/03 03:11:26 http: TLS handshake error from 172.20.13.54:32826: no valid subject specified
> I0103 03:11:30.517089       1 apiserver.go:264] Getting TLS config
> I0103 03:11:30.520382       1 apiserver.go:160] ----------------------------
> I0103 03:11:30.520396       1 apiserver.go:161] remoteAddress:172.20.11.128
> I0103 03:11:30.520400       1 apiserver.go:162] username: -
> I0103 03:11:30.520403       1 apiserver.go:163] method: GET
> I0103 03:11:30.520407       1 apiserver.go:164] url: /healthz
> I0103 03:11:30.520411       1 apiserver.go:165] proto: HTTP/1.1
> I0103 03:11:30.520415       1 apiserver.go:166] headers: map[Accept:[*/*] Connection:[close] User-Agent:[kube-probe/1.21]]
> I0103 03:11:30.520452       1 apiserver.go:167] statusCode: 200
> I0103 03:11:30.520458       1 apiserver.go:168] contentLength: 2
> I0103 03:11:33.418962       1 apiserver.go:264] Getting TLS config
> I0103 03:11:33.421377       1 apiserver.go:264] Getting TLS config
> I0103 03:11:33.421592       1 apiserver.go:264] Getting TLS config
> I0103 03:11:33.421623       1 apiserver.go:264] Getting TLS config
> I0103 03:11:33.423442       1 apiserver.go:264] Getting TLS config
> I0103 03:11:33.426283       1 auth-config.go:70] Validating CN: kube-proxy
> 2023/01/03 03:11:33 http: TLS handshake error from 172.20.13.54:32866: no valid subject specified
> I0103 03:11:33.429675       1 auth-config.go:70] Validating CN: kube-proxy
> 2023/01/03 03:11:33 http: TLS handshake error from 172.20.13.54:32862: no valid subject specified
> I0103 03:11:33.429870       1 auth-config.go:70] Validating CN: kube-proxy
> 2023/01/03 03:11:33 http: TLS handshake error from 172.20.13.54:32856: no valid subject specified
> I0103 03:11:33.429980       1 auth-config.go:70] Validating CN: kube-proxy
> 2023/01/03 03:11:33 http: TLS handshake error from 172.20.13.54:32864: no valid subject specified
> I0103 03:11:33.432108       1 auth-config.go:70] Validating CN: kube-proxy
> 2023/01/03 03:11:33 http: TLS handshake error from 172.20.13.54:32858: no valid subject specified

as I checked to the pod that belong that ip I found that is `konnectivity-agent-7bd7f45fdd-kd62k`

>$ kubectl get pods -o wide --all-namespaces | grep 172.20.13.54
> kube-system          konnectivity-agent-7bd7f45fdd-kd62k                    1/1     Running     0          9d      172.20.13.54    gl-runner-workers-xl-1-21-6-khbsc    <none>           <none>

I checked that pods log and found the connectivity error between its and cdi-apiserver log

> E0103 03:18:03.654670       1 client.go:514] "connection read failure" err="read tcp 172.20.13.54:35516->172.20.11.109:8443: read: connection reset by peer" connectionID=880859
> I0103 03:18:03.654727       1 client.go:406] "close connection" connectionID=880859
> I0103 03:18:03.654781       1 client.go:492] "Exiting remoteToProxy" connectionID=880859
> I0103 03:18:03.654790       1 client.go:534] "Exiting proxyToRemote" connectionID=880859
> I0103 03:18:03.654800       1 client.go:507] "connection EOF" connectionID=880860
> I0103 03:18:03.654803       1 client.go:406] "close connection" connectionID=880860
> I0103 03:18:03.654854       1 client.go:492] "Exiting remoteToProxy" connectionID=880860
> I0103 03:18:03.654860       1 client.go:534] "Exiting proxyToRemote" connectionID=880860
> I0103 03:18:03.655018       1 client.go:451] "received DATA" connectionID=880859
> I0103 03:18:03.655031       1 client.go:462] "received CLOSE_REQ" connectionID=880859
> I0103 03:18:03.655037       1 client.go:468] "Failed to find connection context for close" connectionID=880859
> I0103 03:18:03.655066       1 client.go:451] "received DATA" connectionID=880860
> I0103 03:18:03.655073       1 client.go:462] "received CLOSE_REQ" connectionID=880860
> I0103 03:18:03.655077       1 client.go:468] "Failed to find connection context for close" connectionID=880860
> I0103 03:18:03.655304       1 client.go:462] "received CLOSE_REQ" connectionID=880859
> I0103 03:18:03.655331       1 client.go:468] "Failed to find connection context for close" connectionID=880859
> I0103 03:18:03.655571       1 client.go:462] "received CLOSE_REQ" connectionID=880860
> I0103 03:18:03.655582       1 client.go:468] "Failed to find connection context for close" connectionID=880860
> I0103 03:18:03.656585       1 client.go:451] "received DATA" connectionID=880861
> I0103 03:18:03.656627       1 client.go:544] "write to remote" connectionID=880861 lastData=1194 dataSize=1194
> I0103 03:18:03.656630       1 client.go:451] "received DATA" connectionID=880861
> I0103 03:18:03.656659       1 client.go:544] "write to remote" connectionID=880861 lastData=228 dataSize=228
> E0103 03:18:03.656996       1 client.go:514] "connection read failure" err="read tcp 172.20.13.54:35520->172.20.11.109:8443: read: connection reset by peer" connectionID=880861
> I0103 03:18:03.657007       1 client.go:406] "close connection" connectionID=880861
> I0103 03:18:03.657075       1 client.go:492] "Exiting remoteToProxy" connectionID=880861
> I0103 03:18:03.657081       1 client.go:534] "Exiting proxyToRemote" connectionID=880861
> I0103 03:18:03.657295       1 client.go:451] "received DATA" connectionID=880858
> I0103 03:18:03.657345       1 client.go:544] "write to remote" connectionID=880858 lastData=1194 dataSize=1194
> I0103 03:18:03.657373       1 client.go:451] "received DATA" connectionID=880858
> I0103 03:18:03.657430       1 client.go:544] "write to remote" connectionID=880858 lastData=228 dataSize=228
> I0103 03:18:03.657574       1 client.go:462] "received CLOSE_REQ" connectionID=880861
> I0103 03:18:03.657596       1 client.go:468] "Failed to find connection context for close" connectionID=880861
> E0103 03:18:03.657830       1 client.go:514] "connection read failure" err="read tcp 172.20.13.54:35518->172.20.11.109:8443: read: connection reset by peer" connectionID=880858
> I0103 03:18:03.657867       1 client.go:406] "close connection" connectionID=880858
> I0103 03:18:03.657953       1 client.go:492] "Exiting remoteToProxy" connectionID=880858
> I0103 03:18:03.657962       1 client.go:534] "Exiting proxyToRemote" connectionID=880858
> I0103 03:18:03.658108       1 client.go:451] "received DATA" connectionID=880858
> I0103 03:18:03.658121       1 client.go:462] "received CLOSE_REQ" connectionID=880858
> I0103 03:18:03.658125       1 client.go:468] "Failed to find connection context for close" connectionID=880858
> I0103 03:18:03.658381       1 client.go:451] "received DATA" connectionID=880857
> I0103 03:18:03.658408       1 client.go:451] "received DATA" connectionID=880857
> I0103 03:18:03.658440       1 client.go:544] "write to remote" connectionID=880857 lastData=1194 dataSize=1194
> I0103 03:18:03.658449       1 client.go:544] "write to remote" connectionID=880857 lastData=228 dataSize=228
> I0103 03:18:03.658472       1 client.go:462] "received CLOSE_REQ" connectionID=880858
> I0103 03:18:03.658480       1 client.go:468] "Failed to find connection context for close" connectionID=880858
> E0103 03:18:03.658857       1 client.go:514] "connection read failure" err="read tcp 172.20.13.54:35524->172.20.11.109:8443: read: connection reset by peer" connectionID=880857

**What you expected to happen**:
Currently , I can't upload the OS image to kube. it returns some error so I guess it could relate on the cdi-apiserver issue that I'm facing with

> kubectl virt image-upload --image-path=/Users/jchodchoy/Desktop/Win10_22H2_EnglishInternational_x64.iso --pvc-name=win10-international-installer --pvc-size=6Gi --insecure --uploadproxy-url=[https://172.18.149.197:443](https://172.18.149.197/)
> Using existing PVC test-kubevirt/win10-international-installer
> Uploading data to [https://172.18.149.197:443](https://172.18.149.197/)
> You are using a client virtctl version that is different from the KubeVirt version running in the cluster
> Client Version: v0.57.1
> Server Version: v0.58.0
> the server is currently unable to handle the request (post uploadtokenrequests.upload.cdi.kubevirt.io)

**How to reproduce it (as minimally and precisely as possible)**:
Nothing to do much. just only check the logs of cdi component. just has only cdi-apiserver that returns the error log.

**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.55.2
- Kubernetes version (use `kubectl version`): server v1.21 , client v1.25
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by awels** [comment]
Just looking at the logs it seems to me that you have an invalid certificate in your kube-proxy. And the cdi api server is refusing to talk to your proxy because of it.

```I0103 03:11:26.386239 1 auth-config.go:70] Validating CN: kube-proxy
2023/01/03 03:11:26 http: TLS handshake error from 172.20.13.54:32828: no valid subject specified
```

**Comment by meenajaeiei** [comment]
I found the issue because the certificate subject CN of kube-proxy and --requestheader-allowed-names flag on kube-apiserver wasn't match.

**Comment by chaseblack** [comment]
I am a bit confused about how to set the 2 values, could you please give more details on how to set the CN of kube-proxy? what other params like --requestheader-client-ca-file should be set?
