### ISSUE TITLE
Support VolumeSnapshot as a volume source

### ISSUE THREAD

**Issue by mattlqx** [kubevirt/containerized-data-importer#2531]
**Is your feature request related to a problem? Please describe**:
I'm looking at ways to minimize launch time for large images. I have images pre-imported into AWS EBS but using them as a source via PVC can be slow as it can take around 5-10 minutes to snapshot a 200GB volume.

**Describe the solution you'd like**:
Since the image volumes themselves don't change and restoring an EBS snapshot is quick, but taking one is slow. I'd like to just pre-create VolumeSnapshots and have KubeVirt create a new DataVolume from that. This should significantly reduce creation times.

**Describe alternatives you've considered**:
I've experimented around a lot with ZFS but snapshots have reference issues, detached snapshots are just about as slow and then you'd have to deal with locality issues of which node has which data and how to migrate between hosts. Using EBS largely solves the data location issues and scales well, but has attachment limits as a trade-off.

**Additional context**:
I'm not sure if this is appropriate here for CDI or if this is more of a kubevirt proper thing.

**Comment by akalenyu** [comment]
Actively being worked on at https://github.com/kubevirt/containerized-data-importer/pull/2522,
feel free to review

**Comment by alromeros** [comment]
@akalenyu @mattlqx  I think we can close this issue since https://github.com/kubevirt/containerized-data-importer/pull/2522 is already merged. WDYT?

**Comment by awels** [comment]
Closing due to issue being solved
