### ISSUE TITLE
DataVolume Labels are not Copied to the PVC

### ISSUE THREAD

**Issue by nunnatsa** [kubevirt/containerized-data-importer#2533]
**What happened**:
Created a DataVolume with `generateName` and some labels and annotations. The PVC was created with the DataVolume annotations but without the DataVolume labels. It was then hard to find the PVC, as it's name is not known, and there is no way to use label selector to find it, as the labels do not exist.

**What you expected to happen**:
The DataVolume labels should be copied to the PVC, as done for the annotations.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a DataVolume with labels.
2. Read the PVC.
3. Notice that the labels do not exist in the PVC

**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): N/A
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by akalenyu** [comment]
We should really dig why we have not been doing this until now,
can't think of any particular reason as of now
