### ISSUE TITLE
CDI download fails with FIPS enabled kernel when using HTTPS source

### ISSUE THREAD

**Issue by k8scoder192** [kubevirt/containerized-data-importer#2558]
**What happened**:
Attempting to use CDI to download a qcow2 image from a *https* source. Importer pod immediately fails 

```E0126 21:10:49.677846       1 prlimit.go:174] qemu-img failed output is:
E0126 21:10:49.677905       1 prlimit.go:175]
E0126 21:10:49.677922       1 prlimit.go:176] qemu-img: Could not open 'nbd+unix:///?socket=/var/run/nbdkit.sock': Requested export not available

E0126 21:10:49.678061       1 data-processor.go:278] qemu-img: Could not open 'nbd+unix:///?socket=/var/run/nbdkit.sock': Requested export not available
, qemu-img execution failed: exit status 1 Log line from nbdkit: nbdkit: curl[1]: error: problem doing HEAD request to fetch size of URL [https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img]: Out of memory: SSL: couldn't create a context: error:00000000:lib(0)::reason(0)
Unable to convert source data to target format
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
        pkg/importer/data-processor.go:242
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
        pkg/importer/data-processor.go:275
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
        pkg/importer/data-processor.go:184
main.handleImport
        cmd/cdi-importer/importer.go:177
main.main
        cmd/cdi-importer/importer.go:143
runtime.main
        GOROOT/src/runtime/proc.go:250
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1571
```

**What you expected to happen**:
CDI create a DV, download and convert image into raw, stored in a PVC 

**How to reproduce it (as minimally and precisely as possible)**:
Ubuntu 18.04 enable FIPS and use a FIPS kernel [link](https://ubuntu.com/tutorials/using-the-ua-client-to-enable-fips#1-overview)

Create a DV, in this case with a Ceph block storage volume
```apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu1804-dv
spec:
  source:
    http:
      url: "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img"
  pvc:
    storageClassName: rook-ceph-block
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
```

**Additional context**:
Increased CDI resource allowance; no change was seen in the behavior; same error seen
```   config:
          podResourceRequirements:
               limits:
                  cpu: 750m
                  memory: 4G
               requests:
                  cpu: 100m
                  memory: 60M
 ```

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 1.54 (seen in previous releases as well)
- Kubernetes version (use `kubectl version`): v1.24.0
- DV specification: See above
- Cloud provider or hardware configuration: Baremetal host
- OS (e.g. from /etc/os-release): Ubuntu 18.04 LTS
- Kernel (e.g. `uname -a`): Linux 4.15.0-1093-fips
- Install tools: N/A
- Others: N/A

**Comment by aglitke** [comment]
Hi @k8scoder192 does this happen with all web servers or just https://cloud-images.ubuntu.com?  Also, if you could try with a compressed image (if available) this could help to determine if the issue is with qemu/nbdkit.

**Comment by k8scoder192** [comment]
Hi @aglitke, any https endpoint causes the issue. I haven't tried any compressed files but I'm not sure that is related to the issue.

**Comment by awels** [comment]
So a raw image gets imported with a different code path than a compressed image.
Could you try https://download.fedoraproject.org/pub/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-37-1.7.x86_64.raw.xz which is a compressed raw image. This will go through a different path, we just want to see if it is just the direct transfer or also compressed images.

**Comment by awels** [comment]
Just an update on this, CDI containers have statically linked binaries in the releases, and that might be the reason the download is failing on FIPS enabled kernel as that might have different requirements for the encryption than what the statically linked binary can provide.

**Comment by k8scoder192** [comment]
@awels / @alromeros 

> So a raw image gets imported with a different code path than a compressed image. Could you try https://download.fedoraproject.org/pub/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-37-1.7.x86_64.raw.xz which is a compressed raw image. This will go through a different path, we just want to see if it is just the direct transfer or also compressed images.

**This worked, so .xz doesn't have the issue.** 

Evidence 
```
Spec:
  Pvc:
    Access Modes:
      ReadWriteOnce
    Resources:
      Requests:
        Storage:         10Gi
    Storage Class Name:  rook-ceph-block
    Volume Mode:         Block
  Source:
    Http:
      URL:  https://download.fedoraproject.org/pub/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-37-1.7.x86_64.raw.xz
Status:
  Claim Name:  test-fedora-xz-file
  Conditions:
    Last Heartbeat Time:   2023-08-07T17:22:35Z
    Last Transition Time:  2023-08-07T17:22:35Z
    Message:               PVC test-fedora-xz-file Bound
    Reason:                Bound
    Status:                True
    Type:                  Bound
    Last Heartbeat Time:   2023-08-07T17:25:23Z
    Last Transition Time:  2023-08-07T17:25:23Z
    Status:                True
    Type:                  Ready
    Last Heartbeat Time:   2023-08-07T17:25:21Z
    Last Transition Time:  2023-08-07T17:25:21Z
    Message:               Import Complete
    Reason:                Completed
    Status:                False
    Type:                  Running
  Phase:                   Succeeded
  Progress:                100.0%
Events:
  Type     Reason            Age    From                   Message
  ----     ------            ----   ----                   -------
  Normal   Pending           3m32s  datavolume-controller  PVC test-fedora-xz-file Pending
  Normal   ImportScheduled   3m30s  datavolume-controller  Import into test-fedora-xz-file scheduled
  Normal   Bound             3m30s  datavolume-controller  PVC test-fedora-xz-file Bound
  Normal   ImportInProgress  3m20s  datavolume-controller  Import into test-fedora-xz-file in progress
  Warning  Completed         44s    datavolume-controller  Import Complete
  Normal   ImportSucceeded   42s    datavolume-controller  Successfully imported into PVC test-fedora-xz-file
```
