### ISSUE TITLE
data volume clone process always failed for ceph rbd csi

### ISSUE THREAD

**Issue by leoryu** [kubevirt/containerized-data-importer#2609]
**What happened**:

I upload an image throung virtctl: 
```sh
virtctl image-upload --image-path=/root/kubevirt/disk.img --namespace=kube-public --storage-class=csi-rbd-sc --pvc-size=20G --uploadproxy-url=https://10.244.255.109:443 --pvc-name=win-server-test2 --insecure --wait-secs=240
```
It works, but when I create an DataVloume to clone image from this pvc, it always failed. Data volume:
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/cloneType: network
    cdi.kubevirt.io/storage.clone.token: eyJhbGciOiJQUzI1NiJ9.eyJleHAiOjE2NzczODU4NTgsImlhdCI6MTY3NzM4NTU1OCwiaXNzIjoiY2RpLWFwaXNlcnZlciIsIm5hbWUiOiJ3aW4tc2VydmVyLXRlc3QyIiwibmFtZXNwYWNlIjoia3ViZS1wdWJsaWMiLCJuYmYiOjE2NzczODU1NTgsIm9wZXJ0YXRpb24iOiJDbG9uZSIsInBhcmFtcyI6eyJ0YXJnZXROYW1lIjoicm9vdGZzLmZkZ2ZkZyIsInRhcmdldE5hbWVzcGFjZSI6ImRlZmF1bHQifSwicmVzb3VyY2UiOnsiZ3JvdXAiOiIiLCJyZXNvdXJjZSI6InBlcnNpc3RlbnR2b2x1bWVjbGFpbXMiLCJ2ZXJzaW9uIjoidjEifX0.Bhp9DL7Scw2j-T4lVKSV1BG4XUX65UPfrB-f8EFyzxPVfjno_1-vMj9Boj4zbbh4uD4lK-GZDmGpIWvYUuHHtdHKMgyrTS-hxKuO2zBPjuaKO1QGr1ofpxqGsVqWdEvsgXndGWN5Y0Lb5xTN18F8TSIH3cPqIfm06IdhOs1_N-e1LwyEDk-OoHp_j0buAkjxcnPCC-X3Yd9LjlNFLThB5yB2v7dAVHCvMdSi17GC39YG_2iKNXvIzhGnxW-GtioHlyzcnNqaXqMlEll0IO5dyMbaHkhMlI2V2Lw0DS_MEUhlygKD__SyZEO7Rkx3xlFbtJs78DHOgl4SD2HPaIxzeQ
  creationTimestamp: "2023-02-26T04:25:58Z"
  generation: 22
  labels:
    kubevirt.io/created-by: 4d6d7d26-e252-491c-9b86-aefda01b8101
  name: rootfs.fdgfdg
  namespace: default
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachine
    name: fdgfdg
    uid: 4d6d7d26-e252-491c-9b86-aefda01b8101
  resourceVersion: "5707189"
  uid: 9a94cb07-9a56-4685-a2ae-bdee7453a20d
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
    storageClassName: csi-rbd-sc
    volumeMode: Filesystem
  source:
    pvc:
      name: win-server-test2
      namespace: kube-public
status:
  claimName: rootfs.fdgfdg
  conditions:
  - lastHeartbeatTime: "2023-02-26T04:26:09Z"
    lastTransitionTime: "2023-02-26T04:26:09Z"
    message: PVC rootfs.fdgfdg Bound
    reason: Bound
    status: "True"
    type: Bound
  - lastHeartbeatTime: "2023-02-26T04:26:34Z"
    lastTransitionTime: "2023-02-26T04:25:59Z"
    reason: TransferRunning
    status: "False"
    type: Ready
  - lastHeartbeatTime: "2023-02-26T04:26:23Z"
    lastTransitionTime: "2023-02-26T04:26:23Z"
    reason: Pod is running
    status: "True"
    type: Running
  phase: CloneInProgress
  progress: 3.07%
```
And the source pod report err: 
```sh
I0226 04:28:50.995932      10 prometheus.go:72] 78.80
I0226 04:28:51.996009      10 prometheus.go:72] 79.83
F0226 04:28:51.997667      10 clone-source.go:41] Subprocess did not execute successfully, result is: '\x01'
./
./disk.img
./lost+found/
/usr/bin/tar: .: file changed as we read it
goroutine 12 [running]:
kubevirt.io/containerized-data-importer/vendor/k8s.io/klog/v2.stacks(0x1)
        vendor/k8s.io/klog/v2/klog.go:1038 +0x8a
kubevirt.io/containerized-data-importer/vendor/k8s.io/klog/v2.(*loggingT).output(0x1452e20, 0x3, 0x0, 0xc00041e8c0, 0x0, {0xff9b4c, 0x2}, 0xc00024e440, 0x0)
        vendor/k8s.io/klog/v2/klog.go:987 +0x5fd
kubevirt.io/containerized-data-importer/vendor/k8s.io/klog/v2.(*loggingT).printf(0x10000, 0x0, 0x0, {0x0, 0x0}, {0xcfe0ea, 0x39}, {0xc00024e440, 0x2, 0x2})
        vendor/k8s.io/klog/v2/klog.go:753 +0x1c5
kubevirt.io/containerized-data-importer/vendor/k8s.io/klog/v2.Fatalf(...)
        vendor/k8s.io/klog/v2/klog.go:1532
main.(*execReader).Read(0xc000437dd0, {0xc000496000, 0x6c2675, 0xc00025dc20})
        cmd/cdi-cloner/clone-source.go:41 +0x1f1
kubevirt.io/containerized-data-importer/pkg/util.(*CountingReader).Read(0xc000267270, {0xc000496000, 0x2000, 0xc000496000})
        pkg/util/util.go:92 +0x32
io.copyBuffer({0xde4f00, 0xc00025dc20}, {0x7f86a58a6048, 0xc000267270}, {0x0, 0x0, 0x0})
        GOROOT/src/io/io.go:423 +0x1b2
io.Copy(...)
        GOROOT/src/io/io.go:382
main.pipeToSnappy.func1()
        cmd/cdi-cloner/clone-source.go:117 +0x6b
created by main.pipeToSnappy
        cmd/cdi-cloner/clone-source.go:116 +0x287
```

**What you expected to happen**:

It works if I switch hostpath csi to upload this image.
I think it also should work for ceph rbd csi

**How to reproduce it (as minimally and precisely as possible)**:

**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.45.0
- Kubernetes version (use `kubectl version`): 1.21.4
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by awels** [comment]
Hi, thanks for the report. I have a few questions/suggestions. If you are using rbd, why are you using a filesystem volume mode? It would give you better performance using a block volume mode. It would also eliminate the source of your particular problem. If you look at the error message it is saying `/usr/bin/tar: .: file changed as we read it` so it appears either something is actively writing to the volume, or the rbd hasn't completely flushed the filesystem from the upload. 1.45 is relatively old, and I would have to look up if we are actively flushing in that version or not. But the latest version of CDI we actively flush before ending the pod, and we also check if other pods are using the volume before we attempt to clone it.

**Comment by leoryu** [comment]
> Hi, thanks for the report. I have a few questions/suggestions. If you are using rbd, why are you using a filesystem volume mode? It would give you better performance using a block volume mode. It would also eliminate the source of your particular problem. If you look at the error message it is saying `/usr/bin/tar: .: file changed as we read it` so it appears either something is actively writing to the volume, or the rbd hasn't completely flushed the filesystem from the upload. 1.45 is relatively old, and I would have to look up if we are actively flushing in that version or not. But the latest version of CDI we actively flush before ending the pod, and we also check if other pods are using the volume before we attempt to clone it.

Thanks for your suggestions, I have changed the volume mode to block, and it works.
