### ISSUE TITLE
Pod-affinity fails when cloning is done within same namespace

### ISSUE THREAD

**Issue by zvikorn** [kubevirt/containerized-data-importer#261]
In an environment of one node, when we try to clone from one PVC to another within one namespace, only one pod is schedules on the node. The other one fails to be scheduled. Need to check if pod-affinity is defined well. If we clone across two namespaces, it works. meaning - both source and target pods are schedules on the node.

**Comment by jeffvance** [comment]
>  If we clone across two namespaces, it works

Do you mean _namespaces_ here or _nodes_

**Comment by zvikorn** [comment]
Namespaces. Why this was closed?

**Comment by jeffvance** [comment]
Sorry, I clicked the wrong button.
/reopen

**Comment by awels** [comment]
Note that currently in a multi node environment if you clone from different name spaces, the pods can be scheduled on different nodes, and thus fail. I will test the patch against that scenario.

**Comment by zvikorn** [comment]
This was fixed in the patch

**Comment by jeffvance** [comment]
#265
