### ISSUE TITLE
do some basic performance measurements on importing...

### ISSUE THREAD

**Issue by jeffvance** [kubevirt/containerized-data-importer#268]
and test if buffered i/o should be used for the various schemes supported (https, s3, file).

**Comment by aglitke** [comment]
Should we keep this issue around or close it?  I think we shouldn't have an issue until we have identified an actually performance problem.

**Comment by erinboyd** [comment]
@aglitke I think it's meant more for tracking. But you are welcome to close in favor of a trello card.

**Comment by jeffvance** [comment]
Yes to @erinboyd 's comment.

**Comment by aglitke** [comment]
This is a tracking issue.  Revisit relevance in October 2018.
