### ISSUE TITLE
Datavolume clones data from a PVC failed, it starts again when the progress bar reaches 97%

### ISSUE THREAD

**Issue by zhangzhangzf** [kubevirt/containerized-data-importer#2694]
**What happened**:
[root@VM-8-157-centos ~]# kubectl get dv
NAME                       PHASE                   PROGRESS   RESTARTS   AGE
rootfs.wincnitest2   CloneInProgress   48.12%         99.               13h

**What you expected to happen**:
DV create success.

**How to reproduce it (as minimally and precisely as possible)**:
Declare a Datavolume with a data source of PVC.
[root@VM-8-157-centos ~]# kubectl get dv rootfs.wincnitest2 -o yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/cloneType: network
    cdi.kubevirt.io/storage.clone.token: eyJhbGciOiJQUzI1ZgmyScjjJwpiArOt1Hm1ENlNUYgopQqmSqF45o2yphS-dfrFBO4uAseKZYQYEE9va2_0nimZkvLzOTKGdJc1nr69aLb-2gWj6N6bWDoE3BIjRsjtMICqn5hnR5SOW7kzaVISbTk7q4U_56bpliKuAkwr1lzB2Fw5yvHlI1pAQ
  creationTimestamp: "2023-04-13T12:52:00Z"
  generation: 34203
  labels:
    kubevirt.io/created-by: 4b5a96f7-16b5-4704-bce4-5b8448758464
  name: rootfs.wincnitest2
  namespace: default
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachine
    name: wincnitest2
    uid: 4b5a96f7-16b5-4704-bce4-5b8448758464
  resourceVersion: "43105086"
  uid: b2c96a53-2787-4313-8459-7df91c31b116
spec:
  pvc:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 30Gi
    storageClassName: csi-rbd-sc
    volumeMode: Block
  source:
    pvc:
      name: wincnitest2
      namespace: kube-public

**Additional context**:
Log of cdi-deployment-6df886b95f-7gpf8.

{"level":"error","ts":1681437230.5296376,"logger":"controller.datavolume-controller","msg":"Reconciler error","name":"rootfs.wincnitest2","namespace":"default","error":"Operation cannot be fulfilled on datavolumes.cdi.kubevirt.io \"rootfs.wincnitest2\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"kubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nkubevirt.io/containerized-data-importer/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tvendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"}

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.45.0
- Kubernetes version (use `kubectl version`): v1.21.1
- OS (e.g. from /etc/os-release): Centos7

**Comment by awels** [comment]
Can you provide the source PVC yaml (in particular the size of it) and the volume mode? Also there should be 2 pods that get created one upload server in the target namespace and one source pod in the source namespace. If you can provide the logs for those

**Comment by zhangzhangzf** [comment]
> Can you provide the source PVC yaml (in particular the size of it) and the volume mode? Also there should be 2 pods that get created one upload server in the target namespace and one source pod in the source namespace. If you can provide the logs for those

Source PVC is:

[root@VM-8-157-centos /home/windows-image-build]# kubectl get dv rootfs.wincnitest2 -o yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/cloneType: network
    cdi.kubevirt.io/storage.clone.token: ifX0.iQ1rKRHg1l9McEMAfQhSrqkH07PsJQe0tMCfvHltMxFMkJyY-qwHR4b4CH4IGW073cHOu_F2eRKY6CFUaPPaq0FhYLgeA3FdRovC-rR8ZLpihIHXE_PcDfeQhNUuC3-1Qp1LpSaym5jYMLS7WLwPnmJRwd95UHGM3iWKQGZDRsMlGZgmyScjjJwpiArOt1Hm1ENlNUYgopQqmSqF45o2yphS-dfrFBO4uAseKZYQYEE9va2_0nimZkvLzOTKGdJc1nr69aLb-2gWj6N6bWDoE3BIjRsjtMICqn5hnR5SOW7kzaVISbTk7q4U_56bpliKuAkwr1lzB2Fw5yvHlI1pAQ
  creationTimestamp: "2023-04-13T12:52:00Z"
  generation: 138472
  labels:
    kubevirt.io/created-by: 4b5a96f7-16b5-4704-bce4-5b8448758464
  name: rootfs.wincnitest2
  namespace: default
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachine
    name: wincnitest2
    uid: 4b5a96f7-16b5-4704-bce4-5b8448758464
  resourceVersion: "46957021"
  uid: b2c96a53-2787-4313-8459-7df91c31b116
spec:
  pvc:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 30Gi
    storageClassName: csi-rbd-sc
    volumeMode: Block
  source:
    pvc:
      name: wincnitest2
      namespace: kube-public
status:
  claimName: rootfs.wincnitest2
  conditions:
  - lastHeartbeatTime: "2023-04-13T12:52:01Z"
    lastTransitionTime: "2023-04-13T12:52:01Z"
    message: PVC rootfs.wincnitest2 Bound
    reason: Bound
    status: "True"
    type: Bound
  - lastHeartbeatTime: "2023-04-15T16:22:57Z"
    lastTransitionTime: "2023-04-13T12:52:00Z"
    reason: TransferRunning
    status: "False"
    type: Ready
  - lastHeartbeatTime: "2023-04-15T16:20:31Z"
    lastTransitionTime: "2023-04-15T16:20:31Z"
    reason: Pod is running
    status: "True"
    type: Running
  phase: CloneInProgress
  progress: 70.11%
  restartCount: 382

===========================
logs of pod1:
[root@VM-8-157-centos /home/windows-image-build]# kubectl logs  -n kube-public f578878e-4fba-4e6b-9964-d1251ceab10e-source-pod
Error from server: no preferred addresses found; known addresses: []

==============================
logs of pod2:
[root@VM-8-157-centos /home/windows-image-build]# kubectl logs cdi-upload-rootfs.wincnitest2
Error from server: no preferred addresses found; known addresses: []

**Comment by zhangzhangzf** [comment]
My backend storage is ceph-rbd.

**Comment by zhangzhangzf** [comment]
> Can you provide the source PVC yaml (in particular the size of it) and the volume mode? Also there should be 2 pods that get created one upload server in the target namespace and one source pod in the source namespace. If you can provide the logs for those

**Comment by zhangzhangzf** [comment]
> My backend storage is ceph-rbd.



> Can you provide the source PVC yaml (in particular the size of it) and the volume mode? Also there should be 2 pods that get created one upload server in the target namespace and one source pod in the source namespace. If you can provide the logs for those

Thank you for your attention to this issue. This problem has been solved. The reason is that the parameter --block-volume was missing when uploading the image by virtctl image-upload.
