### ISSUE TITLE
Images that require too much space actually get imported potentially overwhelming disk

### ISSUE THREAD

**Issue by akalenyu** [kubevirt/containerized-data-importer#2715]
**What happened**:
[test_id:2329] fails from time to time with evicted importer pods complaining about DiskPressure:
https://search.ci.kubevirt.io/?search=too+much+space&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
When running the test and inspecting the importer log, one can see that we actually import those "malicious" images
instead of rejecting them at an earlier phase (regression?)
Together with the readahead nbdkit filter, this can get messy, causing DiskPressure on the node.

**What you expected to happen**:
Reject such images early on

**How to reproduce it (as minimally and precisely as possible)**:
Run [test_id:2329]

**Additional context**:
```bash
I0516 17:00:57.575666       1 importer.go:103] Starting importer
I0516 17:00:57.575728       1 importer.go:172] begin import process
I0516 17:00:57.575808       1 http-datasource.go:392] Attempting to HEAD "http://cdi-file-host.cdi/cirros-large-virtual-size.raw.xz" via http client
I0516 17:00:57.580394       1 http-datasource.go:404] GO CLIENT: key: Server, value: [nginx/1.20.1]
I0516 17:00:57.580430       1 http-datasource.go:404] GO CLIENT: key: Date, value: [Tue, 16 May 2023 17:00:57 GMT]
I0516 17:00:57.580442       1 http-datasource.go:404] GO CLIENT: key: Content-Type, value: [text/plain]
I0516 17:00:57.580452       1 http-datasource.go:404] GO CLIENT: key: Connection, value: [keep-alive]
I0516 17:00:57.580463       1 http-datasource.go:404] GO CLIENT: key: Content-Length, value: [12340872]
I0516 17:00:57.580473       1 http-datasource.go:404] GO CLIENT: key: Last-Modified, value: [Tue, 16 May 2023 10:38:31 GMT]
I0516 17:00:57.580483       1 http-datasource.go:404] GO CLIENT: key: Etag, value: ["64635d27-bc4e88"]
I0516 17:00:57.580508       1 http-datasource.go:404] GO CLIENT: key: Accept-Ranges, value: [bytes]
I0516 17:00:57.580524       1 http-datasource.go:424] Content length: 12340872
I0516 17:00:57.580558       1 http-datasource.go:327] Attempting to get object "http://cdi-file-host.cdi/cirros-large-virtual-size.raw.xz" via http client
I0516 17:00:57.603283       1 data-processor.go:356] Calculating available size
I0516 17:00:57.603407       1 data-processor.go:368] Checking out file system volume size.
I0516 17:00:57.603444       1 data-processor.go:376] Request image size not empty.
I0516 17:00:57.603498       1 data-processor.go:381] Target size 492768256.
I0516 17:00:57.603573       1 format-readers.go:112] constructReaders: checking compression and archive formats
I0516 17:00:57.603622       1 format-readers.go:121] found header of type "xz"
I0516 17:00:57.646847       1 data-processor.go:255] New phase: TransferDataFile
I0516 17:00:57.647003       1 util.go:194] Writing data...
I0516 17:00:58.647782       1 prometheus.go:75] 73.66
I0516 17:00:59.648428       1 prometheus.go:75] 97.64
I0516 17:01:00.648879       1 prometheus.go:75] 97.76
I0516 17:01:01.649697       1 prometheus.go:75] 97.91
E0516 17:01:02.508903       1 util.go:196] Unable to write file from dataReader: write /data/disk.img: no space left on device
E0516 17:01:02.635696       1 data-processor.go:251] write /data/disk.img: no space left on device
```

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): N/A
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by rwmjones** [comment]
Image seems to be this one: https://github.com/kubevirt/containerized-data-importer/blob/main/tests/images/cirros-large-virtual-size.raw.xz

**Comment by awels** [comment]
So if this is a raw xz file, we bypass nbdkit (since there is no need for conversion) and I guess our golang xz library is not complaining about the invalid block size.

**Comment by rwmjones** [comment]
I didn't mean to imply that the block size is invalid (it's not).  Just that it's too large for nbdkit to use it for random access, since it has to uncompress the current block and we set a limit on the block size and number of concurrent blocks that we are prepared to uncompress, to avoid running out of memory.

**Comment by akalenyu** [comment]
> * Reject the file early on (which xz filter should be doing, if you're using that)

We stopped using the xz filter with https://github.com/kubevirt/containerized-data-importer/pull/2351

I guess the real problem is that we're bypassing validation with this image somehow;
The user asks for 500Mi but we end up almost writing the entire uncompressed size

**Comment by awels** [comment]
I am closing this as I have verified that we are not writing the 0s out to the disk when the virtual size is > requested space. We write the original file to the scratch space and run some queries before attempting the copy. At that point we detect the size issue and exit.

**Comment by akalenyu** [comment]
> ```shell
> I0516 17:01:01.649697       1 prometheus.go:75] 97.91
> E0516 17:01:02.508903       1 util.go:196] Unable to write file from dataReader: write /data/disk.img: no space left on device
> E0516 17:01:02.635696       1 data-processor.go:251] write /data/disk.img: no space left on device
> ```

Is this because we changed behavior at some point? because the original logs on this issue imply that we do
attempt to write this to target

**Comment by awels** [comment]
I think it was just unfortunate coincidence with somethine else taking up the space. We did increase the size of the VM disk for the node to be 50ish instead of 35G.
