### ISSUE TITLE
Deprecation Notice - cdi-controller-deployment.yaml

### ISSUE THREAD

**Issue by copejon** [kubevirt/containerized-data-importer#272]
Beginning in v1.1.0, `manifests/cdi-controller-deployment.yaml` will be considered deprecated and replaced by generated manifests provided by releases or by running `make 

The file will be removed in v1.2.0.

**Comment by xsgordon** [comment]
Note also the readme currently still has this:

```
$ VERSION=<cdi version>
$ kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-controller-deployment.yaml
```
Which of course no longer works for all possible variants of $VERSION.
