### ISSUE TITLE
Metrics names failed promlint linter

### ISSUE THREAD

**Issue by avlitman** [kubevirt/containerized-data-importer#2773]
**What happened**:
We created a metric name linter based on promlint: https://github.com/kubevirt/containerized-data-importer/pull/2774
This metrics names failed:
```
$ make lint-metrics
./hack/ci/prom_metric_linter.sh --operator-name="kubevirt" --sub-operator-name="cdi"
CDI_CRI: docker, CDI_CONTAINER_BUILDCMD: docker
clone_progress: counter metrics should have "_total" or "_timestamp_seconds" suffix
clone_progress: name need to start with 'kubevirt_'
kubevirt_cdi_incomplete_storageprofiles_total: non-counter metrics should not have "_total" suffix
kubevirt_cdi_operator_up_total: non-counter metrics should not have "_total" suffix
make: *** [Makefile:171: lint-metrics] Error 1

```

**What you expected to happen**:
Metrics named will be aligned with promlint linter and Prometheus best practices.

**How to reproduce it (as minimally and precisely as possible)**:
run make lint-metrics in containerized-data-importer dir.

**Additional context**:
A bugzilla bug opened as well: https://bugzilla.redhat.com/show_bug.cgi?id=2218468

**Comment by aglitke** [comment]
Discussed this during the SIG-Storage call and it seems that only the DataVolume controller and alerting code would be impacted by changing these.  We don't anticipate any other effects to end users by changing these names.

**Comment by avlitman** [comment]
> Discussed this during the SIG-Storage call and it seems that only the DataVolume controller and alerting code would be impacted by changing these. We don't anticipate any other effects to end users by changing these names.

@aglitke wow!! thanks for verifying this!

I just found a few places I'm not sure if needs update:
https://pkg.go.dev/kubevirt.io/containerized-data-importer/pkg/monitoring
Here seems like somine is using the metrics in their Thanos:
https://prometheus.nrp-nautilus.io/rules
https://www.google.com/search?q=kubevirt_cdi_operator_up_total&nfpr=1&filter=0&biw=1920&bih=971&dpr=1
