### ISSUE TITLE
Import virtual machine image using ceph-csi encryption storage class error

### ISSUE THREAD

**Issue by am6737** [kubevirt/containerized-data-importer#2775]
**What happened**:
The virtual machine I created using the ceph-csi encrypted storage class was unable to mount the file system

I think it is, after ceph pvc decryption，When cdi imported the virtual machine image, the file type was modified to gpt.
But the file type of the disk after the import is complete should be ext4 or xfs
Otherwise, kubelet cannot mount the file system to the virtual machine.   I don't know what cdi did here.   Does it have anything to do with cdi

```
Warning FailedMapVolume 64s (x16 over 18m) kubelet MapVolume.SetUpDevice failed for volume "pvc-275597f6-633b-45e8-b2d8-043732a0c7f8" : rpc error: code = Internal desc = rpc error: code = Internal desc = need resize check failed on devicePath /dev/mapper/luks-rbd-0001-0024-xxx-0000000000000002-e03af360-21b6-4b87-ad93-e3c9ef1aa91b and stagingPath /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-275597f6-633b-45e8-b2d8-043732a0c7f8/0001-0024-xxx-0000000000000002-e03af360-21b6-4b87-ad93-e3c9ef1aa91b, error: Could not parse fs info on given filesystem format: unknown data, probably partitions. Supported fs types are: xfs, ext3, ext4
```

 blkid -p -s TYPE -s PTTYPE -o export /dev/mapper/luks-rbd-0001-0024-xxx-0000000000000002-e03af360-21b6-4b87-ad93-e3c9ef1aa91b
```
DEVNAME=/dev/mapper/luks-rbd-0001-0024-xxx-0000000000000002-e03af360-21b6-4b87-ad93-e3c9ef1aa91b
PTTYPE=gpt
```

**What you expected to happen**:
The virtual machine successfully mounts the file system

**How to reproduce it (as minimally and precisely as possible)**:

**Additional context**:
You can see relevant information here. #https://github.com/ceph/ceph-csi/issues/3945

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.56.0
- Kubernetes version (use `kubectl version`): v1.26.0
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 20.04.6 LTS
- Kernel (e.g. `uname -a`): Linux 5.4.0-152-generic
- Install tools: N/A
- Ceph cluster version : v17.2.6
- Kubevirt version: v0.59

**Comment by akalenyu** [comment]
Sounds similar to https://github.com/kubevirt/kubevirt/issues/9620,
maybe one of the comments can help shed some light? sounds like the Block PVC is being mounted like a filesystem PVC

Also long shot, there is a note on ceph csi docs - **Do not change for existing storageclasses**
maybe that's the case?

**Comment by am6737** [comment]
> Sounds similar to [kubevirt/kubevirt#9620](https://github.com/kubevirt/kubevirt/issues/9620), maybe one of the comments can help shed some light? it sounds like a block PVC is being mounted like a filesystem PVC
> 
> Also long shot, there is a note on ceph csi docs - **Do not change for existing storageclasses** maybe that's the case?

Thank you for your help
https://github.com/ceph/ceph-csi/pull/3958 This has been resolved
