### ISSUE TITLE
CDI upload concurrency performance issues

### ISSUE THREAD

**Issue by Learntotolearn** [kubevirt/containerized-data-importer#2781]
**What happened**:
```
Starting 50 pods of cdi upload at the same time and cloning the mirror resources of the datasource will result in most cdi upload services reporting errors as follows:

Back-off restarting failed container cdi-clone-source in pod 04d96b7c-83b4-4640-8c17-09d0f49d7304-source-pod_default(c74c0b37-c731-4ae5-9620-62ce360f4df9)
```
>Most errors are shown in the following figure:
![image](https://github.com/kubevirt/containerized-data-importer/assets/85656971/6866b77c-bf33-44f3-b997-d6e964bccc60)

**What you expected to happen**:
```
The expectation is to be able to upload or clone images normally.
```
**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
```
Start 50 cdi upload pods simultaneously for mirror cloning.
```

**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 1.54.2
- Kubernetes version (use `kubectl version`): 1.26.0
- DV specification: 
- Cloud provider or hardware configuration: hardware configuration 48c256g6T*5
- OS (e.g. from /etc/os-release): ubuntu20.04
- Kernel (e.g. `uname -a`): 5.4.0-152-generic
- Install tools: yaml 
- Others: N/A

**Comment by Learntotolearn** [comment]
![image](https://github.com/kubevirt/containerized-data-importer/assets/85656971/d7ff2070-3f71-4ce5-bede-cc5ae5443207)

**Comment by awels** [comment]
Okay just so I understand what you are doing properly, and understand all the pieces involved. You are essentially starting 50 clones from one source to 50 targets, and that causes these issues? You are not upload from outside the cluster into the cluster? Because that involves Ingress and the upload proxy.

**Comment by Learntotolearn** [comment]
> Okay just so I understand what you are doing properly, and understand all the pieces involved. You are essentially starting 50 clones from one source to 50 targets, and that causes these issues? You are not upload from outside the cluster into the cluster? Because that involves Ingress and the upload proxy.

>You are essentially starting 50 clones from one source to 50 targets, and that causes these issues?
>Yes, I initiated 50 clones from the datasource at once, and this issue will occur. No involvement in ingress

>This is how I installed CDI
```
export TAG=$(curl -s -w %{redirect_url} https://github.com/kubevirt/containerized-data-importer/releases/latest)  
export VERSION=$(echo ${TAG##*/})  
kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-operator.yaml  
kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-cr.yaml  
```
```
apiVersion: v1
kind: Service
metadata:
  name: cdi-uploadproxy-nodeport
  namespace: cdi
  labels:
    cdi.kubevirt.io: "cdi-uploadproxy"
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 8443
      nodePort: 31001
      protocol: TCP
  selector:
    cdi.kubevirt.io: cdi-uploadproxy
```

**Comment by awels** [comment]
Okay so doing a host assisted clone should not involve the upload proxy at all since everything happens inside the cluster. Each clone has 2 pods involved one in the source namespace and one in the target namespace. Can you give me the logs of a pair of those? I am just seeing the target pod which notes the connection is dropped which usually happens if the source pod crashes for some reason.

**Comment by Learntotolearn** [comment]
> Okay so doing a host assisted clone should not involve the upload proxy at all since everything happens inside the cluster. Each clone has 2 pods involved one in the source namespace and one in the target namespace. Can you give me the logs of a pair of those? I am just seeing the target pod which notes the connection is dropped which usually happens if the source pod crashes for some reason.

>cdi-upload log
```
Readiness probe failed: Get "http://10.0.4.52:8080/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by Learntotolearn** [comment]
>This is the log of Clone Times:
```
crypto/tls.(*Conn).readFromUntil(0xc0002d6000, {0xe814a0?, 0xc00030a020}, 0x0?)
	GOROOT/src/crypto/tls/conn.go:807 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0002d6000, 0x0)
	GOROOT/src/crypto/tls/conn.go:614 +0x116
crypto/tls.(*Conn).readRecord(...)
	GOROOT/src/crypto/tls/conn.go:582
crypto/tls.(*Conn).Read(0xc0002d6000, {0xc000480000, 0x1000, 0x203000?})
	GOROOT/src/crypto/tls/conn.go:1285 +0x16f
net/http.(*connReader).Read(0xc0002d8780, {0xc000480000, 0x1000, 0x1000})
	GOROOT/src/net/http/server.go:780 +0x16d
bufio.(*Reader).fill(0xc000301e00)
	GOROOT/src/bufio/bufio.go:106 +0x103
bufio.(*Reader).ReadSlice(0xc000301e00, 0x0?)
	GOROOT/src/bufio/bufio.go:371 +0x2f
bufio.(*Reader).ReadLine(0xc000301e00)
	GOROOT/src/bufio/bufio.go:400 +0x27
net/textproto.(*Reader).readLineSlice(0xc00034d7a0)
	GOROOT/src/net/textproto/reader.go:57 +0x99
net/textproto.(*Reader).ReadLine(...)
	GOROOT/src/net/textproto/reader.go:38
net/http.readRequest(0xc0007379e8?)
	GOROOT/src/net/http/request.go:1029 +0x79
net/http.(*conn).readRequest(0xc0002ce0a0, {0xe89fa8, 0xc0001d6080})
	GOROOT/src/net/http/server.go:988 +0x24a
net/http.(*conn).serve(0xc0002ce0a0, {0xe8a050, 0xc0004058f0})
	GOROOT/src/net/http/server.go:1891 +0x32b
created by net/http.(*Server).Serve
	GOROOT/src/net/http/server.go:3071 +0x4db
```

**Comment by aglitke** [comment]
Does the situation eventually resolve (with all requested clones completing successfully after a certain number of retries?  I definitely understand that the current situation is sub-optimal.  Perhaps we could rate-limit the number of concurrent clones active at one time but this depends on many factors and could be hard to guess correctly.

**Comment by Learntotolearn** [comment]
It seems to be related to the storage used. Previously, I used linbit storage, linstor csi, but later I switched to ceph, and this situation no longer occurs.
This is just my guess.

**Comment by alromeros** [comment]
> It seems to be related to the storage used. Previously, I used linbit storage, linstor csi, but later I switched to ceph, and this situation no longer occurs. This is just my guess.

Closing the issue since the problem seems to be storage-related and is no longer ocurring. Feel free to reopen if needed, thanks!
