### ISSUE TITLE
Virtual image size is larger than the reported available storage

### ISSUE THREAD

**Issue by michaelcourcy** [kubevirt/containerized-data-importer#2786]
**What happened**:
When uploading a very small image (cirros-0.3.0-x86_64-disk.img  9M) I always get this error : 

**unexpected return value 400, Saving stream failed: Virtual image size 41126400 is larger than the reported available storage -1. A larger PVC is required.**

The command 
```
virtctl image-upload dv cirros-vm-disk --image-path=cirros-0.3.0-x86_64-disk.img --uploadproxy-url=https://cdi.mcourcy.dev.azure.kasten.io --insecure --storage-class=cdi --size=100Gi  
PVC cdi/cirros-vm-disk not found 
DataVolume cdi/cirros-vm-disk created
Waiting for PVC cirros-vm-disk upload pod to be ready...
Pod now ready
Uploading data to https://cdi.mcourcy.dev.azure.kasten.io

 9.31 MiB / 9.31 MiB [========================================================================================================] 100.00% 0s

unexpected return value 400, Saving stream failed: Virtual image size 41126400 is larger than the reported available storage -1. A larger PVC is required.
```

**What you expected to happen**:
100 Gi should be enough for this small image actually even less.

**How to reproduce it (as minimally and precisely as possible)**:
I use cdi v1.56.0 I expect this command to repro for anyone but I'm not quite sure as I start on this field
you can get this image with 
```
wget https://launchpad.net/cirros/trunk/0.3.0/+download/cirros-0.3.0-x86_64-disk.img
```
**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.56.0
- Kubernetes version (use `kubectl version`): 
```
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:24Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9", GitCommit:"10c91e1361d3ac832eabff795d431216be430fcc", GitTreeState:"clean", BuildDate:"2023-05-19T00:02:26Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.24) exceeds the supported minor version skew of +/-1
```
- DV specification: 
```
 k get dv
NAME             PHASE         PROGRESS   RESTARTS   AGE
cirros-vm-disk   UploadReady   N/A                   8m33s
michaelcourcy@PAR0377 kubevirt % k get dv cirros-vm-disk -o yaml 
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/storage.deleteAfterCompletion: "true"
  creationTimestamp: "2023-07-04T14:35:42Z"
  generation: 238
  name: cirros-vm-disk
  namespace: cdi
  resourceVersion: "48264658"
  uid: ddc656fd-fb9b-4f73-ba28-2775d4d3f622
spec:
  contentType: kubevirt
  source:
    upload: {}
  storage:
    resources:
      requests:
        storage: 100Gi
    storageClassName: cdi
status:
  claimName: cirros-vm-disk
  conditions:
  - lastHeartbeatTime: "2023-07-04T14:35:49Z"
    lastTransitionTime: "2023-07-04T14:35:49Z"
    message: PVC cirros-vm-disk Bound
    reason: Bound
    status: "True"
    type: Bound
  - lastHeartbeatTime: "2023-07-04T14:44:43Z"
    lastTransitionTime: "2023-07-04T14:35:42Z"
    reason: TransferRunning
    status: "False"
    type: Ready
  - lastHeartbeatTime: "2023-07-04T14:37:11Z"
    lastTransitionTime: "2023-07-04T14:37:11Z"
    reason: Pod is running
    status: "True"
    type: Running
  phase: UploadReady
  progress: N/A
```
- Cloud provider or hardware configuration: Azure AKS
- OS (e.g. from /etc/os-release): cirros
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by michaelcourcy** [comment]
Checking the logs of the 

```
I0704 15:36:06.002455       1 uploadserver.go:74] Running server on 0.0.0.0:8443
I0704 15:36:08.414151       1 uploadserver.go:324] Content type header is ""
I0704 15:36:08.414192       1 data-processor.go:379] Calculating available size
E0704 15:36:08.415669       1 data-processor.go:383] exit status 1, blockdev: cannot open /dev/cdi-block-volume: Permission denied
I0704 15:36:08.415725       1 data-processor.go:391] Checking out file system volume size.
E0704 15:36:08.415760       1 data-processor.go:394] no such file or directory
I0704 15:36:08.415769       1 data-processor.go:399] Request image size not empty.
I0704 15:36:08.415783       1 data-processor.go:404] Target size -1.
I0704 15:36:08.415814       1 data-processor.go:282] New phase: TransferScratch
I0704 15:36:08.416173       1 util.go:191] Writing data...
I0704 15:36:08.824676       1 data-processor.go:282] New phase: ValidatePause
I0704 15:36:08.824734       1 data-processor.go:288] Validating image
E0704 15:36:08.831396       1 data-processor.go:278] Virtual image size 41126400 is larger than the reported available storage -1. A larger PVC is required.
E0704 15:36:08.831435       1 uploadserver.go:336] Saving stream failed: Virtual image size 41126400 is larger than the reported available storage -1. A larger PVC is required.
```

And in the pod I can see that I cannot read the content of the file /dev/cdi-block-volume
```
sh-5.1$ ls -al /dev/cdi-block-volume 
brw-rw---- 1 root disk 8, 128 Jul  4 15:36 /dev/cdi-block-volume
sh-5.1$ id 
uid=107 gid=0(root) groups=0(root),107
```

But a this point I don't see how to move forward, any ideas ?

**Comment by akalenyu** [comment]
Some CRIs may require extra configuration to allow non-root manipulation of block PVCs:
https://github.com/kubevirt/containerized-data-importer/blob/f5d0b70b096abd856acff67eb4fc0cab0b474d89/doc/block_cri_ownership_config.md

**Comment by michaelcourcy** [comment]
Thanks for the link @akalenyu,  ownership of the device seems to address my issue. 

However I check the documentation on AKS to [change the configuration of my nodes](https://learn.microsoft.com/en-us/azure/aks/custom-node-configuration?tabs=linux-node-pools#create-an-aks-cluster-with-a-customized-node-configuration) and changing the containerd configuration seems unclear to me. 

Is there by any chance an example or how to that explains that specifically for AKS. Maybe AKS is not the right platform for that. I used it because it was convenient to obtain nested virtualization but maybe I pushed too far.

**Comment by michaelcourcy** [comment]
I was able to execute the exact same command against an OCP install with success. So it really depends of the containerd or crio conf. I close the issue.

**Comment by akalenyu** [comment]
> Thanks for the link @akalenyu, ownership of the device seems to address my issue.
> 
> However I check the documentation on AKS to [change the configuration of my nodes](https://learn.microsoft.com/en-us/azure/aks/custom-node-configuration?tabs=linux-node-pools#create-an-aks-cluster-with-a-customized-node-configuration) and changing the containerd configuration seems unclear to me.
> 
> Is there by any chance an example or how to that explains that specifically for AKS. Maybe AKS is not the right platform for that. I used it because it was convenient to obtain nested virtualization but maybe I pushed too far.

Yeah I understand, usually you'd just change the containerd config and `systemctl restart containerd`
but for managed k8s it's probably best to be steered into the "appropriate" way of doing this.

Anyway, the config should be at `/etc/containerd/config.toml`:
https://github.com/containerd/containerd/blob/main/docs/PLUGINS.md
