### ISSUE TITLE
Remove cloning label from target pods to fix pod affinity

### ISSUE THREAD

**Issue by zvikorn** [kubevirt/containerized-data-importer#279]
Having the cloning label in the target pod, make the pod affinity fails.
The target pod looks for a pod with a specific label (specified in the pod affinity) that matches the source pod label.
In my case the target pod included this label as well, so we can see that the target pod found matching pod, but it is the WRONG pod. It's itself!!
The target was running without finding the source pod first.
If we remove this label from the target pod, it will find the source pod and then will be scheduled on the same node.
If it does not find the source pod (because the scheduler tried to schedule it before the source pod), it will be in 'Pending' state until the source pod is scheduled, and then will be running on the same node.

**Comment by zvikorn** [comment]
Fixed. PR - https://github.com/kubevirt/containerized-data-importer/pull/280

**Comment by jeffvance** [comment]
fixed #280
