### ISSUE TITLE
could not get file descriptor for fsync call:  .... no such file or directory

### ISSUE THREAD

**Issue by Fevereiro6** [kubevirt/containerized-data-importer#2808]
I get this error after pulling an image successfully using a datavolume:

`
I0714 10:03:01.948580       1 data-processor.go:282] New phase: Resize
W0714 10:03:01.967247       1 data-processor.go:361] Available space less than requested size, resizing image to available space 2028994560.
I0714 10:03:01.967310       1 data-processor.go:369] Calculated new size is < than current size, not resizing: requested size 2028994560, virtual size: 2147483648.
I0714 10:03:01.967336       1 data-processor.go:288] Validating image
I0714 10:03:01.985336       1 data-processor.go:282] New phase: Complete
I0714 10:03:01.985533       1 util.go:38] deleting file: /scratch/disk
I0714 10:03:02.187245       1 util.go:38] deleting file: /scratch/disk.img
I0714 10:03:02.868594       1 importer.go:212] Import Complete
E0714 10:03:02.868700       1 importer.go:342] could not get file descriptor for fsync call: open /data/disk.img: no such file or directory
`

I checked inside the container and the file is there. What might be happening?

**Comment by awels** [comment]
Hi, could you provide us with the version of CDI you are using, as well as the kubernetes version? And the DataVolume yaml would also help.

**Comment by Fevereiro6** [comment]
The CDI version is v1.56.0 and the Kubernetes version is v1.26.3.

Here's the DataVolume.yaml:

`apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: registry-image-datavolume
spec:
  source:
    registry:
      url: "docker://<add-repo-here>"
      secretRef: vm-reg-secret
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local-storage`

**Comment by Fevereiro6** [comment]
I discovered the issue. I was using the same path for the persistentVolume for the scratch space and to the PV used by the DataVolume. Changed the path and it works now. Thank you for your time.
