### ISSUE TITLE
Investigate WFFC ceph lane being significantly slower than immediate binding lane

### ISSUE THREAD

**Issue by akalenyu** [kubevirt/containerized-data-importer#2828]
**What happened**:
As can be seen in this comparison:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/2815/pull-containerized-data-importer-e2e-ceph/1684474065181478912
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/2815/pull-containerized-data-importer-e2e-ceph-wffc/1684602514835509248
The same set of tests ran against a ceph wffc variation is resulting in a longer runtime
for the job (1.5h~).

**What you expected to happen**:
Some difference was indeed expected (consumer pod) but that should take about 4 seconds
per test, and we have around 500 so around 30 minute difference was expected.
Unfortunately, we get a significantly longer difference between the runtimes.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
This goes back to 1.56 as well https://github.com/kubevirt/containerized-data-importer/pull/2820
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by aglitke** [comment]
Would it be possible to enable some sort of timestamp logging in ginkgo to understand the time that individual steps are taking in the tests.  @akalenyu suggested to look into the kubevirt tests since they have some bash-based logging mechanism.  @awels also suggested using the same seed on a wffc and immediate run so that we can more easily compare the two runs.
