### ISSUE TITLE
Define a label specific to importer pods

### ISSUE THREAD

**Issue by shiywang** [kubevirt/containerized-data-importer#285]
Former title: `Make each importer-pod with a unique label`

When importer controller creates different importer-pods, could we make each pod add a unique label instead of currently only one label `app=containerized-data-importer`? prefix could begins with pvc name.

this is not a high priority, but it would be nice if we could have it.

cc @jeffvance @copejon

**Comment by jeffvance** [comment]
@shiywang can you provide the customer or QE use case for this? Thanks.

**Comment by nellyc** [comment]
@shiywang can you please add more info

**Comment by shiywang** [comment]
so I have multiple importer-pods and I want to fetch one of them using a script, but the labels is same, I have to write some complex sed, awk command to fetch them. 
also in code here: https://github.com/kubevirt/kubevirt-ansible/blob/master/tests/cdi/cdi_test.go#L38 I have to delete previous pod, then I can use same label to fetch the new one.

**Comment by jeffvance** [comment]
@shiywang There is a 1-1 mapping of a pvc to a golden image. Each importer pod contains the name of the triggering pvc so if you know the name of the pvc you can find the importer pod. I don't see how a unique (random) label is different from the existing unique pod names.

**Comment by jeffvance** [comment]
@shiywang I am still having a problem understanding how a unique label per pod (and I assume there is some randomness in this label to obtain uniqueness) is any different from a unique, generated pod name. If this issue was not requesting *unique* labels I could understand it better, since the existing label applies to non-pods too. But requesting unique importer pod labels still doesn't make sense to me. Would you mind showing a few examples of these labels, I think that would help. Thanks.

**Comment by shiywang** [comment]
@jeffvance 
I have three pods here:
```
NAME                          READY     STATUS      RESTARTS   AGE
importer-golden-pvc-lxbtd     0/1       Completed   0          24m
importer-test-pvc-asdfd     0/1       Completed   0          24m
importer-abc-pvc-asdfs     0/1       Completed   0          24m
```
How do I check the status of `importer-test-pvc-asdfd` with one command? because three of them are having the same label.

`oc get pod importer-test-pvc-asdfd` doesn't work, because I can't predict the generated string `asdfd`

**Comment by jeffvance** [comment]
@shiywang I understand that the random part of the pod's name needs to be handled. I'm asking for examples of pod labels that are both unique and predictable so that you do not need to parse out whatever it is that makes the label unique. Unique is in the title of this issue. Thanks.

**Comment by shiywang** [comment]
@jeffvance thank you and sorry for writing an misleading title, English is my second language ; )

**Comment by jeffvance** [comment]
@shiywang No worries and your English is very good. So, to rephrase this issue: you are asking for an importer pod specific label that identifies the importer pod(s) as being cdi importer pods, but not other cdi resources, such as cloner pods or golden pvcs, correct?  For example:
```
label=cdi-importer-pod
```

**Comment by aglitke** [comment]
@shiywang Is this still needed?
