### ISSUE TITLE
API server fails to discover Kubernetes API 

### ISSUE THREAD

**Issue by tclxzhengyang-li** [kubevirt/containerized-data-importer#2851]
**What happened**:
When I perform image upload, the following problem occurs：
`[root@sztcyl-177-151-26 lzy]# virtctl image-upload pvc iso-centos7 -n cdi --image-path='CentOS-7-x86_64-Minimal-2009.iso' --storage-class hostpath-csi --pvc-size=2Gi --uploadproxy-url=https://10.179.157.243 --insecure --wait-secs=240`
`the server is currently unable to handle the request (post uploadtokenrequests.upload.cdi.kubevirt.io)`

the log of cdi-apiserver is as follows:
_`2023/08/17 08:05:36 http: TLS handshake error from 10.177.153.49:64798: no valid subject specified`_

the api is not avaliable
`v1beta1.upload.cdi.kubevirt.io            cdi/cdi-api         False (FailedDiscoveryCheck)   24h`
the message is follow 
`failing or missing response from https://10.179.153.111:8443/apis/upload.cdi.kubevirt.io/v1beta1: Get "https://10.179.153.111:8443/apis/upload.cdi.kubevirt.io/v1beta1": remote error: tls: bad certificate`

**What you expected to happen**:
cdi-apiserver can be authenticated successfully

**How to reproduce it (as minimally and precisely as possible)**:
Installing CDI on a k8s cluster

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):  1.54.3
- Kubernetes version (use `kubectl version`):  1.22.7
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by alromeros** [comment]
Hey @tclxzhengyang-li, thanks for opening the issue. I found other two similar cases: https://github.com/kubevirt/containerized-data-importer/issues/2526 and https://github.com/kubevirt/containerized-data-importer/issues/1295. You probably have some invalid fields in your certificate, so I'd recommend rechecking it along the cdi-apiserver/kube-apiserver logs for more specific information.

**Comment by alromeros** [comment]
Closing the issue due to inactivity, feel free to reopen if necessary. Thanks!
