### ISSUE TITLE
Document & log file:/// endpoints as debug use only

### ISSUE THREAD

**Issue by copejon** [kubevirt/containerized-data-importer#286]
Use of the `file:///` endpoint location is causing confusion with users who attempt to access a file on the host filesystem.    The local file scheme is designed with debugging in mine ( e.g. when running the importer binary on the host machine outside of a container).   This needs to be documented and log output needs to be produced to better inform users.

It should be noted in the [README.md](https://github.com/kubevirt/containerized-data-importer/blob/master/README.md#start-importing-images) and log output should be written from the [`local()`](https://github.com/kubevirt/containerized-data-importer/blob/master/pkg/importer/dataStream.go#L184) method.

The log output should be a Warning vLog level 1.

**Comment by jeffvance** [comment]
@copejon what is the actual confusion?
Also, I think the issue title is a bit restrictive since `file://` endpoint are often used in testing

**Comment by copejon** [comment]
@jeffvance The confusion comes from users attempting to import files from the host's f/s, which isn't possible to do from inside a container.  

The process was added early in CDI as a way to quickly test/debug import logic - we could just execute the binary directly on the host, which allowed it to access the host's f/s.

 We've seen several emails and a bugzilla opened against this already which is a sign that we need to make it clear that it's not for production.
