### ISSUE TITLE
Cannot set an ownerRef on a resource you can't delete

### ISSUE THREAD

**Issue by aglitke** [kubevirt/containerized-data-importer#287]
When attempting to import into a PVC the following error appears in the logs:

E0731 17:09:55.135611       1 import-controller.go:206] error processing pvc "default/golden-pvc": importer pod API create errored: pods "importer-golden-pvc-g4nsb" is forbidden: cannot set an ownerRef on a resource you can't delete: User "system:serviceaccount:default:cdi-sa" cannot delete pods in project "default", <nil>

**Comment by jeffvance** [comment]
@davidvossel can you take a look?

**Comment by davidvossel** [comment]
those verbs should be in the controller manifest already as well

**Comment by jeffvance** [comment]
@screeley44 @aglitke Is this a master (:latest) issue or an issue with our current release-v.1.1 branch?

**Comment by aglitke** [comment]
fixed by #291
