### ISSUE TITLE
cdi importer: open /data/disk.img: permission denied

### ISSUE THREAD

**Issue by screeley44** [kubevirt/containerized-data-importer#288]
This requires some SELinux magic to fix - not sure if this error will be addressed by ansible and the automated parts of the setup?  But for now, we should document that if you hit this error to:

`setenforce 0` 

or maybe there is a more elegant way

**Comment by jeffvance** [comment]
Thanks. It would be nice to find a more granular solution. And there is likely a doc need here too.

**Comment by aglitke** [comment]
On which environment did you encounter this?

**Comment by screeley44** [comment]
encountered on OCP 3.9 using `oc cluster up`

**Comment by aglitke** [comment]
@screeley44 What kind of underlying storage?  HostPath? Local Storage?

**Comment by aglitke** [comment]
@screeley44 can we close this?

**Comment by karmab** [comment]
the following would do the trick on a oc cluster up setup

```
setfacl -m user:107:rwx /root/openshift.local.clusterup/openshift.local.pv/pv*
```
note this would be for 3.10 , for 3.9, the command would be

``` 
setfacl -m user:107:rwx /var/lib/origin/openshift.local.pv/pv*
```

**Comment by jeffvance** [comment]
@karmab can you comment on the kubernetes equivalent, if any? Thanks!

**Comment by xsgordon** [comment]
For completeness in minishift land looks like this would be:

    setfacl -m user:107:rwx /var/lib/minishift/base/openshift.local.pv/pv0100

**Comment by xsgordon** [comment]
Actually I lie, while that would be the correct path looks like I'm hitting a different issue.

**Comment by CamelCaseNotation** [comment]
I am deploying this on a non-openshift cluster. Any way around it?

**Comment by awels** [comment]
Most common reason for seeing this issue is:
1. Using local storage and not setting the permissions of the directory on the host correctly.
2. Using local storage and not setting the selinux permissions of the directory on the host correctly (mostly on OpenShift)
3. Mounting the PVC in the POD as a user that doesn't have permissions to write to it.

Without some more details I can't help more.
