### ISSUE TITLE
DataVolume.cdi.kubevirt.io error: no matches for kind "DataVolume"

### ISSUE THREAD

**Issue by webnotesweb** [kubevirt/containerized-data-importer#2916]
**What happened**:
This is a fresh kubeadm (minikube) cluster with KubeVirt v1.0.0, CDI v1.57.0 and [VMIO](https://github.com/kubevirt/vm-import-operator/) v0.4.0 (at least attempt of VMIO). I tried kubeadm clusters and minikube as well, same error occurs. Please find error below. In short resources keep asking for "DataVolume.cdi.kubevirt.io". However it seems to be there and it seems to be there.

```
$ kubectl get crd | grep cdi
cdiconfigs.cdi.kubevirt.io                                    2023-09-28T13:12:16Z
cdis.cdi.kubevirt.io                                          2023-09-28T13:12:07Z
dataimportcrons.cdi.kubevirt.io                               2023-09-28T13:12:16Z
datasources.cdi.kubevirt.io                                   2023-09-28T13:12:16Z
datavolumes.cdi.kubevirt.io                                   2023-09-28T13:12:16Z
objecttransfers.cdi.kubevirt.io                               2023-09-28T13:12:16Z
storageprofiles.cdi.kubevirt.io                               2023-09-28T13:12:16Z
volumeclonesources.cdi.kubevirt.io                            2023-09-28T13:12:16Z
volumeimportsources.cdi.kubevirt.io                           2023-09-28T13:12:16Z
volumeuploadsources.cdi.kubevirt.io                           2023-09-28T13:12:16Z
```

This is actual error that I keep getting:

```
$ kubectl logs vm-import-controller-65fd85b4bd-h95cd
...
{"level":"error","ts":1696409661.8821468,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"DataVolume.cdi.kubevirt.io","error":"no matches for kind \"DataVolume\" in version \"cdi.kubevirt.io/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/opt/app-root/src/vm-import-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/opt/app-root/src/vm-import-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:117\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/opt/app-root/src/vm-import-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:140\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/opt/app-root/src/vm-import-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:175\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/opt/app-root/src/vm-import-operator/vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go:661"}
{"level":"error","ts":1696409661.8823407,"logger":"cmd","msg":"Manager exited non-zero","error":"no matches for kind \"DataVolume\" in version \"cdi.kubevirt.io/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/opt/app-root/src/vm-import-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/opt/app-root/src/vm-import-operator/cmd/manager/main.go:159\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:204"}
```
Please note that I am able to create VMs and console access them just fine. As example [this](https://raw.githubusercontent.com/kubevirt/containerized-data-importer/main/manifests/example/vm-dv.yaml) works just fine. Only two related issues that I was able to find are [this one](https://github.com/kubevirt/kubevirt/issues/7078#issuecomment-1022330007) and [this one](https://bugzilla.redhat.com/show_bug.cgi?id=1915404).

**What you expected to happen**:
I am expecting for vm-import-controller pod to deploy successfully but it keeps failing and it throws out error that DataVolume.cdi.kubevirt.io is not available.

**How to reproduce it (as minimally and precisely as possible)**:
This can be reproduces on minikube by installing KubeVirt, CDI and trying to setup https://github.com/kubevirt/vm-import-operator
This should suffice. For me it keeps failing with this error: _DataVolume.cdi.kubevirt.io error: no matches for kind "DataVolume"_

**Additional context**:
Just trying to setup initial environment for VMIO migration process and it keeps failing. Any input or insight is very welcome. I am not sure what am I missing here.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): operator.cdi.kubevirt.io/createVersion: v1.57.0
- Kubernetes version (use `kubectl version`): Client Version: v1.27.6, Kustomize Version: v5.0.1, Server Version: v1.27.6
- DV specification: N/A
- Cloud provider or hardware configuration: Test system, bare metal, VMs... Lot of tests with same outcome.
- OS (e.g. from /etc/os-release): 22.04.1 LTS
- Kernel (e.g. `uname -a`): Linux hostname-1 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Custom installation
- Others: StorageClass is local-path (rancher.io/local-path), when using kubeadm and network is flannel.

**Comment by akalenyu** [comment]
I think the VM import operator is deprecated, so what happens is
that it's using the deprecated v1alpha1 CDI APIs, which is why the VM import operator is failing

I know the Red Hat successor is `Migration Toolkit for Virtualization`:
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/virtualization/virt-4-10-release-notes#virt-4-10-removed
But not sure exactly which upstream project this maps to. @awels any idea?

**Comment by aglitke** [comment]
It seems like this issue is resolved so I will close it.  Please feel free to reopen if I am mistaken.
