### ISSUE TITLE
FeatureGate/Flag for allowing CDI workloads to run as root

### ISSUE THREAD

**Issue by awels** [kubevirt/containerized-data-importer#2919]
**Is your feature request related to a problem? Please describe**:
Some storage providers don't support fsGroups, and for those provisioners not running as root will prevent them from using CDI. I propose we add a featureGate or flag to CDI that instructs the controller to create work loads as root.

**Describe the solution you'd like**:
We need some kind of mechanism to tell the CDI controller to create workload pods (import/upload/clone) to run as root instead of the kvm user. In particular either a featureGate, or a flag in the CDI CR to indicate we want to run as root.

**Describe alternatives you've considered**:
Preferred would be that all storage providers support fsGroups properly, but this is not the case in real world scenarios, so we need to supply a solution for users with these types of providers.

**Additional context**:

**Comment by akalenyu** [comment]
@Ranjeet-Nvidia @lzang Hi! Would you mind sharing which storage providers hit these issues? any docs about the reasoning would also help :pray:

**Comment by Ranjeet-Nvidia** [comment]
@akalenyu Please check below details 

**_CDI version : v1.57.0
Kubernetes version : 1.22.8
KubeVirt v1.0.0_**

k describe sc blossom-retain

```
Name:                  blossom-retain
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           [csi.trident.netapp.io](http://csi.trident.netapp.io/)
Parameters:            backendType=ontap-nas,media=hdd,provisioningType=thin
AllowVolumeExpansion:  <unset>
MountOptions:
  rw
  nfsvers=3
  proto=tcp
ReclaimPolicy:      Retain
VolumeBindingMode:  Immediate
Events:             <none>
```

~$ k get CSIDriver
```
NAME                    ATTACHREQUIRED   PODINFOONMOUNT   STORAGECAPACITY   TOKENREQUESTS   REQUIRESREPUBLISH   MODES        AGE
[csi.trident.netapp.io](http://csi.trident.netapp.io/)   true             false            false             <unset>         false               Persistent   19h
```


$ k describe CSIDriver [csi.trident.netapp.io](http://csi.trident.netapp.io/)
```
Name:         [csi.trident.netapp.io](http://csi.trident.netapp.io/)
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  [storage.k8s.io/v1](http://storage.k8s.io/v1)
Kind:         CSIDriver
Metadata:
  Creation Timestamp:  2023-10-04T13:11:10Z
  Managed Fields:
    API Version:  [storage.k8s.io/v1](http://storage.k8s.io/v1)
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:attachRequired:
        f:fsGroupPolicy:
        f:podInfoOnMount:
        f:requiresRepublish:
        f:storageCapacity:
        f:volumeLifecycleModes:
          .:
          v:"Persistent":
    Manager:         tridentctl
    Operation:       Update
    Time:            2023-10-04T13:11:10Z
  Resource Version:  133615864
  UID:               3c4ae5d3-a115-4d2c-b4a8-62aa91d953b7
Spec:
  Attach Required:     true
  Fs Group Policy:     ReadWriteOnceWithFSType
  Pod Info On Mount:   false
  Requires Republish:  false
  Storage Capacity:    false
  Volume Lifecycle Modes:
    Persistent
Events:  <none>
```

**Comment by akalenyu** [comment]
Are you sure you don't want `fsGroupPolicy: File` on the trident CSIDriver? This is why you don't get fsGroup set up (only for RWO)
Trident does support fsGroup

**Comment by lzang** [comment]
@akalenyu I am using Robin (https://docs.robin.io/storage/5.3.4/index.html). The CSIDriver spec is pretty much the same as what @Ranjeet-Nvidia showed above for trident.

**Comment by akalenyu** [comment]
> @akalenyu I am using Robin (https://docs.robin.io/storage/5.3.4/index.html). The CSIDriver spec is pretty much the same as what @Ranjeet-Nvidia showed above for trident.

So I guess the same question applies, it may make sense to switch this CSIDriver spec

**Comment by mhenriks** [comment]
I am strongly in favor of having a "run as root escape hatch."  The issue doesn't only apply just to FSGroup.  Also root devices as documented here:  https://github.com/kubevirt/containerized-data-importer/blob/main/doc/block_cri_ownership_config.md

There simply may be cases where it is not possible to change driver/node settings.  Also since kubevirt/kubevirt supports root pods I think we should too.

**Comment by akalenyu** [comment]
> I am strongly in favor of having a "run as root escape hatch." The issue doesn't only apply just to FSGroup. Also root devices as documented here: https://github.com/kubevirt/containerized-data-importer/blob/main/doc/block_cri_ownership_config.md
> 
> There simply may be cases where it is not possible to change driver/node settings. Also since kubevirt/kubevirt supports root pods I think we should too.

Makes sense :+1:

**Comment by aglitke** [comment]
We still think this is something worth having as an escape hatch.  https://github.com/kubevirt/community/pull/248

**Comment by RoryDoherty** [comment]
Has this been implemented?
Running into this issue using a GKE cluster where I'm unable to change the containerd config on the nodes to implement this workaround https://github.com/kubevirt/containerized-data-importer/blob/main/doc/block_cri_ownership_config.md
which means I'm running into this issue: https://github.com/kubevirt/containerized-data-importer/issues/2433 

Open to any other workarounds as well

**Comment by akalenyu** [comment]
> Has this been implemented? Running into this issue using a GKE cluster where I'm unable to change the containerd config on the nodes to implement this workaround https://github.com/kubevirt/containerized-data-importer/blob/main/doc/block_cri_ownership_config.md which means I'm running into this issue: #2433
> 
> Open to any other workarounds as well

Usually you'd just change the containerd config and `systemctl restart containerd`,
but, for managed k8s it's probably best to be steered into the "appropriate" way of doing this.
Maybe it's one of the knobs at the point of cluster creation? with vague wording?

I was really surprised to see it omitted in https://cloud.google.com/kubernetes-engine/docs/how-to/customize-containerd-configuration because Block PVCs with non root pods will essentially be broken on GKE. So this is more than just a CDI problem.
