### ISSUE TITLE
Wrong API Group specified for blockOwnerDeletion

### ISSUE THREAD

**Issue by aglitke** [kubevirt/containerized-data-importer#292]
When attempting to import into a PVC the following error appears in the logs...

E0731 17:53:43.133558       1 import-controller.go:206] error processing pvc "default/golden-pvc": importer pod API create errored: pods "importer-golden-pvc-t5zvn" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion apps/v1 Kind PersistentVolumeClaim: allowed by openshift authorizer, no matches for apps/, Kind=PersistentVolumeClaim

**Comment by screeley44** [comment]
this is fixed with PR #249 afaict as stated in closed issue #290

**Comment by aglitke** [comment]
fixed by #293
