### ISSUE TITLE
upload success but datavolume PROGRESS is N/A

### ISSUE THREAD

**Issue by ZhangSetSail** [kubevirt/containerized-data-importer#2941]
**What happened**:
upload success but datavolume PROGRESS is N/A

**What you expected to happen**:
PROGRESS is 100.0% 

**How to reproduce it (as minimally and precisely as possible)**:
I have a windows iso image,I uploaded it through the following command
```
virtctl image-upload dv win10 --namespace default --size=8Gi --image-path /root/zh-cn_windows_10_consumer_editions_version_22h2_updated_oct_2023_x64_dvd_eb811ccc.iso  --storage-class=rainbondvolumerwx --uploadproxy-url=https://127.0.0.1:18443 --insecure
```
upload success
<img width="516" alt="image" src="https://github.com/kubevirt/containerized-data-importer/assets/101104760/a1d1a465-5a9b-4c8e-9213-59788de21c17">

**Additional context**:

I tried to use this dv to deploy a virtual machine. It can be used, but this N/A looks weird. I don’t know if it is a bug.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.57.0
- Kubernetes version (use `kubectl version`): 1.23
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by ZhangSetSail** [comment]
this is the dv deployed through url
<img width="460" alt="image" src="https://github.com/kubevirt/containerized-data-importer/assets/101104760/847884ac-b025-44d3-a783-076648544a1e">

**Comment by alromeros** [comment]
Hey @ZhangSetSail, thanks for opening the issue. This behavior is expected, we only report progress with import and clone-related operations. With upload, we set the N/A [here](https://github.com/kubevirt/containerized-data-importer/blob/main/pkg/controller/datavolume/controller-base.go#L703) but then skip the progress reporting since there's no available metrics.

Hope this helps!

**Comment by alromeros** [comment]
That said, this shouldn't be hard to implement. We always encourage users to open PRs, it should be a matter of implementing the last 100% once the upload pod succeeds (as happens [here](https://github.com/kubevirt/containerized-data-importer/blob/main/pkg/controller/datavolume/import-controller.go#L290) in the import-controller).

**Comment by ZhangSetSail** [comment]
OK Thanks for the reply, your reply is really fast.
