### ISSUE TITLE
Unable to mesh CDI importer pod with linkerd

### ISSUE THREAD

**Issue by bc185174** [kubevirt/containerized-data-importer#2948]
**What happened**:

Attempted to mesh the CDI component as per linkerd documentation, adding `linkerd.io/inject: enabled` annotation to CDI `importer` pods. The problem is the life cycle of sidecar containers and is something [Kubernetes is looking to address](https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/). It is currently feature gated and not GA. AFAIK, Istio suffers the same problem, because a k8s Job is not considered complete until all containers have stopped running.

```
Containers:
  linkerd-proxy:
...
    State:          Running
      Started:      Mon, 30 Oct 2023 15:33:21 +0000
    Ready:          True
...
  importer:
...
    State:          Terminated
      Reason:       Completed
      Message:      Import Complete
      Exit Code:    0
      Started:      Mon, 30 Oct 2023 15:33:22 +0000
      Finished:     Mon, 30 Oct 2023 15:33:35 +0000
    Ready:          False
...
  server:
...
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 30 Oct 2023 15:33:22 +0000
      Finished:     Mon, 30 Oct 2023 15:33:36 +0000
    Ready:          False
...
```

**What you expected to happen**:

Should be able to mesh cdi importer pods with linkerd.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy linkerd control plane using the helm chart as per the docs https://linkerd.io/2.14/tasks/install-helm/.
2. Create a VM that downloads disk image using CDI (i.e. download container image).
3. Mesh the CDI importer Pod with annotation: `linkerd.io/inject: enabled`.
4. Wait for pod to complete container image download. Will see that the `linkerd-proxy` continues to run indefinitely.

**Additional context**:

Related to https://github.com/kubevirt/kubevirt/issues/10556.

Kubernetes are actively looking to address this although currently behind feature gate. There are ways around this at the moment and this [article](https://tech.ingrid.com/on-linkerd-and-kubernetes-jobs/) explains it pretty well.

As per linkerds suggestion, on completion of importer, the container should call `curl -X POST http://localhost:4191/shutdown` to shutdown the linkerd proxy container.

The alternate solution is to allow the annotation `linkerd.io/inject: enabled` to propagate the annotation to importer pod as done with istio. Although the first option is preferred as it allows us to mesh the pod.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): N/A
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by bc185174** [comment]
@akalenyu any thoughts on following to support meshing the pod with linkerd?

> As per linkerds suggestion, on completion of importer, the container should call curl -X POST http://localhost:4191/shutdown to shutdown the linkerd proxy container.

**Comment by akalenyu** [comment]
> @akalenyu any thoughts on following to support meshing the pod with linkerd?
> 
> > As per linkerds suggestion, on completion of importer, the container should call curl -X POST http://localhost:4191/shutdown to shutdown the linkerd proxy container.

So one thought I had, since this problem would extend to others like istio, is to add a CDI config
field that lets you customize the workloads pod's hooks (importer/uploader/cloner):
https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/

But ultimately adopting the k8s solution would be better. I think its alpha in 1.28, so it may arrive soon?

**Comment by bc185174** [comment]
Yeah, linkerd do have it on their roadmap but ultimatly k8s native sidecar solution is the way to go. It is in alpha so likely it will graduate soon in future release. It also requires linkerd/istio to support this change and it is unlikely users will want to take alpha versions of these security-driven applications. So IMO it would make sense in the interim to support custom lifecycle hooks.
