### ISSUE TITLE
Permission errors when initiating clone

### ISSUE THREAD

**Issue by aglitke** [kubevirt/containerized-data-importer#295]
The clone source pod fails to create with the following error:

E0731 19:32:34.595426       1 clone-controller.go:213] error processing pvc "default/target-pvc": source pod API create errored: pods "clone-source-pod-" is forbidden: unable to validate against any security context constraint: [spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000000000, 1000009999] spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]

**Comment by mhenriks** [comment]
This help?

oc adm policy add-scc-to-user privileged -z hostpath-sa

**Comment by aglitke** [comment]
Actually you need (for kubevirtci based environments):

```
./cluster/kubectl.sh adm policy add-scc-to-user privileged -z cdi-sa
```

**Comment by aglitke** [comment]
The issue is that I didn't find this documented anywhere.  According to the README.md you just need to deploy the manifests.
