### ISSUE TITLE
Upload a qcow2 format file to dv， not convert it to raw format

### ISSUE THREAD

**Issue by liyang516** [kubevirt/containerized-data-importer#2988]
If I upload a qcow2 format file to dv，I wish cdi don't convert it to raw format

**Comment by awels** [comment]
So kubevirt PVC all contain raw images, why don't you want it converted?

**Comment by AmazingPangWei** [comment]
We have envisioned two uses of the qcow2 image format:
1. The VMs of a certain host may jointly rely on a public image, which can be used as a base using the qcow2 image, thereby saving time for downloading public images. This can accelerate the creation speed of virtual machines
2. Based on the qcow2 format, kubevirt can try to support internal snapshots of libvirt, thereby providing the possibility for the implementation of system checkpoint

**Comment by awels** [comment]
You don't need qcow2 images for 1. You can use a raw image as a base and layer cow layers on top. This is what happens when you use ephemeral images right now. For 2, we don't want to support internal snapshots of libvirt, we are supporting snapshots for the underlying storage providers. This is already possible right now with VMSnapshots. We are leveraging as much of the k8s eco system as possible, and we found using RAW images made that a lot easier than qcow2.

**Comment by AmazingPangWei** [comment]
Thank you so much. I'll try ephemeral images for 1. 
But for 2, can you tell me why supporting internal snapshots(or memory snapshot like `save/restore`) of libvirt is not a good choice for kubevirt? I've been posting this issue(https://github.com/kubevirt/kubevirt/issues/10609) for a long time,  but no one has replied.

**Comment by akalenyu** [comment]
So we're kind of trying to follow a principle where we stay as k8s native as possible wrt to kubevirt:
https://github.com/kubevirt/kubevirt/blob/main/docs/architecture.md#the-razor

Therefore we rely on the underlying storage provider to handle snapshots.
We have an API around this today with a solid docs entrypoint at https://github.com/kubevirt/user-guide/blob/main/docs/operations/snapshot_restore_api.md

BTW, are you sure https://github.com/kubevirt/kubevirt/issues/10609 is about memory snapshot? as opposed to regular persistent ones?

**Comment by AmazingPangWei** [comment]
@akalenyu Thanks for your explanation.
Yes, I'm sure https://github.com/kubevirt/kubevirt/issues/10609 is about memory snapshot, which has been implemented by `virsh snapshot-create/snapshot-revert` or `virsh save/restore`

**Comment by akalenyu** [comment]
/close

since memory snapshot is being tracked in https://github.com/kubevirt/kubevirt/issues/10609
