### ISSUE TITLE
Cloning node affinity not working with local storage

### ISSUE THREAD

**Issue by aglitke** [kubevirt/containerized-data-importer#299]
When using local storage with cloning if the target pod is scheduled first, it might bind to a PVC on a different node than the source pod.  In that case it will be impossible to schedule the target pod since it requests affinity with the source pod (which is bound to the node containing the source pvc) and affinity with the target pvc which is on a different node.

The solution is probably to spawn the source pod and ensure it has been scheduled prior to creating the target pod.

**Comment by jeffvance** [comment]
I think maybe kubernetes _expectations_ may help here  @davidvossel ?

**Comment by zvikorn** [comment]
Was the target pod scheduled before the source pod? It should be in pending state until the source pod is created.

**Comment by jeffvance** [comment]
Interested in feedback from @davidvossel but _maybe_ expectations could be used to ensure that the source pod is created and running before the target pod is created. The create order in the code does not dictate the order these pod will actually be scheduled/created. I don't see in the cloner code a mechanism to ensure the source pod is scheduled/created prior the target pod.

**Comment by zvikorn** [comment]
I don’t understand why we need this. The target pod will be in pending state until the source pod is scheduled

**Comment by zvikorn** [comment]
"When using local volumes, it is recommended to create a StorageClass with volumeBindingMode set to WaitForFirstConsumer. See the example. Delaying volume binding ensures that the PersistentVolumeClaim binding decision will also be evaluated with any other node constraints the Pod may have, such as node resource requirements, node selectors, Pod affinity, and Pod anti-affinity."

**Comment by aglitke** [comment]
On my 3.9 cluster it appears I was missing a feature gate.  According to [the docs](https://github.com/kubernetes-incubator/external-storage/tree/local-volume-provisioner-v2.0.0/local-volume#enabling-the-alpha-feature-gates) the three required are:

 - PersistentLocalVolumes=true
 - VolumeScheduling=true
 - MountPropagation=true

You are also correct that the volumeBindingMode must be WaitForFirstConsumer

**Comment by aglitke** [comment]
Retesting this with the necessary changes....

**Comment by aglitke** [comment]
Proper enablement of the feature gates has resolved this problem.  Closing.

**Comment by jeffvance** [comment]
@aglitke Should there be a doc issue somewhere to capture these requirements:

> PersistentLocalVolumes=true
VolumeScheduling=true
MountPropagation=true
volumeBindingMode must be WaitForFirstConsumer

**Comment by aglitke** [comment]
It's specific to k8s < 1.10 with local storage.  I think it belongs in the domain of storage setup.  At least if someone hits this issue again with local storage we'll have it documented here in this issue and we can reference it.
