### ISSUE TITLE
Document the make targets and environment variables required to build the CDI builder container

### ISSUE THREAD

**Issue by cfilleke** [kubevirt/containerized-data-importer#2990]
**Description**:
Document how to build the builder helper with bazel on various architectures

**What you expected**:
There are undocumented make targets and environment variables, and the build scripts invoke environment variables that are undocumented, and set defaults which are inappropriate for building test builder containers and for architectures other than x86.

**URL**:
Provide a link to the documentation: there is none for this aspect of the KubeVirt CDI tool. That's the problem. 

**Additional context**:
This procedure will be tested on an s390x Ubunu LPAR, with the test builder container to be stored in IBM cloud container storage so that _all_ the environment variable settings can be tested, as these are at variance with the default settings of an x86 build container object format and quay.io registry.

**Comment by alromeros** [comment]
Hey @cfilleke, thanks for opening this issue.

I agree this is something that could be improved. I created a Jira story to track the issue: https://issues.redhat.com/browse/CNV-35422.

Will update with any relevant updates.

**Comment by akalenyu** [comment]
Thanks for opening this. We have an outdated dock at https://github.com/kubevirt/containerized-data-importer/blob/dd78d005e62e73b4dada200f425e6fe9146a1804/hack/README.md?plain=1#L66
And meanwhile this may be a good reference for building different arch:
https://github.com/kubevirt/containerized-data-importer/pull/1863/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R36
