### ISSUE TITLE
StorageProfile needs to be patched for the rancher local-path provisioner

### ISSUE THREAD

**Issue by ishankhare07** [kubevirt/containerized-data-importer#3005]
**Is your feature request related to a problem? Please describe**:
A clear and concise description of what the problem is.
Currently when creating a `DataVolume` under a fresh install of k3s, to be compatible with rancher's `local-path` provisioner, on needs to patch the `StorageProfile` named `local-path` as described in [this comment](https://github.com/kubevirt/kubevirt/issues/7078#issuecomment-1022333608). Instead of `local` I just had to do
```
kubectl patch --type merge -p '{"spec": {"claimPropertySets": [{"accessModes": ["ReadWriteOnce"]}]}}' StorageProfile local-path
```

**Describe the solution you'd like**:
Rancher's (k3s) default storage provisioner be supported(?)

**Describe alternatives you've considered**:

**Additional context**:

**Comment by alromeros** [comment]
Hey @ishankhare07, thanks for opening this issue. I think this is the default behavior for unrecognized provisioners, and the best way to proceed would be to manually specify the desired access mode when creating the DV or to patch the storage profile as you did. As an alternative, you can also submit a PR to hardcode defaults for your provisioner. You can use this PR as an example: https://github.com/kubevirt/containerized-data-importer/pull/2613. Hope this helps!

**Comment by dcjulian29** [comment]
I had a similar problem recently with the CDI Quick Lab and was able to resolve the issue by adding this to the YAML to define the value during deployment:

    storage:
      accessModes:
        - ReadWriteOnce
After adding that, the import was able to complete.
