### ISSUE TITLE
enable build-the-builder script to build container that will work for s390x

### ISSUE THREAD

**Issue by cfilleke** [kubevirt/containerized-data-importer#3010]
**Is your feature request related to a problem? Please describe**:
Built in to the CDI builder helper container is a script `output-bazel-arch.sh` which excludes support for non-ARM non-x86 architectures. Also, the Dockerfile assumes there is a pre-built binary available in https://github.com/bazelbuild/bazel/releases/download which in the case of s390x architecture there is not. 

**Describe the solution you'd like**:
 The 'new feature' here would be to add s390x to the output-bazel-arch.sh list of supported architecture, e.g:

```
PLATFORM=$(uname -m)
case ${PLATFORM} in
x86_64* | i?86_64* | amd64*)
    ARCH="x86_64"
    ;;
s390x)
    ARCH="s390x"
    ;;
aarch64* | arm64*)
    ARCH="arm64"
    ;;
*)
    echo "invalid Arch, only support x86_64, aarch64"
    exit 1
    ;;
esac

echo $ARCH

```

and obtain the pre-built bazel binary for s390x from an alternative release download repository

**Describe alternatives you've considered**:
An alternative would be to provide the script to build bazel on the local host before copying it to the builder container

**Comment by akalenyu** [comment]
/close
encapsulated in https://github.com/kubevirt/containerized-data-importer/issues/3021
