### ISSUE TITLE
CDI importer requires static credentials for S3 and GCS

### ISSUE THREAD

**Issue by emmanuel** [kubevirt/containerized-data-importer#3026]
**Is your feature request related to a problem? Please describe**:
Workloads should not have access to long-lived credentials. In cloud environments in particular, there are mechanisms for distributing short-lived credentials and SDKs support fetching and utilizing such creds. CDI prevents using the security best practice of using short-lived credentials for image retrieval from S3 and GCS sources. 

**Describe the solution you'd like**:
CDI's operator should provide a method for specifying the image importer pod's `ServiceAccount`. This would enable access to existing credential distribution mechanisms: AWS's IRSA credentials as well as GKE Workload Identity. Additionally, the importer will need to be updated to rely on "ambient" credentials (retrieved by the cloud provider SDK), instead of [the importer's current hard-coded reliance on static credentials](https://github.com/kubevirt/containerized-data-importer/blob/main/pkg/importer/s3-datasource.go#L174). This could be accomplished by extending the `S3DataSource` and `GCSDataSource` structs with a `serviceAccountName` member, updating the relevant function signatures, and then branching when creating the client.

**Describe alternatives you've considered**:
Currently have created a specific IAM user, issued an access key ID and secret key, and using a set of hard-coded creds in a Kubernetes secret referenced by the importer. It "works", at the cost of violating existing security approaches for workload authentication.

**Comment by feitnomore** [comment]
I understand that using AWS's IRSA or GKE Workload Identity will only work if you're running CDI inside AWS or GCP. If you are running CDI/Kubevirt, let's say, in an OnPrem Environment, that approach won't work.
My understanding is that the solution was designed in a way that you would be able to import an image from AWS S3 or GCS, to any place you run CDI.
@awels , would love to hear your thoughts here!

Thanks

**Comment by emmanuel** [comment]
I can't speak to the intent of the existing implementation. However, the fact that AWS & GCP's workload identity mechanisms only apply in their respective environments seems implied. I'm not sure what your comment is communicating. 

My request is (1) to allow specifying the _Kubernetes_ `ServiceAccount` that the importer runs with, and (2) to utilize the (already-linked) cloud-provider clients _in the way they're designed to be used_. This will result in less and more flexible code, and better security.

**Comment by emmanuel** [comment]
Regarding (1): supporting specifying the `ServiceAccount` of the importer pod better aligns KubeVirt with the security infrastructure of Kubernetes overall. 

Is there an argument against that as a goal?

**Comment by feitnomore** [comment]
Please, don't get me wrong, I'm not arguing against anything, I'm just trying to understand the request.

**Comment by emmanuel** [comment]
Ahh, I read your comment too hastily. I now see that you are pointing out that the current implementation supports _pulling from_ cloud storage without _running on_ cloud compute. I see the reasoning behind the existing implementation now, and I see that I responded too harshly, based on my assumed understanding. 

I'm sorry for jumping to conclusions and reacting rashly. Sorry @feitnomore.

**Comment by feitnomore** [comment]
Not a problem. I would still love to hear @awels comments on this. From my standpoint, I understand that the implementation today is done in a way that we don't *lock-in* certain *image sources* to the  *environment* we're running on. This implementation would be the *foundation* to  allow workloads to move/run in different infrastructures.

**Comment by awels** [comment]
So I see no fundamental problem with the request, just that we have no infra structure to test it. Best we could do is unit tests. As @feitnomore mentioned the current implementation is aimed at having the cloud storage in the cloud while the image is imported into a local cluster. The importer pod run in the context of the local cluster and thus has no access to service accounts associated with the cloud storage.

We can definitely implement that change that allows it, but as I said we have no real mechanism for testing it properly which would be my biggest issue.

**Comment by feitnomore** [comment]
I think we'll also need to define/create/implement some kind of mechanism so that the importer pod can determine if it is running inside a Cloud Provider, no? The mechanisms suggested by @emmanuel authenticate in a different way, so the importer pod would need to know its running on a cloud environment, thus, authenticating in a different way.

**Comment by awels** [comment]
We would have to modify the API that will include that information. So if certain fields are set, we will assume we are in the cloud environment and use those settings. If you set those fields and are not in the cloud environment it will simply fail. I am not too worried about that.

**Comment by awels** [comment]
I have no issues with the proposed change, as I mentioned the issue is with the testing. Once we get the code in, we own it and have to support it, and I want confidence the code remains working, so I need some kind testing arrangement that gives me that confidence. I would probably be fine with some unit tests that mock out the actual SDK calls. At least so we can see that our end of the code works provided that the SDK gives us the right information.

**Comment by awels** [comment]
I can help with that no problem. The structs for the API can be found in https://github.com/kubevirt/containerized-data-importer/blob/main/staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go Each different source has its own struct. Once you have modified the struct run `make generate` and it should generate the appropriate code that you can be used in the application.

**Comment by emmanuel** [comment]
Great, glad to hear the change would be welcomed. I hear you about the testing; I will look around for some references/example tests where the AWS/GCP SDKs are in play. I don't have a slam-dunk idea at the moment, but I'm pretty confident that there are ways to get reasonable assurances via unit tests. 

I'll start putting together a PR. I probably won't have much time this coming week, but I'll get in touch when I have something to show; I'd be glad for some early feedback to verify directional alignment before I get too far into it. 

Thanks for the discussion and guidance @awels and @feitnomore.
