### ISSUE TITLE
Uninstall requires additional steps

### ISSUE THREAD

**Issue by ErikEngerd** [kubevirt/containerized-data-importer#3036]
**What happened**:
In installed v1.58.0 of cdi using

```
VERSION=v1.58.0
wget https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-operator.yaml
wget https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-cr.yaml
kubectl apply -f cdi-operator.yaml
kubectl apply -f cdi-cr.yaml 
```
Then I uninstalled the two files using `kubectl delete -f`. 
Now the `cdi` namespace remains in Terminating state. 
To clean up the installation, I had to do 
```
kubectl delete apiservices.apiregistration.k8s.io v1beta1.upload.cdi.kubevirt.io
kubectl delete mutatingwebhookconfigurations.admissionregistration.k8s.io cdi-api-datavolume-mutate
kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io cdi-api-dataimportcron-validate cdi-api-datavolume-validate cdi-api-populator-validate cdi-api-validate

# set finalizers array to empty
k edit cdi cdi :w
```

**What you expected to happen**:

CDI should be uninstalled. 

**How to reproduce it (as minimally and precisely as possible)**:

Install followed by uninstall. 

**Environment**:
- CDI version: v1.58.0
- Kubernetes version: 1.26.11 
- DV specification: N/A
- Cloud provider or hardware configuration: AKS
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by awels** [comment]
The order when uninstalling is important. delete the cr first, then the operator.yaml. Deleting the CR causes the operator to clean up resources. Then you can delete the namespace. If you delete them at the same time, it is possible for the operator pod to be deleted before it can clean up the resources.

**Comment by aglitke** [comment]
During the SIG-Storage meeting we discussed the idea of putting a finalizer on the operator that would not be removed until the CDI CRs are removed.  This could keep the operator around even after NS deletion so that it could finish cleaning up.  However, finalizers come with their own complexities.  It's best to delete the CRs first and then the operator.
