### ISSUE TITLE
Use ptr instead of pointer and update code that now can use ptr as well

### ISSUE THREAD

**Issue by avlitman** [kubevirt/containerized-data-importer#3042]
**Is your feature request related to a problem? Please describe**:
In this pr: https://github.com/kubevirt/containerized-data-importer/pull/3009 I needed to upgrade pointer to ptr, I replaced the parts usinf directly pointer.
Now as a next step we can reduce code in other places by using ptr.

**Describe the solution you'd like**:
like here:
![image (1)](https://github.com/kubevirt/containerized-data-importer/assets/64130977/fc06cb85-6800-4219-9ad7-9ae25b4d4dc9)

And @nunnatsa started a tool to identify the places in the code we need to update: https://github.com/nunnatsa/redundantptr

**Describe alternatives you've considered**:
The current state is an alternative but we prefer to reduce code .

**Additional context**:
This issue discussed with @akalenyu.

**Comment by aglitke** [comment]
@akalenyu Is this resolved?  I hear you might have done a PR to address this.
