### ISSUE TITLE
Document how to enable podman sockets to run cluster-up

### ISSUE THREAD

**Issue by cfilleke** [kubevirt/containerized-data-importer#3052]
**Description**:
if your CLI is podman, get 
```
./cluster-up/up.sh
no working container runtime found. Neither docker nor podman seems to work.
make: *** [Makefile:108: cluster-up] Error 1
```

**What you expected**:
running `make cluster-up` should result in a running cluster with kubevirt-cli operator installed and ready to test. 
This requires that the unix socket in `/run/podman/podman.socket` be enabled. This is not documented. 

**URL**:
[documentation for podman socket activation](https://github.com/containers/podman/blob/main/docs/tutorials/socket_activation.md)

So at minimum need a link to the above documentation and an exhortation in cluster-up/README.md to at least run 
```
systemctl start podman.socket
```
as root in order to enable `/run/podman/podman.sock` 

**Additional context**:
Add any other context about the issue here.

**Comment by awels** [comment]
So this is documented in the kubevirtci repo. https://github.com/kubevirt/kubevirtci/blob/main/PODMAN.md it explains how to do both root and rootless podman. Maybe link that as well?

**Comment by cfilleke** [comment]
This actually is documented. It was just a matter of finding out where.
