### ISSUE TITLE
【VDDK】No new block status data at offset

### ISSUE THREAD

**Issue by cjbAda** [kubevirt/containerized-data-importer#3054]
**What happened**:
When I copy continuous data exceeding 2GB from VMware disk, I noticed that the log keeps printing "No new block status data at offset". After analyzing the code, I found an error in the logic for retrieving blocks in the GetBlockStatus function.

**What you expected to happen**:
It is expected to be able to complete the copying process normally.

**How to reproduce it (as minimally and precisely as possible)**:
There is an error in the following code block. The value of lastOffset is incorrect when checking whether to merge the previous block.
vddk-datasource_amd64.go：

		for i := 0; i < len(extents); i += 2 {
			length, flags := extents[i], extents[i+1]
			if blocks != nil {
				last := len(blocks) - 1
				lastBlock := blocks[last]
				lastFlags := lastBlock.Flags
				**lastOffset := lastBlock.Offset + uint64(lastBlock.Length)**
				if lastFlags == flags && lastOffset == offset {
					// Merge with previous block
					blocks[last] = &BlockStatusData{
						Offset: lastBlock.Offset,
						Length: lastBlock.Length,
						Flags:  lastFlags,
					}
				} else {
					blocks = append(blocks, &BlockStatusData{Offset: offset, Length: length, Flags: flags})
				}
			} else {
				blocks = append(blocks, &BlockStatusData{Offset: offset, Length: length, Flags: flags})
			}
			offset += uint64(length)
		}

I modified it as follows, and it has been verified to run normally:

		for i := 0; i < len(extents); i += 2 {
			length, flags := extents[i], extents[i+1]
			if blocks != nil {
				last := len(blocks) - 1
				lastBlock := blocks[last]
				lastFlags := lastBlock.Flags
				**lastOffset := lastBlock.Offset**
				if lastFlags == flags && lastOffset == offset {
					// Merge with previous block
					blocks[last] = &BlockStatusData{
						Offset: lastBlock.Offset,
						**Length: lastBlock.Length + length,**
						Flags:  lastFlags,
					}
				} else {
					blocks = append(blocks, &BlockStatusData{Offset: offset, Length: length, Flags: flags})
				}
			} else {
				blocks = append(blocks, &BlockStatusData{Offset: offset, Length: length, Flags: flags})
			}
			offset += uint64(length)
		}

Please help me confirm if this modification is okay. Thank you.

**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): N/A
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by akalenyu** [comment]
Hey, thanks for submitting this. I would be interested to know if this passes our functional tests too. There are a few in datavolume_test.go you can try running, otherwise, you can open a draft PR and cc me; we will run one of the CI lanes ad-hoc.
/cc @mrnold

**Comment by mrnold** [comment]
I think this length addition is right:

```
// Merge with previous block
blocks[last] = &BlockStatusData{
	Offset: lastBlock.Offset,
	**Length: lastBlock.Length + length,**
	Flags:  lastFlags,
}
```
It was even present in the original precopy code this was derived from: https://github.com/ManageIQ/manageiq-v2v-conversion_host/blob/master/wrapper/pre_copy.py#L50 

I am less sure about this one though:
`-**lastOffset := lastBlock.Offset + uint64(lastBlock.Length)** `
`+**lastOffset := lastBlock.Offset**`

I think the name "lastOffset" might not accurately describe its intention, it's more like "expectedOffsetOfNextExtent". If I am remembering correctly, it is used to make sure that the start of the extent given by libnbd matches the end of the last block stored in the block status list. If it matches, and the flags match (basically is all the data zero or not), then GetBlockStatus can merge it into a bigger block for more efficient transfer.

Does your VMware disk only transfer correctly if you apply both of these changes?

**Comment by cjbAda** [comment]
> I think this length addition is right:
> 
> ```
> // Merge with previous block
> blocks[last] = &BlockStatusData{
> 	Offset: lastBlock.Offset,
> 	**Length: lastBlock.Length + length,**
> 	Flags:  lastFlags,
> }
> ```
> 
> It was even present in the original precopy code this was derived from: https://github.com/ManageIQ/manageiq-v2v-conversion_host/blob/master/wrapper/pre_copy.py#L50
> 
> I am less sure about this one though: `-**lastOffset := lastBlock.Offset + uint64(lastBlock.Length)** ` `+**lastOffset := lastBlock.Offset**`
> 
> I think the name "lastOffset" might not accurately describe its intention, it's more like "expectedOffsetOfNextExtent". If I am remembering correctly, it is used to make sure that the start of the extent given by libnbd matches the end of the last block stored in the block status list. If it matches, and the flags match (basically is all the data zero or not), then GetBlockStatus can merge it into a bigger block for more efficient transfer.
> 
> Does your VMware disk only transfer correctly if you apply both of these changes?

Thanks.

**Comment by cjbAda** [comment]
> I think this length addition is right:
> 
> ```
> // Merge with previous block
> blocks[last] = &BlockStatusData{
> 	Offset: lastBlock.Offset,
> 	**Length: lastBlock.Length + length,**
> 	Flags:  lastFlags,
> }
> ```
> 
> It was even present in the original precopy code this was derived from: https://github.com/ManageIQ/manageiq-v2v-conversion_host/blob/master/wrapper/pre_copy.py#L50
> 
> I am less sure about this one though: `-**lastOffset := lastBlock.Offset + uint64(lastBlock.Length)** ` `+**lastOffset := lastBlock.Offset**`
> 
> I think the name "lastOffset" might not accurately describe its intention, it's more like "expectedOffsetOfNextExtent". If I am remembering correctly, it is used to make sure that the start of the extent given by libnbd matches the end of the last block stored in the block status list. If it matches, and the flags match (basically is all the data zero or not), then GetBlockStatus can merge it into a bigger block for more efficient transfer.
> 
> Does your VMware disk only transfer correctly if you apply both of these changes?

yes, Modifying these two places will ensure that the VMware disk is transmitted correctly. 
However, after reviewing the code again, I understand that lastOffset should be kept as lastOffset := lastBlock.Offset + uint64(lastBlock.Length) as you said, and there is no need to modify it; only Length: lastBlock.Length + length needs to be modified.
Additionally, could we consider adding a break statement in the following code snippet? Changing it from:

go
if uint64(lastOffset) == newOffset {
	logger.Log().Errorf("No new block status data at offset %d", newOffset)
}
to:

go
if uint64(lastOffset) == newOffset {
	logger.Log().Errorf("No new block status data at offset %d", newOffset)
	break
}
This modification will exit the loop if there is no new block status data at the specified offset.
thanks.

**Comment by mrnold** [comment]
Yes, I think it would be okay to exit the loop after the first occurrence of that message. That matches the original code more closely too: https://github.com/ManageIQ/manageiq-v2v-conversion_host/blob/master/wrapper/pre_copy.py#L80

The only thing I might do differently is instead of a break, return the whole block like in the error handling case immediately above:

```
if uint64(lastOffset) == newOffset {
	klog.Infof("No new block status data at offset %d", newOffset)
	block := &BlockStatusData{
		Offset: uint64(extent.Start),
		Length: uint32(extent.Length),
		Flags:  0,
	}
	blocks = []*BlockStatusData{block}
	return blocks
}
```

I haven't checked this completely, but it seems safer to fall back to copying the whole block if there's a problem getting the status of any range inside that block.

**Comment by cjbAda** [comment]
> Yes, I think it would be okay to exit the loop after the first occurrence of that message. That matches the original code more closely too: https://github.com/ManageIQ/manageiq-v2v-conversion_host/blob/master/wrapper/pre_copy.py#L80
> 
> The only thing I might do differently is instead of a break, return the whole block like in the error handling case immediately above:
> 
> ```
> if uint64(lastOffset) == newOffset {
> 	klog.Infof("No new block status data at offset %d", newOffset)
> 	block := &BlockStatusData{
> 		Offset: uint64(extent.Start),
> 		Length: uint32(extent.Length),
> 		Flags:  0,
> 	}
> 	blocks = []*BlockStatusData{block}
> 	return blocks
> }
> ```
> 
> I haven't checked this completely, but it seems safer to fall back to copying the whole block if there's a problem getting the status of any range inside that block.

Yes, this approach is more reliable. It is possible that the size of this block exceeds 2GB.

**Comment by cjbAda** [comment]
> lastBlock.Length + length
There is an integer overflow issue here with lastBlock.Length + length because length is of type uint32. If lastBlock.Length is 2GB and the subsequent length to be merged is also 2GB, adding them together would exceed the maximum value of uint32, causing an overflow. It is recommended to define Length as uint64. Thank you.

**Comment by mrnold** [comment]
I'm not sure if anyone else was planning to take this on, but I gave it a shot anyway: #3242
