### ISSUE TITLE
We should replace "cdi-controller-***" with "cdi-deployment-***"

### ISSUE THREAD

**Issue by matthewei** [kubevirt/containerized-data-importer#3066]
**What happened**:
when we deploy the cdi and we can get the result as fllows
![image](https://github.com/kubevirt/containerized-data-importer/assets/86186853/00ad2422-067f-438c-acc1-c5bb85cf043d)

**What you expected to happen**:
I think we should replace "cdi-controller-***" with "cdi-deployment-***" and we get the controller pod.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): N/A
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by alromeros** [comment]
Hi @matthewei, thanks for bringing up this issue. We can have some conversation around this but we would need to delve into the reasons/arguments behind your proposal. CDI is currently functioning well, and changing this name doesn't seem a high priority, but as said, we can see what other team members think.

**Comment by akalenyu** [comment]
I agree the name is confusing; I worry that the upgrade path would need special handling (delete leftover cdi-deployment Deployment rsc)

**Comment by matthewei** [comment]
> Hi @matthewei, thanks for bringing up this issue. We can have some conversation around this but we would need to delve into the reasons/arguments behind your proposal. CDI is currently functioning well, and changing this name doesn't seem a high priority, but as said, we can see what other team members think.
Yes, I can't aggree anymore. The CDI works well. As there are more and more CDI users, we should standardize the naming of CDI, and the naming should be conscious. Although the priority is not high, we should optimize it in a planned way. What do you think?

**Comment by matthewei** [comment]
> Hi @matthewei, thanks for bringing up this issue. We can have some conversation around this but we would need to delve into the reasons/arguments behind your proposal. CDI is currently functioning well, and changing this name doesn't seem a high priority, but as said, we can see what other team members think.

As there are more and more CDI users, we should standardize the naming of CDI, and the naming should be conscious. Although the priority is not high, we should optimize it in a planned way. What do you think?

**Comment by matthewei** [comment]
> delete leftover cdi-deployment Deployment rsc)

yes, this is a challenge. But the "cdi-deployment-***" name does confuse users.

**Comment by matthewei** [comment]
What about other experts' opinion?

**Comment by ShellyKa13** [comment]
/reopen
I think we should update the issue with resolution before it being closed.

**Comment by akalenyu** [comment]
My thought haven't changed much https://github.com/kubevirt/containerized-data-importer/issues/3066#issuecomment-1892024933; I still think that introducing the extra upgrade path is quite risky so I am not very inclined to take that risk for a small benefit
