### ISSUE TITLE
copy cdi-deployment manifest as part of `make manifests`

### ISSUE THREAD

**Issue by jeffvance** [kubevirt/containerized-data-importer#322]
This may be a short-term fix so that we don't have to manually update the version string in the deployment manifest. Longer term we may or may not want to include any manifests in the cdi repo.

**Comment by screeley44** [comment]
I think this can be closed, the generated manifests are created in the folder called `generated` and the old controller manifest will be going away so not sure there needs to be any work done for this... @jeffvance do you agree?

**Comment by aglitke** [comment]
Worked fine when releasing cdi-1.1.1-alpha.1 -- closing.
