### ISSUE TITLE
Slow import

### ISSUE THREAD

**Issue by cybercoder** [kubevirt/containerized-data-importer#3220]
the import of a qcow2 image via HTTP is too slow. Also, I've tried a not-compressed raw image and it's as slow as the first one.

I've used ```"preallocation": true```, and have placed the Ubuntu cloud image in the node and called it using in-cluster service.
```mynginx.svc.defaul.cluster.local...```
And there's no difference.
I'm using ```Ceph``` as SC in my bare-metal Kubernetes cluster. All Ceph OSDs are SSD disks.
When it tries to import a 15GB ms-windows 2019 raw cloud image, it takes about 15-20 mins.

**Comment by cybercoder** [comment]
The Ceph storage class benchmark using ```kubestr```:  ( Averages in KiB/s )
![Screen Shot 1403-02-13 at 14 18 13](https://github.com/kubevirt/containerized-data-importer/assets/437872/a0fe2017-8529-41bf-8f7a-32c19d272ce4)

**Comment by alromeros** [comment]
Hey @cybercoder, which version of CDI are you using?

**Comment by cybercoder** [comment]
> Hey @cybercoder, which version of CDI are you using?

The ceph cluster on vmware esxi was the bottleneck. I've used 3 HP g8 bare-metals with SSDs as OSDs, and it's perfect.
