### ISSUE TITLE
Post jinjia template on release page

### ISSUE THREAD

**Issue by shiywang** [kubevirt/containerized-data-importer#323]
Although this https://github.com/kubevirt/containerized-data-importer/issues/223 was closed, I haven't seen jinja template posted on release page, this is an issue to track that, I'll close it once I see it appears on the release page. then I will start to look at https://github.com/kubevirt/kubevirt-ansible/issues/301 https://github.com/kubevirt/kubevirt-ansible/issues/327

@copejon thanks!!

**Comment by jeffvance** [comment]
closed by pr #321
