### ISSUE TITLE
Add s390x cross-build libraries to builder container docker file

### ISSUE THREAD

**Issue by cfilleke** [kubevirt/containerized-data-importer#3289]
**Is your feature request related to a problem? Please describe**:
The problem this solves is enabling a cross-build of CDI s390x containers on x86. 

**Describe the solution you'd like**:
The libraries for s390x cross-compilation are maintained in the epel repositories, so the preferred solution is to `dnf install` these libraries directly into the x86 builder container for CDI, i.e. putting these lines into the Dockerfile:

```
RUN \
       if test "${ARCH}" = amd64; then 
       dnf install -y --setopt=install_weak_deps=False  --installroot /usr/s390x-linux-gnu/sys-root --forcearch s390x --releasever 9 \
          glibc-devel \
          glibc-static && \
      dnf install -y epel-release && \
      dnf install -y --setopt=install_weak_deps=False \
          gcc-s390x-linux-gnu && \
      dnf clean -y all;
fi
```

**Describe alternatives you've considered**:
It wasn't clear, at first, whether the support for s390x cross-compiles should be statically built into the builder container as in kubevirt, or should be installed on the fly during the build of the CDI images as is done for cross-compile of arm containers. 

**Additional context**:
in order to _only_ build the cross-compile support for s390x into the x86 builder container, need to check the architecture of the platform as in the kubevirt builder build.

**Comment by awels** [comment]
So if I understand the question correctly. KubeVirt has one builder per arch, where CDI has one builder, that installs packages based on the detected arch when running the build. And you want to know which version we want to do with CDI. Aka either switch to the KubeVirt model, or keep the CDI model, and install the packages on the fly if we detect s390x build in progress?

**Comment by cfilleke** [comment]
Good questions! Let me see if I can address that in a design document to
attach to the issue today.

**Comment by cfilleke** [comment]
<img width="1072" alt="Screenshot 2024-08-05 at 8 59 01 AM" src="https://github.com/user-attachments/assets/7c0f77ef-3684-4eaa-a862-22706ccbd9e0">
We're intending to use option 'D' for the unit test phase of CI/CD implementation, where the runtime of the builder container is built in the github x86 test environment without Bazel (since there is no official binary of bazel build for s390x, and it's not needed for unit test anyway), use option 'C' when we progress to end-to-end testing there, and option 'A' for when we can build the builder container for s390x in our orange zone.  This issue addresses option 'C'.
