### ISSUE TITLE
should there be a default provider defined in cluster/up.sh?

### ISSUE THREAD

**Issue by jeffvance** [kubevirt/containerized-data-importer#331]
and if so should it be "k8s-1.10.4"?

**Comment by aglitke** [comment]
Yes.  I was going to propose something like this as well.  It should probably be the latest reasonable k8s release so the above looks good to me.

**Comment by nellyc** [comment]
Is there a PR for this one already?

**Comment by jeffvance** [comment]
@nellyc No pr yet.

**Comment by jeffvance** [comment]
@awels mentions in pr #332 that there is a provider default ( k8s-1.10.4)
