### ISSUE TITLE
为啥指定的镜像源，比如qcow2格式的镜像文件，会默认转为img格式，能保持原格式不变，供kubevirt使用吗

### ISSUE THREAD

**Issue by zhenliangliang** [kubevirt/containerized-data-importer#3330]
**Is your feature request related to a problem? Please describe**:
A clear and concise description of what the problem is.

**Describe the solution you'd like**:

**Describe alternatives you've considered**:

**Additional context**:

**Comment by zhenliangliang** [comment]
Why is the specified image source, such as the image file in qcow2 format, converted to img format by default? Can the original format be kept unchanged for use by kubevirt?

**Comment by awels** [comment]
We want to leverage the storage capabilities of the kubernetes platform as much as possible and converting the images to RAW makes this much simpler. qcow2 images come with their own capabilities that we would have to manage and we prefer to use the capabilities from the storage provider instead. Is there any particular reason you want to use qcow2 images directly?
