### ISSUE TITLE
Intermittent CI failures in master

### ISSUE THREAD

**Issue by copejon** [kubevirt/containerized-data-importer#335]
CI is failing sporadically on the [CI master branch buildes](https://travis-ci.org/kubevirt/containerized-data-importer/builds/415627625).

The failures occur with tests involving `xz`:

Message: `could not format test data: Error writing to file: limit reached`

Complete test output:

```
Streaming Data Conversion
/go/src/kubevirt.io/containerized-data-importer/test/functional/importer/datastream/datastream_test.go:22
  when data is in a supported file format
  /go/src/kubevirt.io/containerized-data-importer/test/functional/importer/datastream/datastream_test.go:24
    should decompress xz [It]
    /go/src/kubevirt.io/containerized-data-importer/test/functional/importer/datastream/datastream_test.go:143
    *** skipping endpoint extension ".iso.xz" as exception
    /go/src/kubevirt.io/containerized-data-importer/test/functional/importer/datastream/datastream_test.go:184
------------------------------
••STEP: [BeforeEach] Creating temporary dir /tmp/.tmp-G2zfqjqX30Zj
STEP: Getting size of source file "/go/src/kubevirt.io/containerized-data-importer/test/images/tinyCore.iso"
INFO: size = 18874368
STEP: Converting source file to format: [.tar .xz]
STEP: [AfterEach] Cleaning up temporary dir /tmp/.tmp-G2zfqjqX30Zj
------------------------------
• Failure [3.099 seconds]
Streaming Data Conversion
/go/src/kubevirt.io/containerized-data-importer/test/functional/importer/datastream/datastream_test.go:22
  when data is in a supported file format
  /go/src/kubevirt.io/containerized-data-importer/test/functional/importer/datastream/datastream_test.go:24
    should unpack .tar.xz [It]
    /go/src/kubevirt.io/containerized-data-importer/test/functional/importer/datastream/datastream_test.go:143
    Error formatting test data.
    Expected error:
        <*errors.withStack | 0xc420300180>: {
            error: {
                cause: {
                    error: {
                        cause: {s: "limit reached"},
                        msg: "Error writing to file",
                    },
                    stack: [0xa2eb26, 0xa2df67, 0xa30b98, 0x6c42fc, 0x6c3f3e, 0x6c321f, 0x6ca316, 0x6c9d23, 0x6e971d, 0x6e943c, 0x6e8a4c, 0x6ead7c, 0x6ecfd8, 0x6ecd59, 0xa2fe24, 0x4eb140, 0x45c781],
                },
                msg: "could not format test data",
            },
            stack: [0xa2dfa7, 0xa30b98, 0x6c42fc, 0x6c3f3e, 0x6c321f, 0x6ca316, 0x6c9d23, 0x6e971d, 0x6e943c, 0x6e8a4c, 0x6ead7c, 0x6ecfd8, 0x6ecd59, 0xa2fe24, 0x4eb140, 0x45c781],
        }
        could not format test data: Error writing to file: limit reached
    not to have occurred
    /go/src/kubevirt.io/containerized-data-importer/test/functional/importer/datastream/datastream_test.go:153
```

**Comment by aglitke** [comment]
How large are these files?  Might we be hitting up against a Travis resource limit of some sort?

**Comment by jeffvance** [comment]
Maybe my comments related to same issue in pr [352](https://github.com/kubevirt/containerized-data-importer/pull/352) is a possible explanation and potential fix.

**Comment by copejon** [comment]
@aglitke  The file is 18mb in size * 8 file format combinations. 

The error is generated internally by the `github.com/ulitunitz/xz` package here https://github.com/ulikunitz/xz/blob/0c6b41e72360850ca4f98dc341fd999726ea007f/lzma/bytewriter.go but it's not clear _what_ triggers this error.

**Comment by jeffvance** [comment]
However, @copejon mentioned the new _xz_ pkg may be the culprit here. More digging...

**Comment by copejon** [comment]
I'm not convinced this is related to the storage footprint of the tests - the error happens only occasionally in CI.  I'm also able to reproduce it after 10 or so consecutive runs on my local env, but then it goes away in the next iteration. 

@jeffvance pointed out that this error is returned by the xz projects function
```
// WriteByte writes a single byte to the limited byte writer. It returns
// ErrLimit if the limit has been reached. If the byte is successfully
// written the field N of the LimitedByteWriter will be decremented by
// one.
func (l *LimitedByteWriter) WriteByte(c byte) error {
    if l.N <= 0 {
        return ErrLimit
    }
    if err := l.BW.WriteByte(c); err != nil {
        return err
    }
    l.N--
    return nil
}
```

So for whatever reason, `l.N` is sometimes smaller than expected.

**Comment by copejon** [comment]
2 more `limit reached` errors have occurred in master CI.  

The errors all happen specifically in the `.tar.xz` test.

**Comment by copejon** [comment]
@jeffvance - @aglitke asked if we could disable this test in master to stop the random blocking on PRs.  I'll have a PR up soon for that.

This won't block us from trying to catch the bug in CI however if you do not rebase `master`.

**Comment by copejon** [comment]
Another thing that's interesting: this _doesn't_ seem to occur on the `.qcow2.tar.xz` test.

**Comment by copejon** [comment]
@jeffvance @aglitke 
To give us a common play space to reproduce this bug, I'm going to open a new upstream branch called something like `debug-issue-335` so we can mess with logging, tests, and CI configs in isolation.

**Comment by copejon** [comment]
Branch up: https://github.com/kubevirt/containerized-data-importer/tree/debug-issue-335
See CI: https://travis-ci.org/kubevirt/containerized-data-importer/branches
