### ISSUE TITLE
upload-controller.go: Upload pod is marked as ready when it is not serving yet

### ISSUE THREAD

**Issue by 0xFelix** [kubevirt/containerized-data-importer#3450]
**What happened**:

upload-controller.go marks the upload Pod as ready once all containers are ready, see:

https://github.com/kubevirt/containerized-data-importer/blob/d08e24523d904cb70324fdf57535c100b81ce8ca/pkg/controller/upload-controller.go#L524

This is not enough on a heavily loaded cluster, because although all containers are ready, the Pod might still not be serving the upload server yet. Because upload-controller.go marked the Pod as ready, the upload proxy will try to connect to it prematurely, which leads to failure of the upload with a message like:

```
error in upload-proxy: http: proxy error: dial tcp 10.97.83.53:443: connect: connection refused
```

See

https://github.com/kubevirt/containerized-data-importer/blob/d08e24523d904cb70324fdf57535c100b81ce8ca/pkg/uploadproxy/uploadproxy.go#L291

https://github.com/kubevirt/containerized-data-importer/blob/d08e24523d904cb70324fdf57535c100b81ce8ca/pkg/uploadproxy/uploadproxy.go#L324

**What you expected to happen**:

upload-controller.go should wait for the upload Pod to be serving before marking it as ready.

**How to reproduce it (as minimally and precisely as possible)**:

**Additional context**:

As observed in https://github.com/kubevirt/kubevirt/pull/12925

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): N/A
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by aglitke** [comment]
It seems like we can and should add a readiness probe.  Assigning to @mhenriks to take a deeper look.
/assign @mhenriks

**Comment by mhenriks** [comment]
upload controller has a readiness probe: https://github.com/kubevirt/containerized-data-importer/blob/5f66979d7cb321c56ca0367e95fd7d2035d092d4/pkg/controller/upload-controller.go#L853-L865

So not sure what more we can do from uploadserver perspective. maybe the k8s service has not detected the server is running and the service is not routing to the pod?

**Comment by 0xFelix** [comment]
The readiness probe maps to the healthz server that runs on a different port than the actual upload server. Maybe that is causing the readiness probe to mark the container as ready while the upload server is not ready yet?

See this method:

https://github.com/kubevirt/containerized-data-importer/blob/d4bee3ddad80f19d267eb16d41d03f4b79ce1a05/pkg/uploadserver/uploadserver.go#L165-L211

**Comment by 0xFelix** [comment]
In virtctl this is being workaround with retries for now. See https://github.com/kubevirt/kubevirt/pull/12925/commits/d3d0d485ae90db97ef52045d53daa0d80e6687a7
