### ISSUE TITLE
containerd  device_ownership_from_security_context configuration moved in v2

### ISSUE THREAD

**Issue by tpretz** [kubevirt/containerized-data-importer#3455]
**Description**:

The configuration for containerd is changed in version 2 regarding device_ownership_from_security_context

**What you expected**:
Add a additional text block detailing the difference

**URL**:
[Provide a link to the documentation.](https://github.com/kubevirt/containerized-data-importer/blob/main/doc/block_cri_ownership_config.md)

**Additional context**:

https://github.com/containerd/containerd/blob/main/docs/cri/config.md?plain=1

**Comment by awels** [comment]
I don't see anything in v2 for device ownership in that documentation. Do you have a specific example we could use?
