### ISSUE TITLE
Multiarch Minio-image for File Host

### ISSUE THREAD

**Issue by Davo911** [kubevirt/containerized-data-importer#3460]
Related to #1959 

**Is your feature request related to a problem? Please describe**:
When building `cdi-func-test-file-host` it uses for the S3 part [a minio image on quay.](https://github.com/kubevirt/containerized-data-importer/blob/7b330eb75575bfcf06644e0b274547de0f9c125e/manifests/templates/file-host.yaml.in#L63), which is only for `amd64`.

Minio seems to be available also for other architectures, [on dockerhub at least](https://hub.docker.com/layers/minio/minio/RELEASE.2024-10-02T17-50-41Z-cpuv1/images/sha256-ba435d3a45fb63d31f3b6101fa663827d5050c19bd99c5700fa8a7436a353628?context=explore).
Building `file-host` with this version on `s390x` worked in a first test.

**Describe the solution you'd like**:
Either a publicly available multiarch image is used, like on dockerhub 
or a `s390x` / `arm64` version is added to the quay repo.

**Additional context**:

**Comment by awels** [comment]
So we can't really do the dockerhub image, since dockerhub imposes a pull limit and if we hit that limit tests will start failing. This is why we use quay since there is no such limit there. So I think it makes sense to see if we can get that image into quay.

**Comment by awels** [comment]
@brianmcarey @dhiller Are you able to copy the appropriate container from dockerhub that matches or closely matches quay.io/kubevirt/minio:RELEASE.2018-08-02T23-11-36Z (or maybe even update that one to something more recent)

**Comment by brianmcarey** [comment]
I have copied across the following image manifest: 
`quay.io/kubevirt/minio:RELEASE.2024-10-02T17-50-41Z`

It includes an s390x image.

**Comment by awels** [comment]
you can get a newer one.

**Comment by Davo911** [comment]
very nice thanks @brianmcarey
I'll do a PR to use the newer one
