### ISSUE TITLE
func test file server does not deploy

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/containerized-data-importer#347]
@copejon I began rebasing my DataVolume functional tests off of the changes in #315 and noticed there are some things missing from the file server PR.

-  [ ] the test server is never deployed during 'make cluster-sync'
- [x] the test server is built during 'make functest' when it should probably be a part of the 'make docker' target
- [x] The test server's Docker file is installing the entire 'qemu' package, which is huge. It probably only needs 'qemu-img' similar to the import component.
- [ ] even after building the docker image during 'make functest', deploying the manifests/generaged/file-host.yaml file results in errors about the image not being found. Maybe the image isn't pushed to the local repo?

ideally the file-server should follow the same docker build patterns as our other containers.

**Comment by copejon** [comment]
Thanks for the notes - I'll have a PR up in today to address this.

> the test server is built during 'make functest' when it should probably be a part of the 'make docker' target

Just a note: the `functest` target is going to go away and `test-functional` will replace it.  It was another `cp` from kubevirt that's made its way into the build flow and doesn't adhere to the naming scheme in the Makefile.

> even after building the docker image during 'make functest', deploying the manifests/generaged/file-host.yaml file results in errors about the image not being found. Maybe the image isn't pushed to the local repo?

I haven't run into this in my own testing using both minikube or running it manually with a `docker run`.  `docker build` places the image in the local registry by default, there shouldn't be a need to push it. Is it running in the env that your run make in?  And if so, how are you send images to it?

**Comment by davidvossel** [comment]
> I haven't run into this in my own testing using both minikube or running it manually with a docker run.

test this with 'make cluster-up' and 'make cluster-sync'.

**Comment by copejon** [comment]
Oh, right.  Annoyingly `kubevirtci` only supports baremetal linux boxes, so I'm up a creek there.  I've tried a number of nested virt setups without any luck.

**Comment by davidvossel** [comment]
@aglitke i haven't seen any changes come in. @copejon is this something you'll be able to address?

**Comment by copejon** [comment]
@davidvossel @aglitke  Sorry this fell through the cracks.  kubevirtCI doesn't run on macs or in virtual environments, which pretty well excludes any option for me to test changes I make.  

I reached out to roman on this a while ago but couldn't find a solution - https://github.com/kubevirt/kubevirtci/issues/30

**Comment by copejon** [comment]
#356 Should have addressed pushing the images to the cluster

I'll open a one line PR to fix the qemu install

**Comment by copejon** [comment]
Reopening as PR #391 doesn't complete address this

**Comment by copejon** [comment]
> -  the test server is never deployed during 'make cluster-sync'

Not sure when it was added but `cluster/sync.sh` should be at least attempting to push the images.  Are you seeing any errors related to this still?

> - even after building the docker image during 'make functest', deploying the manifests/generaged/file-host.yaml file results in errors about the image not being found. Maybe the image isn't pushed to the local repo?

@davidvossel @awels @aglitke can you verify this is still the case?  I have no way of testing it on mac

**Comment by davidvossel** [comment]
>  can you verify this is still the case? I have no way of testing it on mac

It's all good now :+1:
