### ISSUE TITLE
New Release request

### ISSUE THREAD

**Issue by IanMoroney** [kubevirt/containerized-data-importer#3486]
Currently hitting [this bug](https://github.com/kubevirt/containerized-data-importer/issues/3159) which would be solved by a new release of the cdi (this issue is already fixed in main two weeks ago, but hasn't yet been released).

Just wondering if we can request a new release be made of CDI?

Many thanks

**Comment by akalenyu** [comment]
I backported it to 1.60 and we could do a 1.60.z after that is merged. Would that work?

**Comment by aglitke** [comment]
We discussed this on the SIG-Storage meeting and agreed that we should do something a bit more regular around z-stream releases to provide some predictability.

**Comment by IanMoroney** [comment]
I encountered the issue in 1.60.3, does that mean it was backported to 1.60, but not to the latest (1.60.3)?

The installation instructions for cdi always does `curl -s https://api.github.com/repos/kubevirt/containerized-data-importer/releases/latest`, which would be 1.60.3.
a 1.60.z release would be good, because fixes like these would never show up in latest otherwise

**Comment by akalenyu** [comment]
> I encountered the issue in 1.60.3, does that mean it was backported to 1.60, but not to the latest (1.60.3)?
> 
> The installation instructions for cdi always does `curl -s https://api.github.com/repos/kubevirt/containerized-data-importer/releases/latest`, which would be 1.60.3. a 1.60.z release would be good, because fixes like these would never show up in latest otherwise

Yes we would make a 1.60.z to solve this issue. Was just waiting on your confirmation.

I do agree that we should release .z more often, maybe through some cron that sends an email to the maintainers?

**Comment by akalenyu** [comment]
Here you go - https://github.com/kubevirt/containerized-data-importer/releases/tag/v1.60.4

**Comment by IanMoroney** [comment]
Thanks very much!
