### ISSUE TITLE
Cloner container creation has hard coded script path

### ISSUE THREAD

**Issue by awels** [kubevirt/containerized-data-importer#374]
The clone controller has a hard coded script path for calling the script when the clone source/target container is instantiated.

In release v1.1.1 its hard coded to /tmp/script.sh
In master its hard coded to /tmp/cloner_startup.sh

We should use the ENTRYPOINT for the container to specify the script path instead of hard coding it in the controller.

**Comment by aglitke** [comment]
In addition, the script should be installed in /usr/bin, not /tmp

**Comment by nellyc** [comment]
fixed
