### ISSUE TITLE
2FA (Two- Factor Authentication) Failed on Binance, What should I do?

### ISSUE THREAD

**Issue by allsupportnumber** [kubevirt/containerized-data-importer#387]
In order to make any activity from your [**Binance** ](http://allsupportnumber.com/binance-customer-service-8883023444/)account, you are required to set up 2FA Google Authy. Every time you sign in you will be reminded to enable 2FA & you should set up Google authentication for security purpose. If anybody trying to log in your account then [Binance ](http://allsupportnumber.com/binance-customer-service-8883023444/)required authy code and in this case, anybody not opens your Binance account without your permission.
[**Binance** ](http://allsupportnumber.com/binance-customer-service-8883023444/)offering SMS-based and App-based two- factor authy options.
We only go to be talking about the 2FA because that was where many **customers** faced some real problems like- 2fa verification code error on [Binance](http://allsupportnumber.com/binance-customer-service-8883023444/).
The issue with **[Google Authentication](http://allsupportnumber.com/binance-customer-service-8883023444/)** was that it kept on output "Binding Failed" whenever I input the 2fa codes on the Binance website www.binance.com. I loosed faith and was deeply troubled. If that is what you are experiencing, new customers are the one I am talking to, please read closely now and visit how to create 2FA for Binance account?

**Go to Your 2FA App On your Mobile Phone.**
•	Click the Upper Right Button
•	Click on setting
•	Click on Time Correction for codes
•	Syn now
After this, you will receive a success message. After that, you should try the codes again and re-input on the Binance website.
Until you have facing problem error with Binance 2FA verification code, it's time you should to contact the [customer service help desk](http://allsupportnumber.com/binance-customer-service-8883023444/).

**Comment by jeffvance** [comment]
spam in github, great... :frowning_face: 
Closed
