### ISSUE TITLE
PR #372 breaks ability of tests to generate junit and polarion output

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/containerized-data-importer#390]
Hi,

one week ago I added ability to generate junit reports for tests: https://github.com/kubevirt/containerized-data-importer/pull/342

It worked fine, yesterday it started failing on missing `-junit-output` option ...

Using `git-bisect` I found following PR which has introduced this problem: https://github.com/kubevirt/containerized-data-importer/pull/372

This is what I expect to see:
```
make build-functest
[lbednar@lbednar containerized-data-importer]$ ./_out/tests/tests.test --help 2>&1 | grep junit
  -junit-output string
```

And this is what I see now:
```
make build-functest
[lbednar@lbednar containerized-data-importer]$ ./_out/tests/tests.test --help 2>&1 | grep junit
```

**Comment by lukas-bednar** [comment]
cc @nellyc

**Comment by awels** [comment]
PR #380 should fix the issue. Basically the order in which init() is called in go is a little odd, and it happened that the reporter init was called after flag.Parse, and the --junit-output flag was getting ignored.

**Comment by jeffvance** [comment]
pr 380 is large (20+ files) and brings in new infra to cdi. @awels can you pull out your framework init() changes into a separate pr so we can address this regression more quickly? Thanks.

**Comment by awels** [comment]
#380 is merged, that should fix this issue

**Comment by lukas-bednar** [comment]
@awels it works for me - closing issue ... thank you!
