### ISSUE TITLE
It looks like the cdi controller is not eventually consistent

### ISSUE THREAD

**Issue by rmohr** [kubevirt/containerized-data-importer#400]
It looks like the `DataVolume` will only try to import an image once and then just goes to a failed state. I think that such a behaviour is fine for workloads (Pod, VMI) but for infrastructure components it is very unusual (I actually can't remember to have seen such a behaviour).

The main issue with that is, that all other controllers which want to use data volumes will also have to manage retry-logic for them to make the system eventually consistent again. Normally controller include retry-logic (including back-off) themselves. Also the whole way on how controller are intended to be written with e.g. client-go are designed with that assumption in mind.

Also PVCs work that way. If a storage provisioner does not have enough space left to back the PVC with a PV, the PVC does not go to a final failed state. Instead, as soon as enough space is left, the provisioner will eventually create a PV and the PVC will go to a bound state.

It is not impossible that a controller can add a proper-retry logic for a DataVolume to itself (see for instance https://github.com/kubevirt/kubevirt/pull/1475), but it significantly increases the complexity of every consumer.

What do you think?

**Comment by davidvossel** [comment]
i agree, we should be re-trying populating the pvc if the import or clone fails.

This retry logic should likely live within the import and clone controllers. The DataVolume controller would just depend on the lower level controllers to be eventually consistent.

**Comment by aglitke** [comment]
I agree too. In the past we’ve refused to import to a pvc when it contains a /disk.img. Now we’d probably want to overwrite the file until there is a confirmation annotation on the PVC.   What I worry about is if someone edits those annotations then CDI might come in and overwrite data when it was not intended.

**Comment by davidvossel** [comment]
> What I worry about is if someone edits those annotations then CDI might come in and overwrite data when it was not intended.

one safeguard here is that if we leave the completed pod around (which we do right now), then the import would fast succeed if someone cleared the annotations related to pod completion. Basically the old completed pod would be found and the annotation would get re-set.  A user would have to delete the completed pod from etcd and clear the annotation.

This assumes a completed pod won't get garbage collected since it has an owner reference. I believe that's the case, but we'll need to double check.

**Comment by davidvossel** [comment]
> Normally controller include retry-logic (including back-off) themselves. Also the whole way on how controller are intended to be written with e.g. client-go are designed with that assumption in mind.

@rmohr @aglitke I think the closest thing our import and clone pods can be compared to is a k8s ["job"](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#handling-pod-and-container-failures)

For example, with a k8s job we can define that a pod needs to execute to completion once. The job controller will ensure that the pod is retried until it eventually runs to completion successfully.

k8s jobs handle failures in two ways.

1. spec.backOffLimit which defines how many times a pod will get retried before the job is retried. There's an exponential backoff here where it goes from 10s, 20s, 40s, etc... all the way to a time cap of 6 minutes. 

2. spec.activeDeadlineSeconds A job fails if it doesn't complete after 'x' amount of time regardless of how many retries occur during that time.

For CDI, I'm not sure it makes sense to use k8s jobs directly. For situations like the clone controller where multiple pods have to be coordinated, having a job controller performing retry logic on our behalf might be unwieldy. However, the k8s jobs API does give us a good precedence for how to perform retry logic for failed import/clone workloads. 

Here are my thoughts on how we should proceed.

**Default Behavior**: retry imports/clone pod execution with exponential back off starting at 10s and capping at 6 minutes just like the Jobs api. This means we'll need the ability to either clobber previous files, or resume writing previous files. If we don't already, It would also be nice if we could trickle up information related to why an import job is failing and post that to the event recorder for the pvc.

**User Deadline Tuneable** Given how vastly different the import/clone times might be depending on file size and network speed, we'll never be able to come up with an acceptable deadline tuneable that works for everyone. Users should be able to define how long they'd like to wait for the CDI job to complete before marking it as failed.

**User Backoff Tuneable** When configuration errors occur (unreachable or invalid http import) the import/clone will fail regardless of how many times CDI retries. The default behavior is that CDI will retry forever. Users should be able to specify a custom limit. 

thoughts?

**Comment by rmohr** [comment]
> I agree too. In the past we’ve refused to import to a pvc when it contains a /disk.img. Now we’d probably want to overwrite the file until there is a confirmation annotation on the PVC. What I worry about is if someone edits those annotations then CDI might come in and overwrite data when it was not intended.

I don't see it as much as a problem. If you for instance re-label a pod which is created by a ReplicaSet, the ReplicaSet will happily create a replacement. So in general, it is not unusual that controller react to such changes. It is also kind of  expected. Never the less, how about putting the annotation on the bound PV instead of the PVC? Users normally don't have access to it.

**Comment by awels** [comment]
> Never the less, how about putting the annotation on the bound PV instead of the PVC? Users normally don't have access to it.

We would have to put a finalizer or something on the PVC, when it gets unbound and the reclaim policy of the PV is Delete, we would want to remove the annotation from the PV, otherwise we would never be able to import into the PV again.

**Comment by jeffvance** [comment]
I focus the discussion a bit I propose creating a separate issue around overwriting _disk.img_., and keep this issue focused on controller retries, recovery, etc. Is that agreeable?

**Comment by rmohr** [comment]
Let me reopen the issue since as far as I understand #481, it only adds parts of the requirements.

**Comment by j-griffith** [comment]
@rmohr 

> Let me reopen the issue since as far as I understand #481, it only adds parts of the requirements.

Correct, that was a partial; still need to deal with clone pods and it doesn't attempt to do fencing to deal with node failures.

**Comment by j-griffith** [comment]
@davidvossel 

> For CDI, I'm not sure it makes sense to use k8s jobs directly. For situations like the clone controller where multiple pods have to be coordinated, having a job controller performing retry logic on our behalf might be unwieldy. However, the k8s jobs API does give us a good precedence for how to perform retry logic for failed import/clone workloads.

For Clone operations I agree using jobs could be tricky to coordinate, however; for the simple import and upload jobs where we're dealing with a single POD it seems like a good fit IMO.  With the importer POD for example if we ensure the container executable to init the destination directory when it launches we wouldn't have to do things like delete/recreate PVCs either.  

For clones we'd want to mimic the behavior as you mentioned with our own implementation.

**Comment by rmohr** [comment]
@mhenriks @awels can the work on this continue? We still carry a workaround for `VMs` in the `kubevirt/kubevirt` codebase.

**Comment by mhenriks** [comment]
@rmohr I think it is possible to add retry logic to cloning.  I believe that is the oly gap we have.

**Comment by rmohr** [comment]
@mhenriks, @j-griffith mentioned in #481 that for instance on Eviction or a node failure CDI would not recover. Is that solved in the meantime?

**Comment by rmohr** [comment]
ping

**Comment by awels** [comment]
So at this point the behaviour of CDI is the following: All pods (import/upload/clone) have a restart policy of OnFailure. This means there is no flapping to Failure and back like before. On start of the pod it will wipe whatever was in the PVC before beginning the transfer.

If a pod is evicted or deleted before the transfer is completed, CDI will create a new pod that will start the process over again. Once the pod is completed we annotate the PVC with success and that will stop CDI from creating new pods.

**Comment by rmohr** [comment]
So it is now fully eventually-consistent and will retry it seems? Can this one be closed then?

**Comment by awels** [comment]
I think so. closing.
