### ISSUE TITLE
API validation

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/containerized-data-importer#439]
CDI needs to validate both UploadToken and DataVolume objects are valid as they are posted to the cluster. There are two parts to this.

1. Use a CRD validation schema
Look at KubeVirt's tools/crd-generator/crd-generator.go code. That program generates a CRD along with the API's openapiv3 schema. 

2. Create a Validation Webhook.
Validation webhooks allow us to catch complex API issues at creation time during the POST request. The k8s apiserver forwards the object to our validation endpoint during admission control.   The validation webhook lets us catch issues such as someone trying to set multiple sources for a single DataVolume. 

related #192

**Comment by mhenriks** [comment]
@igoihman @aglitke @davidvossel UploadTokenRequest is not a CRD, so we can't use webhooks.  The cdi-apiserver is (I think) doing all necessary validation now.
