### ISSUE TITLE
cdi-controller leader election

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/containerized-data-importer#453]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

Multiple cdi-controllers deployed at the same time can cause consistency issues. This could happen during the process of performing an update or in the event of certain types of node failures. 

Leader election allows us safely run multiple cdi-controllers in parallel. Only one of the controllers will obtain a lock in etcd which makes it the current active instance. The passive instances continue to try and obtain the lock for the duration of their life-cycle. If the active instance goes away, the lock times out and one of the passive instances will be able to obtain it.

KubeVirt has an example implementation of this in the ```pkg/virt-controller/watch/application.go``` file. 

**What you expected to happen**:

multiple cdi-controller instances can be deployed at once in active/passive mode.

**Comment by davidvossel** [comment]
@aglitke This is pretty important. Updates to the cdi infrastructure could result in some unexpected behavior if two cdi-controllers happen to briefly run at the same time (old one while it is shutting down, new one when it is coming up). There's also always the chance that the cluster enters into split brain. Leader election should be able to guarantee consistency there as well.

**Comment by jeffvance** [comment]
so does the deployment controller not provide the guarantee of one and only one cdi controller?

**Comment by davidvossel** [comment]
> so does the deployment controller not provide the guarantee of one and only one cdi controller?

The deployment controller does not provide a strong enough guarantee. It will try to keep only a single controller pod running, but there are scenarios where two can overlap with one another.

It's best that we default to a multi controller pod scenario and make that the normal mode of operation. This is how the k8s controllers now work and what we've adopted in kubevirt as well. Leader election fixes consistency issues and provides active/passive failover as well.
