### ISSUE TITLE
Pod garbage collection

### ISSUE THREAD

**Issue by mhenriks** [kubevirt/containerized-data-importer#463]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
Currently import/clone/upload pods are not deleted by their controllers after they reach Completed or Error state.  They will get deleted if the corresponding PVC is deleted.  Which may not happen.  They may also get garbage collected by Kubernetes but that may take awhile.

**What you expected to happen**:

My concern is not so much that these pods are consuming resources but that they are displayed when pods in a namespace are listed.  Could be annoying to a user.

**How to reproduce it (as minimally and precisely as possible)**:

import/clone/upload

**Anything else we need to know?**:

We may want to treat the Error pods differently from Completed.  Logs in Error Pods may be useful.  So maybe don' delete them straight away.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by zvikorn** [comment]
I will have to disagree (but this is my opinion only).
For me it’s helpful to know what happened in the cluster when I check it after awhile.
With the different names of the PVC’s it’s easier to figure out everything from the pod names.

**Comment by awels** [comment]
Fixed by #481
