### ISSUE TITLE
Release pages should include links to new docker containers

### ISSUE THREAD

**Issue by mhenriks** [kubevirt/containerized-data-importer#469]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

Upload brought along with it three new containers (cdi-apiserver, cdi-uploaproxy, cdi-uploadserver) and links to them should be included with the rest of the containers on release pages.  See here for example:  https://github.com/kubevirt/containerized-data-importer/releases/tag/v1.2.0-alpha.2

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
The actual release since 1.2 and up do have the links to the new containers. I also recently merged a PR that will make sure any new releases have them automatically included.
