### ISSUE TITLE
Add ability to create empty disk images

### ISSUE THREAD

**Issue by dcritch** [kubevirt/containerized-data-importer#497]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
I've been working with a combination of CNV, glusterfs and PXE. I've been creating VMs to PXE boot from a Satellite server to be provisioned. I've been using CDI to import a blank disk image from a URL.

**What you expected to happen**:
Would it be possible for CDI to have an option to create empty/blank disks rather than import an existing image?

**How to reproduce it (as minimally and precisely as possible)**:
n/a
**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
n/a. using `kubevirtci/disk-importer`
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-09-26T12:30:09Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-09-26T12:30:09Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
bare metal PowerEdge servers
- Install tools:
openshift-ansible, cnv installed directly from manifest

**Comment by zvikorn** [comment]
yes. I have started working on this today.

**Comment by dcritch** [comment]
Awesome! Looking forward to the feature.

**Comment by zvikorn** [comment]
Please do NOT merge until #502 is merged. This PR will have to be rebased.
