### ISSUE TITLE
Host-assisted cloning runs after PVC is already cloned

### ISSUE THREAD

**Issue by aglitke** [kubevirt/containerized-data-importer#534]
/kind bug

**What happened**:
Host-assisted cloning runs on a PVC which was already cloned by the gluster subvol provisioner.

**What you expected to happen**:
Host-assisted cloning should not run on PVCs which already carry the CloneOf annotation.

**How to reproduce it (as minimally and precisely as possible)**:

- Begin with a development environment using ```make cluster-up cluster-sync```
- Create 10 PVCs and 10 Pods that use the PVCs in order to use up all PVs
-  Create PVC with CloneRequest annotation to clone one of the dummy PVCs
- The PVC is in pending state and clone pods are scheduled to run
- Simulate the completion of a clone by adding a CloneOf annotation to the PVC
- Delete one of the dummy PVCs
- Clone PVC binds to a PV and cloning pods run against the bound PVC

**Anything else we need to know?**:
The above steps simulate the behavior without needing to deploy the gluster subvol provisioner.  I think the proper fix for this issue is to not schedule the clone pods unless the target PVC is either Bound or Pending/WaitFirstConsumer.  At that point you can check for the CloneOf annotation and if it's missing you will be confident that the provisioner will not actually do a clone itself.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by zvikorn** [comment]
Fixed in https://github.com/kubevirt/containerized-data-importer/pull/545
