### ISSUE TITLE
Cannot clone disk image with cloning PVC

### ISSUE THREAD

**Issue by zvikorn** [kubevirt/containerized-data-importer#548]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 
 /kind bug

**What happened**:
Cannot clone disk image by deploying cloning PVC. When deploying cloning PVC (i.e - manifest/examples/target-pvc.yaml), seems like the CPU is very busy, cloning pods remain in Running state, and it's very hard to do anything else on the machine. Machine barely responding. When you get a chance to run kubectl commands, you get 'Unable to connect to the server: net/http: TLS handshake timeout' error.
I could finally run 'make cluster-down' (which also took a while) and then, my machine could responded again.

**What you expected to happen**:
cloning pods running and completes.

**How to reproduce it (as minimally and precisely as possible)**:
make cluster-up
make cluster-sync
cluster/kubectl.sh create -f manifest/examples/golden-pvc.yaml
cluster/kubectl.sh create -f manifest/exmaples/target-pvc.yaml

**Anything else we need to know?**:
does not happen with datavolumes.

**Environment**:
- CDI version v1.3.0
- Kubernetes version 1.10.4:
- cluster running on k8s

**Comment by awels** [comment]
Just tried this locally and it cloned fine on master.

**Comment by awels** [comment]
@zvikorn So this could be that your nodes don't have enough memory (or barely enough). #533 increases the node memory by default from 2G to 5G which should make it work much better.
