### ISSUE TITLE
hard-coded importer-template

### ISSUE THREAD

**Issue by shiywang** [kubevirt/containerized-data-importer#55]
this part shouldn't be hardcoded: https://github.com/shiywang/containerized-data-importer/blob/d06b6da42f69b4e581a210841cb1159f33b177a9/pkg/controller/util.go#L138

espically nelly suggest using an offical repo url

I suggest using json.Unmarshal parse from a fixed file.

@jeffvance @copejon wdyt ?

**Comment by jeffvance** [comment]
Agree. It will likely be "filled in" somehow by an APB.

**Comment by jeffvance** [comment]
This should be a bit higher priority. If we have a go template for the importer pod then we won't need the `IMPORTER_IMAGE` env variable.
 We also could change _hack/version/lib.sh_'s `getVersionedFiles` function to only grep .yml, .yaml, .json files, and thus we would be able to delete CDI_VERSION from _common.go_.

**Comment by jeffvance** [comment]
Can someone add a use case for this issue? Thanks!
@nellyc @shiywang @davidvossel

**Comment by nellyc** [comment]
for me its just to avoid having some person's name in the code
docker.io/jcoperh

**Comment by davidvossel** [comment]
> Can someone add a use case for this issue? Thanks! @nellyc @shiywang @davidvossel

if we're using the the hardcoded "docker.io/jcoperh/importer:" prefix, how can I test my own dev build of the importer?

In kubevirt, we pass the VM pod's image as a cli arg to our virt-controller component. https://github.com/kubevirt/kubevirt/blob/master/manifests/dev/virt-controller.yaml.in#L37

The same thing could be done here with CDI.  the cdi controller would take an argument to represent the import container image

**Comment by awels** [comment]
Resolved by PR#269
