### ISSUE TITLE
Container import example on how to create the container image.

### ISSUE THREAD

**Issue by awels** [kubevirt/containerized-data-importer#558]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
There is no good example on how to prepare a container image for importing with CDI.

**What you expected to happen**:
Some documentation on how to prepare a container image that you can push to a registry so you can import it.
**How to reproduce it (as minimally and precisely as possible)**:

**Comment by awels** [comment]
Hey can you guys write up an example on how to prepare a container image for use with the new import functionality? @danielerez @rollandf

**Comment by rollandf** [comment]
Solved by #569
