### ISSUE TITLE
import-pod error will conflict with next creatation

### ISSUE THREAD

**Issue by shiywang** [kubevirt/containerized-data-importer#57]
Let's say I'm about to create a pvc but provided some wrong endpoint url,
then the pod created by cdi will error out, then I figure it out my url was wrong, I have to manually delete the pod, then delele pvc, then change pvc and create.

but ideally, I just want to oc edit pvc change to a valid url, then let the cdi do the rest of job.

**Comment by shiywang** [comment]
/kind of a feature we could enhance in the future I guess ?

**Comment by jeffvance** [comment]
fixed by pr #64
