### ISSUE TITLE
Do we have a plan to integrate this repo into kubevirt/kubevirt ? 

### ISSUE THREAD

**Issue by shiywang** [kubevirt/containerized-data-importer#62]
I'm working on a research on how to setup e2e test, there're two solutions here: 1. setting up a ci in this repo. 2. integrate e2e test in kubevirt/kubevirt, integrate in kubevirt/kubevirt has some pros but it will be no meaning if we didn't integrate the code base into kubevirt/kubevirt: no pr trigger tests.  so I was just asking if there's a long term plan for doing that ?

@jeffvance @copejon @aglitke

**Comment by jeffvance** [comment]
@shiywang As far as we know we there are no plans to add the containerized-data-importer repo to kubevirt. Unless that changes I think it makes sense for CI to focus on this repo.

**Comment by nellyc** [comment]
I also don't see the CDI merging into kubevirt repo, but I don't understand what is the meaning of E2E testing inside this repo.
From my POV the tests should be either under kubevirt or if it's not accepted there, we need to start discussing creating a new repo

**Comment by jeffvance** [comment]
@nellyc that's reasonable. We do not necessarily need official e2e tests in this repo -- unit tests could be sufficient. As for CI, maybe all we need are a couple of webhooks to run the tests when a PR is created/merged?

**Comment by nellyc** [comment]
@ifireball @gbenhaim is there something we can do to support CDI?

**Comment by copejon** [comment]
Tabling the discussion for now as there is desire to migrate the code base into kubvirt/kubevirt.
