### ISSUE TITLE
ISO error message when importing non ISO image

### ISSUE THREAD

**Issue by aglitke** [kubevirt/containerized-data-importer#643]
When importing a xz compressed raw image that is not in ISO format I see the following error message in the pod log:

E0207 20:20:03.314322       1 dataStream.go:617] isoSize: Atoi error on endpoint "/Fedora-Cloud-Base-29-1.2.x86_64.raw.xz": strconv.Atoi: parsing "f5": invalid syntax

Since this is not an ISO image I would not expect to see such a message.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.5.2

**Comment by awels** [comment]
Fixed by PR #721
