### ISSUE TITLE
not able to vendor kubevirt/containerized-data-importer

### ISSUE THREAD

**Issue by bharatnc** [kubevirt/containerized-data-importer#654]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:

I was using ``dep`` as a Golang package management tool to vendor dependencies for using the ``kubevirt`` api to create VMI for my kubernetes controller. Initially had trouble vendoring ``kubevirt.io/kubevirt`` itself, but raised [this ticket](https://github.com/kubevirt/kubevirt/issues/2017) and found a resolution. 

``kubevirt.io/kubevirt`` uses  ``kubevirt.io/containerized-data-importer`` internally and is essential that the same fix should be done to this project as well.

TL;DR

``dep`` expects a ``.go`` file to be present in the root of the project directory or otherwise it complains that it cannot parse metadata headers.

**What you expected to happen**:

There should be a .go file in the root of the directory. In this is the case, the package should be vendored fine. I verified this by adding the following constraints and overrides  to my Gopkg.toml file:

```
required = [
	"kubevirt.io/kubevirt/pkg/precond",
	"kubevirt.io/kubevirt/pkg/api/v1",
	"kubevirt.io/containerized-data-importer",
]
[[constraint]]
  name="kubevirt.io/kubevirt"
  branch="add-root-gofile-for-dep"

[[override]]
name = "kubevirt.io/containerized-data-importer"
source = "https://github.com/bharatnc/containerized-data-importer.git"
branch="bnc/add-go-file"

```

Note: here *add-root-gofile-for-dep* refers to the branch that is out there - a PR is active against that branch [here](https://github.com/kubevirt/kubevirt/pull/2019).
Also,  *bnc/add-go-file* is the fix that I added under my branch [here](https://github.com/bharatnc/containerized-data-importer/tree/bnc/add-go-file). Just referencing these in my Gopkg.toml file.

**How to reproduce it (as minimally and precisely as possible)**:

One can reproduce by trying to fetch the library using ``go-get``  - ``go get go get -d "kubevirt.io/containerized-data-importer/"``

**Anything else we need to know?**:

I have added a new go file called ``doc.go`` in my branch and will try to submit in a pull request.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

It would be great to have this merged in. This would also be useful anyone who is trying to leverage the kubernetes api for kubevirt.io - for all those folks who use dep as a package manager.

**Comment by slintes** [comment]
let me clarify the issue a bit:
- `go get kubevirt.io/containerized-data-importer` works fine.
- but `dep ensure -add kubevirt.io/containerized-data-importer` doesn't, because dep requires a Go file at the project root.

**Comment by bharatnc** [comment]
> let me clarify the issue a bit:
> 
> * `go get kubevirt.io/containerized-data-importer` works fine.
> * but `dep ensure -add kubevirt.io/containerized-data-importer` doesn't, because dep requires a Go file at the project root.

@slintes , thanks, that is correct, I correct myself and will update the issue.

**Comment by bharatnc** [comment]
This is all working fine, so  I'm closing this issue. Hope that other dep users will benefit from this fix! Thanks again @slintes !

**Comment by slintes** [comment]
> Hope that other dep users will benefit from this fix

I bet, thanks for raising this issue!
