### ISSUE TITLE
determine image type w/o relying on file extension names

### ISSUE THREAD

**Issue by jeffvance** [kubevirt/containerized-data-importer#66]
Today VM images are validated only by their filename extension. We could improve this by peeking inside the image and verifying headers, checksums (if any), etc to be more certain that we have a supported image type.
Something to consider is should we use the file's extension (suffix) at all? What if an image is named
_foo.tar.gz_ but it is not a gzip file? Is this an error or do we ignore the extension?

**Comment by copejon** [comment]
Point in case: cirros official (unarchived/uncompressed) images are named `cirros-0.4.0-aarch64-disk.img ` when they are in fact qcow2. (From https://download.cirros-cloud.net/0.4.0/)

Something to consider - ignoring file extensions completely is okay, but there is the added cost of having to download at least the first few kilobytes of the data to examine it.  Not exactly a crushing amount.

**Comment by jeffvance** [comment]
There are risks with this issue. It could be error prone inferring an image format based only on content. If the format changes over time (v2) our code would have to be updated to detect the change.
From an implementation perspective, in the absence of extensions, we'd have to assume some format (eg. gz or tar) try that, if false try something else. If true we need to undo that particular format and then guess again...
Each Reader needs `Peek` or we have to use some variation of Multireaders.

**Comment by jeffvance** [comment]
closed by pr #220

**Comment by jeffvance** [comment]
close by #220
