### ISSUE TITLE
Documentation for deployment using operator for version > 1.5.1

### ISSUE THREAD

**Issue by shayrybak** [kubevirt/containerized-data-importer#672]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
 /kind enhancement

**What happened**:
Deployment documentation only shows examples of how to deploy using the controller. However on version > 1.5.0 deployment is done via the operator. trying to install using the controller failed due to namespace and rbac issues.
**What you expected to happen**:
Document need to be updated to have the information on the deployment change.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): >= 1.5.1
- Kubernetes version (use `kubectl version`): 1.13
- Cloud provider or hardware configuration: bare metal
- Install tools: kubernetes manifest.
- Others:

**Comment by mhenriks** [comment]
addressed in https://github.com/kubevirt/containerized-data-importer/pull/646
