### ISSUE TITLE
Installing, removing, and reinstalling causes the controller to crash

### ISSUE THREAD

**Issue by mhenriks** [kubevirt/containerized-data-importer#674]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
kind bug
> /kind enhancement

**What happened**:

In controller log I see:

`
E0226 01:26:09.316306       1 config-controller.go:319] Error updating CDI Config: resource name may not be empty
F0226 01:26:09.316993       1 controller.go:220] Error running config controller: %+v Error creating CDI config: Error updating CDI Config: resource name may not be empty
goroutine 77 [running]:
kubevirt.io/containerized-data-importer/vendor/github.com/golang/glog.stacks(0xc42047c800, 0xc42034e000, 0xab, 0xe4)
	/go/src/kubevirt.io/containerized-data-importer/vendor/github.com/golang/glog/glog.go:769 +0xcf
kubevirt.io/containerized-data-importer/vendor/github.com/golang/glog.(*loggingT).output(0x1b6f7e0, 0xc400000003, 0xc4200f80b0, 0x1ad590d, 0xd, 0xdc, 0x0)
	/go/src/kubevirt.io/containerized-data-importer/vendor/github.com/golang/glog/glog.go:720 +0x32d
kubevirt.io/containerized-data-importer/vendor/github.com/golang/glog.(*loggingT).println(0x1b6f7e0, 0x3, 0xc420723f98, 0x2, 0x2)
	/go/src/kubevirt.io/containerized-data-importer/vendor/github.com/golang/glog/glog.go:633 +0xe7
kubevirt.io/containerized-data-importer/vendor/github.com/golang/glog.Fatalln(0xc420723f98, 0x2, 0x2)
	/go/src/kubevirt.io/containerized-data-importer/vendor/github.com/golang/glog/glog.go:1141 +0x53
main.start.func8(0xc4204020f0, 0xc420098780, 0xc4203a2820)
	/go/src/kubevirt.io/containerized-data-importer/cmd/cdi-controller/controller.go:220 +0xc3
created by main.start
	/go/src/kubevirt.io/containerized-data-importer/cmd/cdi-controller/controller.go:217 +0xd70
`

**What you expected to happen**:  no errors

**How to reproduce it (as minimally and precisely as possible)**:

```bash
make cluster-up cluster-sync
./cluster/kubectl.sh delete cdi cdi
./cluster/kubectl.sh apply -f manifests/generated/cdi-operator-cr.yaml
```

**Anything else we need to know?**:

Couple things to note:  The CDIConfig object is not removed when the cdi object is deleted which is weird.  I think that's actually a Kubernetes bug that is fixed in 1.12 or 1.13.

The CDIConfig object should probably be owned by the CDI obect.  See `SetOwner` in pkg/operator.  

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): f025943d706dfeed9620c5a2c771598e93320520
- Kubernetes version (use `kubectl version`): kubernetes 1.11.0
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by mhenriks** [comment]
attn @igoihman

**Comment by igoihman** [comment]
Thanks @mhenriks
