### ISSUE TITLE
Glide update could not fetch "kubevirt.io/containerized-data-importer"

### ISSUE THREAD

**Issue by shiywang** [kubevirt/containerized-data-importer#679]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:

when I'm trying to import some of the lib from cdi to kubevirt-ansible
like 
```
import "kubevirt.io/kubevirt/containerized-data-importer/test/framework"

```
it throws

```
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Fetching kubevirt.io/containerized-data-importer/tests/framework
[WARN]	Unable to checkout kubevirt.io/containerized-data-importer/tests/framework
[ERROR]	Update failed for kubevirt.io/containerized-data-importer/tests/framework: https://kubevirt.io/containerized-data-importer/tests/framework Not Found
[ERROR]	Could not update packages: https://kubevirt.io/containerized-data-importer/tests/framework Not Found
+ finish
+ docker stop c013c5a2531e465882c7564087cacd7986fe3eb8a8c09c152ba15a5a0531ba5d
+ docker rm -f c013c5a2531e465882c7564087cacd7986fe3eb8a8c09c152ba15a5a0531ba5d
make: *** [Makefile:2: deps-update] Error 1

```

But change to "github/kubevirt/containerized-data-importer"

it works.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
That is the correct behavior you have to import github.com/kubevirt/containerized-data-importer.
