### ISSUE TITLE
error while converting raw: Could not create file: Permission denied

### ISSUE THREAD

**Issue by shiywang** [kubevirt/containerized-data-importer#691]
[cnv-qe-jenkins@cnv-executor-kbidarka ~]$ oc logs -f importer-generate-c98dz972jt-lkz2b
I0305 06:34:07.697824       1 importer.go:45] Starting importer
I0305 06:34:07.698074       1 importer.go:65] begin import process
I0305 06:34:07.699149       1 importer.go:91] begin import process
I0305 06:34:07.699168       1 dataStream.go:299] copying "https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img" to "/data/disk.img"...
I0305 06:34:07.699182       1 dataStream.go:148] IMPORTER_ACCESS_KEY_ID and/or IMPORTER_SECRET_KEY are empty
I0305 06:34:07.699195       1 dataStream.go:395] create the initial Reader based on the endpoint's "https" scheme
I0305 06:34:07.699211       1 dataStream.go:258] Attempting to get object "https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img" via http client
I0305 06:34:08.045101       1 dataStream.go:411] constructReaders: checking compression and archive formats: /0.4.0/cirros-0.4.0-x86_64-disk.img
I0305 06:34:08.117874       1 dataStream.go:421] found header of type "qcow2"
I0305 06:34:08.117889       1 dataStream.go:441] constructReaders: no headers found for file "/0.4.0/cirros-0.4.0-x86_64-disk.img"
I0305 06:34:08.117894       1 dataStream.go:443] done processing "/0.4.0/cirros-0.4.0-x86_64-disk.img" headers
I0305 06:34:08.117899       1 dataStream.go:182] NewDataStream: endpoint "https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img"'s computed byte size: 46137344
I0305 06:34:08.118970       1 dataStream.go:706] Validating qcow2 file
I0305 06:34:08.118991       1 prlimit.go:107] ExecWithLimits qemu-img, [info --output=json https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img]
I0305 06:34:09.084403       1 dataStream.go:712] Doing streaming qcow2 to raw conversion
I0305 06:34:09.084433       1 prlimit.go:107] ExecWithLimits qemu-img, [convert -p -f qcow2 -O raw json: {"file.driver": "https", "file.url": "https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img", "file.timeout": 3600} /data/disk.img]
I0305 06:34:09.090740       1 qemu.go:192] 0.00
E0305 06:34:10.113322       1 prlimit.go:159] qemu-img [convert -p -f qcow2 -O raw json: {"file.driver": "https", "file.url": "https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img", "file.timeout": 3600} /data/disk.img] failed output is:
E0305 06:34:10.113856       1 prlimit.go:160]     (0.00/100%)qemu-img: /data/disk.img: error while converting raw: Could not create file: Permission denied
E0305 06:34:10.122718       1 importer.go:94] exit status 1
qemu-img execution failed
kubevirt.io/containerized-data-importer/pkg/system.ExecWithLimits
	/go/src/kubevirt.io/containerized-data-importer/pkg/system/prlimit.go:161
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertQcow2ToRawStream
	/go/src/kubevirt.io/containerized-data-importer/pkg/image/qemu.go:111
kubevirt.io/containerized-data-importer/pkg/importer.(*DataStream).copy
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/dataStream.go:713
kubevirt.io/containerized-data-importer/pkg/importer.CopyData
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/dataStream.go:316
main.main
	/go/src/kubevirt.io/containerized-data-importer/cmd/cdi-importer/importer.go:92
runtime.main
	/gimme/.gimme/versions/go1.10.linux.amd64/src/runtime/proc.go:198
runtime.goexit
	/gimme/.gimme/versions/go1.10.linux.amd64/src/runtime/asm_amd64.s:2361
could not stream/convert qcow2 image to raw
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertQcow2ToRawStream
	/go/src/kubevirt.io/containerized-data-importer/pkg/image/qemu.go:114
kubevirt.io/containerized-data-importer/pkg/importer.(*DataStream).copy
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/dataStream.go:713
kubevirt.io/containerized-data-importer/pkg/importer.CopyData
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/dataStream.go:316
main.main
	/go/src/kubevirt.io/containerized-data-importer/cmd/cdi-importer/importer.go:92
runtime.main
	/gimme/.gimme/versions/go1.10.linux.amd64/src/runtime/proc.go:198
runtime.goexit
	/gimme/.gimme/versions/go1.10.linux.amd64/src/runtime/asm_amd64.s:2361
Streaming qcow2 to raw conversion failed
kubevirt.io/containerized-data-importer/pkg/importer.(*DataStream).copy
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/dataStream.go:715
kubevirt.io/containerized-data-importer/pkg/importer.CopyData
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/dataStream.go:316
main.main
	/go/src/kubevirt.io/containerized-data-importer/cmd/cdi-importer/importer.go:92
runtime.main
	/gimme/.gimme/versions/go1.10.linux.amd64/src/runtime/proc.go:198
runtime.goexit
	/gimme/.gimme/versions/go1.10.linux.amd64/src/runtime/asm_amd64.s:2361
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):

  - containerID: cri-o://066a3cc6ccb8b5c72f688bb53ddcc9487ce6615d4168c4f5fd35b500ac8b370b
    image: docker.io/kubevirt/cdi-controller:v1.5.4
    imageID: docker.io/kubevirt/cdi-controller@sha256:f40ea5324121be3ddaecfbee8f48a3f2dfda42b6df5d479b2b774cc5f0a13cdc

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by mhenriks** [comment]
Yeah, this shows up in functional tests on occasion.  Unfortunately, it is not consistent and I am having trouble diagnosing.
