### ISSUE TITLE
performance degradation: Qcow2 image imported from registry is copied twice locally in dataStream

### ISSUE THREAD

**Issue by annastopel** [kubevirt/containerized-data-importer#705]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind enhancement

**What happened**:
qcow2 image imported from registry is saved on scratch space and then is copied in dataStream.copy to another temp location and only then converted and stored in /data/disk.img
There is no need to copy the image locally the second time
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
Actually no, that is not what happens. The following happens:
1. container is downloaded to scratch space.
2. Layers are extracted in scratch space.
3. disk image file is located in scratch space.
4. disk image file is either copied or converted to target space.
Read the code again, its all there.

**Comment by annastopel** [comment]
Paragraph 4 is exactly the issue - in case it is a qcow2 file from https source it will be copied one more time from the place registry code put it to (scratch space) to the new temporary place in scratch and then copied to target.

The degradation is that the second copy inside scratch is unnecessary

Thank You 

> Actually no, that is not what happens. The following happens:
> 
> 1. container is downloaded to scratch space.
> 2. Layers are extracted in scratch space.
> 3. disk image file is located in scratch space.
> 4. disk image file is either copied or converted to target space.
>    Read the code again, its all there.

Paragraph 4 is exactly the issue - in case it is a qcow2 file from https source it will be copied one more time from the place registry code put it to (scratch space) to the new temporary place in scratch and then copied to target.

The degradation is that the second copy inside scratch is unnecessary

Thank You

**Comment by awels** [comment]
Can you point me to the code where this second copy happens, because I don't see it.

**Comment by annastopel** [comment]
> Can you point me to the code where this second copy happens, because I don't see it.

https://github.com/kubevirt/containerized-data-importer/blob/f9a1bf79582fafaddaf100c9294a89701905aa5a/pkg/importer/dataStream.go#L915

**Comment by awels** [comment]
Yep, you are right, I was under the assumption tmpDest and the file pointed to by the reader where the same and thus nothing happened with the StreamDataToFile, but the top reader is pointing to /scratch/temp/something (wherever the layer is extracted) and tmpDest is pointing to /scratch/disk.img, so that is an unneeded copy.

**Comment by awels** [comment]
I am doing some extensive changes with the refactor, and I believe I will take care of this particular issue as well.

**Comment by annastopel** [comment]
Cool, thanks

**Comment by awels** [comment]
Fixed with data stream refactor.
