### ISSUE TITLE
Add the CDI CustomResource to the controller schema when the CDi struct is invoked

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/containerized-data-importer#709]
**FEATURE REQUEST**:
When trying to vendor in the CDI CustomResource, I get the error ```"error":"no kind is registered for the type v1alpha1.CDI in scheme```.  In order to avoid this error, I would have to add the object to the schema in my project.  It would be easier if the object was added in an init function so I'm ready to consume once it's vendored in.

Code would look similar to `kubevirt.io/kubevirt/pkg/api/v1/types.go`
```go
func init() {
        AddToScheme(Scheme)
        AddToScheme(scheme.Scheme)
}
```

/kind enhancement

**Comment by mhenriks** [comment]
When are you getting this error?  This seems like a pretty non standard thing to do.  The projects generated by the operator sdk don't do it.  Specifically wondering about the second line (adding the type to the default scheme for client go).

This is what we do in the CDI operator to add the CDI object to the scheme of the manager: 

```golang
if err := cdiv1alpha1.AddToScheme(mgr.GetScheme()); err != nil {
	log.Error(err, "")
	os.Exit(1)
}
```

**Comment by rthallisey** [comment]
This should actually be on kubevirt/kubevirt.  Had a conversation with an sdk developer and he said the same thing.  A lot of controllers are moving away from using an init function to register the scheme and towards using controller-runtime/manager.

More of a case for https://github.com/kubevirt/kubevirt/issues/1505.
