### ISSUE TITLE
Make CDI Component Creation Vendorable

### ISSUE THREAD

**Issue by djzager** [kubevirt/containerized-data-importer#715]
/kind enhancement

@slintes did a great job in https://github.com/kubevirt/kubevirt/pull/2062 integrating KubeVirt into OLM. I suspect that similar work must be done for CDI to integrate with OLM.

**What you expect to happen**:

This issue is meant to request that whatever code is written for generating the necessary OLM manifests for integration with OLM be made vendorable for the sake of https://github.com/kubevirt/hyperconverged-cluster-operator , of particular concern are the:

* Operator Deployment Spec
* Granular Cluster Role Rules
* Operator CRD

Regardless of whether the hyperconverged-cluster-operator moves towards making CDI a dependency or make the CDI Operator CRD "owned", we'll want a procedural way of generating a combined CSV.

**Comment by djzager** [comment]
@rthallisey asked that I tag @mhenriks

**Comment by mhenriks** [comment]
ack

**Comment by mhenriks** [comment]
cc @annastopel

**Comment by annastopel** [comment]
ack

**Comment by djzager** [comment]
Hopefully the silly `cdicomponents` pkg I created for generating the manifests are useful to you https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/pkg/cdicomponents/cdicomponents.go

**Comment by djzager** [comment]
@annastopel I believe this is fixed with #748 and can be closed.
