### ISSUE TITLE
Prometheus scrape configuration and the prometheus.kubevirt.io label

### ISSUE THREAD

**Issue by rmohr** [kubevirt/containerized-data-importer#753]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

You seem to add the `prometheus.kubevirt.io` label to pods which expose metrics. If that label is put on pods which is configured different than the pods in `kubevirt/kubevirt`, then it is not possible to configure prometheus properly. We will soon merge a PR which will serve valid TLS certificates for everything, including prometheus endpoints. With CDI installed it would be impossible to verify certificates, like it is right now. They would be all added to the same `Endpoint`, where then some targets have valid certs and others don't.

**What you expected to happen**:

Please consider using your own label. Something like `prometheus.cdi.kubevirt.io`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by rmohr** [comment]
It should only be an issue if for some reason one of your components which expose metrics run in the kubevirt install namespace, but I would prefer to have it resolved to avoid strange, hard to debug issues.

**Comment by awels** [comment]
@rmohr What is the PR, we don't have proper TLS certificate management in CDI and we need it as well (I want to steal either the code, or figure out how to use it for CDI). We modeled our prometheus after kubevirts and tried to configure them all the same, in the hope to be able to use the same infrastructure as kubevirt. But if that is a problem we can put a different label on our pods.

**Comment by awels** [comment]
> It should only be an issue if for some reason one of your components which expose metrics run in the kubevirt install namespace, but I would prefer to have it resolved to avoid strange, hard to debug issues.

If someone switches to the kubevirt namespace and imports something, then it will be an issue, so lets change the label.

**Comment by rmohr** [comment]
> @rmohr What is the PR, we don't have proper TLS certificate management in CDI and we need it as well (I want to steal either the code, or figure out how to use it for CDI).

You can have a look at https://github.com/kubevirt/kubevirt/pull/2027. client-go already brings most of the needed things for cert requests and cert rotation.

> We modeled our prometheus after kubevirts and tried to configure them all the same, in the hope to be able to use the same infrastructure as kubevirt. But if that is a problem we can put a different label on our pods.

I think the modelling is fine, just sharing the label can cause issues, but we should not share a `ServiceMonitor`.

**Comment by rmohr** [comment]
@awels thanks! :+1:
