### ISSUE TITLE
cdi operator uses cluster-admin ClusterRole. 

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/containerized-data-importer#759]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind enhancement

The cdi operator's service account is bound to the 'cluster-admin' ClusterRole, which i believe grants more permissions than the operator needs. 

This issue is a request to limit the scope of the permissions given to the cdi-operator to only what is required to manage the deployment/updating/deprovisioning of the cdi infrastructure.

**Comment by mhenriks** [comment]
Oh yeah, this is bad but should be fixed in #748

**Comment by mhenriks** [comment]
No longer uses cluster-admin but permissions are still too broad.  Currently all Operator permissions exist in a single ClusterRole.  But some of those permissions only need apply to the namespace CDI is installed in.

**Comment by annastopel** [comment]
The issue is resolved in  #748
