### ISSUE TITLE
CDIConfig not getting url from Ingress

### ISSUE THREAD

**Issue by mmazur** [kubevirt/containerized-data-importer#761]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
CDI is deployed and working (upload proxy is responding), but no ingress is set up yet:

```
[mmazur@klapek ~]$ k get -n cdi svc
NAME              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
cdi-api           ClusterIP   10.107.119.116   <none>        443/TCP   22h
cdi-uploadproxy   ClusterIP   10.101.104.236   <none>        443/TCP   22h
[root@node01 ~]# curl -ki https://10.101.104.236/v1alpha1/upload
HTTP/1.1 400 Bad Request
[mmazur@klapek ~]$ k get -n cdi ing
No resources found.
[mmazur@klapek ~]$ k get -n cdi cdiconfig/config -o yaml
(…)
spec: {}
status:
  scratchSpaceStorageClass: local
```
It's my understanding that once I add an Ingress pointing at that service (yaml taken from [here](https://github.com/kubevirt/containerized-data-importer/blob/master/doc/exposing-upload-proxy.md#kubernetes)), the config object should reflect that. That's not what's happening:

```
[mmazur@klapek ~]$ k apply -f ingress-cdi.yaml
ingress.extensions/cdi-uploadproxy-ingress created
[mmazur@klapek ~]$ k get -n cdi ing
NAME                      HOSTS                    ADDRESS          PORTS     AGE
cdi-uploadproxy-ingress   cdi-upload.example.com   192.168.66.201   80, 443   79s
[mmazur@klapek ~]$ k get -n cdi cdiconfig/config -o yaml
(…)
spec: {}
status:
  scratchSpaceStorageClass: local
```

Is there some step I'm missing/doing wrong or is the controller responsible for monitoring Ingress changes not doing it's job correctly?

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 1.8.0
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-12-06T18:30:39Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: standard intel hw
- Install tools: kubevirtci + deployments of metallb, ingress-nginx and cdi
- Others:

**Comment by igoihman** [comment]
@mmazur it should work when adding this to `metadata`:
``` yaml
labels:
    app: containerized-data-importer
```

I will fix it to have a consistent behavior with Routes.

**Comment by mhenriks** [comment]
I don't think Ingress/Routes should be required to have that label or any label.

**Comment by igoihman** [comment]
Correct, I'm going to remove that label from Ingress informer.
