### ISSUE TITLE
Support of http_proxy

### ISSUE THREAD

**Issue by salkin** [kubevirt/containerized-data-importer#775]
**FEATURE REQUEST**:

/kind enhancement

**What happened**:
Not possible to import when cluster is behind proxy

**What you expected to happen**: 
Support for adding http_proxy to the import

**How to reproduce it (as minimally and precisely as possible)**:
In cluster where proxy is enforced to reach outside world, import of image is failing

**Comment by zakkg3** [comment]
I would also like to /remove-lifecycle stale 
+1 :)

**Comment by awels** [comment]
There now it doesn't rot.
