### ISSUE TITLE
CDI 1.9.0 - creation of data-volume does not work IBM Cloud Private 3.1.2 - no PV to bind PVC to

### ISSUE THREAD

**Issue by ramanavakka** [kubevirt/containerized-data-importer#793]
> /kind bug
**What happened**:

With ICP 3.1.2 (IBM Cloud Private), sample suggested to create a CDI based data-volume does not work 

**What you expected to happen**:

The steps given at the example are supposed to create a data-volume. 

However since there is no default PV for IBM Cloud Private, this example does
not work. 

**How to reproduce it (as minimally and precisely as possible)**:

From https://github.com/kubevirt/containerized-data-importer
Do the following steps as suggested:

$ export VERSION=$(curl -s https://github.com/kubevirt/containerized-data-importer/releases/latest | grep -o "v[0-9]\.[0-9]*\.[0-9]*")
$ kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-operator.yaml
$ kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-cr.yaml
$ kubectl create -f https://raw.githubusercontent.com/kubevirt/containerized-data-importer/$VERSION/manifests/example/import-kubevirt-datavolume.yaml

**Anything else we need to know?**:

Here are the description from the pvc creation process:

user@ubuntu102:~/icp-312$ kubectl describe pvc my-data-volume
Name:          my-data-volume
Namespace:     cdi
StorageClass:
Status:        Pending
Volume:
Labels:        app=containerized-data-importer
               cdi-controller=my-data-volume
Annotations:   cdi.kubevirt.io/storage.contentType: kubevirt
               cdi.kubevirt.io/storage.import.endpoint: https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img
               cdi.kubevirt.io/storage.import.importPodName: importer-my-data-volume-l9djb
               cdi.kubevirt.io/storage.import.source: http
               cdi.kubevirt.io/storage.pod.phase: Pending
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
Events:
  Type       Reason         Age                From                         Message
  ----       ------         ----               ----                         -------
  Normal     FailedBinding  13s (x7 over 58s)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
Mounted By:  importer-my-data-volume-l9djb
user@ubuntu102:~/icp-312$

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
1.9.0
- Kubernetes version (use `kubectl version`):
user@ubuntu102:~/icp-312$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4+icp", GitCommit:"3f5277fa129f05fea532de48284b8b01e3d1ab4e", GitTreeState:"clean", BuildDate:"2019-01-17T13:41:02Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4+icp", GitCommit:"3f5277fa129f05fea532de48284b8b01e3d1ab4e", GitTreeState:"clean", BuildDate:"2019-01-17T13:41:02Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
user@ubuntu102:~/icp-312$
- Cloud provider or hardware configuration:
Private cloud 
- Install tools:
ICP installation tools 

user@ubuntu102:~/icp-312$ kubectl get nodes
NAME             STATUS   ROLES                          AGE   VERSION
192.168.20.102   Ready    etcd,management,master,proxy   9d    v1.12.4+icp
192.168.20.105   Ready    worker                         9d    v1.12.4+icp
user@ubuntu102:~/icp-312$

- Others:

**Comment by awels** [comment]
So basically you are saying there is no default storage class, and because you didn't specify a storage class the example didn't work?

If you look at the example file provided, there is a note at the top stating it assumes a default storage class. If there is none, you have to provide a storage class for it to work. The PVC section of a DV is 100% identical to a regular PVC definition, so you can set your storage class there.

**Comment by j-griffith** [comment]
Closing this, as the example does note specifying a SC.
