### ISSUE TITLE
[Doc] Clarify import from registry using CDI v1.5, the VM disk image file in container should be in raw format

### ISSUE THREAD

**Issue by qwang1** [kubevirt/containerized-data-importer#819]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind enhancement

**What happened**:
This is only for CDI release-v1.5
The functionality of registry import is as follows:
In order to import to succeed, the disk image file must be located in root directory of the container and should be named disk.img and be in raw format. 
The release-v1.5 document [image-from-registry.md](https://github.com/kubevirt/containerized-data-importer/blob/release-v1.5/doc/image-from-registry.md) doesn't mention the format should be in RAW format, so users might use any format. We should clarify this.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): release-v1.5

**Comment by zvikorn** [comment]
Wasn't this change included in 1.6 and not before that? This bug fix (https://github.com/kubevirt/containerized-data-importer/pull/641) is described in the CDI 1.6 release email.

**Comment by qwang1** [comment]
Since v1.6, the VM disk image file can be any format CDI supported, such as qcow2, raw, archive. But for v1.5, it still has the constraint that It must be the only raw format. @annastopel
