### ISSUE TITLE
IsOpenShift function is broken on OpenShift 4.x

### ISSUE THREAD

**Issue by igoihman** [kubevirt/containerized-data-importer#844]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:
`IsOpenShift` checks a certain REST API path `/oapi/v1` which exists on OpenShift 3.x and not on 4.x.
This causes `IsOpenShift` function to return false, thus config controller ignores Routes and `CDIConfig` status is not updated with route details.
Another impact: all functional tests that should run on OpenShift are bring skipped.
**What you expected to happen**:
If we are on OpenShift platform, the function should return `true`.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by dollierp** [comment]
Downstream issue https://bugzilla.redhat.com/show_bug.cgi?id=1714980
