### ISSUE TITLE
CDI failes when using a local http server for qcow2 files - help debug

### ISSUE THREAD

**Issue by ramanavakka** [kubevirt/containerized-data-importer#857]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Not sure if this is a bug or a pilot error - maybe an enhancement request

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:
I wanted to import a qcow2 file from a local http server.   I could get the file with 
wget but using the same via cdi to import - does not work.

Image location -http://192.168.1.101/Fedora-Cloud-Base-28-1.1.x86_64.qcow2
wget http://192.168.1.101/Fedora-Cloud-Base-28-1.1.x86_64.qcow2 - works fine

Created a PVC using the local file:
user@ubuntu112:~$ cat pvc_fed_local.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "fedora-local"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "http://192.168.1.101/Fedora-Cloud-Base-28-1.1.x86_64.qcow2"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

**What you expected to happen**:
It says PVC is created. 
Name:          fedora-local
Namespace:     default
StorageClass:  hostpath
Status:        Bound
Volume:        pvc-5568681c-915e-11e9-8233-e8fd9000001c
Labels:        app=containerized-data-importer
Annotations:   cdi.kubevirt.io/storage.import.endpoint: http://192.168.1.101/Fedora-Cloud-Base-28-1.1.x86_64.qcow2
               cdi.kubevirt.io/storage.import.importPodName: importer-fedora-local-l29p2
               cdi.kubevirt.io/storage.pod.phase: Failed
               control-plane.alpha.kubernetes.io/leader:
                 {"holderIdentity":"513c35fc-912d-11e9-89d4-be91d7b6175d","leaseDurationSeconds":15,"acquireTime":"2019-06-18T00:16:35Z","renewTime":"2019-...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      10Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Events:
  Type       Reason                 Age   From                                           Message
  ----       ------                 ----  ----                                           -------
  Normal     Provisioning           28m   hostpath 513c35fc-912d-11e9-89d4-be91d7b6175d  External provisioner is provisioning volume for claim "default/fedora-local"
  Normal     ProvisioningSucceeded  28m   hostpath 513c35fc-912d-11e9-89d4-be91d7b6175d  Successfully provisioned volume pvc-5568681c-915e-11e9-8233-e8fd9000001c
Mounted By:  importer-fedora-local-l29p2

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):

user@ubuntu112:~$ kubectl get deployments cdi-deployment -o yaml
Error from server (NotFound): deployments.extensions "cdi-deployment" not found
user@ubuntu112:~$ kubectl get deployments -A
NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
cdi           cdi-apiserver             1/1     1            1           6h22m
cdi           cdi-deployment            1/1     1            1           6h22m
cdi           cdi-uploadproxy           1/1     1            1           6h22m
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
Ubuntu 16.04 based server - Aparna Systems 4015 
- Install tools:
- Others:
[cdi-import-issue-kubectl-061719.txt](https://github.com/kubevirt/containerized-data-importer/files/3299352/cdi-import-issue-kubectl-061719.txt)

**Comment by zvikorn** [comment]
can you attach the pod (importer-fedora-local-l29p2) log?
and also the content of the hostpath storageclass. Thanks.

**Comment by ramanavakka** [comment]
Hi,
Thanks for your response:

Here is the log from the importer:
user@ubuntu112:~$ kubectl logs -p importer-fedora-local-l29p2
I0618 21:11:19.454906       1 importer.go:58] Starting importer
I0618 21:11:19.455108       1 importer.go:100] begin import process
E0618 21:11:49.455403       1 importer.go:106] Get http://192.168.1.101/Fedora-Cloud-Base-28-1.1.x86_64.qcow2: dial tcp 192.168.1.101:80: i/o timeout
HTTP request errored
kubevirt.io/containerized-data-importer/pkg/importer.createHTTPReader
        /go/src/kubevirt.io/containerized-data-importer/pkg/importer/http-datasource.go:254
kubevirt.io/containerized-data-importer/pkg/importer.NewHTTPDataSource
        /go/src/kubevirt.io/containerized-data-importer/pkg/importer/http-datasource.go:77
main.main
        /go/src/kubevirt.io/containerized-data-importer/cmd/cdi-importer/importer.go:104
runtime.main
        /gimme/.gimme/versions/go1.11.5.linux.amd64/src/runtime/proc.go:201
runtime.goexit
        /gimme/.gimme/versions/go1.11.5.linux.amd64/src/runtime/asm_amd64.s:1333
user@ubuntu112:~$

Contents of the storage - on the hostpath:

user@ubuntu112:~$ ls /var/kubernetes/
default-fedora2-pvc-82879576-913f-11e9-8233-e8fd9000001c       default-fedora-pvc-a192a70f-912d-11e9-8233-e8fd9000001c
default-fedora-local-pvc-5568681c-915e-11e9-8233-e8fd9000001c  default-forti-pvc-c0327a32-9156-11e9-8233-e8fd9000001c
**user@ubuntu112:~$ ls /var/kubernetes/default-fedora-local-pvc-5568681c-915e-11e9-8233-e8fd9000001c/**
user@ubuntu112:~$

**Comment by ramanavakka** [comment]
[cdi-import-issue-kubectl-061819.txt](https://github.com/kubevirt/containerized-data-importer/files/3303547/cdi-import-issue-kubectl-061819.txt)

**Comment by qwang1** [comment]
@ramanavakka Is your http server behind a proxy?

**Comment by qwang1** [comment]
@ramanavakka sorry for the noise, didn't see it's a local http server.

**Comment by ramanavakka** [comment]
Hi 
I am able to wget files from the local server as well as from the browser.  That is the only difference between the example given.  Where should I look for any issues? 

thanks
--ramana

**Comment by rollandf** [comment]
@ramanavakka Did you try the wget command from the node? It seems like a network issue.

**Comment by ramanavakka** [comment]
Yes. I am able to get from wget. I can also download with a browser. 
—ramana


Sent from Yahoo Mail for iPhone


On Thursday, June 20, 2019, 1:03 AM, Fred Rolland <notifications@github.com> wrote:


@ramanavakka Did you try the wget command from the node? It seems like a network issue.

**Comment by ramanavakka** [comment]
All,
I have tried a few things:
1. giving a local IP address as the  cdi.kubevirt.io/storage.import.endpoint does not work.  I believe this is a bug. 
2. Then I gave a fully qualified path to the address instead of the IP address - this also fails with a hard code address being used to DNS lookup the address - here is the error. 

Get http://server101.local.aparnasystems.com/media-vsrx-vmdisk-15.1X49-D170.4.qcow2: dial tcp: lookup server101.local.aparnasystems.com on 10.96.0.10:53: no such host

What is 10.96.0.53?
user@ubuntu112:~$ kubectl get rc,services
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   3d3h

Could this be a Calico networking issue? I setup kubeadm with the following command
sudo kubeadm init --pod-network-cidr=10.10.0.0/16

If anyone has suggestion on how to overcome the issue of using internal http address as the endpoint for CDI, please let me know. 

I have tried with an S3 endpoint and that works. 

thanks
--ramana

**Comment by awels** [comment]
Basically all our functional tests use a local to the cluster http server. This is likely a networking configuration issue in your cluster. Can you create a long running (busybox or something) pod, and exec into that pod, then see what your network configuration looks like in the pod.

**Comment by ramanavakka** [comment]
Thanks for the confirmation.  I have a single node cluster and nothing else.

**Comment by awels** [comment]
So when you say local http server, do you mean http server running in the cluster, or http server running on your local machine but not inside the cluster network? This is why I asked you to check from inside a running pod, since that pod will be on the pod network inside the cluster. There are several layers of network, and depending on where your 'local' http server lives, different things need to happen.

**Comment by ramanavakka** [comment]
Two bare metal servers - one of them host for kubectl node and the other has a web server (http).
The only question I have is - if CDI was able to access S3 server and get the image, why is it not able to do the same with the local http server?  In both cases, files are available via wget. Somehow 
the call httpget is failing for local http server.

**Comment by awels** [comment]
So there are 2 networks, the host network and the pod network. CDI uses the pod network to connect to the outside world. If you wget from the host to the local http server that is using the host network, and both hosts are on the same network. This is why I asked you to exec into a pod and run the wget from there, that way you are using the pod network.

As to why it can connect to S3, but not your local http server, that depends on how your pod network is configured. I am assuming using an external http server also works.

**Comment by niuplayer** [comment]
> So there are 2 networks, the host network and the pod network. CDI uses the pod network to connect to the outside world. If you wget from the host to the local http server that is using the host network, and both hosts are on the same network. This is why I asked you to exec into a pod and run the wget from there, that way you are using the pod network.
> 
> As to why it can connect to S3, but not your local http server, that depends on how your pod network is configured. I am assuming using an external http server also works.

It is indeed a problem with the pod network.
