### ISSUE TITLE
DataVolume should be in terminating state if PVC is not deleted yet

### ISSUE THREAD

**Issue by igoihman** [kubevirt/containerized-data-importer#859]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
 /kind enhancement

**What happened**:
When Deleting a DataVolume, it is responsible to delete also the corresponding PVC it creates.
I noticed that there is a phase where DataVolume is already deleted and PVC still exists and this is not a healthy state.
 
**What you expected to happen**:
DataVolume should be in terminating state until PVC is deleted.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
1.9.3
- Kubernetes version (use `kubectl version`):
ocp-4.1
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by maya-r** [comment]
#1031 would have fixed this, but we decided against having it.
I guess this issue should be closed as well.

**Comment by awels** [comment]
Correct, it is expected that the DV which owns the PVC can be deleted and the PVC remains until kubernetes deletes the PVC. This will happen automatically due to the DV having an ownerRef on the PVC.
