### ISSUE TITLE
[RFE]Local PV selector for upload image using virtctl tool

### ISSUE THREAD

**Issue by qwang1** [kubevirt/containerized-data-importer#860]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
I have different size of PVs in my cluster. When I used virtcl tool to upload a big image, although I requested proper PVC(enough for the virtual size and smaller than the biggest PV), PVC didn't bind to the most suitable PV. I learned that the prerequisites for PVC/PV binding are the same access mode and PVC request size <= PV. Once meet the access mode, then consider size, I have the right PVs available, why they are ignored?

For example:
I have 10Gi and few 25Gi local PV.
```
$ oc get pv
NAME                CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM     STORAGECLASS   REASON    AGE
local-pv-271c9ee9   10Gi       RWO            Delete           Available             local-sc                 7s
local-pv-32175b5c   25Gi       RWO            Delete           Available             local-sc                 110m
local-pv-6a6f574f   10Gi       RWO            Delete           Available             local-sc                 54m
local-pv-9116487e   25Gi       RWO            Delete           Available             local-sc                 110m
local-pv-a2aa6686   10Gi       RWO            Delete           Available             local-sc                 7s
local-pv-a794aed    10Gi       RWO            Delete           Available             local-sc                 110m
local-pv-ba561a78   10Gi       RWO            Delete           Available             local-sc                 110m
local-pv-c58b5d7    10Gi       RWO            Delete           Available             local-sc                 110m
```

I want to upload an image which needs 21G to be used by VM.
```
# qemu-img info win_12.qcow2
image: win_12.qcow2
file format: qcow2
virtual size: 21G (22548578304 bytes)
disk size: 7.9G
cluster_size: 65536
Format specific information:
    compat: 1.1
    lazy refcounts: false
```

Then I will request 23Gi PVC, hope that can bind to 25Gi PV.
```
$ virtctl image-upload --image-path=./win_12.qcow2 --uploadproxy-url=https://$(oc get route cdi-uploadproxy -n kubevirt-hyperconverged -o=jsonpath='{.status.ingress[0].host}) --pvc-name=win12-4 --pvc-size=23Gi --insecure
PVC qwang1/win12-4 created
Waiting for PVC win12-4 upload pod to be running...
timed out waiting for the condition
```
Check PVC
```
$ oc describe pvc win12-4-scratch
Name:          win12-4-scratch
Namespace:     qwang1
StorageClass:  local-sc
Status:        Pending
Volume:
Labels:        app=containerized-data-importer
               cdi-controller=cdi-upload-win12-4
               cdi.kubevirt.io/storage.import.importPvcName=win12-4
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Events:
  Type    Reason                Age                 From                         Message
  ----    ------                ----                ----                         -------
  Normal  WaitForFirstConsumer  28s (x350 over 1h)  persistentvolume-controller  waiting for first consumer to be created before binding


$ oc get pvc win12-4 -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    cdi.kubevirt.io/storage.pod.phase: Pending
    cdi.kubevirt.io/storage.upload.target: ""
  creationTimestamp: 2019-06-19T09:13:52Z
  finalizers:
  - kubernetes.io/pvc-protection
  name: win12-4
  namespace: qwang1
  resourceVersion: "72389"
  selfLink: /api/v1/namespaces/qwang1/persistentvolumeclaims/win12-4
  uid: 8e8b8522-9272-11e9-9b27-fa163e04ecf4
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 23Gi
  storageClassName: local-sc
  volumeMode: Filesystem
status:
  phase: Pending

```
Check upload pod, then I got events:
```
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  23s (x2 over 23s)  default-scheduler  persistentvolumeclaim "win12-4-scratch" not found
  Warning  FailedScheduling  22s (x3 over 22s)  default-scheduler  0/5 nodes are available: 2 node(s) didn't find available persistent volumes to bind, 3 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  22s (x3 over 22s)  default-scheduler  persistentvolumeclaim "win12-4-scratch" not found
  Warning  FailedScheduling  22s (x2 over 22s)  default-scheduler  persistentvolumeclaim "win12-4-scratch" not found
  Warning  FailedScheduling  21s (x3 over 21s)  default-scheduler  0/5 nodes are available: 2 node(s) didn't find available persistent volumes to bind, 3 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  21s (x3 over 21s)  default-scheduler  0/5 nodes are available: 2 node(s) didn't find available persistent volumes to bind, 3 node(s) had taints that the pod didn't tolerate.
```

**What you expected to happen**:
I hope we can specify PV when using `virtctl image-upload` 
Or all available PV can be considered.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): CDI 1.9.3
- Kubernetes version (use `kubectl version`): v1.13.4
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by qwang1** [comment]
https://github.com/kubevirt/containerized-data-importer/issues/861

**Comment by awels** [comment]
So the problem is you have 25G PVs available, and you need both for your particular operation. However since it is local storage, and one is on one node, and one is on another node, it can't bind both because they are on different nodes. So the requirements is for LOCAL storage that both PVs are on the same node.

**Comment by qwang1** [comment]
@awels Yes, that's what I mean.

**Comment by awels** [comment]
I am not sure what you want CDI to do about a badly configured cluster?

**Comment by qwang1** [comment]
Assuming that the cluster has the correct configuration. Is this can be a use case that I want to upload images to the specified node?

**Comment by awels** [comment]
Assuming you have a correctly configured cluster, where you have 2 PVs available on a node for upload, you cannot upload to a particular node because that is not how kubernetes works. You request a PVC, and based on that PVC, CDI will create an uploadserver pod. Kubernetes will schedule that pod on a node to run. That node will be where the file is saved. PVCs have no mechanism to specify which node they go on, as storage is an abstraction in kubernetes, and it doesn't care if the storage is local or not.

**Comment by qwang1** [comment]
I saw this doc [local-storage-selector](https://github.com/kubevirt/containerized-data-importer/blob/master/doc/local-storage-selector.md). it works for importing, that's where my proposal come from.

**Comment by awels** [comment]
Right but for that you need to manually create a PVC (or DV) with the label selector, and you need to put a label on the PV you want to use. In theory you can do the same for upload if you manually create the PVC ahead of time, and then virtctl upload with that existing PVC.
