### ISSUE TITLE
[RFE] Clarify scratch space requirement for local volume

### ISSUE THREAD

**Issue by qwang1** [kubevirt/containerized-data-importer#861]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
I took a long time to investigate the problem I mentioned in https://github.com/kubevirt/containerized-data-importer/issues/860, and as far as I know many ppl encountered this constantly and don't know why. In QE's cluster, the only two PVs which meet the requested size are not on the same node, so they're ignored.

**What you expected to happen**:
In order to save time and preventing duplicated bugs reported, I propose that we add a note to the document such as "If some operations need scratch space and you are using local volume, make sure there are two available PV meet PVC request attached on the same node". I believe that you will polish a better description:)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.9.3
- Kubernetes version (use `kubectl version`): v1.13.4
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
https://github.com/kubevirt/containerized-data-importer/blob/master/doc/supported_operations.md answers this question.

**Comment by qwang1** [comment]
@awels Do you mean the last paragraph *“From a technical perspective uploading a RAW kubevirt image doesn't require scratch space, however we can't tell ahead of time if the data coming in is raw or not, so we have to attach scratch to the upload server pod even if we don't use it.”*？I explained  it to a few people that for uploading images such as qcow2 we need scratch space and a targeted space and got response "so what?" till I explained more clear “they have to be attached to the same node!” We cannot guarantee that people get used to using distributed storage system can realize it.

**Comment by awels** [comment]
So basically you want a note that both scratch space and target space need to be accessible from the same node? Which is a requirement for any pod accessing two PVCs at the same time. Local storage or not.

**Comment by qwang1** [comment]
@awels Correct. It would be better if we state that Local storage - both scratch space and target space need to be accessible from the same node is a requirement for any pod accessing two PVCs at the same time

**Comment by awels** [comment]
Any storage that requirement is true, not just local storage. And that statement is true for any pod accessing 2 PVCs.

**Comment by qwang1** [comment]
Good to know. When we were using glusterfs, we seldom to care about the size and numbers of PV resources, that's why I overlooked many user scenarios. Using local storage is tricky and makes me think more.

**Comment by awels** [comment]
And that is why we highly suggest using shared storage instead instead of local storage because there are less gotchas like what you are experiencing. But the same requirement is true, both PVC need to be accessible on the node. Shared storage all PVCs are accessible on all nodes and thus you don't have this problem.
