### ISSUE TITLE
Travis fails when trying to build a release

### ISSUE THREAD

**Issue by annastopel** [kubevirt/containerized-data-importer#890]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind enhancement

**What happened**:
When building a release, travis fails with error 
```bash
/go/src/kubevirt.io/containerized-data-importer/_out/tools/cdi-func-test-file-host-init/
/go/src/kubevirt.io/containerized-data-importer/_out/tools/cdi-func-test-registry-init/
/go/src/kubevirt.io/containerized-data-importer/_out/tools/cdi-olm-catalog/
cp: cannot stat /go/src/kubevirt.io/containerized-data-importer/_out/manifests/release/olm/bundle/package: No such file or directory
make:[build] Error 1
fatal: cannot create directory at _out/apidocs: Permission denied
Could not restore untracked files from stash entry
Script failed with status 2
failed to deploy 
```

This is due to to the fact that now ``` make docker``` expects that ``` make manifests``` was executed before and olm related manifests were created.
olm related manifests are required in order to build cdi-olm-catalog container image.
NOTE: make manifests are to be executed with respective environmental variables that match the release to be issued : CNV_VERSION, DOCKER_PREFIX etc.
**What you expected to happen**:
release build is executed successfully
**How to reproduce it (as minimally and precisely as possible)**:
build a rlease with travis
**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 1.10.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by annastopel** [comment]
@awels  what is the proper way to solve this? 
Apparently in release mode, travis runs publish target which runs docker only, without manifests. Now manifests are required for docker as described in this issue. But manifests require respective environmental variables that correspond to the release being issued.

**Comment by awels** [comment]
#891 fixes this issue.
