### ISSUE TITLE
Panic when importing images

### ISSUE THREAD

**Issue by moadqassem** [kubevirt/containerized-data-importer#892]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
During the validating of the image I have got a panic, even though I reran the importer on the very same image it didn't panic and it was imported successfully.

`
I0725 20:29:17.406438       1 importer.go:100] begin import process
I0725 20:29:17.406870       1 data-processor.go:237] Calculating available size
I0725 20:29:17.410291       1 data-processor.go:245] Checking out file system volume size.
I0725 20:29:17.410315       1 data-processor.go:249] Request image size not empty.
I0725 20:29:17.410326       1 data-processor.go:254] Target size 10Gi.
I0725 20:29:17.410465       1 data-processor.go:167] New phase: Convert
I0725 20:29:17.410480       1 data-processor.go:173] Validating image
I0725 20:29:17.430386       1 qemu.go:205] 0.00
I0725 20:29:17.475286       1 qemu.go:205] 1.00
I0725 20:29:17.489096       1 qemu.go:205] 2.01
I0725 20:29:17.510145       1 qemu.go:205] 3.01
I0725 20:29:17.531953       1 qemu.go:205] 4.02
I0725 20:29:17.552685       1 qemu.go:205] 5.02
I0725 20:29:17.583154       1 qemu.go:205] 6.03
I0725 20:29:17.653171       1 qemu.go:205] 7.03
I0725 20:29:17.708166       1 qemu.go:205] 8.03
I0725 20:29:17.746036       1 qemu.go:205] 9.05
I0725 20:29:17.766260       1 qemu.go:205] 10.12
I0725 20:29:17.821945       1 qemu.go:205] 11.13
I0725 20:29:17.870483       1 qemu.go:205] 12.13
I0725 20:29:17.939576       1 qemu.go:205] 13.13
I0725 20:29:17.991312       1 qemu.go:205] 14.14
I0725 20:29:18.050381       1 qemu.go:205] 15.14
I0725 20:29:18.117173       1 qemu.go:205] 16.15
I0725 20:29:18.162908       1 qemu.go:205] 17.15
I0725 20:29:18.191509       1 qemu.go:205] 18.16
I0725 20:29:18.231358       1 qemu.go:205] 19.16
I0725 20:29:18.271596       1 qemu.go:205] 20.16
I0725 20:29:18.320687       1 qemu.go:205] 21.17
I0725 20:29:18.395882       1 qemu.go:205] 22.17
I0725 20:29:18.460358       1 qemu.go:205] 23.18
I0725 20:29:18.520874       1 qemu.go:205] 24.18
I0725 20:29:19.102981       1 qemu.go:205] 25.19
I0725 20:29:19.175588       1 qemu.go:205] 26.19
I0725 20:29:19.235831       1 qemu.go:205] 27.20
I0725 20:29:19.284622       1 qemu.go:205] 28.20
I0725 20:29:19.341569       1 qemu.go:205] 29.20
I0725 20:29:19.380420       1 qemu.go:205] 30.21
I0725 20:29:19.449800       1 qemu.go:205] 31.21
I0725 20:29:19.501416       1 qemu.go:205] 32.22
I0725 20:29:19.547881       1 qemu.go:205] 33.22
I0725 20:29:19.612214       1 qemu.go:205] 34.23
I0725 20:29:19.668267       1 qemu.go:205] 35.23
I0725 20:29:19.721616       1 qemu.go:205] 36.23
I0725 20:29:19.787334       1 qemu.go:205] 37.24
I0725 20:29:19.848257       1 qemu.go:205] 38.24
I0725 20:29:19.906871       1 qemu.go:205] 39.25
I0725 20:29:19.963187       1 qemu.go:205] 40.25
I0725 20:29:20.023784       1 qemu.go:205] 41.26
E0725 20:29:20.129452       1 prlimit.go:158] qemu-img failed output is:
E0725 20:29:20.129956       1 prlimit.go:159]     (0.00/100%)    (1.00/100%)    (2.01/100%)    (3.01/100%)    (4.02/100%)    (5.02/100%)    (6.03/100%)    (7.03/100%)    (8.03/100%)    (9.05/100%)    (10.12/100%)    (11.13/100%)    (12.13/100%)    (13.13/100%)    (14.14/100%)    (15.14/100%)    (16.15/100%)    (17.15/100%)    (18.16/100%)    (19.16/100%)    (20.16/100%)    (21.17/100%)    (22.17/100%)    (23.18/100%)    (24.18/100%)    (25.19/100%)    (26.19/100%)    (27.20/100%)    (28.20/100%)    (29.20/100%)    (30.21/100%)    (31.21/100%)    (32.22/100%)    (33.22/100%)    (34.23/100%)    (35.23/100%)    (36.23/100%)    (37.24/100%)    (38.24/100%)    (39.25/100%)    (40.25/100%)    (41.26/100%)qemu-img: /builddir/build/BUILD/qemu-3.0.1/util/async.c:490: aio_co_enter: Assertion self != co' failed.
E0725 20:29:20.283203       1 data-processor.go:164] signal: aborted (core dumped)
qemu-img execution failed
kubevirt.io/containerized-data-importer/pkg/system.ExecWithLimits
	/go/src/kubevirt.io/containerized-data-importer/pkg/system/prlimit.go:160
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
	/go/src/kubevirt.io/containerized-data-importer/pkg/image/qemu.go:111
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/data-processor.go:188
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/data-processor.go:157
main.main
	/go/src/kubevirt.io/containerized-data-importer/cmd/cdi-importer/importer.go:123
runtime.main
	/gimme/.gimme/versions/go1.11.5.linux.amd64/src/runtime/proc.go:201
runtime.goexit
	/gimme/.gimme/versions/go1.11.5.linux.amd64/src/runtime/asm_amd64.s:1333
could not stream/convert image to raw
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
	/go/src/kubevirt.io/containerized-data-importer/pkg/image/qemu.go:115
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/data-processor.go:188
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/data-processor.go:157
main.main
	/go/src/kubevirt.io/containerized-data-importer/cmd/cdi-importer/importer.go:123
runtime.main
	/gimme/.gimme/versions/go1.11.5.linux.amd64/src/runtime/proc.go:201
runtime.goexit
	/gimme/.gimme/versions/go1.11.5.linux.amd64/src/runtime/asm_amd64.s:1333
Conversion to Raw failed
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/data-processor.go:190
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/data-processor.go:157
main.main
	/go/src/kubevirt.io/containerized-data-importer/cmd/cdi-importer/importer.go:123
runtime.main
	/gimme/.gimme/versions/go1.11.5.linux.amd64/src/runtime/proc.go:201
runtime.goexit
	/gimme/.gimme/versions/go1.11.5.linux.amd64/src/runtime/asm_amd64.s:1333
E0725 20:29:20.283347       1 importer.go:125] signal: aborted (core dumped)
qemu-img execution failed
kubevirt.io/containerized-data-importer/pkg/system.ExecWithLimits
	/go/src/kubevirt.io/containerized-data-importer/pkg/system/prlimit.go:160
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
	/go/src/kubevirt.io/containerized-data-importer/pkg/image/qemu.go:111
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/data-processor.go:188
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/data-processor.go:157
main.main
	/go/src/kubevirt.io/containerized-data-importer/cmd/cdi-importer/importer.go:123
runtime.main
	/gimme/.gimme/versions/go1.11.5.linux.amd64/src/runtime/proc.go:201
runtime.goexit
	/gimme/.gimme/versions/go1.11.5.linux.amd64/src/runtime/asm_amd64.s:1333
could not stream/convert image to raw
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
	/go/src/kubevirt.io/containerized-data-importer/pkg/image/qemu.go:115
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/data-processor.go:188
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/data-processor.go:157
main.main
	/go/src/kubevirt.io/containerized-data-importer/cmd/cdi-importer/importer.go:123
runtime.main
	/gimme/.gimme/versions/go1.11.5.linux.amd64/src/runtime/proc.go:201
runtime.goexit
	/gimme/.gimme/versions/go1.11.5.linux.amd64/src/runtime/asm_amd64.s:1333
Conversion to Raw failed
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/data-processor.go:190
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	/go/src/kubevirt.io/containerized-data-importer/pkg/importer/data-processor.go:157
main.main
	/go/src/kubevirt.io/containerized-data-importer/cmd/cdi-importer/importer.go:123
runtime.main
	/gimme/.gimme/versions/go1.11.5.linux.amd64/src/runtime/proc.go:201
runtime.goexit
	/gimme/.gimme/versions/go1.11.5.linux.amd64/src/runtime/asm_amd64.s:1333
`

**What you expected to happen**:
I expect the image to be imported all the time. 

**How to reproduce it (as minimally and precisely as possible)**:
Deployed CDI with Kubevirt and create VM with VMI Data volume template. 

The images that I am using: 
https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2 
and 
https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
v1.9.3
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Hitzner Cloud

**Comment by alvaroaleman** [comment]
Not sure if related, but why does the CDI set CPU and memory limits to the `qemu-img` call? Those are supposed to be enforced at container level IMHO, having a process inside a container set that for a child in a oneshot-scenario where the main process basically exits when its child exits primarily makes debugging hard, but I fail a little to see the added value.

Also, why are these CPU and memory limit hardcoded?

**Comment by rmohr** [comment]
@aglitke did you think about running `qemu-img info` in an init container? When browsing through the code, it looks like you are setting the limits on the convert call. Can that be? If I remember the issue correctly, the limits were only meant for the metadata call, not for the conversion itself.

**Comment by awels** [comment]
Interesting, we only set the limits on the qemu-img info call, not the convert. This is to protect against malicious images.

**Comment by rmohr** [comment]
Maybe I don't understand the code but this looks like it is wrapped: https://github.com/kubevirt/containerized-data-importer/blob/b457828ca7224c6776531bd0acd873563cc9b5a9/pkg/image/qemu.go#L119

**Comment by awels** [comment]
Right, but if you compare it to https://github.com/kubevirt/containerized-data-importer/blob/b457828ca7224c6776531bd0acd873563cc9b5a9/pkg/image/qemu.go#L154 you will see the first parameter not being nil, the nil parameter means no limits.

**Comment by rmohr** [comment]
Ah, OK. 👍

**Comment by awels** [comment]
I do admit its a bit hokey to wrap the call and then pass it nil to not do anything. Something else to put on the technical debt to fix list.

**Comment by awels** [comment]
> Not sure if related, but why does the CDI set CPU and memory limits to the `qemu-img` call? Those are supposed to be enforced at container level IMHO, having a process inside a container set that for a child in a oneshot-scenario where the main process basically exits when its child exits primarily makes debugging hard, but I fail a little to see the added value.
> 
> Also, why are these CPU and memory limit hardcoded?

I am not familiar with the entire history of the prlimits, but afaik the actual limit values come from open stack where they noticed a potential security issue with malicious images (we have some here https://github.com/kubevirt/containerized-data-importer/tree/master/tests/images/invalid_qcow_images) that could potentially attempt to allocate all the memory or other stuff. The limits were put in place to protect against that.

But as I said before, it only uses them on the info call. Once the info call deems the image safe, we can convert (without a limit).

The thing that is confusing me, the stack trace is identical to a limits being reached, I just killed your process stack trace, like we saw when we had the limits on the convert as well. Are you sure CDI version is 1.9.3?

**Comment by moadqassem** [comment]
@awels Yes, I mean here is the spec of the CDI deployment yaml file: 
`spec:
      containers:
      - args:
        - -v=1
        env:
        - name: IMPORTER_IMAGE
          value: kubevirt/cdi-importer:v1.9.3
        - name: CLONER_IMAGE
          value: kubevirt/cdi-cloner:v1.9.3
        - name: UPLOADSERVER_IMAGE
          value: kubevirt/cdi-uploadserver:v1.9.3
        - name: UPLOADPROXY_SERVICE
          value: cdi-uploadproxy
        - name: PULL_POLICY
          value: IfNotPresent
        image: kubevirt/cdi-controller:v1.9.3`

**Comment by aglitke** [comment]
@moadqassem Are you still encountering this issue or has it been solved by upgrading CDI?

**Comment by moadqassem** [comment]
@aglitke Up until this moment, we haven't encountered this issue again so we can close it.

**Comment by NicolaiSchmid** [comment]
I'm still encountering this issue regularly. 
```
I0403 16:19:56.201140       1 importer.go:51] Starting importer
I0403 16:19:56.201292       1 importer.go:107] begin import process
I0403 16:19:56.205612       1 data-processor.go:275] Calculating available size
I0403 16:19:56.206392       1 data-processor.go:283] Checking out file system volume size.
I0403 16:19:56.206412       1 data-processor.go:287] Request image size not empty.
I0403 16:19:56.206429       1 data-processor.go:292] Target size 10692558848.
I0403 16:19:56.206511       1 data-processor.go:205] New phase: Convert
I0403 16:19:56.206524       1 data-processor.go:211] Validating image
I0403 16:19:56.238917       1 qemu.go:212] 0.00
I0403 16:19:56.456983       1 qemu.go:212] 1.00
I0403 16:19:56.628066       1 qemu.go:212] 2.00
I0403 16:19:56.754673       1 qemu.go:212] 3.00
I0403 16:19:56.898483       1 qemu.go:212] 4.01
I0403 16:19:57.057289       1 qemu.go:212] 5.01
I0403 16:19:57.207744       1 qemu.go:212] 6.01
I0403 16:19:57.483918       1 qemu.go:212] 7.01
I0403 16:19:57.687076       1 qemu.go:212] 8.01
I0403 16:19:57.879905       1 qemu.go:212] 9.01
I0403 16:19:58.028386       1 qemu.go:212] 10.01
I0403 16:19:58.162272       1 qemu.go:212] 11.02
I0403 16:19:58.324017       1 qemu.go:212] 12.02
I0403 16:19:58.498066       1 qemu.go:212] 13.02
I0403 16:19:58.740138       1 qemu.go:212] 14.02
I0403 16:19:58.959771       1 qemu.go:212] 15.02
I0403 16:19:59.115134       1 qemu.go:212] 16.02
I0403 16:19:59.316981       1 qemu.go:212] 17.02
I0403 16:19:59.498677       1 qemu.go:212] 18.03
I0403 16:19:59.703699       1 qemu.go:212] 19.03
I0403 16:19:59.886221       1 qemu.go:212] 20.03
I0403 16:20:00.021915       1 qemu.go:212] 21.03
I0403 16:20:00.160177       1 qemu.go:212] 22.03
I0403 16:20:00.368794       1 qemu.go:212] 23.03
I0403 16:20:00.564990       1 qemu.go:212] 24.04
I0403 16:20:00.735495       1 qemu.go:212] 25.04
I0403 16:20:00.866513       1 qemu.go:212] 26.04
I0403 16:20:01.020012       1 qemu.go:212] 27.04
I0403 16:20:01.171230       1 qemu.go:212] 28.04
I0403 16:20:01.331624       1 qemu.go:212] 29.04
I0403 16:20:01.490980       1 qemu.go:212] 30.04
E0403 16:20:01.851227       1 prlimit.go:164] qemu-img failed output is:
E0403 16:20:01.851258       1 prlimit.go:165]     (0.00/100%)
    (1.00/100%)
    (2.00/100%)
    (3.00/100%)
    (4.01/100%)
    (5.01/100%)
    (6.01/100%)
    (7.01/100%)
    (8.01/100%)
    (9.01/100%)
    (10.01/100%)
    (11.02/100%)
    (12.02/100%)
    (13.02/100%)
    (14.02/100%)
    (15.02/100%)
    (16.02/100%)
    (17.02/100%)
    (18.03/100%)
    (19.03/100%)
    (20.03/100%)
    (21.03/100%)
    (22.03/100%)
    (23.03/100%)
    (24.04/100%)
    (25.04/100%)
    (26.04/100%)
    (27.04/100%)
    (28.04/100%)
    (29.04/100%)
    (30.04/100%)
qemu-img: /builddir/build/BUILD/qemu-3.0.1/util/async.c:490: aio_co_enter: Assertion `self != co' failed.

E0403 16:20:01.851868       1 data-processor.go:202] signal: aborted (core dumped)
qemu-img execution failed
kubevirt.io/containerized-data-importer/pkg/system.ExecWithLimits
	pkg/system/prlimit.go:166
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
	pkg/image/qemu.go:118
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:226
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:189
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:141
main.main
	cmd/cdi-importer/importer.go:142
runtime.main
	GOROOT/src/runtime/proc.go:203
runtime.goexit
	src/runtime/asm_amd64.s:1357
could not stream/convert image to raw
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
	pkg/image/qemu.go:122
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:226
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:189
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:141
main.main
	cmd/cdi-importer/importer.go:142
runtime.main
	GOROOT/src/runtime/proc.go:203
runtime.goexit
	src/runtime/asm_amd64.s:1357
Conversion to Raw failed
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:228
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:189
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:141
main.main
	cmd/cdi-importer/importer.go:142
runtime.main
	GOROOT/src/runtime/proc.go:203
runtime.goexit
	src/runtime/asm_amd64.s:1357
Unable to convert source data to target format
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:191
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:141
main.main
	cmd/cdi-importer/importer.go:142
runtime.main
	GOROOT/src/runtime/proc.go:203
runtime.goexit
	src/runtime/asm_amd64.s:1357
E0403 16:20:01.852002       1 importer.go:144] signal: aborted (core dumped)
qemu-img execution failed
kubevirt.io/containerized-data-importer/pkg/system.ExecWithLimits
	pkg/system/prlimit.go:166
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
	pkg/image/qemu.go:118
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:226
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:189
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:141
main.main
	cmd/cdi-importer/importer.go:142
runtime.main
	GOROOT/src/runtime/proc.go:203
runtime.goexit
	src/runtime/asm_amd64.s:1357
could not stream/convert image to raw
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
	pkg/image/qemu.go:122
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:226
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:189
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:141
main.main
	cmd/cdi-importer/importer.go:142
runtime.main
	GOROOT/src/runtime/proc.go:203
runtime.goexit
	src/runtime/asm_amd64.s:1357
Conversion to Raw failed
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:228
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:189
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:141
main.main
	cmd/cdi-importer/importer.go:142
runtime.main
	GOROOT/src/runtime/proc.go:203
runtime.goexit
	src/runtime/asm_amd64.s:1357
Unable to convert source data to target format
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:191
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:141
main.main
	cmd/cdi-importer/importer.go:142
runtime.main
	GOROOT/src/runtime/proc.go:203
runtime.goexit
	src/runtime/asm_amd64.s:1357
```

**Comment by awels** [comment]
@NicolaiSchmid which version of CDI are you running?

**Comment by NicolaiSchmid** [comment]
I'm not encountering it anymore
