### ISSUE TITLE
Revisit #895 (PVC name length limits)

### ISSUE THREAD

**Issue by mhenriks** [kubevirt/containerized-data-importer#923]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

Let's revisit the fix to #895.  I'm not sure limiting the length of the DataVolume name is the right thing to do.  The 63 char limit hit was for a label key, not a PVC name.  And as far as I can tell, CDI does not include the PVC name in any labels set on the PVC.  So, where did the label come from in the initial bug report?  My guess is the storage provisioner.   Unfortunately, I don't think there is any way for the DataVolume webhook to know what labels/annotations the provisioner is going to put on the PVC.

Looks like a PVC name can theoretically be up to 253 characters but certain (most?) provisioners do have limits.  Looks like Gluster limits to 45 chars for example.

**What you expected to happen**:

I don't think we should limit DataVolume names unless it is for some reason internal to CDI.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by mhenriks** [comment]
Turns out there is a 63 char limit on label VALUES as well as keys.  News to me and we put pod/pvc names as label values all over the place.  Like here:  https://github.com/kubevirt/containerized-data-importer/blob/master/pkg/controller/datavolume-controller.go#L934 (where the initial issue was reported)

**Comment by maya-r** [comment]
Did @brybacki do enough revisiting with #1200?

**Comment by brybacki** [comment]
@mhenriks should we close the issue?

**Comment by mhenriks** [comment]
> @mhenriks should we close the issue?

yup
