### ISSUE TITLE
401 Unauthorized401 Unauthorized

### ISSUE THREAD

**Issue by Helenbj** [kubevirt/containerized-data-importer#925]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by kvaps** [comment]
/reopen

I have the same problem when uploading large images:

```console
$ virtctl image-upload --image-path ~/Downloads/Win10_21H2_EnglishInternational_x64.iso  --pvc-name=iso-win10 --pvc-size=10G --insecure --wait-secs=240 --storage-class=linstor-thindata-r1
PVC cdi/iso-win10 not found
PersistentVolumeClaim cdi/iso-win10 created
Waiting for PVC iso-win10 upload pod to be ready...
Pod now ready
Uploading data to https://cdi-uploadproxy.34.66.42.159.nip.io

 5.48 GiB / 5.48 GiB [=========================================================] 100.00% 7m31s

unexpected return value 401,
```

ingress-nginx log:

```
{ "time": "2022-08-22T11:48:36+00:00", "request_id": "0ba1984aa40a6ff7e30dae92d5c96ee2", "user": "", "address": "109.164.100.246", "bytes_received": 5886073709, "bytes_sent": 123, "protocol": "HTTP/1.1", "scheme": "https", "method": "POST", "host": "cdi-uploadproxy.XX.XX.XX.XXX.nip.io", "path": "/v1alpha1/upload-async", "request_query": "", "referrer": "", "user_agent": "Go-http-client/1.1", "request_time": 463.428, "status": 401, "content_kind": "cache-headers-not-present", "upstream_response_time": 0.077, "upstream_retries": 0, "namespace": "cdi", "ingress": "cdi-uploadproxy", "service": "cdi-uploadproxy", "service_port": "443", "vhost": "cdi-uploadproxy.XX.XX.XX.XXX.nip.io", "location": "/", "nginx_upstream_addr": "10.111.0.62:8443", "nginx_upstream_bytes_received": "118", "nginx_upstream_response_time": "0.077", "nginx_upstream_status": "401" }
```

**Comment by awels** [comment]
Can you provide the logs for the upload-server (in the namespace you are uploading to) and the upload-proxy server (in the cdi namespace)

**Comment by kvaps** [comment]
I don't see any related logs on this error:

upload-server:
```
I0822 13:15:24.633226       1 uploadserver.go:74] Running server on 0.0.0.0:8443
```

upload-proxy:
```
I0822 13:23:31.491940       1 uploadproxy.go:203] Received valid token: pvc: iso-win10-2, namespace: default
```

**Comment by awels** [comment]
I checked the code, it only gives a 401 when the token is expired. Does it take a long time to upload? Or is it failing in one of the follow steps like conversion and resizing?

**Comment by kvaps** [comment]
Yeah, image uploading takes some time. I don't have any issues when I upload small images.

**Comment by awels** [comment]
Okay so I suspect that the token simply expired, and that is why you are seeing the 401. I suppose we could modify the token to have a longer lifetime. @mhenriks Any thoughts on this?

**Comment by aglitke** [comment]
@kvaps Are you able to reliably reproduce this issue?  We'd like to understand more about what is happening in order to help resolve the issue.

**Comment by mhenriks** [comment]
@kvaps does the nginx proxy have request buffering enabled?  If so It is possible that the token is timing out before nginx sends data to the uploadproxy.

http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_request_buffering

**Comment by MeiYiWZz** [comment]
Can you help me? 
Why does this appear when I call the api?
curl -k --insecure  https://10.223.14.82:443/apis/kubevirt.io/v1/virtualmachineinstances
request is not authenticated
but i  curl -k --insecure  https://10.223.14.82:443/apis
it is ok 
{
 "kind": "APIGroupList",
 "groups": [
  {
   "kind": "APIGroup",
   "name": "subresource.kubevirt.io",
   "versions": [
    {
     "groupVersion": "subresources.kubevirt.io/v1",
     "version": "v1"
    },
    {
     "groupVersion": "subresources.kubevirt.io/v1alpha3",
     "version": "v1alpha3"
    }
   ],
   "preferredVersion": {
    "groupVersion": "subresources.kubevirt.io/v1",
    "version": "v1"
   },
   "serverAddressByClientCIDRs": [
    {
     "clientCIDR": "0.0.0.0/0",
     "serverAddress": ""
    }
   ]
  }
 ]

**Comment by aglitke** [comment]
It seems we have lost traction on this issue and it has gone rotten again.  If you are still seeing this issue in your environment and can provide the requested details please feel free to reopen so that we can help to resolve the issue.  Thanks.

**Comment by CafeLungo** [comment]
This is still a current problem. I'm attempting to upload a qcow2 that is ~86GB, and I'm getting this same 401, after multiple automatic retries. It takes approximately 20min to upload once.

Compressing the image to roughly 43GB also did not offer success here.

I've tested this with an image of size ~1GB, and it has no problem.

No logs anywhere about the issue. I do not see an argument to make this token last longer. It's also unclear how long the token lasts. 

logs, through the nginx ingress:
```
10.244.3.1 - - [12/May/2025:16:35:01 +0000] "POST /v1beta1/upload-async HTTP/2.0" 499 0 "-" "Go-http-client/2.0" 22516678686 296.314 [cdi-cdi-uploadproxy-443] [] - - - - dfb8154fda89a43539d79832341c7122
10.244.3.1 - - [12/May/2025:16:48:06 +0000] "HEAD /v1beta1/upload-async HTTP/2.0" 200 0 "-" "Go-http-client/2.0" 625 0.053 [cdi-cdi-uploadproxy-443] [] 10.244.1.53:8443 0 0.053 200 0d8f9ee759a270eb742f4a9cfc19e6b3
2025/05/12 16:48:06 [warn] 2052#2052: *15149255 a client request body is buffered to a temporary file /tmp/nginx/client-body/0000000084, client: 10.244.3.1, server: cdi-uploadproxy.my.domain.com, request: "POST /v1beta1/upload-async HTTP/2.0", host: "cdi-uploadproxy.marimon.lan"
10.244.3.1 - - [12/May/2025:16:57:52 +0000] "POST /v1beta1/upload-async HTTP/2.0" 401 0 "-" "Go-http-client/2.0" 46899420439 585.917 [cdi-cdi-uploadproxy-443] [] 10.244.1.53:8443 0 0.013 401 6f3190c52c47f741cd1819b3bd7c8605
```

**Comment by mhenriks** [comment]
@CafeLungo what is your ingress configuration? Do you have the same problem if you upload via `kubectl port-forward` to `cdi-uploadproxy`?

**Comment by cisco-abrandel** [comment]
> [@CafeLungo](https://github.com/CafeLungo) what is your ingress configuration? Do you have the same problem if you upload via `kubectl port-forward` to `cdi-uploadproxy`?

For what it's worth, with ingress-nginx the problem for me was indeed proxy request buffering. Disabling that on the ingress and I no longer received the 401s along with other symptoms shown in this issue.
