### ISSUE TITLE
image.UnpackData should return the filename variable

### ISSUE THREAD

**Issue by copejon** [kubevirt/containerized-data-importer#94]
[UnpackData()](https://github.com/kubevirt/containerized-data-importer/blob/master/pkg/image/decompress.go#L25) takes a filename and attempts to mutate it dynamically as different decompression and unarchiving is performed such that the output would contain the appropriate extensions.  However, this string var is not returned and cannot be used by the caller.

cc @jeffvance @screeley44

**Comment by jeffvance** [comment]
I think this will be addressed in issue #74 .
Basically, I think we need the `dataStream` struct to be an _io.ReadCloser_. Then it can be returned by the unpack functions.

**Comment by jeffvance** [comment]
UnpackData() has been refactored out by pr #102
